### PR TITLE
Fixed ZooKeeper service usage to delete /controller znode on migration rollback

### LINKED ISSUE #10371: [Bug]: KRaft rollback failed when cluster is deployed in another namespace
### Bug Description

We have a Zookeeper based cluster and we want to move to KRaft.
Our Kafka cluster is deployed in another namespace than the operator.
I tried the rollback operation twice and it seems to consistently fail, and I suspect it is because the Kafka cluster in another namespace.

After preforming the process described [here](https://strimzi.io/docs/operators/latest/deploying#proc-deploy-migrate-kraft-rollback-str) When I set the annotation to `disabled`. The `Kafka` resource is stuck on the status:
```
Cluster Id:  3gB-eOZuSymSd7kjWBkQzA
  Conditions:
    Last Transition Time:            2024-07-22T13:51:16.677458833Z
    Message:                         The Kafka cluster main-cluster-kafka-cluster is invalid: [At least one KafkaNodePool with the controller role and at least one replica is required when KRaft mode is enabled]
    Reason:                          InvalidResourceException
    Status:                          True
    Type:                            NotReady
  Kafka Metadata State:              KRaftDualWriting
  Kafka Version:                     3.7.0
  Observed Generation:               4
  Operator Last Successful Version:  0.41.0
```

And in the operator logs I see the following repeating exception:
```
2024-07-22 07:51:36 ERROR StaticHostProvider:148 - Unable to resolve address: main-cluster-kafka-cluster-zookeeper-client/<unresolved>:2181
java.net.UnknownHostException: main-cluster-kafka-cluster-zookeeper-client
        at java.net.InetAddress$CachedAddresses.get(InetAddress.java:801) ~[?:?]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1533) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1385) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1306) ~[?:?]
        at org.apache.zookeeper.client.StaticHostProvider$1.getAllByName(StaticHostProvider.java:88) ~[org.apache.zookeeper.zookeeper-3.8.4.jar:3.8.4]
        at org.apache.zookeeper.client.StaticHostProvider.resolve(StaticHostProvider.java:141) ~[org.apache.zookeeper.zookeeper-3.8.4.jar:3.8.4]
        at org.apache.zookeeper.client.StaticHostProvider.next(StaticHostProvider.java:368) ~[org.apache.zookeeper.zookeeper-3.8.4.jar:3.8.4]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1204) ~[org.apache.zookeeper.zookeeper-3.8.4.jar:3.8.4]
2024-07-22 07:51:36 WARN  ClientCnxnSocketNetty:151 - future isn't success.
java.net.UnknownHostException: main-cluster-kafka-cluster-zookeeper-client
        at java.net.InetAddress$CachedAddresses.get(InetAddress.java:801) ~[?:?]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1533) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1385) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1306) ~[?:?]
        at java.net.InetAddress.getByName(InetAddress.java:1256) ~[?:?]
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41) ~[io.netty.netty-resolver-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61) ~[io.netty.netty-resolver-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53) ~[io.netty.netty-resolver-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55) ~[io.netty.netty-resolver-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31) ~[io.netty.netty-resolver-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106) ~[io.netty.netty-resolver-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220) ~[io.netty.netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:47) ~[io.netty.netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:189) ~[io.netty.netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:175) ~[io.netty.netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[io.netty.netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990) ~[io.netty.netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516) ~[io.netty.netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[io.netty.netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[io.netty.netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[io.netty.netty-transport-classes-epoll-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.108.Final.jar:4.1.108.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

As you can see the operator tries the address `main-cluster-kafka-cluster-zookeeper-client/<unresolved>:2181` and is not appending the namespace suffix (in our case `kafka.svc`)

I also turned on the DEBUG log and I see this line before the exception:
```
2024-07-22 07:51:13 DEBUG VertxUtil:93 - Reconciliation #2(watch) Kafka(kafka/main-cluster-kafka-cluster): Waiting for ZooKeeperAdmin connection to main-cluster-kafka-cluster-zookeeper-client:2181 to get connected
```

I looked at another environment which runs with Zookeeper normally, and I see the address in DEBUG logs is different:
```
2024-07-23 07:38:43 DEBUG VertxUtil:91 - Reconciliation #1(watch) Kafka(kafka/main-cluster-kafka-cluster): Waiting for ZooKeeperAdmin connection to main-cluster-kafka-cluster-zookeeper-0.main-cluster-kafka-cluster-zookeeper-nodes.kafka.svc:2181,main-cluster-kafka-cluster-zookeeper-1.main-cluster-kafka-cluster-zookeeper-nodes.kafka.svc:2181,main-cluster-kafka-cluster-zookeeper-2.main-cluster-kafka-cluster-zookeeper-nodes.kafka.svc:2181 to get connected
```

I dug into the code and I saw the log of `ZooKeeperAdmin connection to` in your code twice:
https://github.com/search?q=repo%3Astrimzi%2Fstrimzi-kafka-operator+%22ZooKeeperAdmin+connection+to%22&type=code

Following the source of this logs shows me that one address is originated here:
https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java#L901
```
String zkConnectionString = KafkaResources.zookeeperServiceName(reconciliation.name()) + ":" + ZookeeperCluster.CLIENT_TLS_PORT;
```
And the other is here:
https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java#L594
```
Function<Integer, String> zkNodeAddress = (Integer i) ->
                DnsNameGenerator.podDnsNameWithoutClusterDomain(reconciliation.namespace(), KafkaResources.zookeeperHeadlessServiceName(reconciliation.name()), KafkaResources.zookeeperPodName(reconciliation.name(), i));
```
Where I can clearly see that one use the namespace while the other not.

### Steps to reproduce

1. Have a Zookeeper based cluster (Kafka version 3.7.0)
Follow the exact process described here (including the rollback): https://strimzi.io/docs/operators/latest/deploying#proc-deploy-migrate-kraft-str

### Expected behavior

`Kafka` resource to become `Ready` and `METADATA STATE` to become `ZooKeeper`

### Strimzi version

0.41.0

### Kubernetes version

Server Version: v1.30.2+k3s2

### Installation method

Helm Chart

### Infrastructure

K3S

### Configuration files and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Bugfix

### Description

This PR fixes #10371.
The current code, to get the ZooKeeper connection string from the service in order to connect to ZooKeeper and delete the `/controller` znode during KRaft migration rollback, doesn't take into account the full name (i.e. including namespace), so the operator can't connect when the cluster is running in a different namespace.
The PR fixes it.

### Checklist

- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java [hunk 1]
```diff
@@ -898,7 +898,7 @@ protected Future<Void> maybeDeleteControllerZnode() {
      */
     protected Future<Void> deleteControllerZnode() {
         // migration rollback process ongoing
-        String zkConnectionString = KafkaResources.zookeeperServiceName(reconciliation.name()) + ":" + ZookeeperCluster.CLIENT_TLS_PORT;
+        String zkConnectionString = DnsNameGenerator.serviceDnsNameWithClusterDomain(reconciliation.namespace(), KafkaResources.zookeeperServiceName(reconciliation.name()))  + ":" + ZookeeperCluster.CLIENT_TLS_PORT;
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java:901]: Do you really want to use the cluster domain? Wouldn't `serviceDnsNameWithoutClusterDomain` be better?

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java:901]: That seems to be also what the scaling is using for example (that uses Pod-based address for connecting to a single pod, but without the cluster domain which is the part relevant here)

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java:901]: Yeah cluster domain is actually not needed, I will change. But out of curiosity, is there any specific issue you see by having it?

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java:901]: Well, the detection of the cluster domain can be tricky. So we try to avoid relying on it.

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java]: Done

**Review by scholzj — APPROVED** [review]
