### PR TITLE
Remove default Pod anti-affinity rules when rack awareness is enabled

### LINKED ISSUE #11509: [Bug]: Incorrect default pod antiaffinity for NodePools
### Bug Description

The value of affinity.podantiaffinity default is generated as follows which does not match documentation which seems to be more correct. [doc]( https://strimzi.io/docs/operators/latest/deploying#configuring-pod-anti-affinity-to-schedule-each-kafka-broker-on-a-different-worker-node-str) The incorrect version below will prevent two pods from the same cluster from running in the same zone

```yaml
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              strimzi.io/cluster: kafka-dev-sci
              strimzi.io/name: kafka-dev-sci-kafka
          topologyKey: topology.kubernetes.io/zone
        weight: 100
```

### Steps to reproduce

The following yaml demonstrats this was default

```yaml
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaNodePool
  metadata:
    annotations:
      meta.helm.sh/release-name: kafka-dev
      meta.helm.sh/release-namespace: kafka
      strimzi.io/next-node-ids: '[100-999]'
    creationTimestamp: "2025-06-07T02:21:10Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: kafka-dev
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: sci
      app.kubernetes.io/version: 1.16.0
      helm.sh/chart: strimzi-cluster-instance-0.0.1-20250606220625
      helm.toolkit.fluxcd.io/name: kafka-dev
      helm.toolkit.fluxcd.io/namespace: kafka
      strimzi.io/cluster: kafka-dev-sci
    name: kafka-dev-sci-controller
    namespace: kafka
    resourceVersion: "160521"
    uid: a8a4ebcd-ac3c-4230-9a51-eb51278dfa7e
  spec:
    replicas: 3
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
    roles:
    - controller
    storage:
      type: jbod
      volumes:
      - id: 0
        kraftMetadata: shared
        sizeLimit: 64Gi
        type: ephemeral
```

### Expected behavior

Per doc 
```yaml
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                        - CLUSTER-NAME-kafka
                topologyKey: "kubernetes.io/hostname"
```

However the doc version is also problematic because this would prevent two pods from the same cluster which may from the same host. The most correct version should only have antiaffinity for the nodepool

```yaml
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/cluster
                      operator: In
                      values:
                        - CLUSTER-NAME
                    - key: strimzi.io/cluster
                      operator: In strimzi.io/pool-name
                      values:
                        - POOL_NAME
                topologyKey: "kubernetes.io/hostname"
```

### Strimzi version

0.46.0

### Kubernetes version

K8s 1.33

### Installation method

yaml

### Infrastructure

kind

### Configuration files and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

This PR implements the [Strimzi Proposal 123](https://github.com/strimzi/proposals/blob/main/123-remove-default-pod-anti-affinity-rules-when-rack-awareness-is-enabled.md) and removes the default preferred pod-anti-affinity rules when rack awareness is used.

This should resolve #11509.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ModelUtils.java [hunk 1]
```diff
@@ -186,54 +188,65 @@ public static List<String> getLinesWithoutCommentsAndEmptyLines(String config) {
...
-            // User has specified some Node Selector Terms => we should enhance them
-            List<NodeSelectorTerm> oldTerms = userAffinity.getNodeAffinity().getRequiredDuringSchedulingIgnoredDuringExecution().getNodeSelectorTerms();
-            List<NodeSelectorTerm> enhancedTerms = new ArrayList<>(oldTerms.size());
-
-            for (NodeSelectorTerm term : oldTerms) {
-                NodeSelectorTerm enhancedTerm = new NodeSelectorTermBuilder(term)
-                        .addToMatchExpressions(selector)
-                        .build();
-                enhancedTerms.add(enhancedTerm);
+                // User has specified some Node Selector Terms => we should enhance them
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ModelUtils.java]: what does this comment exactly mean? Mostly the part "we should enhance them"?

File: documentation/modules/configuring/con-config-kafka-kraft.adoc [hunk 2]
```diff
@@ -169,6 +169,7 @@ spec:
 <16> ADVANCED OPTION: Container image configuration, which is recommended only in special situations.
 <17> Authorization enables simple, OAuth 2.0, custom, or OPA (deprecated) authorization on the Kafka broker. Simple authorization uses the `StandardAuthorizer` Kafka plugin.
 <18> Rack awareness configuration to spread replicas across different racks, data centers, or availability zones. The `topologyKey` must match a node label containing the rack ID. The example used in this configuration specifies a zone using the standard `{K8sZoneLabel}` label.
+     You should use it together with custom `topologySpreadConstraint` or `affnity` rules for spreading the Pods across the zones.
```
Comment (ppatierno) [inline documentation/modules/configuring/con-config-kafka-kraft.adoc]:
```suggestion
     You should use it together with custom `topologySpreadConstraint` or `affinity` rules for spreading the Pods across the zones.
```

File: documentation/modules/configuring/proc-distributing-brokers-across-zones.adoc [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+
+.Prerequisites
+
+* xref:deploying-cluster-operator-str[The Cluster Operator must be deployed.]  
+
+.Procedure
+
+. Configure `rack` in the `Kafka` resource and `topologySpreadConstraints` in the `KafkaNodePool` resources.
++
+Make sure the `strimzi.io/cluster` label in the `topologySpreadConstraint` `labelSelector` field is set to the name of your Kafka cluster.
```
Comment (ppatierno) [inline documentation/modules/configuring/proc-distributing-brokers-across-zones.adoc]:
```suggestion
Make sure the `strimzi.io/cluster` label in the `topologySpreadConstraint[ ].labelSelector` field is set to the name of your Kafka cluster.
```

... or something better? Don't we use something similar when referring to a field which is part of an object within an array?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ModelUtils.java (hunk 1 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ModelUtils.java]: That describes how we go through the node selector terms and _enhance_ them by adding our own selector into them.

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ModelUtils.java]: I tried to improve the comment a bit - hope it helps.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ModelUtils.java [hunk 4]
```diff
@@ -186,54 +188,65 @@ public static List<String> getLinesWithoutCommentsAndEmptyLines(String config) {
...
-            // User has specified some Node Selector Terms => we should enhance them
-            List<NodeSelectorTerm> oldTerms = userAffinity.getNodeAffinity().getRequiredDuringSchedulingIgnoredDuringExecution().getNodeSelectorTerms();
-            List<NodeSelectorTerm> enhancedTerms = new ArrayList<>(oldTerms.size());
-
-            for (NodeSelectorTerm term : oldTerms) {
-                NodeSelectorTerm enhancedTerm = new NodeSelectorTermBuilder(term)
-                        .addToMatchExpressions(selector)
-                        .build();
-                enhancedTerms.add(enhancedTerm);
+                // User has specified some Node Selector Terms => we should enhance them by injecting out own selector to the matchExpressions
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ModelUtils.java]:
```suggestion
                // User has specified some Node Selector Terms => we should enhance them by injecting our own selector to the matchExpressions
```

**Review by ppatierno — APPROVED** [review]
LGTM. Just one nit.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ModelUtils.java (hunk 1 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ModelUtils.java]: Thanks.

File: documentation/api/io.strimzi.api.kafka.model.common.Rack.adoc [hunk 5]
```diff
@@ -38,8 +38,8 @@ NOTE: The _rack_ in which brokers are running can change in some cases when the
 As a result, the replicas running in different racks might then share the same rack.
 Use Cruise Control and the `KafkaRebalance` resource with the `RackAwareGoal` to make sure that replicas remain distributed across different racks.
 
-When rack awareness is enabled in the `Kafka` custom resource, Strimzi will automatically add the Kubernetes `preferredDuringSchedulingIgnoredDuringExecution` affinity rule to distribute the Kafka brokers across the different racks.
-However, the _preferred_ rule does not guarantee that the brokers will be spread.
+When rack awareness is enabled, Strimzi will automatically add a node affinity rule to make sure the Kafka nodes are scheduled on one Kubernetes workers with the `topologyKey` label present.
```
Comment (PaulRMellor) [inline documentation/api/io.strimzi.api.kafka.model.common.Rack.adoc]:
```suggestion
When rack awareness is enabled, Strimzi adds a node affinity rule to ensure Kafka nodes are scheduled on Kubernetes workers that include the specified `topologyKey` label. 
```

File: documentation/api/io.strimzi.api.kafka.model.common.Rack.adoc [hunk 6]
```diff
@@ -38,8 +38,8 @@ NOTE: The _rack_ in which brokers are running can change in some cases when the
...
+It will not add any rules for distributing the Kafka nodes across the racks or zones.
```
Comment (PaulRMellor) [inline documentation/api/io.strimzi.api.kafka.model.common.Rack.adoc]:
```suggestion
It does not configure additional rules to distribute nodes across racks or zones.
```

File: documentation/modules/configuring/con-common-configuration.adoc [hunk 7]
```diff
@@ -158,12 +159,17 @@ Enable rack-aware broker assignment to improve fault tolerance.
...
-  # ...  
+rack:
+  topologyKey: topology.kubernetes.io/zone
+# ...
 ----
 
+IMPORTANT: With the rack awareness enabled, Strimzi will automatically set the rack (zone) information from the `topologyKey` label in the Kafka configuration.
+It will also automatically add a node affinity rule to make sure the Pods are scheduled only on the nodes that have the `topologyKey` label.
+But it will not add any anti-affinity or topology spread constraints to spread the Pods across the racks/zones.
+To do so, make sure to add your own rules in the `Kafka` or `KafkaNodePool` custom resources.
```
Comment (PaulRMellor) [inline documentation/modules/configuring/con-common-configuration.adoc]:
```suggestion
IMPORTANT: When rack awareness is enabled, Strimzi sets the rack (zone) information in the `Kafka` configuration using the `topologyKey` label. 
It also adds a node affinity rule to schedule Pods only on nodes that include this label. 
Strimzi does not add anti-affinity rules or topology spread constraints to distribute Pods across racks or zones. 
To configure distribution, define your own rules in the `Kafka` or `KafkaNodePool` custom resources.
```

File: documentation/modules/configuring/con-config-kafka-kraft.adoc [hunk 8]
```diff
@@ -169,6 +169,7 @@ spec:
 <16> ADVANCED OPTION: Container image configuration, which is recommended only in special situations.
 <17> Authorization enables simple, OAuth 2.0, custom, or OPA (deprecated) authorization on the Kafka broker. Simple authorization uses the `StandardAuthorizer` Kafka plugin.
 <18> Rack awareness configuration to spread replicas across different racks, data centers, or availability zones. The `topologyKey` must match a node label containing the rack ID. The example used in this configuration specifies a zone using the standard `{K8sZoneLabel}` label.
+     You should use it together with custom `topologySpreadConstraint` or `affinity` rules for spreading the Pods across the zones.
```
Comment (PaulRMellor) [inline documentation/modules/configuring/con-config-kafka-kraft.adoc]:
```suggestion
Use rack awareness together with custom `topologySpreadConstraint` or `affinity` rules to distribute Kafka broker pods (replicas) across zones.
```

File: documentation/modules/configuring/proc-distributing-brokers-across-zones.adoc [hunk 9]
```diff
@@ -0,0 +1,84 @@
...
+
+// Module included in the following assemblies:
+//
+// assembly-scheduling.adoc
+
+[id='proc-distributing-brokers-across-zones-{context}']
+= Distributing brokers across availability zones
+
+[role="_abstract"]
+To improve fault tolerance, you should distribute your Kafka nodes across multiple different availability zones (racks).
```
Comment (PaulRMellor) [inline documentation/modules/configuring/proc-distributing-brokers-across-zones.adoc]:
```suggestion
To improve fault tolerance, distribute Kafka nodes across multiple different availability zones (racks).
```

File: documentation/modules/configuring/proc-distributing-brokers-across-zones.adoc [hunk 10]
```diff
@@ -0,0 +1,84 @@
...
+This is typically combined with the xref:con-common-config-rack-awareness-{context}[Rack awareness] feature.
+
+This procedure provides configuration examples for the `Kafka` resource with enabled rack awareness and the pool-specific `KafkaNodePool` resources with the topology spread constraints configuration to balance pods across zones.
```
Comment (PaulRMellor) [inline documentation/modules/configuring/proc-distributing-brokers-across-zones.adoc]:
```suggestion
This procedure provides configuration examples for the `Kafka` resource with rack awareness enabled, and the pool-specific `KafkaNodePool` resources with the topology spread constraints configuration to balance pods across zones.
```

File: documentation/modules/configuring/proc-distributing-brokers-across-zones.adoc [hunk 11]
```diff
@@ -0,0 +1,84 @@
...
+
+* xref:deploying-cluster-operator-str[The Cluster Operator must be deployed.]  
+
+.Procedure
+
+. Configure `rack` in the `Kafka` resource and `topologySpreadConstraints` in the `KafkaNodePool` resources.
++
+Make sure the `strimzi.io/cluster` label in the `topologySpreadConstraint[].labelSelector` fields is set to the name of your Kafka cluster.
++
+.Example cluster with rack awareness and topology spread constraints
```
Comment (PaulRMellor) [inline documentation/modules/configuring/proc-distributing-brokers-across-zones.adoc]:
```suggestion
The following configuration shows a Kafka cluster with rack awareness enabled and topology spread constraints defined in the `KafkaNodePool` resources:
+
```

**Review by PaulRMellor — APPROVED** [review]
Great. Thanks.
Just a few comments.
Outside this PR, I wonder if any of the titles in the scheduling section could be clearer about what the intended outcome will be (like the title you use for the new procedure Distributing brokers across availability zones)?  That might make it easier for users to find what they want

**Comment by scholzj** [comment]
> Outside this PR, I wonder if any of the titles in the scheduling section could be clearer about what the intended outcome will be (like the title you use for the new procedure Distributing brokers across availability zones)? That might make it easier for users to find what they want

I'm happy to talk about it. But when I was going through them while working on this PR, I did not had the feeling that they would be somehow wrong. They are by definition a bit more generic and have less defined use-case. So I think the titles naturally correspond to that as well.
