### PR TITLE
Fix paused connector status when Connect is scaled to zero

### LINKED ISSUE #9843: Flaky test: ConnectorMockTest.testConnectorResourceMetricsScaledToZero
### Bug Description

This test seems to fail randomly when running the full unit and integration test suites. Instead, it always works when running in isolation.

```sh
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] io.strimzi.operator.cluster.operator.assembly.ConnectorMockTest.testConnectorResourceMetricsScaledToZero(VertxTestContext)
[ERROR]   Run 1: ConnectorMockTest.testConnectorResourceMetricsScaledToZero(VertxTestContext) java.lang.AssertionError: 
Expected: is <0.0>
     but: was <1.0>
[ERROR]   Run 2: ConnectorMockTest.testConnectorResourceMetricsScaledToZero(VertxTestContext) java.lang.AssertionError: 
Expected: is <0.0>
     but: was <1.0>
[ERROR]   Run 3: ConnectorMockTest.testConnectorResourceMetricsScaledToZero(VertxTestContext) java.lang.AssertionError: 
Expected: is <0.0>
     but: was <1.0>
[ERROR]   Run 4: ConnectorMockTest.testConnectorResourceMetricsScaledToZero(VertxTestContext) java.lang.AssertionError: 
Expected: is <0.0>
     but: was <1.0>
[ERROR]   Run 5: ConnectorMockTest.testConnectorResourceMetricsScaledToZero(VertxTestContext) java.lang.AssertionError: 
Expected: is <0.0>
     but: was <1.0>
[ERROR]   Run 6: ConnectorMockTest.testConnectorResourceMetricsScaledToZero(VertxTestContext) java.lang.AssertionError: 
Expected: is <0.0>
     but: was <1.0>
[INFO] 
[INFO] 
[ERROR] Tests run: 2138, Failures: 1, Errors: 0, Skipped: 1
[INFO] 
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Strimzi version

main

### Kubernetes version

1.28

### Installation method

_No response_

### Infrastructure

_No response_

### Configuration files and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fvaleri**
The common strategy across operators is that a paused resource should overwrite any error in terms of status update. This is currently not happening when a connector is paused after Connect is scaled to zero.

The connector is first updated to `NotReady` by `connectorEventHandler`, and then `ReconciliationPaused` by `reconcileConnectors`. The `testConnectorResourceMetricsScaledToZero` fails randmonly because of this double status update. Besides, the test is wrong, as it does not expect the connector to be paused.

This should fix #9843.

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperator.java [hunk 1]
```diff
@@ -142,7 +142,6 @@ protected Future<KafkaConnectStatus> createOrUpdate(Reconciliation reconciliatio
         Map<String, String> podAnnotations = new HashMap<>();
         Map<String, String> controllerAnnotations = new HashMap<>();
 
-        boolean hasZeroReplicas = connect.getReplicas() == 0;
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperator.java:145]: Wat os the reason for removing this? It does not seem to be in any way relevant to the change in the code. This seems like a good way to trace all the code related to scale-to-0 problems.

**Review by scholzj — COMMENTED** [review]
One nit ... it seems to look good otherwise.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperator.java (hunk 1 above)
Comment (fvaleri) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperator.java:145]: Wdym? To me this doesn't add much value, as the information is already present in KafkaConnectCluster object.

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperator.java:145]: I think it adds value -> you can trace the variable to see where it is used to see what parts to be careful about in respect to scale-to-0. The way you rewrite it is not so easy to do anymore because you have just unlinked places that check the number of replicas.

**Review by see-quick — APPROVED** [review]
Thanks @fvaleri. Good job! 👍

**Review by scholzj — APPROVED** [review]
LGTM. I found more issues related to scale-to-zero while testing this, but they are not related to the changes from this PR (this Pr fixes what it promises to fix) and should be addressed separately.

**Review by henryZrncik — APPROVED** [review]
LGTM!

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks!
