### PR TITLE
Fix `emptyDir` `sizeLimit` handling in our CRDs

### LINKED ISSUE #12067: [Bug]: Size Limit setting for emptyDir causes StackOverError in strimzi operator
### Bug Description

I've been trying to create an emptyDir through the kafkaNodePool to use as cache for remote tiered storage segments but the operator runs in to stackOverflow error while trying to parse the emptyDir sizeLimit config.

This is pod template in kafkaNodePool CR:
`    template:
      pod:
        volumes:
          - name: cache-volume
            emptyDir:
              medium: Memory
              sizeLimit:
                amount: "1"
                format: "Gi"`

This is the error in operator logs:

`2025-10-23 02:58:04 ERROR ResourceVisitor:95 - Reconciliation #9733(watch) Kafka(kafka-shared/tiered-storage): Error while visiting [spec, kafka, template, pod, volumes, emptyDir, sizeLimit, numericalAmount, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO, ZERO,`

Also tried the k8s native way to set the sizeLimit but it seems the the strimzi spec doesn't support it
`      volumes:
        - name: tiered-storage-cache
          emptyDir:
            medium: Memory
            sizeLimit: "9Gi"`

Error:

`Error: INSTALLATION FAILED: 1 error occurred:
	* KafkaNodePool.kafka.strimzi.io "broker-tiered-storage" is invalid: spec.template.pod.volumes[3].emptyDir.sizeLimit: Invalid value: "string": spec.template.pod.volumes[3].emptyDir.sizeLimit in body must be of type object: "string"`

### Steps to reproduce

1. Create an emptyDir volume with sizeLimit in kafkaNodePool.

### Expected behavior

There should be an emptyDir volume created with the provided size limit,

### Strimzi version

0.47.0

### Kubernetes version

v1.30.3

### Installation method

helm chart

### Infrastructure

_No response_

### Configuration files and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

#12067 describes a pretty nasty bug in our CRDs. The additional volumes in the Pod template use the native Fabric8 `EmptyDirVolumeSource` class in the API model. However, this class relies on the Fabric8 `Quantity` class and this class has a structure that our CRDs cannot handle. As a result:
* The CRDs have a wrong structure for configuring the size limit of the emptyDir volumes, which does not allow using the right Kubernetes format:
  ```yaml
            emptyDir:
              sizeLimit: 10Mi
              medium: Memory
  ```
  and instead expects something like this:
  ```yaml
            emptyDir:
              sizeLimit:
                amount: 10
                format: Gi
              medium: Memory
  ```
* However, even with the wrong format generated into the CRDs, Strimzi cannot decode the it and it cannot be used.

This PR creates our own model class to replace the Fabric8 `EmptyDirVolumeSource`. It does not use `Quantity` (similarly to our storage configuration) and makes sure the CRDs use the correct layout and Strimzi can handle it.

However, strictly speaking, this breaks the compatibility of the API. Given that it:
* Introduces the correct layout intended from the beginning
* This does not work in the existing CRDs / layout anyway
* This is the first complaint about it, so nobody seems ti be using it

I think it might be ok to do this. But there is some extent of risk worth considering during the review.

This should resolve #12067 

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by ppatierno** [comment]
Trying to understanding the issue better.
Isn't it a bug within Fabric8 then? AFAICS from the Kube doc about the `EmptyDirVolumeSource` here https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#emptydirvolumesource-v1-core it should be the expected structure where `sizeLimit` is a `Quantity` (without the `amount` and `format` fields). So it looks to me it's Fabric8 using "something" different/wrong?

> However, this class relies on the Fabric8 Quantity class and this class has a structure that our CRDs cannot handle.

So it looks the `Quantity` class from Fabric8 is wrong, but then we are using it in the `TemplateUtils` class in this PR?

Can you clarify a bit the above, please?

**Comment by scholzj** [comment]
> Trying to understanding the issue better. Isn't it a bug within Fabric8 then? AFAICS from the Kube doc about the `EmptyDirVolumeSource` here https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#emptydirvolumesource-v1-core it should be the expected structure where `sizeLimit` is a `Quantity` (without the `amount` and `format` fields). So it looks to me it's Fabric8 using "something" different/wrong?
> 
> > However, this class relies on the Fabric8 Quantity class and this class has a structure that our CRDs cannot handle.
> 
> So it looks the `Quantity` class from Fabric8 is wrong, but then we are using it in the `TemplateUtils` class in this PR?
> 
> Can you clarify a bit the above, please?

But none of this is really in the Fabric8 code. This is our CRD generator that generates this. When passing the actual `EmptyDirVolumeSource` to/from Kube API, Fabric8 seems to handle it well. So I do not see any issue on their side. I guess they have custom (de)serialization routines there to handle it which we do not have. That is why we do not use `Quantity` in any of our APIs directly -> nor for memory, CPU, disk size in the storage configuration, etc. So I don't think this is a Fabric8 bug.

File: api/src/main/java/io/strimzi/api/kafka/model/common/template/EmptyDirVolume.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+@JsonPropertyOrder({"medium", "sizeLimit"})
+@EqualsAndHashCode
+@ToString
+public class EmptyDirVolume implements UnknownPropertyPreserving {
+    private EmptyDirMedium medium;
+    private String sizeLimit;
+    private Map<String, Object> additionalProperties;
+
+    @Description("Medium represents the type of storage medium should back this volume. " +
+            "Valid values are unset or `Memory`.")
```
Comment (ppatierno) [inline api/src/main/java/io/strimzi/api/kafka/model/common/template/EmptyDirVolume.java]: What would "unset" mean here? Using some default?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectClusterTest.java [hunk 2]
```diff
@@ -917,8 +918,8 @@ public void testTemplate() {
                 .withSecretName("secret1")
                 .build();
 
-        EmptyDirVolumeSource emptyDir = new EmptyDirVolumeSourceBuilder()
-                .withMedium("Memory")
+        EmptyDirVolume emptyDir = new EmptyDirVolumeBuilder()
+                .withMedium(EmptyDirMedium.MEMORY)
```
Comment (ppatierno) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectClusterTest.java:922]: We were just using a hard-coded string here, now we have an enum but with just the same "Memory" value only. Is it really needed? Are we expecting additional mediums?

File: api/src/main/java/io/strimzi/api/kafka/model/common/template/EmptyDirVolume.java (hunk 1 above)
Comment (scholzj) [reply api/src/main/java/io/strimzi/api/kafka/model/common/template/EmptyDirVolume.java]: It means you do not have to set it (in which case it will use the _node's default medium_).

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectClusterTest.java (hunk 2 above)
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectClusterTest.java:922]: Well, it is a different class/object now. The Strimzi model I created for it uses an Enum. While the Fabric8 class uses String.

Do you want to use Strimzi as well? Would you expect the validation to rely on Kubernetes only? I think the Enum provides better validation and it is easier to switch from Enum to String than the other way around.

> Are we expecting additional mediums?

The medium is really defined by Kubernetes. I'm not aware of any plans for a new type. But obviously I might not know about it.

File: api/src/main/java/io/strimzi/api/kafka/model/common/template/EmptyDirVolume.java (hunk 1 above)
Comment (ppatierno) [reply api/src/main/java/io/strimzi/api/kafka/model/common/template/EmptyDirVolume.java]: Ok, thanks ... can we clarify it by adding what you just said ... "it will use the node's default medium"?

Comment (scholzj) [reply api/src/main/java/io/strimzi/api/kafka/model/common/template/EmptyDirVolume.java]: Yeah, of course we can make it more clear. Would this work for you?

```
Medium represents the type of storage medium should back this volume.
Valid values are unset or `Memory`.
When not set, it will use the node's default medium.
```

Comment (ppatierno) [reply api/src/main/java/io/strimzi/api/kafka/model/common/template/EmptyDirVolume.java]: Absolutely! Thanks Jakub.

Comment (scholzj) [reply api/src/main/java/io/strimzi/api/kafka/model/common/template/EmptyDirVolume.java]: Ok, updated. Thanks.
