### PR TITLE
Fix upgrade from 0.19 when Kafka version is not specified in the CRD

### LINKED ISSUE #3685: [Bug] Kafka pods are infinitely rolling when the version of Kafka is not specified
**Describe the bug**

When we deploy Kafka without version on strimzi-0.19.0 and then we want to upgrade it to our master, the Kafka pods will infinitely roll. It can be caused by new listeners or by removing `tls-sidecar`.

The whole scenario you can see in `StrimziUpgradeST.testUpgradeKafkaWithoutVersion` -> that also the way how to reproduce it.

**To Reproduce**
1. Deploy CO and Kafka (without version) from Strimzi version 0.19.0 
2. Upgrade the CO
3. The pods will infinitely roll

**Expected behavior**
After upgrading to master/HEAD the pod should roll only once and the image of Kafka should be `2.6.0`.

**Environment (please complete the following information):**
 - Strimzi version: 0.19.0 and master
 - Installation method: yaml
 - Kubernetes cluster: OCP3.11, OCP4.5 (tested here)

**YAML files and logs**

https://gist.github.com/im-konge/83e5697d9944755f09b491c90b3d3160
https://gist.github.com/im-konge/68f4862452f517536b9d42b1601817f1

Don't know how much related is this:
```
2020-09-10 14:30:58,504 ERROR Exiting Kafka due to fatal exception (kafka.Kafka$) [main]
org.apache.kafka.common.config.ConfigException: Missing required configuration "zookeeper.connect" which has no default value.
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:478)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:468)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1270)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1273)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1221)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:34)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:29)
	at kafka.Kafka$.main(Kafka.scala:68)
	at kafka.Kafka.main(Kafka.scala)
```

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

Kafka upgrade can currently happen in two ways:

1) The regular one when `.spec.kafka.version` is specified happens separately from the operator upgrade. In that case the operator does first a regular rolling update (in this case for example from Strimzi 0.19.0/2.5.0 to Strimzi 0.20.0/2.5.0) and only in later phase it upgrades the Kafka to 2.6.0 when user changes the version. This means that when the Kafka upgrade happens, all the other Kubernetes resources are already updated to the new version of the operator. We want to do the upgrade as soon as possible to make sure it does just the upgrade and ideally doesn't mix in any other changes.

2) The second upgrade type happens when `.spec.kafka.version` is not specified. In that case the upgrade is done in one go - both operator upgrade as well as Kafka upgrade ((in this case for example from Strimzi 0.19.0/2.5.0 to Strimzi 0.20.0/2.6.0). This is problematic, because we start with all the services, config maps and stateful sets not updated. So ideally we want to first let the operator update all the Kube resources and only as the last thing do the upgrade roll of the Kafka pods. This means we have different requirements here from the regular Kafka upgrade.

In this PR I split the version change into 3 parts:
* The upgrade check on the beginning just checks if versions changed and upgrade is needed.
* The first upgrade call does the regular upgrade with the old statefulset and config maps from previous reconciliation. This is used only for the regular upgrade. This runs early in the reconciliation.
* The second upgrade call does the all-in-one upgrade without specified Kafka version. I called this _postponed_ and it runs only as the last part before the regular rolling update.

This should make it much easier to handle both kinds of upgrades even when there were major changes to the way the pods are configured such as happened in relation to the listener change which caused the latest issue here.

This should close #3685.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=upgrade

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 1]
```diff
@@ -896,35 +898,65 @@ private KafkaVersionChange getKafkaVersionChange(StatefulSet kafkaSts) {
...
+         * @param postponedUpgrade     Indicates the phase from which is this method called.
+         * @return
+         */
+        Future<ReconciliationState> kafkaVersionChange(boolean postponedUpgrade) {
+            boolean shouldBePostponed = kafkaAssembly.getSpec().getKafka().getVersion() == null;
 
-                        StatefulSet sts;
-                        ConfigMap cm;
+            if (versionChange == null)   {
+                log.debug("{}: Kafka versions are not known yet, upgrade iwll be skipped", reconciliation);
```
Comment (im-konge) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java:921]: Just typo ... 
```suggestion
                log.debug("{}: Kafka versions are not known yet, upgrade will be skipped", reconciliation);
```

File: systemtest/src/test/java/io/strimzi/systemtest/upgrade/StrimziUpgradeST.java [hunk 2]
```diff
@@ -180,33 +179,34 @@ void testChainUpgrade() throws Exception {
...
+        File dir = FileUtils.downloadAndUnzip(strimziReleaseWithOlderKafka);
+        File previousKafkaPersistent = new File(dir, "strimzi-" + strimziReleaseWithOlderKafkaVersion + "/examples/kafka/kafka-persistent.yaml");
+        File previousKafkaVersionsYaml = FileUtils.downloadYaml("https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/" + strimziReleaseWithOlderKafkaVersion + "/kafka-versions.yaml");
+        File latestKafkaVersionsYaml = new File(TestUtils.USER_PATH + "//../kafka-versions.yaml");
 
-        coDir = new File(dir, "strimzi-" + latestReleasedVersion + "/install/cluster-operator/");
+        coDir = new File(dir, "strimzi-" + strimziReleaseWithOlderKafkaVersion + "/install/cluster-operator/");
 
-        String latestKafkaVersion = getValueForLastKafkaVersionInFile(kafkaVersions, "version");
+        //String previousKafkaVersion = getValueForLastKafkaVersionInFile(previousKafkaVersionsYaml, "version");
```
Comment (im-konge) [inline systemtest/src/test/java/io/strimzi/systemtest/upgrade/StrimziUpgradeST.java:191]: I think that we can remove this, as we are not checking this anywhere.

**Review by im-konge — APPROVED** [review]
Just two small nits, otherwise LGTM. Thanks for this fix :)

**Comment by tombentley** [comment]
The upgrade process was never really designed for the broker upgrade to happen after updates to the other resources. Doing so means a whole bunch of things can now happen before the upgrade. It widens the window for problems if a broker were to restart spontaneously before the upgrade runs, because the broker would see resources which it maybe couldn't properly understand (it is a problem that such a windows even exists, of course...). There might not be any actual problems with that, but it makes it harder to reason about upgrades if the upgrade can happen early or late.

Did we consider just disallowing upgrade when the version is not set?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 3]
```diff
@@ -280,7 +280,8 @@ public KafkaAssemblyOperator(Vertx vertx, PlatformFeaturesAvailability pfa,
                 .compose(state -> state.kafkaManualPodCleaning())
                 .compose(state -> state.kafkaNetPolicy())
                 .compose(state -> state.kafkaManualRollingUpdate())
-                .compose(state -> state.kafkaVersionChange())
+                .compose(state -> state.kafkaVersionChangeCheck())
+                .compose(state -> state.kafkaVersionChange(false))
```
Comment (samuel-hawker) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java:284]: Do we want to use a boolean argument here, I wonder if it would be better to have two separate methods:
```
kafkaVersionChange
```
and
```
kafkaVersionChangePostponed
```

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java:284]: The methods are otherwise almost the same. So is it really worth to have separate methods duplicating the code?

Comment (samuel-hawker) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java:284]: I was thinking through this as I was reading through the method, it would be nice if they could be split, with the duplicated logic being moved out to separate methods, I started refactoring it locally and realized to rip out the boolean would be a non-trivial effort for not enough value. I thought it was worth bringing up, as boolean arguments normally can be extracted, but in this case it wouldn't be worth it.

**Review by samuel-hawker — APPROVED** [review]
LGTM, nice clean fix.

**Comment by scholzj** [comment]
> Did we consider just disallowing upgrade when the version is not set?

@tombentley I think we did in the past. I do not think this is a solution when the version field is not required (and TBH I think there are good reasons why it should not be required). What would people do if the operator tells them it will not do anything without the version? They would just add version and do the upgrade without the upgrade really being correct because maybe the version was wrong.

The solution here seemed to be best from both worlds -> it doesn't change the original upgrade procedure when the version is used. At the same time it also works fine for the case without the version.

**Review by tombentley — APPROVED** [review]
