### PR TITLE
Fix wrong escaping of OAuth configuration in Mirror Maker 2

### LINKED ISSUE #9786: [Bug]: Fail to run Mirror Maker 2 connector task when using OAUTH to connect to kafka clusters
### Bug Description

I applied Mirror Maker 2 cr, and the pod is running successfully. But I checked the status of this new connector via rest api, 
I got "caused by: java.lang.IllegalArgumentException: Value not specified for key 'XXXX(**mm2 cluster alias**)' in JAAS config"

My authentication type is "oauth", and set trustedCertificates for TLS connection to the OAuth server.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Strimzi version

0.39.0

### Kubernetes version

K8s 1.27

### Installation method

_No response_

### Infrastructure

_No response_

### Configuration files and logs

_No response_

### Additional context

I think I find the root cause of this issue, I will create a PR, and fix it.

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

The OAuth configuration in Mirror Maker 2 seems to have some bad escaping. This PR fixes it. For some reason, we were also missing MM2 in system tests for OAuth with TLS encryption. So this PR adds the system test as well.

This should resolve #9786

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

File: systemtest/src/test/java/io/strimzi/systemtest/security/oauth/OauthTlsST.java [hunk 1]
```diff
@@ -412,6 +423,187 @@ void testMirrorMaker() {
         ClientUtils.waitForClientSuccess(consumerName, Environment.TEST_SUITE_NAMESPACE, testStorage.getMessageCount());
     }
 
+    @Description("As a OAuth MirrorMaker 2, I am able to replicate Topic data using using encrypted communication")
+    @IsolatedTest("Using more tha one Kafka cluster in one Namespace")
+    @Tag(MIRROR_MAKER)
```
Comment (im-konge) [inline systemtest/src/test/java/io/strimzi/systemtest/security/oauth/OauthTlsST.java:428]:
```suggestion
    @Tag(MIRROR_MAKER2)
```

**Review by im-konge — APPROVED** [review]
LGTM, just one nit, thanks

**Review by ppatierno — APPROVED** [review]
