### PR TITLE
Roll controller-only nodes when logging configuration changes

### LINKED ISSUE #10204: [Bug]: Logging update does not effect for controllers until rolled manually
### Bug Description

We currently cannot update logging configuration dynamically for controllers because we cannot talk to controllers directly as reported here #9692. If the logging config is not dynamic, the controllers would not be rolled either. The user would need to trigger manual rolling update for controllers to change their log level. This can be solved once we can talk to the controller directly but this is currently blocked behind a bug in upstream Kafka. In the meantime,  we may need to add a workaround similar to how we handle controller config changes (we extract the controller-relevant configurations and use it in the configuration annotations). 

### Steps to reproduce

1. Deploy a cluster in KRaft mode with separate controller and broker nodes. 
2. Change the log levels by specifying the logger and level (inline), e.g.
```
  kafka:
    # ...
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "DEBUG"
```
2. Observe the logs from both brokers and controllers. Brokers produce DEBUG level logs but controllers produce INFO level logs. 
3. Trigger manual rolling update by applying the annotation on controller StrimziPodSet
4. After controller pods are rolled, they produce DEBUG level logs. 

### Expected behavior

Either controller pods are automatically rolled or dynamically updated when there is an update on the logging configuration. User should not need to trigger manual rolling update to set the log levels. 

### Strimzi version

main

### Kubernetes version

1.29

### Installation method

_No response_

### Infrastructure

_No response_

### Configuration files and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

Changes to log levels are normally done through dynamic reconfiguration. However, that is currently not available for controller-only nodes due to limitations on the Apache Kafka side. This PR changes the way the logging annotation works. Today it contains the hash only based on the appenders. But this PR changes and it and controller-only nodes uses a hash of a full logging file to ensure it rolls when logging changes. For broker-only or mixed nodes, the annotation is generated as today without any change.

This should resolve #10204.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorWithPoolsKRaftMockTest.java [hunk 1]
```diff
@@ -280,6 +280,89 @@ public void testReconcileWithControllerRelevantConfigChange(VertxTestContext con
...
+
+                    StrimziPodSet spsBrokers = supplier.strimziPodSetOperator.client().inNamespace(namespace).withName(CLUSTER_NAME + "-brokers").get();
+                    assertThat(spsBrokers, is(notNullValue()));
+
+                    spsBrokers.getSpec().getPods().stream().map(PodSetUtils::mapToPod).forEach(pod -> {
+                        // Broker annotations should be the same
+                        assertThat(pod.getMetadata().getAnnotations().get(Annotations.ANNO_STRIMZI_LOGGING_APPENDERS_HASH), is(loggingConfigurationAnnos.get(pod.getMetadata().getName())));
+                    });
+
+                    // Update Kafka with dynamically changeable controller relevant option => controller pod annotations should change
```
Comment (tinaselenge) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorWithPoolsKRaftMockTest.java:340]: Unless I'm misunderstanding, I think this should non dynamic 
```suggestion
                    // Update Kafka with not dynamically changeable option => both controller and broker pod annotations should change
```

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaReconciler.java [hunk 2]
```diff
@@ -764,7 +767,7 @@ private Map<String, String> podSetPodAnnotations(int nodeId) {
         podAnnotations.put(Ca.ANNO_STRIMZI_IO_CLUSTER_CA_CERT_GENERATION, String.valueOf(this.clusterCa.caCertGeneration()));
         podAnnotations.put(Ca.ANNO_STRIMZI_IO_CLUSTER_CA_KEY_GENERATION, String.valueOf(this.clusterCa.caKeyGeneration()));
         podAnnotations.put(Ca.ANNO_STRIMZI_IO_CLIENTS_CA_CERT_GENERATION, String.valueOf(this.clientsCa.caCertGeneration()));
-        podAnnotations.put(Annotations.ANNO_STRIMZI_LOGGING_APPENDERS_HASH, loggingHash);
+        podAnnotations.put(Annotations.ANNO_STRIMZI_LOGGING_APPENDERS_HASH, brokerLoggingHash.get(nodeId));
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaReconciler.java:770]: Maybe now the `ANNO_STRIMZI_LOGGING_APPENDERS_HASH` name is not the right one anymore, because it's not just appenders?

**Review by ppatierno — APPROVED** [review]
LGTM. Just one nit.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaReconciler.java (hunk 2 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaReconciler.java:770]: It is not, but I hope one day Kafka gets its act together and we can update it dynamically again in which case it would change back to _appenders only_. So I did not think it made sense to rename it. If you insist on it, I can do it, but otherwise I would keep it as it is.

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaReconciler.java:770]: What do we say? The hope is the last one to die ;-)

**Review by tinaselenge — APPROVED** [review]
