### PR TITLE
[systemtest] Add pull secret to Scraper pod if appropriate env variable is set

### LINKED ISSUE #7822: System test failure due to imagePullSecret being not applied to ScraperTemplate with private image
**Describe the bug**
Image pull secret not being applied into scraper pod when the system tests are run with private images. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Insert the docker secret into the default namespace.
2. Run a system test that deploys the scrapper in a namespace (e.g namespace-0).
3. Scrapper od can not able to pull the image from the private registry due to the secret not being injected in scraper deployment. 

**Expected behaviour**
Test to run successfully

**Environment (please complete the following information):**
 - Strimzi version: 0.32.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes & Minikube
 - Infrastructure: Minikube

**Additional context**
The command we run to test is:

`CLUSTER_OPERATOR_INSTALL_TYPE=HELM SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET=<<SECRET>> mvn -f pom.xml -Pall -B -V -Dit.test=KafkaST#testForTopicOperator -Djunit.jupiter.execution.parallel.enabled=false -Djunit.jupiter.execution.parallel.config.fixed.parallelism=1 verify`

To resolve this we had to add:
We have to add following lines in ScraperTemplate.java 
```
List<LocalObjectReference> imagePullSecrets  = new ArrayList<>();
if (Environment.SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET != null && !Environment.SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET.isEmpty()) {
            imagePullSecrets.add(new LocalObjectReference(Environment.SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET));
        }

.withNewSpec()
       .withImagePullSecrets(imagePullSecrets)
```

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Type of change

- Bugfix

### Description

As it is mentioned in #7822 , we are not passing the pull secret specified in `SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET` env variable to the Scraper pod template, so if the user wants to run STs with custom images in some private registry, all of the tests which are using Scraper pod will simply fail.

Fixes #7822 

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by Frawless — APPROVED** [review]

**Review by scholzj — APPROVED** [review]
LGTM. But should be reviewed by system test SMEs ;-)

File: systemtest/src/main/java/io/strimzi/systemtest/templates/specific/ScraperTemplates.java [hunk 1]
```diff
@@ -25,6 +29,13 @@ public static DeploymentBuilder scraperPod(String namespaceName, String podName)
         label.put(Constants.SCRAPER_LABEL_KEY, Constants.SCRAPER_LABEL_VALUE);
         label.put(Constants.DEPLOYMENT_TYPE, DeploymentTypes.Scraper.name());
 
+        PodSpecBuilder podSpecBuilder = new PodSpecBuilder();
+
+        if (Environment.SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET != null && !Environment.SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET.isEmpty()) {
```
Comment (fvaleri) [inline systemtest/src/main/java/io/strimzi/systemtest/templates/specific/ScraperTemplates.java:34]:
```suggestion
        if (Environment.SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET != null && !Environment.SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET.isBlank()) {
```

Comment (im-konge) [reply systemtest/src/main/java/io/strimzi/systemtest/templates/specific/ScraperTemplates.java:34]: Okay, sounds good. Thanks :)

**Review by fvaleri — APPROVED** [review]
LGTM. Thanks.
