### PR TITLE
Fixed log4j2 support for the bridge

### LINKED ISSUE #3232: [Bug] Bridge doesn't start due to wrong log4j configuration file name
The current "master" bridge doesn't start properly with the current CO "master" due to the wrong log4j configuration file name set in the corresponding ConfigMap mounted as volume for the bridge pod.
The bridge is now using log4j2 and it's searching for a log4j2.properties file on startup, while the CO still mounts the file as log4j.properties.

```shell
ERROR StatusLogger Unable to access file:/opt/strimzi/custom-config/log4j2.properties                                                                                                                                                      │
│  java.io.FileNotFoundException: /opt/strimzi/custom-config/log4j2.properties (No such file or directory)                                                                                                                                   │
│     at java.io.FileInputStream.open0(Native Method)                                                                                                                                                                                        │
│     at java.io.FileInputStream.open(FileInputStream.java:195)                                                                                                                                                                              │
│     at java.io.FileInputStream.<init>(FileInputStream.java:138)                                                                                                                                                                            │
│     at java.io.FileInputStream.<init>(FileInputStream.java:93)                                                                                                                                                                             │
│     at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)                                                                                                                                                      │
│     at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)                                                                                                                                              │
│     at org.apache.logging.log4j.core.config.ConfigurationSource.fromUri(ConfigurationSource.java:325)                                                                                                                                      │
│     at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:480)                                                                                                                   │
│     at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:473)                                                                                                                   │
│     at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:410)                                                                                                                   │
│     at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:318)                                                                                                                           │
│     at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:687)                                                                                                                                                     │
│     at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)                                                                                                                                                     │
│     at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)                                                                                                                                                           │
│     at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)                                                                                                                                     │
│     at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)                                                                                                                                      │
│     at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)                                                                                                                                                                 │
│     at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)                                                                                                                                       │
│     at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)                                                                                                                                                  │
│     at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)                                                                                                                                         │
│     at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)                                                                                                                                                   │
│     at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)                                                                                                                                                                           │
│     at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)                                                                                                                                                                           │
│     at io.strimzi.kafka.bridge.Application.<clinit>(Application.java:51) 
```

Anyway even fixing the naming problem, the content of the log4j2.properties file is wrong; it's still using old format.

### PR DESCRIPTION
**Pull request by ppatierno**
Signed-off-by: Paolo Patierno <ppatierno@live.com>

### Type of change

- Bugfix

### Description

This PR fixes #3232 allowing the cluster operator to support the bridge log4j2 properly.
This PR also replaces the closed #3085 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ppatierno** [comment]
@strimzi/maintainers this PR cannot be merged until bridge 0.17.0 is released (currently we have a 0.17.0-RC1 out)

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java [hunk 1]
```diff
@@ -1203,7 +1203,7 @@ protected String determineImagePullPolicy(ImagePullPolicy requestedImagePullPoli
         }
     }
 
-    String getAncillaryConfigMapKeyLogConfig() {
+    public String getAncillaryConfigMapKeyLogConfig() {
```
Comment (tombentley) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java:1206]: Maybe it would be better, at this point to change the value of `ANCILLARY_CM_KEY_LOG_CONFIG` to `"log4j2.properties"` and override `getAncillaryConfigMapKeyLogConfig()` on the Kafka and other things which are still log4j 1.

File: cluster-operator/src/main/resources/kafkaBridgeDefaultLoggingProperties [hunk 2]
```diff
@@ -1,9 +1,24 @@
...
-log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
-log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} %p %m (%c) [%t]%n
-bridge.root.logger=INFO
-log4j.rootLogger=${bridge.root.logger}, CONSOLE
-log4j.logger.http.openapi.operation.healthy=WARN, CONSOLE
-log4j.additivity.http.openapi.operation.healthy=false
-log4j.logger.http.openapi.operation.ready=WARN, CONSOLE
-log4j.additivity.http.openapi.operation.ready=false
\ No newline at end of file
+name = BridgeConfig
```
Comment (tombentley) [inline cluster-operator/src/main/resources/kafkaBridgeDefaultLoggingProperties:1]: So, hang on one moment. In the bridge itself we have two copies of this config, and now in the CO we're also embedding a 3rd copy. Is that really necessary?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java (hunk 1 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java:1206]: Why? For making `log4j2` the new default?

File: cluster-operator/src/main/resources/kafkaBridgeDefaultLoggingProperties (hunk 2 above)
Comment (ppatierno) [reply cluster-operator/src/main/resources/kafkaBridgeDefaultLoggingProperties:1]: This copy is from where the CO creates the configmap with the logging configuration.
The other two in the bridge project are mostly related 1) for development (in the resources) 2) in the config folder for bridge running on bare metal.

Comment (tombentley) [reply cluster-operator/src/main/resources/kafkaBridgeDefaultLoggingProperties:1]: So if the bridge classpath one is really "for development" what's it doing built into the bridge jar? If, on the other hand, that was a sensible default then there would be no need to have the default here.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java (hunk 1 above)
Comment (tombentley) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java:1206]: Yes, AFAIK all the Strimzi stuff is using log4j2 at this point. Kafka will move at some point. IDK about Zookeeper, but I'm not aware of any reason it has to be log4j 1 any more. So it makes more sense to just override this method for Kafka than having to override it for everything except Kafka.

File: cluster-operator/src/main/resources/kafkaBridgeDefaultLoggingProperties (hunk 2 above)
Comment (ppatierno) [reply cluster-operator/src/main/resources/kafkaBridgeDefaultLoggingProperties:1]: It's in the jar to avoid that you have to start your bridge in the IDE specifying a log4j2.properties file path for logging configuration.
About having it here, currently, it's placed in the configmap mounted as volume and then it is set in the bridge run script as following:

```
export KAFKA_BRIDGE_LOG4J_OPTS="-Dlog4j2.configurationFile=file:$STRIMZI_HOME/custom-config/log4j2.properties
```

using the embedded one directly then means that if we remove that line, the user cannot specify an external logging file anymore, right? And changing the default logging would mean releasing a new bridge then, while we much more release the operator often than the bridge.
Or I am just misleading your point :-)

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java (hunk 1 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java:1206]: I searched a little bit more in the code and it seems we have ZooKeeper, Kafka, Kafka Connect, Cruise Control, Mirror Maker and Mirror Maker 2 all using log4j 1 ... while just operator and bridge are using log4j2. So 6 vs 3 ... is it really useful doing the change now?

Comment (tombentley) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java:1206]: No, I guess not. 

However, we're going to have to do this at some point:

* log4jv1 has at least 1 CVE and will not be fixed, so there are good reasons to move
* Zookeeper and CC both use slf4j as a facade, so there's a good chance we could switch to using lo4j2 as the back end with no ill effects. It should be enough to grep to see if they `import` anything more than loggers.
* https://github.com/apache/kafka/pull/7898 is making steady progress, so hopefully it won't be long before Kafka changes too.

So maybe I'm a little premature, but our work here is not done.

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java:1206]: We can open an issue and propose the change to the Cruise Control community? Do you think that we should contribute to the same for ZooKeeper as well? Anyway, we rely on the ZooKeeper version brought by Kafka, right? So even if moving to log4j2 on Zookeeper we have to wait for Kafka community to takes that version.

Comment (tombentley) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java:1206]: See https://issues.apache.org/jira/browse/ZOOKEEPER-2342. The comments suggest that is basically just works, and the only reason they've stuck with v1 so far is simply for compatibility with v1 configuration syntax. Also:

```
$ grep -Fr 'import org.apache.log' .
./zookeeper-server/src/test/java/org/apache/zookeeper/audit/Log4jAuditLoggerTest.java:import org.apache.log4j.Layout;
./zookeeper-server/src/test/java/org/apache/zookeeper/audit/Log4jAuditLoggerTest.java:import org.apache.log4j.Level;
./zookeeper-server/src/test/java/org/apache/zookeeper/audit/Log4jAuditLoggerTest.java:import org.apache.log4j.Logger;
./zookeeper-server/src/test/java/org/apache/zookeeper/audit/Log4jAuditLoggerTest.java:import org.apache.log4j.SimpleLayout;
./zookeeper-server/src/test/java/org/apache/zookeeper/audit/Log4jAuditLoggerTest.java:import org.apache.log4j.WriterAppender;
./zookeeper-server/src/test/java/org/apache/zookeeper/audit/StandaloneServerAuditTest.java:import org.apache.log4j.Layout;
./zookeeper-server/src/test/java/org/apache/zookeeper/audit/StandaloneServerAuditTest.java:import org.apache.log4j.Level;
./zookeeper-server/src/test/java/org/apache/zookeeper/audit/StandaloneServerAuditTest.java:import org.apache.log4j.Logger;
./zookeeper-server/src/test/java/org/apache/zookeeper/audit/StandaloneServerAuditTest.java:import org.apache.log4j.SimpleLayout;
./zookeeper-server/src/test/java/org/apache/zookeeper/audit/StandaloneServerAuditTest.java:import org.apache.log4j.WriterAppender;
./zookeeper-server/src/test/java/org/apache/zookeeper/test/ReadOnlyModeTest.java:import org.apache.log4j.Layout;
./zookeeper-server/src/test/java/org/apache/zookeeper/test/ReadOnlyModeTest.java:import org.apache.log4j.Level;
./zookeeper-server/src/test/java/org/apache/zookeeper/test/ReadOnlyModeTest.java:import org.apache.log4j.Logger;
./zookeeper-server/src/test/java/org/apache/zookeeper/test/ReadOnlyModeTest.java:import org.apache.log4j.WriterAppender;
./zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerMainTest.java:import org.apache.log4j.Level;
./zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerMainTest.java:import org.apache.log4j.Logger;
./zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerMainTest.java:import org.apache.log4j.PatternLayout;
./zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerMainTest.java:import org.apache.log4j.WriterAppender;
```

I.e. the only place where they depend on log4j v1 is in the tests.

For CC that grep shows nothing. 

So there's pretty much nothing to do, unless you want to get bogged down in the config compatibility debate. But that needn't concern us: In both cases we could switch really easily if we wanted to, it's just a matter of writing a log4j2 config file or using v2's support for reading v1 configs: http://logging.apache.org/log4j/2.x/manual/migration.html and arranging the classpath appropriately.

**Comment by ppatierno** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.log.LogSettingST

**Comment by ppatierno** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.log.LogSettingST

**Comment by ppatierno** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.log.LogSettingST
