### PR TITLE
Fix for #6046 - Topic Operator failing to start with io.vertx.core.VertxException: Thread blocked

### LINKED ISSUE #6046: Topic Operator failing to start with io.vertx.core.VertxException: Thread blocked
**Describe the bug**
When deploying a very simple cluster with the topicOperator enabled, the topicOperator container fails to start. The logs for the container report a blocked thread. The k8s liveness check eventually kills the container. 
```
2021-12-16 00:16:50,79115 WARN  [vertx-blocked-thread-checker] BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2542 ms, time limit is 2000 ms
2021-12-16 00:16:51,79090 WARN  [vertx-blocked-thread-checker] BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3542 ms, time limit is 2000 ms
2021-12-16 00:16:52,79034 WARN  [vertx-blocked-thread-checker] BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4541 ms, time limit is 2000 ms
2021-12-16 00:16:53,79105 WARN  [vertx-blocked-thread-checker] BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5542 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?]
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194) ~[?:?]
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128) ~[?:?]
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998) ~[?:?]
	at io.apicurio.registry.utils.ConcurrentUtil.get(ConcurrentUtil.java:35) ~[io.apicurio.apicurio-registry-common-1.3.2.Final.jar:?]
	at io.apicurio.registry.utils.ConcurrentUtil.get(ConcurrentUtil.java:27) ~[io.apicurio.apicurio-registry-common-1.3.2.Final.jar:?]
	at io.apicurio.registry.utils.ConcurrentUtil.result(ConcurrentUtil.java:54) ~[io.apicurio.apicurio-registry-common-1.3.2.Final.jar:?]
	at io.strimzi.operator.topic.Session.lambda$start$9(Session.java:198) ~[io.strimzi.topic-operator-0.26.0.jar:0.26.0]
	at io.strimzi.operator.topic.Session$$Lambda$278/0x0000000840319840.handle(Unknown Source) ~[?:?]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase$$Lambda$293/0x000000084031e040.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[io.netty.netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[io.netty.netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[io.netty.netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[io.netty.netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**To Reproduce**
1. Install Strimzi Operator using the 0.26.0 helm chart
2. Create a Cluster manifest:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-basic
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:   
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
3. Apply the manifest with `kubectl apply -f kafka-basic.yaml`
4. Watch the topic operator logs with `kubectl logs deploy/kafka-basic-entity-operator -c topic-operator`

**Expected behavior**
The topic operator starts correctly. 

**Environment:**
 - Strimzi version: 0.26.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.20.7
 - Infrastructure: Amazon EKS

**YAML files and logs**
Thanks for the handy script!
[report-16-12-2021_11-26-59.zip](https://github.com/strimzi/strimzi-kafka-operator/files/7723669/report-16-12-2021_11-26-59.zip)

**Additional context**
Similar errors show up in these issues: 
https://github.com/strimzi/strimzi-kafka-operator/issues/383
https://github.com/strimzi/strimzi-kafka-operator/issues/1050
https://github.com/strimzi/strimzi-kafka-operator/issues/4964

Increasing the resource claims for the topic operator didn't change the behaviour. 

Zookeeper doesn't show any errors or timeouts.

### PR DESCRIPTION
**Pull request by LiamClarkeNZ**
### Type of change

- Bugfix

### Description

Fixes #6046 by refactoring Topic Operator startup sequence so that a slow Kafka Streams state store start up doesn't prevent the liveness probe being provisioned before the initial liveness delay expires, causing Kubernetes to kill the Topic Operator.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [X] Write tests
- [X] Make sure all tests pass
- [N/A] Update documentation
- [N/A] Check RBAC rights for Kubernetes / OpenShift roles
- [X] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [X] Reference relevant issue(s) and close them after merging
- [X] Update CHANGELOG.md
- [N/A] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

File: topic-operator/src/main/java/io/strimzi/operator/topic/Main.java [hunk 1]
```diff
@@ -25,6 +26,11 @@
 
     private final static Logger LOGGER = LogManager.getLogger(Main.class);
 
+    static String blockingWorkerPoolName = "blocking-ops-executor";
+
+    // TODO, change this if/when this worker pool is shared with ZkImpl that has its own worker pool also
+    static int blockingWorkerPoolSize  = 1;
```
Comment (scholzj) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Main.java:32]: Should these be `public / private final ...`?

Comment (scholzj) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Main.java:32]: Should these be `public / private final ...`?

**Review by scholzj — COMMENTED** [review]
Some formal comments. LGTM otherwise, but should be reviewed by SMEs.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Main.java [hunk 2]
```diff
@@ -47,7 +53,9 @@ private void deploy(Config config) {
                         .setJvmMetricsEnabled(true)
                         .setEnabled(true));
         Vertx vertx = Vertx.vertx(options);
-        Session session = new Session(kubeClient, config);
+
+        WorkerExecutor executor = vertx.createSharedWorkerExecutor(blockingWorkerPoolName, blockingWorkerPoolSize);
```
Comment (fvaleri) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Main.java:57]: Why we don't use the same approach of ZkImpl? I think that having a dedicated executor per verticle/class is safer, as you can tune its configuration without the risk of messing up other classes. Bonus: you don't need to change tests.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java [hunk 3]
```diff
@@ -171,96 +192,114 @@ public void start(Promise<Void> start) {
...
+                    start.fail(cause);
+                })
+                .onSuccess(zookeeper -> {
+                    zk = zookeeper;
+                    LOGGER.debug("Using ZooKeeper {}", zk);
+                })
+                .compose(zk -> executor.executeBlocking((Handler<Promise<TopicStore>>) storePromise -> {
+                    Instant startedAt = Instant.now();
+                    TopicStore topicStore = createTopicStore(zk, config);
+                    LOGGER.info("Topic store created, took {} ms", Duration.between(startedAt, Instant.now()).toMillis());
```
Comment (fvaleri) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:221]: Useful logging.

**Comment by fvaleri** [comment]
LGTM. I also tested it on my local Minikube (low resources, default probes):

```
$ kubectl get k my-cluster -o yaml | yq eval ".spec.entityOperator.topicOperator" -
resources:
  limits:
    cpu: 200m
    memory: 256Mi
```

And this is the result (no blocked thread warnings and restarts):

```
2022-04-07 16:36:59,19195 INFO  [kafka-admin-client-thread | adminclient-2] KafkaStreamsTopicStoreService:97 - Creating Kafka Streams, store name: topic-store
2022-04-07 16:37:02,38116 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:119 - Kafka version: 3.1.0
2022-04-07 16:37:02,38144 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:120 - Kafka commitId: 37edeed0777bacb3
2022-04-07 16:37:02,38170 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:121 - Kafka startTimeMs: 1649349422380
2022-04-07 16:37:04,78709 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:119 - Kafka version: 3.1.0
2022-04-07 16:37:04,78735 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:120 - Kafka commitId: 37edeed0777bacb3
2022-04-07 16:37:04,78755 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:121 - Kafka startTimeMs: 1649349424786
2022-04-07 16:37:07,08533 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:119 - Kafka version: 3.1.0
2022-04-07 16:37:07,18043 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:120 - Kafka commitId: 37edeed0777bacb3
2022-04-07 16:37:07,18109 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:121 - Kafka startTimeMs: 1649349427084
2022-04-07 16:37:09,78474 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:119 - Kafka version: 3.1.0
2022-04-07 16:37:09,78544 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:120 - Kafka commitId: 37edeed0777bacb3
2022-04-07 16:37:09,78610 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:121 - Kafka startTimeMs: 1649349429784
2022-04-07 16:37:18,98662 INFO  [__strimzi-topic-operator-kstreams-a3b3c139-ca18-411d-848d-63fbf85bc212-StreamThread-1] LoggingStateRestoreListener:16 - restore start: topicPartition=__strimzi-topic-operator-kstreams-topic-store-changelog-0, storeName=topic-store, startingOffset=0, endingOffset=3
2022-04-07 16:37:19,48874 INFO  [__strimzi-topic-operator-kstreams-a3b3c139-ca18-411d-848d-63fbf85bc212-StreamThread-1] LoggingStateRestoreListener:21 - batch restored: topicPartition=__strimzi-topic-operator-kstreams-topic-store-changelog-0, storeName=topic-store, batchEndOffset=2, numRestored=3
2022-04-07 16:37:19,48904 INFO  [__strimzi-topic-operator-kstreams-a3b3c139-ca18-411d-848d-63fbf85bc212-StreamThread-1] LoggingStateRestoreListener:27 - restore end: topicPartition=__strimzi-topic-operator-kstreams-topic-store-changelog-0, storeName=topic-store, totalRestored=3
2022-04-07 16:37:19,79099 INFO  [Thread-3] KafkaStreamsTopicStoreService:81 - Creating topic store ...
2022-04-07 16:37:20,08672 INFO  [Thread-4] KafkaStreamsTopicStoreService:72 - Started.
2022-04-07 16:37:20,18481 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:83 - App info kafka.admin.client for adminclient-2 unregistered
2022-04-07 16:37:20,38176 INFO  [kafka-admin-client-thread | adminclient-2] Metrics:659 - Metrics scheduler closed
2022-04-07 16:37:20,38196 INFO  [kafka-admin-client-thread | adminclient-2] Metrics:663 - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-04-07 16:37:20,38227 INFO  [kafka-admin-client-thread | adminclient-2] Metrics:669 - Metrics reporters closed
2022-04-07 16:37:20,38310 INFO  [blocking-ops-executor-0] Session:221 - Topic store created, took 36700 ms
```

File: topic-operator/src/main/java/io/strimzi/operator/topic/Main.java (hunk 1 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Main.java:32]: Good point. I've refactored them away now :)

File: topic-operator/src/main/java/io/strimzi/operator/topic/Main.java (hunk 2 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Main.java:57]: @fvaleri I was trying to make the executor a dependency I could replace at test time, but there was not actual point in doing so now that I've written some tests :)

File: pom.xml [hunk 4]
```diff
@@ -592,6 +592,12 @@
                 <version>${mockito.version}</version>
                 <scope>test</scope>
             </dependency>
+            <dependency>
```
Comment (LiamClarkeNZ) [inline pom.xml:595]: Using mockito-inline in TO to mock statics.

File: topic-operator/pom.xml [hunk 5]
```diff
@@ -17,6 +17,10 @@
         </license>
     </licenses>
 
+    <properties>
+        <mockito.version>4.4.0</mockito.version>
+    </properties>
+
```
Comment (LiamClarkeNZ) [inline topic-operator/pom.xml:23]: Overrode Mockito version here to pick up better API

File: topic-operator/pom.xml [hunk 6]
```diff
@@ -141,7 +145,7 @@
         </dependency>
         <dependency>
             <groupId>org.mockito</groupId>
-            <artifactId>mockito-core</artifactId>
+            <artifactId>mockito-inline</artifactId>
```
Comment (LiamClarkeNZ) [inline topic-operator/pom.xml:148]: Use Mockito inline to mock statics

File: topic-operator/pom.xml [hunk 7]
```diff
@@ -214,6 +218,15 @@
...
             </plugin>
+            <plugin>
+                <groupId>org.apache.maven.plugins</groupId>
+                <artifactId>maven-surefire-plugin</artifactId>
+                <configuration>
+                    <systemPropertyVariables>
+                        <vertx.logger-delegate-factory-class-name>io.strimzi.operator.topic.vertx.OverrideBlockedThreadCheckerLoggerDelegateFactory</vertx.logger-delegate-factory-class-name>
+                    </systemPropertyVariables>
+                </configuration>
+            </plugin>
```
Comment (LiamClarkeNZ) [inline topic-operator/pom.xml:229]: Added this system property as part of my Rube Goldberg machine to override the BlockedThreadChecker's logger, as that's the only way to hook into it for unit testing - maybe the unit test isn't worth the overhead?

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java [hunk 8]
```diff
@@ -61,23 +74,51 @@
...
+    /**
+     * Constructor is package private for testing
+     *
+     * @param kubeClient         kubernetes client
+     * @param config             TopicOperator config
+     * @param topicStoreCreator  indirection to allow unit testing of start-up sequence with mock topicstore creation
+     * @param zkClientCreator    indirection to allow unit testing of start-up sequence with mock ZK client creation
+     * @param topicOperatorState used to communicate liveness/readiness to health server from things that can potentially fail
+     */
+    Session(KubernetesClient kubeClient, Config config, BiFunction<Zk, Config, TopicStore> topicStoreCreator, BiFunction<Vertx, Config, Future<Zk>> zkClientCreator, TopicOperatorState topicOperatorState) {
```
Comment (LiamClarkeNZ) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:102]: So this is the new improved package private constructor for unit testing so that I can swap out creation of the Zk that uses a static factory method (but in a different thread, where Mockito's mockStatic capacity can't reach it), and the creation of the TopicOperatorStore that is either created via a static factory or a direct instantiation.

Comment (LiamClarkeNZ) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:102]: So this is the new improved package private constructor for unit testing so that I can swap out creation of the Zk that uses a static factory method (but in a different thread, where Mockito's mockStatic capacity can't reach it), and the creation of the TopicOperatorStore that is either created via a static factory or a direct instantiation.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java [hunk 9]
```diff
@@ -61,23 +74,51 @@
...
             sb.append("\t").append(v.key).append(": ").append(Util.maskPassword(v.key, config.get(v).toString())).append(System.lineSeparator());
         }
         LOGGER.info("Using config:{}", sb.toString());
         this.metricsRegistry = (PrometheusMeterRegistry) BackendRegistries.getDefaultNow();
     }
 
+    @Override
+    public void init(Vertx vertx, Context context) {
+        super.init(vertx, context);
+        executor = vertx.createSharedWorkerExecutor("blocking-startup-ops", 1);
```
Comment (LiamClarkeNZ) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:119]: @fvaleri took your advice, and moved worker pool creation inside :)

Comment (LiamClarkeNZ) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:119]: @fvaleri took your advice, and moved worker pool creation inside :)

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java [hunk 10]
```diff
@@ -171,96 +212,116 @@ public void start(Promise<Void> start) {
...
+                    start.complete();
+                    topicOperatorState.setReady(true);
+                    LOGGER.info("Started");
+                })
+                .onFailure(cause -> {
+                    topicOperatorState.setAlive(false);
+                    start.fail(cause);
+                    LOGGER.error("Topic operator start up failed, cause was", cause);
+                });
+    }
```
Comment (LiamClarkeNZ) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:235]: I had to refactor this chain due to my misunderstanding of how Vert.x futures work - basically, if a future fails, the failed future is passed along. 

Previously when I had multiple `onFailure` clauses, they were triggering when an upstream future failed, causing misleading log messages (e.g., the ZK client failing to create would trigger its `onFailure` but then also trigger the `onFailure` clause that followed the topic store creation).

So now I rely on the fact that the argument to a single arg `compose` call is only ever called when the previous future is successful, so will never trigger for a failed previous future.

So I've a) refactored some onSuccess/onFailure handlers out to join their parent future in their own method so we still log on success/failure, but having it in a separate method keeps this chain cleaner. 
and b) as a failed future will be passed all the way down the chain, all of the code around failing the start up promise, and setting the topicOperatorState liveness, can be handled in one onFailure at the very end.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java (hunk 3 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Session.java]: Thanks :)

**Comment by LiamClarkeNZ** [comment]
> LGTM. I also tested it on my local Minikube (low resources, default probes):
> 
> ```
> $ kubectl get k my-cluster -o yaml | yq eval ".spec.entityOperator.topicOperator" -
> resources:
>   limits:
>     cpu: 200m
>     memory: 256Mi
> ```
> 
> And this is the result (no blocked thread warnings and restarts):
> 
> ```
> 2022-04-07 16:36:59,19195 INFO  [kafka-admin-client-thread | adminclient-2] KafkaStreamsTopicStoreService:97 - Creating Kafka Streams, store name: topic-store
> 2022-04-07 16:37:02,38116 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:119 - Kafka version: 3.1.0
> 2022-04-07 16:37:02,38144 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:120 - Kafka commitId: 37edeed0777bacb3
> 2022-04-07 16:37:02,38170 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:121 - Kafka startTimeMs: 1649349422380
> 2022-04-07 16:37:04,78709 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:119 - Kafka version: 3.1.0
> 2022-04-07 16:37:04,78735 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:120 - Kafka commitId: 37edeed0777bacb3
> 2022-04-07 16:37:04,78755 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:121 - Kafka startTimeMs: 1649349424786
> 2022-04-07 16:37:07,08533 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:119 - Kafka version: 3.1.0
> 2022-04-07 16:37:07,18043 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:120 - Kafka commitId: 37edeed0777bacb3
> 2022-04-07 16:37:07,18109 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:121 - Kafka startTimeMs: 1649349427084
> 2022-04-07 16:37:09,78474 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:119 - Kafka version: 3.1.0
> 2022-04-07 16:37:09,78544 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:120 - Kafka commitId: 37edeed0777bacb3
> 2022-04-07 16:37:09,78610 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:121 - Kafka startTimeMs: 1649349429784
> 2022-04-07 16:37:18,98662 INFO  [__strimzi-topic-operator-kstreams-a3b3c139-ca18-411d-848d-63fbf85bc212-StreamThread-1] LoggingStateRestoreListener:16 - restore start: topicPartition=__strimzi-topic-operator-kstreams-topic-store-changelog-0, storeName=topic-store, startingOffset=0, endingOffset=3
> 2022-04-07 16:37:19,48874 INFO  [__strimzi-topic-operator-kstreams-a3b3c139-ca18-411d-848d-63fbf85bc212-StreamThread-1] LoggingStateRestoreListener:21 - batch restored: topicPartition=__strimzi-topic-operator-kstreams-topic-store-changelog-0, storeName=topic-store, batchEndOffset=2, numRestored=3
> 2022-04-07 16:37:19,48904 INFO  [__strimzi-topic-operator-kstreams-a3b3c139-ca18-411d-848d-63fbf85bc212-StreamThread-1] LoggingStateRestoreListener:27 - restore end: topicPartition=__strimzi-topic-operator-kstreams-topic-store-changelog-0, storeName=topic-store, totalRestored=3
> 2022-04-07 16:37:19,79099 INFO  [Thread-3] KafkaStreamsTopicStoreService:81 - Creating topic store ...
> 2022-04-07 16:37:20,08672 INFO  [Thread-4] KafkaStreamsTopicStoreService:72 - Started.
> 2022-04-07 16:37:20,18481 INFO  [kafka-admin-client-thread | adminclient-2] AppInfoParser:83 - App info kafka.admin.client for adminclient-2 unregistered
> 2022-04-07 16:37:20,38176 INFO  [kafka-admin-client-thread | adminclient-2] Metrics:659 - Metrics scheduler closed
> 2022-04-07 16:37:20,38196 INFO  [kafka-admin-client-thread | adminclient-2] Metrics:663 - Closing reporter org.apache.kafka.common.metrics.JmxReporter
> 2022-04-07 16:37:20,38227 INFO  [kafka-admin-client-thread | adminclient-2] Metrics:669 - Metrics reporters closed
> 2022-04-07 16:37:20,38310 INFO  [blocking-ops-executor-0] Session:221 - Topic store created, took 36700 ms
> ```

Thank you very much for checking that @fvaleri - I've added a unit test that _should_ be able to pick up blocking, but I have yet to see how it runs in the CI environment, so may end up deleting it, as it was a bit of a hack to connect my unit test to the blocked thread checker.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java [hunk 11]
```diff
@@ -171,96 +212,116 @@ public void start(Promise<Void> start) {
...
-                    if (topicStore == null) {
-                        return; // [1]
-                    }
-                }
+        startHealthServer(topicOperatorState)
+                .onFailure(cause -> LOGGER.error("Failed to start health server", cause))
+                .onSuccess(httpServer -> healthServer = httpServer)
+                .compose(ignored -> zkClientCreator.apply(vertx, config))
+                .onSuccess(zookeeper -> zk = zookeeper)
+                .compose(zk -> executor.executeBlocking(createTopicStoreAsync(zk, config)))
```
Comment (LiamClarkeNZ) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:220]: To verify that the test `SessionStartupDoesNotBlockMainThreadTest.java` is actually verifying correct behaviour, change this line to 

```
                .compose(zk -> {
                    Promise<TopicStore> promise = Promise.promise();
                    createTopicStore(zk, config, start).handle(promise);
                    return promise.future();
                })
```

to bring back the old blocking behaviour.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java (hunk 9 above)
Comment (fvaleri) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:119]: Great, much cleaner and safer.

File: topic-operator/pom.xml (hunk 5 above)
Comment (tombentley) [reply topic-operator/pom.xml:23]: Any reason not to bump it globally?

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java (hunk 8 above)
Comment (tombentley) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:102]: Parameters in separate lines, to avoid the long line.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java (hunk 10 above)
Comment (tombentley) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:235]: There vertx Javadocs are pretty good, but I've always thought it's pretty easy to miss the significance of the word 'this' (meaning the method receiver) in those docs. Note also there's a two parameter version of `compose` which takes one handler for success and another for failure, which _can_ be clearer, but not if you're passing lambdas where the fact that there are two arguments is easily lost. If both args are method references then it's fine.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java [hunk 12]
```diff
@@ -171,96 +212,116 @@ public void start(Promise<Void> start) {
...
+                .compose(topicStore -> createTopicOperatorAndZkWatchers(labels, namespace, topicStore))
+                .compose(this::createK8sWatcher)
+                .onSuccess(this::createPeriodicReconcileTrigger)
+                .onSuccess(ignored -> {
+                    start.complete();
+                    topicOperatorState.setReady(true);
+                    LOGGER.info("Started");
+                })
+                .onFailure(cause -> {
+                    topicOperatorState.setAlive(false);
```
Comment (tombentley) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:231]: IDK, just from looking at the diff, if it's guaranteed that only the context thread will call these lambdas on all possible paths. If we don't know then maybe using `volatile` on the fields of `TopicOperatorState` could avoid a stale read.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java (hunk 11 above)
Comment (tombentley) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:220]: Why not put the `executeBlocking` call inside `createTopicStoreAsync`?

File: topic-operator/pom.xml (hunk 5 above)
Comment (LiamClarkeNZ) [reply topic-operator/pom.xml]: Nope, have done so now :)

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java (hunk 8 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Session.java]: Done.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java (hunk 11 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Session.java]: Done :)

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java (hunk 12 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:235]: Done :)

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java [hunk 13]
```diff
@@ -171,96 +216,116 @@ public void start(Promise<Void> start) {
...
-                }
+        startHealthServer(topicOperatorState)
+                .onFailure(cause -> LOGGER.error("Failed to start health server", cause))
+                .onSuccess(httpServer -> healthServer = httpServer)
+                .compose(ignored -> zkClientCreator.apply(vertx, config))
+                .onSuccess(zookeeper -> zk = zookeeper)
+                .compose(zk -> createTopicStoreAsync(zk, config))
+                .onSuccess(topicStore -> LOGGER.debug("Using TopicStore {}", topicStore))
+                .compose(topicStore -> createTopicOperatorAndZkWatchers(labels, namespace, topicStore))
+                .compose(this::createK8sWatcher)
```
Comment (tombentley) [inline topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:227]: Looking at `startWatcher` (which is called by `createK8sWatcher`)... it looks like it could block in the kube client.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java (hunk 10 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Session.java]: Yeah, I was looking at the two param compose, but as you said, it made things harder to read with lambdas.

File: topic-operator/src/main/java/io/strimzi/operator/topic/Session.java (hunk 13 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:227]: Cheers @tombentley, I'll guard against that.

Comment (LiamClarkeNZ) [reply topic-operator/src/main/java/io/strimzi/operator/topic/Session.java:227]: I've added a unit test to verify that the changes work.:)

File: topic-operator/pom.xml (hunk 7 above)
Comment (LiamClarkeNZ) [reply topic-operator/pom.xml:231]: Done :)

**Review by tombentley — APPROVED** [review]

**Comment by tombentley** [comment]
@scholzj are you happy for this to be merged now?

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR!
