### PR TITLE
Prevent tests passing when they should fail, fix for #5161

### LINKED ISSUE #5161: Some unit tests using Vert.x extensions can pass incorrectly
**Describe the bug**
Due to how the Vert.x Junit extension code is being used, some unit tests can pass when they should fail.

**To Reproduce**
1. Go to PlatformFeaturesAvailabilityTest.java
2. In any test method calling `startMockApi()`, change an assertion to fail. 
3. Run the test and it will pass

**Expected behavior**

Tests that should fail should fail. 

**Environment (please complete the following information):**
 - Strimzi version: 0.25.0-SNAPSHOT
 - Installation method: N/A
 - Kubernetes cluster: N/A
 - Infrastructure: N/A

**YAML files and logs**

N/A

**Additional context**

This issue affects other unit tests in the Strimzi codebase that utilise Vert.x checkpoints.

### PR DESCRIPTION
**Pull request by LiamClarkeNZ**
### Type of change

- Bugfix

### Description

Fixes #5161 
Removes nearly all usages of checkpoints, as erroneous use can cause tests to pass when they should fail. 
Of all tests modified, only 7 failed with the checkpoints removed, and none of them failed because the code under test was incorrect, failures were mostly due to mocking issues.

Nearly all checkpoint usages weren't erroneous, but chose to replace them with calls to `VertxTestContext#completeNow` to make the completion of the context explicit, instead of relying on the implicit completion of the context when the last checkpoint is flagged. 

### Checklist

- [X] Write tests
- [X] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [X] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java [hunk 1]
```diff
@@ -274,17 +262,17 @@ Admin ac() {
     @Test
     public void testBelowMinIsr(VertxTestContext context) {
         KSB ksb = new KSB()
-            .addNewTopic("A", false)
-                .addToConfig(TopicConfig.MIN_IN_SYNC_REPLICAS_CONFIG, "2")
-                .addNewPartition(0)
+            .addNewTopic("A")
+                .addToConfig("2")
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java:266]: Wasn't it much more readable before when it was clear what the `2` meant? It is called `addToConfig` to add configuration to the topic. It is not called `setMinInSyncReplicas`. So I think this is wrong.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java [hunk 2]
```diff
@@ -274,17 +262,17 @@ Admin ac() {
...
+                .addNewPartition()
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java:267]: Are you sure the partition number will not be needed in the future for example?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java [hunk 3]
```diff
@@ -274,17 +262,17 @@ Admin ac() {
...
                     .leader(0)
                     .isr(0, 1)
                 .endPartition()
             .endTopic()
-            .addNewTopic("B", false)
-                .addToConfig(TopicConfig.MIN_IN_SYNC_REPLICAS_CONFIG, "2")
-                .addNewPartition(0)
+            .addNewTopic("B")
+                .addToConfig("2")
+                .addNewPartition()
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java:275]: Same as above and everywhere else in this file.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java [hunk 4]
```diff
@@ -449,19 +448,17 @@ private TestingKafkaRoller rollerWithControllers(StatefulSet sts, PodOperator po
 
     private void doSuccessfulConfigUpdate(VertxTestContext testContext, TestingKafkaRoller kafkaRoller,
                                             List<Integer> expected) {
-        Checkpoint async = testContext.checkpoint();
         kafkaRoller.rollingRestart(pod -> emptyList())
                 .onComplete(testContext.succeeding(v -> {
                     testContext.verify(() -> assertThat(restarted(), is(expected)));
                     assertNoUnclosedAdminClient(testContext, kafkaRoller);
-                    async.flag();
+                    testContext.completeNow();
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java:455]: How do we know the test ends here? That sounds like a bad practice which will cause problems later because the test will be ended here and ingnore some followup code?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java [hunk 5]
```diff
@@ -472,7 +469,7 @@ private void doSuccessfulRollingRestart(VertxTestContext testContext, TestingKaf
             .onComplete(testContext.succeeding(v -> {
                 testContext.verify(() -> assertThat(restarted(), is(expected)));
                 assertNoUnclosedAdminClient(testContext, kafkaRoller);
-                async.flag();
+                testContext.completeNow();
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java:472]: Same as above.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java [hunk 6]
```diff
@@ -180,20 +176,14 @@ public void testConnectionTimeout(VertxTestContext context)  {
         ZooKeeperAdmin mockZooAdmin = mock(ZooKeeperAdmin.class);
         when(mockZooAdmin.getState()).thenReturn(ZooKeeper.States.NOT_CONNECTED);
 
-        ZooKeeperAdminProvider zooKeeperAdminProvider = new ZooKeeperAdminProvider() {
-            @Override
-            public ZooKeeperAdmin createZookeeperAdmin(String connectString, int sessionTimeout, Watcher watcher, ZKClientConfig conf) throws IOException {
-                return mockZooAdmin;
-            }
-        };
+        ZooKeeperAdminProvider zooKeeperAdminProvider = (connectString, sessionTimeout, watcher, conf) -> mockZooAdmin;
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java:179]: Wasn't the original code more readable? I have no idea what does this mean.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java [hunk 7]
```diff
@@ -206,21 +196,17 @@ public void testNoChange(VertxTestContext context) throws KeeperException, Inter
...
 
-        ZooKeeperAdminProvider zooKeeperAdminProvider = new ZooKeeperAdminProvider() {
-            @Override
-            public ZooKeeperAdmin createZookeeperAdmin(String connectString, int sessionTimeout, Watcher watcher, ZKClientConfig conf) throws IOException {
-                watcher.process(new WatchedEvent(null, Watcher.Event.KeeperState.SyncConnected, null));
-                return mockZooAdmin;
-            }
+        ZooKeeperAdminProvider zooKeeperAdminProvider = (connectString, sessionTimeout, watcher, conf) -> {
+            watcher.process(new WatchedEvent(null, Watcher.Event.KeeperState.SyncConnected, null));
+            return mockZooAdmin;
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java:201]: Same as above.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java [hunk 8]
```diff
@@ -238,21 +224,17 @@ public void testWithChange(VertxTestContext context) throws KeeperException, Int
...
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java:229]: Same as above.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java [hunk 9]
```diff
@@ -267,32 +249,27 @@ public void testWhenThrows(VertxTestContext context) throws KeeperException, Int
...
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java:254]: Same as above.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java [hunk 10]
```diff
@@ -303,20 +280,14 @@ public void testConnectionClosedOnGetConfigFailure(VertxTestContext context) thr
         when(mockZooAdmin.getConfig(false, null)).thenThrow(KeeperException.ConnectionLossException.class);
         when(mockZooAdmin.close(1_000)).thenThrow(InterruptedException.class);
 
-        ZooKeeperAdminProvider zooKeeperAdminProvider = new ZooKeeperAdminProvider() {
-            @Override
-            public ZooKeeperAdmin createZookeeperAdmin(String connectString, int sessionTimeout, Watcher watcher, ZKClientConfig conf) throws IOException {
-                return mockZooAdmin;
-            }
-        };
+        ZooKeeperAdminProvider zooKeeperAdminProvider = (connectString, sessionTimeout, watcher, conf) -> mockZooAdmin;
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java:283]: Same as above

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java [hunk 11]
```diff
@@ -71,9 +66,8 @@ private void runTest(Vertx vertx, VertxTestContext context, String userTaskID, i
                     response.getJson().getString("Status"),
                     is(CruiseControlUserTaskStatus.COMPLETED.toString()))
             );
-            checkpoint.flag();
             return Future.succeededFuture(response);
-        });
+        }).onComplete(x -> context.completeNow());
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java:70]: This looks dangerous because you complete the test from a method which is not a test it self.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java [hunk 12]
```diff
@@ -99,33 +93,29 @@ public void testCCUserTaskDelayVerbose(Vertx vertx, VertxTestContext context) th
     @Test
     public void testMockCCServerPendingCallsOverride(Vertx vertx, VertxTestContext context) throws IOException, URISyntaxException {
 
-        CruiseControlApi client = new CruiseControlApiImpl(vertx);
-        String userTaskID = MockCruiseControl.REBALANCE_NO_GOALS_RESPONSE_UTID;
-
         int pendingCalls1 = 2;
-        Checkpoint firstPending = context.checkpoint(pendingCalls1);
         int pendingCalls2 = 4;
-        Checkpoint secondPending = context.checkpoint(pendingCalls2);
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java:108]: How is this checked now when you do not use the async checkpoints?

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java [hunk 13]
```diff
@@ -7,157 +7,155 @@
...
-        KubernetesClient client = new DefaultKubernetesClient("127.0.0.1:" + mockHttp.actualPort());
-
-        Checkpoint a = context.checkpoint();
-
-        PlatformFeaturesAvailability.create(vertx, client).onComplete(context.succeeding(pfa -> context.verify(() -> {
-            assertThat("Versions are not equal", pfa.getKubernetesVersion(), is(KubernetesVersion.V1_20));
-            stopMockApi(context, mockHttp);
-            a.flag();
-        })));
+    @Disabled
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:74]: Why is this disabled? Or maybe why i this present?

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java [hunk 14]
```diff
@@ -7,157 +7,155 @@
...
+                                            "}";
+    private Vertx vertx;
+    private KubernetesClient kubernetesClient;
+
+    @BeforeEach
+    void setup(Vertx vertx) throws ExecutionException, InterruptedException {
+        this.vertx = vertx;
+
+        //Default to no apis.
+        apis = List::of;
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:60]: Can't we just create empty list?

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java [hunk 15]
```diff
@@ -7,157 +7,155 @@
...
+        version = () -> defaultVersion;
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:61]: What does this do?

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java [hunk 16]
```diff
@@ -7,157 +7,155 @@
...
+
+        mockHttp = waitForMockApiServer(vertx);
+        kubernetesClient = new DefaultKubernetesClient("127.0.0.1:" + mockHttp.actualPort());
     }
 
-    @AfterAll
-    public static void after() {
-        vertx.close();
+    @AfterEach
+    void cleanup() throws ExecutionException, InterruptedException {
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:68]: I think that in most cases we call it `teardown` or `afterAll`.

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java [hunk 17]
```diff
@@ -7,157 +7,155 @@
...
+                        "  \"gitVersion\": \"v1.20.1\",\n" +
+                        "  \"gitCommit\": \"c4d752765b3bbac2237bf87cf0b1c2e307844666\",\n" +
+                        "  \"gitTreeState\": \"clean\",\n" +
+                        "  \"buildDate\": \"2020-12-18T12:09:25Z\",\n" +
+                        "  \"goVersion\": \"go1.15.5\",\n" +
+                        "  \"compiler\": \"gc\",\n" +
+                        "  \"platform\": \"linux/amd64\"\n" +
+                        "}";
+
+        verify(context, pfa ->  assertThat("Versions are not equal", pfa.getKubernetesVersion(), is(KubernetesVersion.V1_20)));
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:110]: What is the point of these tests? 
* Why do they check which version it isn't instead of which version it is?
* How do these two tests differ? The version info seems to be exactly the same

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java [hunk 18]
```diff
@@ -7,157 +7,155 @@
...
+                        "  \"gitVersion\": \"v1.20.1\",\n" +
+                        "  \"gitCommit\": \"c4d752765b3bbac2237bf87cf0b1c2e307844666\",\n" +
+                        "  \"gitTreeState\": \"clean\",\n" +
+                        "  \"buildDate\": \"2020-12-18T12:00:47Z\",\n" +
+                        "  \"goVersion\": \"go1.15.5\",\n" +
+                        "  \"compiler\": \"gc\",\n" +
+                        "  \"platform\": \"linux/amd64\"\n" +
+                        "}";
+
+        verify(context, pfa -> assertThat("Versions are not equal", pfa.getKubernetesVersion(), is(KubernetesVersion.V1_20)));
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:93]: How does this create the `PlatformFeaturesAvailability`?

File: operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java [hunk 19]
```diff
@@ -66,16 +70,17 @@ public static void after() {
     public void testSuccessfulReconcile(VertxTestContext context)  {
         MetricsProvider metrics = createCleanMetricsProvider();
 
-        AbstractWatchableStatusedResourceOperator resourceOperator = resourceOperatorWithExistingResource();
+        FooWatchableStatusedResourceOperator resourceOperator = resourceOperatorWithExistingResource();
+
+        FooOperator operator = new FooOperator(vertx, "TestResource", resourceOperator, metrics, null) {
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java:75]: Why do we need to rename these?

File: operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java [hunk 20]
```diff
@@ -109,24 +113,24 @@ protected Status createStatus() {
...
 
     @Test
     public void testFailingReconcile(VertxTestContext context)  {
         MetricsProvider metrics = createCleanMetricsProvider();
 
-        AbstractWatchableStatusedResourceOperator resourceOperator = resourceOperatorWithExistingResource();
+        FooWatchableStatusedResourceOperator resourceOperator = resourceOperatorWithExistingResource();
 
-        AbstractOperator operator = new AbstractOperator(vertx, "TestResource", resourceOperator, metrics, null) {
+        FooOperator operator = new FooOperator(vertx, "TestResource", resourceOperator, metrics, null) {
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java:126]: Why do we have to rename these?

File: operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java [hunk 21]
```diff
@@ -321,15 +321,13 @@ protected Status createStatus() {
...
-                                .tag("kind", "TestResource")
-                                .tag("name", "my-resource")
-                                .tag("resource-namespace", "my-namespace")
-                                .gauge();
-                    });
+                    assertThrows(MeterNotFoundException.class, () -> registry.get(AbstractOperator.METRICS_PREFIX + "resource.state")
+                                                                             .tag("kind", "TestResource")
+                                                                             .tag("name", "my-resource")
+                                                                             .tag("resource-namespace", "my-namespace")
+                                                                             .gauge());
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java:328]: Why do we need to reformat this?

File: operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java [hunk 22]
```diff
@@ -342,11 +340,11 @@ public void testReconcileAll(VertxTestContext context)  {
         resources.add(new NamespaceAndName("my-namespace", "vtid"));
         resources.add(new NamespaceAndName("my-namespace", "utv"));
 
-        AbstractWatchableStatusedResourceOperator resourceOperator = resourceOperatorWithExistingResource();
+        FooWatchableStatusedResourceOperator resourceOperator = resourceOperatorWithExistingResource();
 
-        AbstractOperator operator = new AbstractOperator(vertx, "TestResource", resourceOperator, metrics, null) {
+        FooOperator operator = new FooOperator(vertx, "TestResource", resourceOperator, metrics, null) {
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java:345]: Why do we need to rename this?

File: operator-common/src/test/java/io/strimzi/operator/common/operator/resource/AbstractCustomResourceOperatorIT.java [hunk 23]
```diff
@@ -114,53 +113,45 @@ public void after() {
...
 
         LOGGER.info("Getting Kubernetes version");
         PlatformFeaturesAvailability.create(vertx, client)
-                .onComplete(context.succeeding(pfa -> context.verify(() -> {
-                    assertThat("Kubernetes version : " + pfa.getKubernetesVersion() + " is too old",
-                            pfa.getKubernetesVersion().compareTo(KubernetesVersion.V1_16), CoreMatchers.is(not(lessThan(0))));
-                })))
+                .onComplete(context.succeeding(pfa -> context.verify(() ->
+                        assertThat("Kubernetes version : " + pfa.getKubernetesVersion() + " is too old",
+                        pfa.getKubernetesVersion().compareTo(KubernetesVersion.V1_16), CoreMatchers.is(not(lessThan(0)))))))
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/common/operator/resource/AbstractCustomResourceOperatorIT.java:124]: Can we indent this line to make it more readable?

File: operator-common/src/test/java/io/strimzi/operator/common/operator/resource/AbstractCustomResourceOperatorIT.java [hunk 24]
```diff
@@ -114,53 +113,45 @@ public void after() {
...
-                .onComplete(context.succeeding(rrDeleted ->  async.flag()));
+                .onComplete(context.succeeding(rrDeleted ->  context.completeNow()));
     }
 
 
     /**
      * Tests what happens when the resource is deleted while updating the status
      *
-     * @param context
+     * @param context - vertx test context
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/common/operator/resource/AbstractCustomResourceOperatorIT.java:149]: Should this have the ` - `?

File: operator-common/src/test/java/io/strimzi/operator/common/operator/resource/AbstractCustomResourceOperatorIT.java [hunk 25]
```diff
@@ -169,60 +160,53 @@ public void testUpdateStatusAfterResourceDeletedThrowsKubernetesClientException(
...
-                    async.flag();
+                    context.completeNow();
                 })));
     }
 
     /**
      * Tests what happens when the resource is modified while updating the status
      *
-     * @param context
+     * @param context - vertx test context
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/common/operator/resource/AbstractCustomResourceOperatorIT.java:189]: Same as above

File: topic-operator/src/test/java/io/strimzi/operator/topic/MockKafka.java [hunk 26]
```diff
@@ -60,7 +60,8 @@ public MockKafka setTopicMetadataResponse(Function<TopicName, Future<TopicMetada
         return this;
     }
 
-    public MockKafka setTopicMetadataResponses(Function<TopicName, Future<TopicMetadata>>... topicMetadataRespose) {
+    @SafeVarargs
```
Comment (scholzj) [inline topic-operator/src/test/java/io/strimzi/operator/topic/MockKafka.java:63]: Why do we need this?

File: topic-operator/src/test/java/io/strimzi/operator/topic/MockKafka.java [hunk 27]
```diff
@@ -231,10 +232,20 @@ public void assertEmpty(VertxTestContext context) {
     }
 
     public void assertContains(VertxTestContext context, Topic topic) {
+        System.out.println(topic.getTopicName());
+        System.out.println(topic);
+        System.out.println(topics.get(topic.getTopicName()));
```
Comment (scholzj) [inline topic-operator/src/test/java/io/strimzi/operator/topic/MockKafka.java:237]: Should this be deleted?

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java [hunk 28]
```diff
@@ -109,18 +105,15 @@ public void createMockKube(VertxTestContext context) throws Exception {
...
                 topicsConfigWatcher = session.topicConfigsWatcher;
                 topicWatcher = session.topicWatcher;
                 topicsWatcher = session.topicsWatcher;
                 metrics = session.metricsRegistry;
-                metrics.forEachMeter(meter -> {
-                    metrics.remove(meter);
-                });
-                async.flag();
+                metrics.forEachMeter(meter -> metrics.remove(meter));
+                context.completeNow();
```
Comment (scholzj) [inline topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java:116]: Maybe I do not understand how the `context.completeNow` is used. But how can it be that we use it in `@BeforeEach` and in `@AfterEach` as well. That does not seem to make sense to me.

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorTest.java [hunk 29]
```diff
@@ -1235,119 +1125,100 @@ public void testReconcileAllTopics_listMapsFails(VertxTestContext context) {
...
             MeterRegistry registry = metrics.meterRegistry();
 
             assertThat(registry.get(TopicOperator.METRICS_PREFIX + "reconciliations").tag("kind", "KafkaTopic").counter().count(), is(2.0));
             assertThat(registry.get(TopicOperator.METRICS_PREFIX + "resources.paused").tag("kind", "KafkaTopic").gauge().value(), is(1.0));
-            assertThat(registry.get(TopicOperator.METRICS_PREFIX + "reconciliations.successful").tag("kind", "KafkaTopic").counter().count(), is(2.0));
+            assertThat(registry.get(TopicOperator.METRICS_PREFIX + "reconciliations.successful").tag("kind", "KafkaTopic").counter().count(), is(1.0));
             assertThat(registry.get(TopicOperator.METRICS_PREFIX + "reconciliations.failed").tag("kind", "KafkaTopic").counter().count(), is(0.0));
 
-            assertThat(registry.get(TopicOperator.METRICS_PREFIX + "reconciliations.duration").tag("kind", "KafkaTopic").timer().count(), is(2L));
+            assertThat(registry.get(TopicOperator.METRICS_PREFIX + "reconciliations.duration").tag("kind", "KafkaTopic").timer().count(), is(1L));
```
Comment (scholzj) [inline topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorTest.java:1191]: Sounds weird when we are changing the numbers. Why are the new ones correct?

File: user-operator/src/test/java/io/strimzi/operator/user/operator/KafkaUserQuotasIT.java [hunk 30]
```diff
@@ -413,13 +408,10 @@ private boolean isPathExist(String path) {
...
     private String encodeUsername(String username) {
-        try {
-            return URLEncoder.encode(username, "UTF-8");
-        } catch (UnsupportedEncodingException e) {
-            throw new RuntimeException("Failed to encode username", e);
-        }
+        return URLEncoder.encode(username, StandardCharsets.UTF_8);
     }
 
+    @SuppressWarnings("SameParameterValue")
```
Comment (scholzj) [inline user-operator/src/test/java/io/strimzi/operator/user/operator/KafkaUserQuotasIT.java:414]: Why is this needed?

**Review by scholzj — COMMENTED** [review]
TBH, I'm not sure this PR is reviewable. I spent more than one hour on it, but the amount of changes which seem completely unrelated is so huge that I have absolutely no idea if the changes relevant to the subject make any sense or not.

**Comment by LiamClarkeNZ** [comment]
> TBH, I'm not sure this PR is reviewable. I spent more than one hour and half on it, but the amount of changes which seem completely unrelated is so huge that I have absolutely no idea if the changes relevant to the subject make any sense or not.

Kia ora Jakub, 

Thanks for the feedback, I'm still getting used to the PR based workflow, and you're dead right - I've made too many unrelated changes, so the signal/noise ratio for actual change is low.

I was working to an old model of mine where you "fixed all the yellow (warnings) in every file you touch", but that was in an organisation that used pair programming and CI/CD on every branch instead of PR code review. 

So, firstly I'll go through and reply to your questions on this one, and then next I'll start preparing an update to this PR that has only the changes directly relevant to the referenced bug.

File: api-conversion/src/test/java/io/strimzi/kafka/api/conversion/cli/ConvertResourceCommandSampleResourcesIT.java [hunk 31]
```diff
@@ -91,20 +92,24 @@ public void convertInvalidSampleResources()    {
...
-            StringWriter sw = new StringWriter();
+
             PrintWriter pw = new PrintWriter(sw);
             cmd.setOut(pw);
             cmd.setErr(pw);
 
             int exitCode = cmd.execute("convert-resource", "--namespace", NAMESPACE);
             assertThat("Checking exit code for conversion of " + testFile + " is " + expectedExitCode, exitCode, is(expectedExitCode));
+        } catch (AssertionError e) {
+            System.out.println(sw);
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply api-conversion/src/test/java/io/strimzi/kafka/api/conversion/cli/ConvertResourceCommandSampleResourcesIT.java:111]: The `StringWriter` and `PrintWriter`  were already there, not being consumed, and this test had failed when I had a GH Action running the integration tests, but the only output was the error code (1), so I made use of the existing `StringWriter` in any future failures.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java [hunk 32]
```diff
@@ -169,11 +166,12 @@ public static void after() {
                 } else {
                     reconcileCasComplete.fail(ar.cause());
                 }
-                async.flag();
+                context.completeNow();
             });
         return reconcileCasComplete.future();
     }
 
+    @SuppressWarnings("ResultOfMethodCallIgnored")
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java:174]: Intellij flags certain IO method calls where  the result (that indicates success or failure) is ignored ,as warnings, in this case 

```
            clusterCaKeyFile.delete();
            clusterCaCertFile.delete();
            clusterCaStoreFile.delete();
```

I know not everyone uses IDEA,  but I want to reduce warning noise, so that we can focus on warnings that are significant.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java [hunk 33]
```diff
@@ -185,6 +183,7 @@ private CertAndKey generateCa(OpenSslCertManager certManager, CertificateAuthori
                 .withCommonName(commonName).build();
 
             certManager.generateSelfSignedCert(clusterCaKeyFile, clusterCaCertFile, sbj, ModelUtils.getCertificateValidity(certificateAuthority));
+            String clusterCaStorePassword = "123456";
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java:186]: It's only used in one place, so didn't need to be a field. I should inline it though.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java [hunk 34]
```diff
@@ -731,10 +720,11 @@ public void testNewCertsGetGeneratedWhenInRenewalPeriodAutoWithinMaintenanceWind
                 String newClientsCaKey = clientsCaKeyData.remove(CA_KEY);
                 assertThat(newClientsCaKey, is(notNullValue()));
                 assertThat(newClientsCaKey, is(initialClientsCaKeySecret.getData().get(CA_KEY)));
-                async.flag();
+                context.completeNow();
             })));
     }
 
+    @SuppressWarnings("OptionalGetWithoutIsPresent")
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java:727]: IDEA complains when you call `.get()` on an `Optional<T>` without calling `isPresent()` first - as the `Optional#get` can throw an exception if the value is null (which `isPresent` checks)

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java [hunk 35]
```diff
@@ -934,10 +922,11 @@ public void testNewKeyGeneratedWhenInRenewalPeriodAutoOutsideOfTimeWindow(VertxT
                 assertThat(newClientsCaKey, is(notNullValue()));
                 assertThat(newClientsCaKey, is(initialClientsCaKeySecret.getData().get(CA_KEY)));
 
-                async.flag();
+                context.completeNow();
             })));
     }
 
+    @SuppressWarnings("OptionalGetWithoutIsPresent")
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java:929]: IDEA complains when you call `.get()` on an `Optional<T>` without calling `isPresent()` first - as the `Optional#get` can throw an exception if the value is null (which `isPresent` checks)

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java [hunk 36]
```diff
@@ -1062,6 +1050,7 @@ private X509Certificate x509Certificate(String newClusterCaCert) throws Certific
                 .generateCertificate(new ByteArrayInputStream(Base64.getDecoder().decode(newClusterCaCert)));
     }
 
+    @SuppressWarnings("ResultOfMethodCallIgnored")
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java:1053]: As per the prior comment, IDEA flags ignored return values of IO methods indicating success/failure as a warning.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/ConnectorMockTest.java [hunk 37]
```diff
@@ -124,13 +120,14 @@ String key(String host, String connectorName) {
...
-        List<Map> tasks = singletonList(task);
+        List<Map<String, Object>> tasks = List.of(task);
         statusNode.put("tasks", tasks);
 
+        //noinspection ConstantConditions - Intellij thinks connectorState is never null, I'm unsure, so will disable this warning
         return connectorState != null ? Future.succeededFuture(statusNode) : Future.failedFuture("No such connector " + connectorName);
     }
 
-    @SuppressWarnings({"checkstyle:MethodLength"})
+    @SuppressWarnings({"checkstyle:MethodLength", "deprecation"})
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/ConnectorMockTest.java:130]: `KafkaConnectS2I`

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/ConnectorMockTest.java [hunk 38]
```diff
@@ -349,52 +343,47 @@ public void teardown() {
...
             resource.waitUntilCondition(predicate, 5, TimeUnit.SECONDS);
         } catch (Exception e) {
-            if (!(e instanceof TimeoutException)) {
-                throw new RuntimeException(e);
-            }
-            String conditions =
-                    resource.get().getStatus() == null ? "no status" :
-                            String.valueOf(resource.get().getStatus().getConditions());
-            fail(resourceName + " never matched required predicate: " + conditions);
+            //Previously we were special casing TimeoutException, but it's never thrown
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/ConnectorMockTest.java:350]: See next comment.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/ConnectorMockTest.java [hunk 39]
```diff
@@ -349,52 +343,47 @@ public void teardown() {
...
         try {
             resource.waitUntilCondition(predicate, 5, TimeUnit.SECONDS);
         } catch (Exception e) {
-            if (!(e instanceof TimeoutException)) {
-                throw new RuntimeException(e);
-            }
-            String conditions =
-                    resource.get().getStatus() == null ? "no status" :
-                            String.valueOf(resource.get().getStatus().getConditions());
-            fail(resourceName + " never matched required predicate: " + conditions);
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/ConnectorMockTest.java:362]: It's never reached, as any `TimeoutException` thrown in the `fabric8` method call is caught and handled within it. 

``` 
// io.fabric8.kubernetes.client.dsl.base.BaseOperation#waitUntilConditionWithRetries, line 1158
catch (TimeoutException e) {
        break;
}
```

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/JbodStorageTest.java [hunk 40]
```diff
@@ -131,38 +130,36 @@ private void init() {
...
+                for (int podId = 0; podId < this.kafka.getSpec().getKafka().getReplicas(); podId++) {
                     for (SingleVolumeStorage volume : this.volumes) {
                         if (volume instanceof PersistentClaimStorage) {
 
                             String expectedPvcName = VolumeUtils.getVolumePrefix(volume.getId()) + "-" + KafkaCluster.kafkaPodName(NAME, podId);
                             List<PersistentVolumeClaim> matchingPvcs = pvcs.stream()
                                     .filter(pvc -> pvc.getMetadata().getName().equals(expectedPvcName))
                                     .collect(Collectors.toList());
-                            assertThat("Exactly one pvc should have the name " + expectedPvcName + " in :\n" + pvcs.toString(),
+                            assertThat("Exactly one pvc should have the name " + expectedPvcName + " in :\n" + pvcs,
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/JbodStorageTest.java:157]: No, was just the unnecessary call to `.toString`

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorMockTest.java [hunk 41]
```diff
@@ -498,22 +491,23 @@ public void testReconcileUpdatesKafkaPersistentVolumes(Params params, VertxTestC
...
             })));
     }
 
-    private Resource<Kafka> kafkaAssembly(String namespace, String name) {
+    @SuppressWarnings("deprecation")
+    private Resource<Kafka> kafkaAssembly() {
         CustomResourceDefinition crd = client.apiextensions().v1().customResourceDefinitions().withName(Kafka.CRD_NAME).get();
         return client.customResources(CustomResourceDefinitionContext.fromCrd(crd), Kafka.class, KafkaList.class)
-                .inNamespace(namespace).withName(name);
+                .inNamespace(KafkaAssemblyOperatorMockTest.NAMESPACE).withName(KafkaAssemblyOperatorMockTest.CLUSTER_NAME);
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorMockTest.java:510]: Yep, fair enough, I'll roll that back.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorMockTest.java [hunk 42]
```diff
@@ -826,16 +814,14 @@ private void reconcileZkVersionChange(VertxTestContext context, String initialKa
...
                 updatedKafka);
 
-        Checkpoint async = context.checkpoint();
         initialReconcile(context)
-            .onComplete(context.succeeding())
             .compose(v -> initialState.getKafkaClusterDescription())
             .compose(v -> initialState.prepareVersionChange())
             .compose(v -> initialState.getZookeeperDescription())
-            .compose(state -> state.zkVersionChange())
+            .compose(KafkaAssemblyOperator.ReconciliationState::zkVersionChange)
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorMockTest.java:821]: I'll definitely take this feedback into consideration when I reiterate over this PR.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorNonParametrizedTest.java [hunk 43]
```diff
@@ -673,10 +660,10 @@ public MockKafkaAssemblyOperatorForIngressTests(
...
         Future<Void> reconcile(ReconciliationState reconcileState)  {
             return reconcileState.getKafkaClusterDescription()
-                    .compose(state -> state.kafkaIngresses())
-                    .compose(state -> state.kafkaIngressesV1Beta1())
-                    .compose(state -> state.kafkaIngressesReady())
-                    .compose(state -> state.kafkaIngressesV1Beta1Ready())
+                    .compose(ReconciliationState::kafkaIngresses)
+                    .compose(ReconciliationState::kafkaIngressesV1Beta1)
+                    .compose(ReconciliationState::kafkaIngressesReady)
+                    .compose(ReconciliationState::kafkaIngressesV1Beta1Ready)
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorNonParametrizedTest.java:666]: No worries.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorTest.java [hunk 44]
```diff
@@ -167,8 +169,8 @@
     private static Storage kafkaStorage;
     private static SingleVolumeStorage zkStorage;
     private static EntityOperatorSpec eoConfig;
-    private static MockCertManager certManager = new MockCertManager();
-    private static PasswordGenerator passwordGenerator = new PasswordGenerator(10, "a", "a");
+    private static final MockCertManager CERT_MANAGER = new MockCertManager();
+    private static final PasswordGenerator PASSWORD_GENERATOR = new PasswordGenerator(10, "a", "a");
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorTest.java:173]: Unsure, they were already static, I just made them `final`.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorTest.java [hunk 45]
```diff
@@ -1163,10 +1161,10 @@ private void updateCluster(VertxTestContext context, Kafka originalAssembly, Kaf
         // Mock Deployment get
         if (originalEntityOperator != null) {
             when(mockDepOps.get(clusterNamespace, EntityOperator.entityOperatorName(clusterName))).thenReturn(
-                    originalEntityOperator.generateDeployment(true, Collections.EMPTY_MAP, null, null)
+                    originalEntityOperator.generateDeployment(true, Map.of(), null, null)
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorTest.java:1164]: `Collections.EMPTY_MAP` is a raw type, it returns `Map`, Map.of() returns a `Map<K, V>` with `K` and `V` inferred from the context, in this case, `generateDeployment` takes a `Map<String, String`. 

https://rules.sonarsource.com/java/RSPEC-1596

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorTest.java [hunk 46]
```diff
@@ -1383,33 +1381,26 @@ public void testReconcile(Params params, VertxTestContext context) {
...
                 config) {
             @Override
             public Future<KafkaStatus> createOrUpdate(Reconciliation reconciliation, Kafka kafkaAssembly) {
                 String name = kafkaAssembly.getMetadata().getName();
-                if ("foo".equals(name)) {
-                    fooAsync.flag();
-                } else if ("bar".equals(name)) {
-                    barAsync.flag();
-                } else {
+                if (!"foo".equals(name) && !"bar".equals(name)) {
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorTest.java:1392]: Good point, I will revert this.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaBridgeAssemblyOperatorTest.java [hunk 47]
```diff
@@ -327,15 +313,6 @@ public void testCreateOrUpdateUpdatesCluster(VertxTestContext context) {
...
 
-        ConfigMap loggingCm = new ConfigMapBuilder().withNewMetadata()
-                    .withName(KafkaBridgeResources.metricsAndLogConfigMapName(kbName))
-                    .withNamespace(kbNamespace)
-                    .endMetadata()
-                    .withData(Collections.singletonMap(AbstractModel.ANCILLARY_CM_KEY_LOG_CONFIG, LOGGING_CONFIG))
-                    .build();
-
-        when(mockCmOps.get(kbNamespace, KafkaBridgeResources.metricsAndLogConfigMapName(kbName))).thenReturn(metricsCm);
-
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaBridgeAssemblyOperatorTest.java:338]: It was unused in the test. I'm unsure if we're missing testing around it, or if it's left over from copy  and paste test cases. I deleted it simply because it was unused.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaBridgeAssemblyOperatorTest.java [hunk 48]
```diff
@@ -556,32 +528,29 @@ public void testCreateOrUpdateWithScaleDown(VertxTestContext context) {
...
 
-        Map<String, Object> metricsCm = new HashMap<>();
-        metricsCm.put("foo", "bar");
-
         KafkaBridge foo = ResourceUtils.createKafkaBridge(kbNamespace, "foo", image, 1,
                 BOOTSTRAP_SERVERS, KAFKA_BRIDGE_PRODUCER_SPEC, KAFKA_BRIDGE_CONSUMER_SPEC, KAFKA_BRIDGE_HTTP_SPEC, true);
         KafkaBridge bar = ResourceUtils.createKafkaBridge(kbNamespace, "bar", image, 1,
                 BOOTSTRAP_SERVERS, KAFKA_BRIDGE_PRODUCER_SPEC, KAFKA_BRIDGE_CONSUMER_SPEC, KAFKA_BRIDGE_HTTP_SPEC, true);
 
+        //noinspection unchecked
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaBridgeAssemblyOperatorTest.java:553]: It suppresses a warning about unchecked assignment when using a Mockito matcher for Optional<T>` because you can't compile `any(Optional<LabelSelector>.class)` so have to write `any(Optional.class)`

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperatorTest.java [hunk 49]
```diff
@@ -893,16 +888,9 @@ public void assertCreateClusterWithDuplicateOlderConnect(VertxTestContext contex
...
-        Checkpoint async = context.checkpoint();
         ops.reconcile(new Reconciliation("test-trigger", KafkaConnect.RESOURCE_KIND, kc.getMetadata().getNamespace(), kc.getMetadata().getName()))
             .onComplete(context.succeeding(v -> context.verify(() -> {
 
-                // No metrics config  => no CMs created
-                Set<String> metricsNames = new HashSet<>();
-                if (connect.isMetricsEnabled()) {
-                    metricsNames.add(KafkaConnectResources.metricsAndLogConfigMapName(kc.getMetadata().getName()));
-                }
-
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperatorTest.java:905]: Could well be, I just deleted unused code.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectS2IAssemblyOperatorTest.java [hunk 50]
```diff
@@ -86,6 +87,7 @@
 import static org.mockito.Mockito.verify;
 import static org.mockito.Mockito.when;
 
+@SuppressWarnings({"deprecation", "HttpUrlsUsage"})
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectS2IAssemblyOperatorTest.java:90]: Intellij warns that statements like `assertThat(connectStatus.getUrl(), is("http://foo-connect-api.test.svc:8083"))` aren't secure because it's `http` not `https`. It's probably a bit pedantic, so was an easy choice to suppress.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectS2IAssemblyOperatorTest.java [hunk 51]
```diff
@@ -900,14 +897,15 @@ public void testCreateClusterStatusNotReady(VertxTestContext context) {
...
+                context.completeNow();
             })));
     }
 
+    @SuppressWarnings("unchecked")
     public void createClusterWithDuplicateOlderConnect(VertxTestContext context, KafkaConnectS2I kcs2i, boolean connectorOperator) {
         ResourceOperatorSupplier supplier = ResourceUtils.supplierWithMocks(true);
-        CrdOperator mockConnectS2IOps = supplier.connectS2IOperator;
-        CrdOperator mockConnectOps = supplier.connectOperator;
+        CrdOperator<OpenShiftClient, KafkaConnectS2I, KafkaConnectS2IList> mockS2IConnectOps = supplier.connectS2IOperator;
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectS2IAssemblyOperatorTest.java:907]: Just added the actual types to remove warnings about the usage of raw types.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectS2IAssemblyOperatorTest.java [hunk 52]
```diff
@@ -1061,8 +1058,8 @@ public void testCreateClusterWitDuplicateOlderConnectWithConnectorOperator(Vertx
     @Test
     public void testCreateClusterWithSameNameAsConnectFails(VertxTestContext context) {
         ResourceOperatorSupplier supplier = ResourceUtils.supplierWithMocks(true);
-        CrdOperator mockConnectS2IOps = supplier.connectS2IOperator;
-        CrdOperator mockConnectOps = supplier.connectOperator;
+        CrdOperator<OpenShiftClient, KafkaConnectS2I, KafkaConnectS2IList> mockS2IConnectOps = supplier.connectS2IOperator;
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectS2IAssemblyOperatorTest.java:1061]: Just added the actual types to remove warnings about the usage of raw types.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaMirrorMaker2AssemblyOperatorTest.java [hunk 53]
```diff
@@ -145,14 +147,8 @@ public void testCreateCluster(VertxTestContext context) {
...
         KafkaMirrorMaker2Cluster mirrorMaker2 = KafkaMirrorMaker2Cluster.fromCrd(Reconciliation.DUMMY_RECONCILIATION, kmm2, VERSIONS);
 
-        Checkpoint async = context.checkpoint();
         ops.reconcile(new Reconciliation("test-trigger", KafkaMirrorMaker2.RESOURCE_KIND, kmm2Namespace, kmm2Name))
             .onComplete(context.succeeding(v -> context.verify(() -> {
-                // No metrics config  => no CMs created
-                Set<String> metricsNames = new HashSet<>();
-                if (mirrorMaker2.isMetricsEnabled()) {
-                    metricsNames.add(KafkaMirrorMaker2Resources.metricsAndLogConfigMapName(kmm2Name));
-                }
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaMirrorMaker2AssemblyOperatorTest.java:155]: Could well be. Once again, just deleted unused code.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaMirrorMaker2AssemblyOperatorTest.java [hunk 54]
```diff
@@ -810,15 +797,8 @@ public void testCreateClusterWithJmxEnabled(VertxTestContext context) {
...
 
-        Checkpoint async = context.checkpoint();
         ops.reconcile(new Reconciliation("test-trigger", KafkaMirrorMaker2.RESOURCE_KIND, kmm2Namespace, kmm2Name))
                 .onComplete(context.succeeding(v -> context.verify(() -> {
-                    // No metrics config  => no CMs created
-                    Set<String> metricsNames = new HashSet<>();
-                    if (mirrorMaker2.isMetricsEnabled()) {
-                        metricsNames.add(KafkaMirrorMaker2Resources.metricsAndLogConfigMapName(kmm2Name));
-                    }
-
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaMirrorMaker2AssemblyOperatorTest.java:821]: Same as above, I'm unsure.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaMirrorMakerAssemblyOperatorTest.java [hunk 55]
```diff
@@ -145,15 +145,8 @@ public void testCreateCluster(VertxTestContext context) {
...
                 VERSIONS);
 
-        Checkpoint async = context.checkpoint();
         ops.reconcile(new Reconciliation("test-trigger", KafkaMirrorMaker.RESOURCE_KIND, kmmNamespace, kmmName))
             .onComplete(context.succeeding(v -> context.verify(() -> {
-                // No metrics config  => no CMs created
-                Set<String> metricsNames = new HashSet<>();
-                if (mirror.isMetricsEnabled()) {
-                    metricsNames.add(KafkaMirrorMakerResources.metricsAndLogConfigMapName(kmmName));
-                }
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaMirrorMakerAssemblyOperatorTest.java:155]: Ditto

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaMirrorMakerAssemblyOperatorTest.java [hunk 56]
```diff
@@ -606,8 +595,6 @@ public void testReconcile(VertxTestContext context) {
 
         Set<String> createdOrUpdated = new CopyOnWriteArraySet<>();
 
-        Checkpoint createdOrUpdateAsync = context.checkpoint(2);
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaMirrorMakerAssemblyOperatorTest.java:609]: Further down, it's asserting that both `MirrorMaker` _foo_ and _bar_ were created, so the checkpoint was superfluous.

```
        // Now try to reconcile all the Kafka Mirror Maker clusters
        ops.reconcileAll("test", kmmNamespace,
            context.succeeding(v -> context.verify(() -> {
                assertThat(createdOrUpdated, is(new HashSet(asList("foo", "bar"))));
                context.completeNow();
            })));
```

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaUpgradeDowngradeMockTest.java [hunk 57]
```diff
@@ -187,24 +186,20 @@ public void testUpgradeWithMessageAndProtocolVersions(VertxTestContext context)
...
+                .onComplete(context.succeeding(v -> context.verify(() ->
                         assertVersionsInStatefulSet(KafkaVersionTestUtils.PREVIOUS_KAFKA_VERSION,
-                                KafkaVersionTestUtils.PREVIOUS_FORMAT_VERSION,
-                                KafkaVersionTestUtils.PREVIOUS_PROTOCOL_VERSION,
-                                KafkaVersionTestUtils.PREVIOUS_KAFKA_IMAGE);
-                    });
-                }))
+                        KafkaVersionTestUtils.PREVIOUS_FORMAT_VERSION,
+                        KafkaVersionTestUtils.PREVIOUS_PROTOCOL_VERSION,
+                        KafkaVersionTestUtils.PREVIOUS_KAFKA_IMAGE))))
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaUpgradeDowngradeMockTest.java:194]: I'm not overly fussed, happy to align it with the start of `assertVersionsInStatefulSet` as before.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaUpgradeDowngradeMockTest.java [hunk 58]
```diff
@@ -220,16 +215,12 @@ public void testUpgradeRecoveryWithMessageAndProtocolVersions(VertxTestContext c
...
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaUpgradeDowngradeMockTest.java:223]: As above.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaUpgradeDowngradeMockTest.java [hunk 59]
```diff
@@ -287,38 +278,31 @@ public void testUpgradeWithoutMessageAndProtocolVersions(VertxTestContext contex
...
-                .onComplete(context.succeeding(v -> context.verify(() -> {
-                    assertVersionsInStatefulSet(KafkaVersionTestUtils.LATEST_KAFKA_VERSION,
-                            KafkaVersionTestUtils.PREVIOUS_FORMAT_VERSION,
-                            KafkaVersionTestUtils.LATEST_PROTOCOL_VERSION,
-                            KafkaVersionTestUtils.LATEST_KAFKA_IMAGE);
-                })))
+                .onComplete(context.succeeding(v -> context.verify(() -> assertVersionsInStatefulSet(KafkaVersionTestUtils.LATEST_KAFKA_VERSION,
+                        KafkaVersionTestUtils.PREVIOUS_FORMAT_VERSION,
+                        KafkaVersionTestUtils.LATEST_PROTOCOL_VERSION,
+                        KafkaVersionTestUtils.LATEST_KAFKA_IMAGE))))
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaUpgradeDowngradeMockTest.java:297]: Fair enough. I'm easy on it, so no worries reverting it.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java [hunk 60]
```diff
@@ -181,9 +173,8 @@ KSB describeConfigsResult(ConfigResource config, Throwable t) {
         }
 
         private Throwable notImplemented() {
-            UnsupportedOperationException unsupportedOperationException = new UnsupportedOperationException("Not implemented by " + KSB.class.getName());
             //unsupportedOperationException.printStackTrace();
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java:176]: We do not, I just inlined the variable, didn't pay close attention to the comment.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java (hunk 1 above)
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java:266]: Yep, this is a definite revert.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java (hunk 2 above)
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaAvailabilityTest.java:267]: As above, will revert.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java (hunk 4 above)
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java:455]: The `async.flag()` was already ending the test there :) I replaced all usages of "create a single checkpoint, then flag it to indicate success" with `context.completeNow()` to make it explicit what is happening. 

So, you may well be right about not knowing where the test ends, but we were ending the test context implicitly with Vert.x Checkpoints. 

I changed them to an explicit `context.completeNow()` to make them easier to reason about :)

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java (hunk 5 above)
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java:472]: Same as above ;)

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java (hunk 6 above)
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java:179]: `ZookeeperAdminProvider` is a function-like/SAM interface, so the new version is shorthand of the old version.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java (hunk 7 above)
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java:201]: And same answer.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java (hunk 11 above)
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java:70]: Good point, it should be wrapped in a `context.suceeding()` block.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java (hunk 12 above)
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java:108]: Yep, good point. This was causing a false positive, as all assertions after both checkpoints were flagged sufficiently were ignored, but I'll revisit to keep the previous behaviour and ensure the test can fail correctly :)

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java (hunk 13 above)
Comment (LiamClarkeNZ) [reply operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:74]: Ah, that shouldn't have been committed.

File: topic-operator/src/test/java/io/strimzi/operator/topic/MockKafka.java (hunk 27 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/test/java/io/strimzi/operator/topic/MockKafka.java:237]: Yes!

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java (hunk 28 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java:116]: Funnily enough, I'm working on a slideshow about these subtleties of the Vertx Junit stuff.

Each method gets its own test context instance - so when `@Test testFoo(VertxTestContext context)` runs, and `@BeforeEach beforeFoo(VertxTestContext context)` and `@AfterEach afterFoo((VertxTestContext context)` run before and after it, they are *not* sharing a test context. 

It's rather subtle and caught me out when I removed usage of checkpoints from an `@AfterEach` but didn't remove the `VertxTestContext` parameter - it caused all the tests to time out because the  context in the after each method wasn't being completed.

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorTest.java (hunk 29 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorTest.java:1191]: If this is around paused reconciliations, I'll have to look into it again, good catch :+1:

File: user-operator/src/test/java/io/strimzi/operator/user/operator/KafkaUserQuotasIT.java (hunk 30 above)
Comment (LiamClarkeNZ) [reply user-operator/src/test/java/io/strimzi/operator/user/operator/KafkaUserQuotasIT.java:414]: To stop IDEA nagging me that a method is always called with the same parameter value. I could've used this for some changes several comments above.

**Comment by LiamClarkeNZ** [comment]
This is still very much a WIP, I'm going to revise this dramatically with far more focused changes, and incorporating @scholzj's feedback.

File: topic-operator/src/test/java/io/strimzi/operator/topic/MockKafka.java (hunk 26 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/test/java/io/strimzi/operator/topic/MockKafka.java:63]: To suppress a warning when using varargs of a parameterised type.
https://www.baeldung.com/java-safevarargs

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java (hunk 14 above)
Comment (LiamClarkeNZ) [reply operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:60]: No worries.

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java (hunk 16 above)
Comment (LiamClarkeNZ) [reply operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:68]: :+1:

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java (hunk 17 above)
Comment (LiamClarkeNZ) [reply operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:110]: I'm not sure, I wasn't evaluating the test cases, just refactoring the plumbing. If it's not going to obscure my desired changes, happy to look into them in PR V2 Electric Boogaloo.

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java (hunk 18 above)
Comment (LiamClarkeNZ) [reply operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:93]:
```
    private void verify(VertxTestContext context, Consumer<PlatformFeaturesAvailability> assertions) {
        Handler<PlatformFeaturesAvailability> runAssertions = pfa -> context.verify(() -> assertions.accept(pfa));

        PlatformFeaturesAvailability.create(vertx, kubernetesClient)
                                    .onComplete(context.succeeding(runAssertions))
                                    .onComplete(unused -> context.completeNow());
    }
```

But! I'll be revising this to be a lot less clever in PRv2.

File: operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java (hunk 19 above)
Comment (LiamClarkeNZ) [reply operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java:75]: I created a specific type or 2 to handle all the raw type warnings (and when I added the actual type parameters, the code became unreadable). But on my second pass I'll probably suppress raw types for the class and leave it at that.

File: operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java (hunk 20 above)
Comment (LiamClarkeNZ) [reply operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java:126]: As above re: raw types.

File: operator-common/src/test/java/io/strimzi/operator/common/operator/resource/AbstractCustomResourceOperatorIT.java (hunk 23 above)
Comment (LiamClarkeNZ) [reply operator-common/src/test/java/io/strimzi/operator/common/operator/resource/AbstractCustomResourceOperatorIT.java:124]: :+1:

File: operator-common/src/test/java/io/strimzi/operator/common/operator/resource/AbstractCustomResourceOperatorIT.java (hunk 24 above)
Comment (LiamClarkeNZ) [reply operator-common/src/test/java/io/strimzi/operator/common/operator/resource/AbstractCustomResourceOperatorIT.java:149]: Probably not.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/ConnectorMockTest.java (hunk 38 above)
[the remark this answers is not in the document]
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/ConnectorMockTest.java:350]: Well, if the TimeoutException is not thrown, then we do not need the comment about it I guess, or?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/JbodStorageTest.java (hunk 40 above)
[the remark this answers is not in the document]
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/JbodStorageTest.java:157]: Yeah. But if you are already changing it, you can probably change the `in :` to `in:`.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorMockTest.java (hunk 41 above)
[the remark this answers is not in the document]
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorMockTest.java:510]: But I do not get it. Why do you need the class to reference the name and namespace? Why `KafkaAssemblyOperatorMockTest.NAMESPACE` and not `NAMESPACE`?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaBridgeAssemblyOperatorTest.java (hunk 47 above)
[the remark this answers is not in the document]
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaBridgeAssemblyOperatorTest.java:338]: I guess if nothing else there should be issues created to investigate it.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaBridgeAssemblyOperatorTest.java (hunk 48 above)
[the remark this answers is not in the document]
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaBridgeAssemblyOperatorTest.java:553]: Weird form. doesn't it have some annotation or something to make it easier to understand?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperatorTest.java (hunk 49 above)
[the remark this answers is not in the document]
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperatorTest.java:905]: Same as explained above ... this needs to have at least an issue for further investigation.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectS2IAssemblyOperatorTest.java (hunk 50 above)
[the remark this answers is not in the document]
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectS2IAssemblyOperatorTest.java:90]: Is that an actual real URL? It seems like a made-up thing in some mock .Can't it be just changed to https?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectS2IAssemblyOperatorTest.java (hunk 51 above)
[the remark this answers is not in the document]
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectS2IAssemblyOperatorTest.java:907]: No, you renamed the variable.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaUpgradeDowngradeMockTest.java (hunk 57 above)
[the remark this answers is not in the document]
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaUpgradeDowngradeMockTest.java:194]: I'm not sure the checkstyle checks tests TBH. I do not think I ever had indentation issues with them. But somehow the original code made it much more clear to me what is one block and what isn't.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java (hunk 4 above)
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java:455]: You are arguing that this is not worse than the previous code. But I think this will lead to the same issue down the road as we had before. Having the test complete in some utility methods and not in the test it self will make it very easy to miss that it is called and add more tests behind it and they will be ignored again.

So maybe the right approach is to return a future from async methods like this and complete the test upon its completion from the test method directly.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java (hunk 6 above)
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/ZookeeperScalerTest.java:179]: I don't know ... for me the old thing was much easier to read and understand without thinking about what it actually does. What was wrong with it? Did IntelliJ suggested to safe 4 lines in the file?

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java (hunk 15 above)
Comment (scholzj) [reply operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:61]: Overnight I realized that you were using suppliers or something like that here. The code would be much more readable if you call it `versionSupplier` and not just `version`.

File: operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java (hunk 18 above)
Comment (scholzj) [reply operator-common/src/test/java/io/strimzi/operator/PlatformFeaturesAvailabilityTest.java:93]: Same as mentioned above with the `version`. I think you should name this better to make the code more readable. If you would call it `verifyPlatformFeaturesAvailability(...)` it would be already much  easier to understand.

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java (hunk 28 above)
Comment (scholzj) [reply topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java:116]: So, I guess this applies only to the annotated methods where the context is injected? Or also to _regular_ unannotated methods where it is passed as a parameter by other method?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java [hunk 61]
```diff
@@ -156,8 +156,6 @@ public static void after() {
                 supplier, ResourceUtils.dummyClusterOperatorConfig(1L));
         Reconciliation reconciliation = new Reconciliation("test-trigger", Kafka.RESOURCE_KIND, NAMESPACE, NAME);
 
-        Checkpoint async = context.checkpoint();
```
Comment (LiamClarkeNZ) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java:159]: Removed as unnecessary for test completion, and a lurking footgun if checkpoint ordering changed in tests using this method.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorTest.java [hunk 62]
```diff
@@ -1385,6 +1385,7 @@ public void testReconcile(Params params, VertxTestContext context) {
 
         Checkpoint fooAsync = context.checkpoint();
         Checkpoint barAsync = context.checkpoint();
+        Checkpoint completeTest = context.checkpoint();
```
Comment (LiamClarkeNZ) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperatorTest.java:1388]: Moved checkpoint creation higher, as previously this checkpoint did nothing after `fooAsync` and `barAsync` were flagged.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaMirrorMaker2AssemblyOperatorMockTest.java [hunk 63]
```diff
@@ -130,7 +130,7 @@ public void afterEach() {
 
         LOGGER.info("Reconciling initially -> create");
         Promise created = Promise.promise();
-        Checkpoint async = context.checkpoint();
```
Comment (LiamClarkeNZ) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaMirrorMaker2AssemblyOperatorMockTest.java:133]: Another potential risk in a helper method that didn't help measure tests passing or not.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java [hunk 64]
```diff
@@ -53,15 +53,16 @@ private void runTest(Vertx vertx, VertxTestContext context, String userTaskID, i
 
         Future<CruiseControlResponse> statusFuture = client.getUserTaskStatus(HOST, PORT, userTaskID);
 
-        Checkpoint checkpoint = context.checkpoint(pendingCalls + 1);
```
Comment (LiamClarkeNZ) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java:56]: Not sure if this is better than a magic number or not.

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java [hunk 65]
```diff
@@ -90,7 +88,10 @@ public static void after() throws InterruptedException {
     }
 
     @BeforeEach
-    public void createMockKube(VertxTestContext context) throws Exception {
+    public void setup(VertxTestContext context) throws Exception {
```
Comment (LiamClarkeNZ) [inline topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java:91]: Create cluster in `@BeforeEach` instead of `@BeforeAll` once checkpoints fixed up, tests were failing due to `my-topic` already existing.

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java [hunk 66]
```diff
@@ -283,21 +274,16 @@ private Config waitUntilTopicInKafka(String topicName, Predicate<Config> p) {
...
 
     void reconcile(VertxTestContext context) throws InterruptedException {
-        Checkpoint async = context.checkpoint();
         session.topicOperator.reconcileAllTopics("test").onComplete(ar -> {
             if (!ar.succeeded()) {
                 context.failNow(ar.cause());
             }
-            async.flag();
         });
-        if (!context.awaitCompletion(60, TimeUnit.SECONDS)) {
```
Comment (tombentley) [inline topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java:293]: This suggests we expected reconcile to block until the reconciliation was finished, but the new code doesn't do that. Given that `awaitCompletion()` was probably not doing what we expected maybe it's not a problem, but maybe some assumptions in the test about the blocking behaviour are now being violated (or always were).

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorTest.java [hunk 67]
```diff
@@ -536,6 +536,9 @@ public void testReconcile_withResource_noKafka_noPrivate(VertxTestContext contex
         Topic privateTopic = null;
 
         Checkpoint async0 = context.checkpoint();
+        //Must create all checkpoints used before flagging any to prevent premature test success
+        Checkpoint async = context.checkpoint(1);
```
Comment (tombentley) [inline topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorTest.java:540]: Can we name these better?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaBridgeAssemblyOperatorTest.java [hunk 68]
```diff
@@ -611,6 +611,9 @@ public void testReconcileCallsCreateOrUpdate(VertxTestContext context) {
         // Should be called twice, once for foo and once for bar
         Checkpoint asyncCreatedOrUpdated = context.checkpoint(2);
 
+        //Must create all checkpoints before flag()ing any to avoid premature test success
+        Checkpoint async = context.checkpoint();
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaBridgeAssemblyOperatorTest.java:615]: I'm hoping this issue will get some traction, and I can push code to raise an exception.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java (hunk 64 above)
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java:56]: @tombentley, just to clarify, your preference is for

```
//Clarifying comment about the +1
Checkpoint checkpoint = context.checkpoint(pendingCalls + 1);
```

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java (hunk 65 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java:91]: :+1:

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java (hunk 66 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java:293]: Good point. I'll add some blocking behaviour.

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorTest.java (hunk 67 above)
Comment (LiamClarkeNZ) [reply topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorTest.java:540]: Sure :)

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java [hunk 69]
```diff
@@ -90,7 +88,13 @@ public static void after() throws InterruptedException {
     }
 
     @BeforeEach
-    public void createMockKube(VertxTestContext context) throws Exception {
+    public void setup(VertxTestContext context) throws Exception {
+        //Create cluster in @BeforeEach instead of @BeforeAll as once the checkpoints causing premature success were fixed,
```
Comment (LiamClarkeNZ) [inline topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java:92]: Ping @tombentley

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java (hunk 64 above)
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControlTest.java:56]: Have gone with option #1.

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java [hunk 70]
```diff
@@ -282,22 +276,18 @@ private Config waitUntilTopicInKafka(String topicName, Predicate<Config> p) {
...
         session.topicOperator.reconcileAllTopics("test").onComplete(ar -> {
             if (!ar.succeeded()) {
                 context.failNow(ar.cause());
             }
-            async.flag();
-        });
-        if (!context.awaitCompletion(60, TimeUnit.SECONDS)) {
-            context.failNow(new Throwable("Test timeout"));
-        }
+        }).toCompletionStage().toCompletableFuture().get();
```
Comment (LiamClarkeNZ) [inline topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorMockTest.java:285]: Ping again @tombentley

File: topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorTest.java [hunk 71]
```diff
@@ -608,12 +612,12 @@ public void testReconcile_noResource_withKafka_noPrivate(VertxTestContext contex
         Topic kafkaTopic = new Topic.Builder(topicName.toString(), 10, (short) 2, map("cleanup.policy", "bar"), metadata).build();
         Topic privateTopic = null;
 
-        CountDownLatch async0 = new CountDownLatch(1);
+        CountDownLatch topicCreatedInKafka = new CountDownLatch(1);
```
Comment (LiamClarkeNZ) [inline topic-operator/src/test/java/io/strimzi/operator/topic/TopicOperatorTest.java:615]: @tombentley  so I went a little over the top renaming everything called `async0`, hopefully captured what was being expected correctly.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java [hunk 72]
```diff
@@ -288,27 +286,26 @@ public void testReconcileCasWhenCustomCertsAreMissingThrows(VertxTestContext con
...
 
     @Test
     public void testReconcileCasNoCertsGetGeneratedOutsideRenewalPeriod(VertxTestContext context)
             throws IOException, CertificateException, KeyStoreException, NoSuchAlgorithmException {
-        assertNoCertsGetGeneratedOutsideRenewalPeriod(context, true);
+        assertNoCertsGetGeneratedOutsideRenewalPeriod(context);
     }
 
-    private void assertNoCertsGetGeneratedOutsideRenewalPeriod(VertxTestContext context, boolean generateCertificateAuthority)
+    private void assertNoCertsGetGeneratedOutsideRenewalPeriod(VertxTestContext context)
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java]: @tombentley - looking at this test case, I think it's creating a CA to test renewal logic, there may be another test elsewhere around user provided certs, but I'm unfamiliar with the cert code.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java [hunk 73]
```diff
@@ -346,29 +343,25 @@ private void assertNoCertsGetGeneratedOutsideRenewalPeriod(VertxTestContext cont
...
-
         reconcileCa(context, certificateAuthority, certificateAuthority)
             .onComplete(context.succeeding(c -> context.verify(() -> {
                 assertThat(c.getAllValues().get(0).getData().keySet(), is(set(CA_CRT, CA_STORE, CA_STORE_PASSWORD)));
                 assertThat(c.getAllValues().get(0).getData().get(CA_CRT), is(initialClusterCaCertSecret.getData().get(CA_CRT)));
-                assertDoesNotThrow(() -> {
-                    assertThat(x509Certificate(initialClusterCaCertSecret.getData().get(CA_CRT)),
-                            is(getCertificateFromTrustStore(CA_CRT, c.getAllValues().get(0).getData())));
-                });
+                assertDoesNotThrow(() ->
```
[the remark this answers is not in the document]
Comment (LiamClarkeNZ) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CertificateRenewalTest.java]: @tombentley  I have removed the pointless assert in my fixup branch coming in a future PR :)

**Review by scholzj — APPROVED** [review]
Thanks ... nice work and nice catch for the issue. I hope Vert.x adopts your suggestion to make sure everyone avoids this in the future.
