### PR TITLE
Fixing pod crash looping to block the reconcile process

### LINKED ISSUE #1437: Operator does not manually delete crashlooping kafka pod
I have a pod in a persistent build of Kafka that filled its disk and is crashlooping. Based on [this](
https://strimzi.io/docs/latest/#proc-manual-delete-pod-pvc-kafka-deployment-configuration-kafka) documentation, I was hoping that I could add the `strimzi.io/delete-pod-and-pvc=true` annotation to the pod and have the operator delete and recreate it. The operator is complaining about the pod being unresponsive and throws an exception.

```
my-kafka-0                            1/2     CrashLoopBackOff   8          20m
```

`k annotate pod my-kafka-0 strimzi.io/delete-pod-and-pvc=true`

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
...
    strimzi.io/clients-ca-cert-generation: "0"
    strimzi.io/cluster-ca-cert-generation: "0"
    strimzi.io/delete-pod-and-pvc: "true"
    strimzi.io/generation: "0"
```

```
2019-03-12 18:00:25 INFO  ClusterOperator:118 - Triggering periodic reconciliation for namespace my-kafka...
2019-03-12 18:00:25 INFO  AbstractAssemblyOperator:157 - Reconciliation #6791(timer) KafkaConnect(my-kafka/my): Assembly my should be created or updated
2019-03-12 18:00:25 INFO  AbstractAssemblyOperator:294 - Reconciliation #6791(timer) KafkaConnect(my-kafka/my): Assembly reconciled
2019-03-12 18:01:25 ERROR Util:59 - Exceeded timeout of 300000ms while waiting for Pods resource my-kafka-0 in namespace my-kafka to be ready
2019-03-12 18:01:25 ERROR AbstractAssemblyOperator:166 - Reconciliation #6786(timer) Kafka(my-kafka/my): createOrUpdate failed
```

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Bugfix

### Description

This PR fixes #1437.
The problem was the following.

When a pod is crash looping let's say `my-cluster-kafka-0` pod, on next reconcile, the CO runs `rollingUpdateForNewCaKey` first which at the end tries to do a rolling update. Of course, it's not the case but in the `StatefulSetOperator.maybeRestartPod` results that the crashing `my-cluster-kafka-0` pod "no need to roll" but anyway we run the readiness waiting for it to be ready which never happen because it's crash looping, so it locked the subsequent steps. Even when the timeout (300000 ms) expires on next reconcile it will be the same.

This PR moves manual actions (as pod and pvc deletion) at the topic and fixes #1437.

Btw I would suggest a trivial change in the `StatefulSetOperator.maybeRestartPod` to avoid checking the readiness if the pod "no need to roll". Wdyt @scholzj @tombentley ?

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by scholzj** [comment]
> When a pod is crash looping let's say my-cluster-kafka-0 pod, on next reconcile, the CO runs rollingUpdateForNewCaKey first which at the end tries to do a rolling update.

That kind of sucks, because it means that whenever one of the pods is not ready, the operator is basically paralysed and will not do anything. But looking at the code the `rollingUpdateForNewCaKey` method seems to do something only if the keys are replaced. So why is it triggering in this case?

> Btw I would suggest a trivial change in the StatefulSetOperator.maybeRestartPod to avoid checking the readiness if the pod "no need to roll".

AFAIK we cannot do this. We introduced this to make sure that when the rolling update is crashing the brokers, we will not spread the issue into the whole cluster during the reconciliation. The only situation when you can do it is when you know that it is "no need to roll" for all pods. But not when its _no need to roll_ just for the single individual pod.

**Comment by ppatierno** [comment]
> That kind of sucks, because it means that whenever one of the pods is not ready, the operator is basically paralysed and will not do anything. But looking at the code the rollingUpdateForNewCaKey method seems to do something only if the keys are replaced. So why is it triggering in this case?

Good point. I have another possible clue ... the `waitForQuiescence` call in the `kafkaUpgrade`

**Comment by scholzj** [comment]
> Good point. I have another possible clue ... the waitForQuiescence call in the kafkaUpgrade

Yeah, that might be ... maybe we should move it and run it only if we things that we should really do some upgrade stuff.

**Comment by ppatierno** [comment]
I added more trace and that's it ... the `waitForQuiescence` is causing the problem.
From the code I see Tom mentioned "Wait until the SS is not being updated (it shouldn't be, but there's no harm in checking)" ... @tombentley now that it seems to be the cause of a problem do you think that this wait is really needed?

**Comment by scholzj** [comment]
> do you think that this wait is really needed?

IMHO we don't have to remove this. I think we can just move it into the else which is executed when `!upgrade.isNoop()`.

> anyway I would move manual actions at the top as the PR does. Or you don't agree on that?

TBH, I'm not sure. I might prefer if the Kafka parts stay in the Kafka section. But it might have some value to do them first even when Zoo doesn't work properly.

**Comment by ppatierno** [comment]
> IMHO we don't have to remove this. I think we can just move it into the else which is executed when !upgrade.isNoop().

I would agree and we can move that but anyway, if a Kafka upgrade is needed but a pod is crash looping it will call this `waitForQuiescence` and the problem will be still there (of course just in case the Kafka upgrade is needed). In this case the manual actions won't be still triggered. Moving them up could at least give to the user a way to kill a pod which could crash looping for some reason and be fixed thanks to the deletion (as reported by #1437)

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 1]
```diff
@@ -162,11 +162,14 @@ public KafkaAssemblyOperator(Vertx vertx, boolean isOpenShift,
         }
         createReconciliationState(reconciliation, kafkaAssembly)
                 .reconcileCas()
+                // manual actions driven by the user come first
+                .compose(state -> state.zkManualPodCleaning())
+                .compose(state -> state.zkManualRollingUpdate())
+                .compose(state -> state.kafkaManualPodCleaning())
+                .compose(state -> state.kafkaManualRollingUpdate())
                 .compose(state -> state.clusterOperatorSecret())
```
Comment (tombentley) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: You shouldn't move the ZK rolling before the CO has generated a cluster CA-signed cert, otherwise it's possible that the ZK rolling can't find the ZK leader because it doesn't have a valid cert.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 2]
```diff
@@ -184,8 +187,6 @@ public KafkaAssemblyOperator(Vertx vertx, boolean isOpenShift,
                 .compose(state -> state.zkHeadlessServiceEndpointReadiness())
                 .compose(state -> state.zkPersistentClaimDeletion())
                 .compose(state -> state.kafkaUpgrade())
-                .compose(state -> state.kafkaManualPodCleaning())
```
Comment (tombentley) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: If you move the `kafkaManualPodCleaning()` and `kafkaManualRollingUpdate()` before `kafkaUpgrade()` then won't the `KafkaCluster` could generate a `StatefulSet` using the upgraded image without going through the upgrade process?

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: The user is annotating pod and not changing the `version` field in the `KafkaCluster` resource and the others needed for upgrading. Why with a manual action did before it should get the new image?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 1 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Good point.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 2 above)
Comment (tombentley) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: > The user is annotating pod and not changing the version field in the KafkaCluster resource and the others needed for upgrading.

You don't know what the user's done since the last reconciliation. They could have changed both, plus a few other things. However, thinking more about it, so long as the STS hasn't changed then I guess this shouldn't be a problem.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 1 above)
Comment (tombentley) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: I only know about this because it was something I ran into recently and had to fix.

**Comment by tombentley** [comment]
The intention behind `waitForQuiescence()` was really just an extra check to ensure we don't go trying to start or complete a Kafka upgrade when the Kafka cluster isn't actually stable. My concern was that if the cluster isn't stable for some reason and we go starting an upgrade we're likely to make the situation worse. You could easily end up with a partially upgraded cluster which had an existing problem somewhere.

I still think that's a sensible check and analogous to what a human operator would do before starting an upgrade. But I suppose we can still have that check without implementing it in the same way. It could just return a `Future<Boolean>`, completing with true when the check is OK (and not actually doing any kind of pod restarting itself). If it returns false that's OK – the following operations would hopefully fix the problem and the upgrade can start in the following reconciliation.

**Comment by scholzj** [comment]
@tombentley Is there any reason why what I suggested would not work? I.e. do the check only when we find out that we should do something (i.e. the upgrade is not an noop)?

**Comment by tombentley** [comment]
That should work @scholzj, but `waitForQuiescence()` returns the SS which is then used in the `kafkaUpgrade()` code, so it's probably not quite as trivial a change as you might think.

**Comment by ppatierno** [comment]
What kind of check are you mentioning? From what I see, `waitForQuiescence` checks if pods are up to date (checking the generation) and eventually doing the rolling update if they are not. Removing the rolling update part but leaving the check on generation what kind of check will be? Or maybe I miss understood what you mean as "check".

**Comment by scholzj** [comment]
> That should work @scholzj, but waitForQuiescence() returns the SS which is then used in the kafkaUpgrade() code, so it's probably not quite as trivial a change as you might think.

True, but it doesn't seem to really so anything with the STS. So we can just get the STS instead which should be without any issues.

> What kind of check are you mentioning?

If that was on me ... I meant the check whether the pods are ready which is part of it.

**Comment by ppatierno** [comment]
After an out of band discussion, I changed the way how waitQuiescence works before doing a Kafka upgrade.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 3]
```diff
@@ -466,80 +469,87 @@ ReconciliationState createReconciliationState(Reconciliation reconciliation, Kaf
         }
 
         /**
-         * If the SS exists, complete any pending rolls
+         * If the SS exists, check that the cluster is stable and no pods need rolling update
          *
-         * @return A Future which completes with the current state of the SS, or with null if the SS never existed.
+         * @return A Future which completes with the current quiescence state of the cluster, if it is stable or not
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Does it really still check whether it is stable? The changed method doesn't do readiness check anymore. So it will not know if it is stable or not.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 4]
```diff
@@ -466,80 +469,87 @@ ReconciliationState createReconciliationState(Reconciliation reconciliation, Kaf
...
-                        String image = versions.kafkaImage(kafkaAssembly.getSpec().getKafka().getImage(), toVersion.version());
-                        Future<StatefulSet> f = Future.succeededFuture(ss);
-                        if (upgrade.isUpgrade()) {
-                            if (currentVersion.equals(fromVersion)) {
-                                f = f.compose(ignored -> kafkaUpgradePhase1(ss, upgrade, image));
-                            }
-                            result = f.compose(ss2 -> kafkaUpgradePhase2(ss2, upgrade));
+            return waitForQuiescence(namespace, kafkaSsName).compose(quiescence -> {
+                if (!quiescence) {
+                    return Future.succeededFuture(this);
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Should this really return success? That will continue the reconciliation which can for example try to reconfigure the broker with new configuration changes without doing the upgrade, or? I think that is dangerous. What does guarantee that the rest of the reconciliation doesn't create any problems?

(At the same time you cannot fail the reconciliation because that would probably never make `quiescence` become `true`.)

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 5]
```diff
@@ -183,9 +186,9 @@ public KafkaAssemblyOperator(Vertx vertx, boolean isOpenShift,
                 .compose(state -> state.zkServiceEndpointReadiness())
                 .compose(state -> state.zkHeadlessServiceEndpointReadiness())
                 .compose(state -> state.zkPersistentClaimDeletion())
-                .compose(state -> state.kafkaUpgrade())
                 .compose(state -> state.kafkaManualPodCleaning())
                 .compose(state -> state.kafkaManualRollingUpdate())
+                .compose(state -> state.kafkaUpgrade())
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Assuming we fix the waiting for readiness, do we still need to change the order?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 6]
```diff
@@ -466,80 +469,87 @@ ReconciliationState createReconciliationState(Reconciliation reconciliation, Kaf
...
+                            toVersion = versions.version(kafkaAssembly.getSpec().getKafka().getVersion());
                         }
+                        log.debug("SS {} is to version {}", ss.getMetadata().getName(), toVersion);
+                        KafkaUpgrade upgrade = new KafkaUpgrade(fromVersion, toVersion);
+                        log.debug("Kafka upgrade {}", upgrade);
+                        if (upgrade.isNoop()) {
+                            log.debug("Kafka.spec.kafka.version unchanged");
+                            result = Future.succeededFuture();
+                        } else {
+                            String image = versions.kafkaImage(kafkaAssembly.getSpec().getKafka().getImage(), toVersion.version());
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: What I expected as the solution was to keep the old `waitForQuiescence` here. Here we already know that we need to do the upgrade so we can ensure the brokers are ready for it.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 3 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: I had an out of band chat with @tombentley to understand what he meant as "check", it turned out that was just about checking generation and not readiness, maybe I miss understood but let's check with him.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 4 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: If the cluster is not "stable" about the generation (related to the "check" discussion), I would say that it's better to avoid the upgrade, or? Is that what you had in mind @tombentley ?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 5 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Maybe not

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 6 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: The problem that I saw was a no need to roll for a pod which was crashing and the readiness blocked indefinitely, can't it happen again?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 3 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Well, I think this is not about what Tom meant but about what people will understand. You say _check that cluster is stable_ and I think that will mean for most people that the cluster is running and not crash looping. If you think that we do not need the readiness check here I'm fine with it. But the Javadoc is confusing then and should make it clear that it has nothing about stability but only about the generations and no need for rolling update.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 6 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Ic oult happen again ... but only in situation when the upgrade is actually happening ... i.e. it will happen only when needed. Where as the original implementation blocks it even when the upgrade is actually completely irrelevant.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 4 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: I do not think this is the right question. The right question to ask is _What happens if the user changed the `version` in CR from 2.0.0 to 2.1.1 and we instead of doing the upgrade let it go through the regular reconciliation and regular rolling update?_ Will it really just fix the rolling update generation without doing any other changes? Or will it do more than that?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 3 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: > I think this is not about what Tom meant ...
I don't agree here, because when someone else wrote some code I would take care of it and what was his rationale to do that in order to not break something.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 4 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Imho it should do the regular rolling update and then doing the upgrade on the next reconciliation.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 6 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: So we don't solve the problem when upgrade should happen

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Maybe we do not need to solve it then. And also the probability that this happens all together is fairly low.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 4 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Why do you think it would still use the image with the old version, use the old configuration etc.?

Comment (tombentley) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: @scholzj has a point here, actually. The regular reconciliation will end up replacing the images in the STS, which would put the cluster into a bad state. To make it work we would need to ensure we didn't honour the `version` (or `image`) in the `Kafka` resource during that regular reconciliation. Doing that would make the code quite complicated. So I'm beginning to think that the better way to solve this would be to do as @scholzj originally suggested and simply move the old `waitForQuiessence()` method into the `!noop` branch. Sorry for leading you astray @ppatierno.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 3 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: The Javadoc comment has to be understandable by everyone. Not just to the one who wrote the method. And for me _check that cluster is stable_ means that it is not crash looping. And that is not what the function does now.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 4 above)
Comment (tombentley) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Thinking about this more... I now think that @ppatierno's original solution (moving `kafkaManualPodCleaning()` and `kafkaManualRollingUpdate()` before the call to `kafkaUpgrade()`) is correct. Neither `kafkaManualPodCleaning()` nor `kafkaManualRollingUpdate()` change the statefulset, so they can delete pods without those pods being restarted with a changed image. That means the user can annotate the STS to trigger the pod cleaning/manual rolling and those will take effect before we enter  (the original version of)`waitForQuiescence()`. If `waitForQuiescence()` times out then we exit the reconciliation loop and a subsequent reconciliation might succeed. Am I missing something?

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: That might be. But we should still do the `waitForQuiescence` only if it is needed. We should not block the reconciliation loop here when no upgrade is going on.

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: I will do then, agree that both cover the issue.

**Comment by ppatierno** [comment]
@tombentley I changed just a little bit the `kafkaUpgrade` method, so it's better having your eyes on that ;)

**Comment by ppatierno** [comment]
@tombentley @scholzj So it seems we are not fine yet ... after passing the `kafkaUpgrade` gate ... we are stuck in the `kafkaRollingUpdate`. 
Jakub when you said ...

> AFAIK we cannot do this. We introduced this to make sure that when the rolling update is crashing the brokers, we will not spread the issue into the whole cluster during the reconciliation. The only situation when you can do it is when you know that it is "no need to roll" for all pods. But not when its no need to roll just for the single individual pod.

Can you elaborate a little bit more why we cannot avoid the readiness when we know that the pod doesn't need a roll? I would expect that I have to check the readiness only when I restart the pod, not in other cases. What am I missing?
