### PR TITLE
Ignore user config provider aliases with conflict

### LINKED ISSUE #11349: [Bug]: Config provider alias conflict in Kafka config
### Bug Description

When a user defines a Kafka configuration in `.spec.kafka.config` that includes a config provider alias with the same name as one automatically created by the operator, the user's alias takes precedence. This occurs because the user's configuration is written after the operator's in the final Kafka config file, effectively overriding the operator-defined alias. As a result, the Kafka configuration may be invalid or behave unexpectedly.

### Steps to reproduce

In the following example, a bad user configuration causes all Kafka nodes to crash loop:

```sh
$ kubectl get k my-cluster -o yaml | yq '.spec.kafka.config'
...
config.providers: strimzienv
config.providers.strimzienv.class: org.apache.kafka.common.config.provider.EnvVarConfigProvider
config.providers.strimzienv.param.allowlist.pattern: test.*

$ kubectl exec my-cluster-broker-0 -- cat /tmp/strimzi.properties
##########
# Config providers
##########
# Configuration providers configured by the user and by Strimzi
config.providers=strimzienv,strimzienv,strimzifile,strimzidir
config.providers.strimzienv.class=org.apache.kafka.common.config.provider.EnvVarConfigProvider
config.providers.strimzienv.param.allowlist.pattern=.*
config.providers.strimzifile.class=org.apache.kafka.common.config.provider.FileConfigProvider
config.providers.strimzifile.param.allowed.paths=/opt/kafka
config.providers.strimzidir.class=org.apache.kafka.common.config.provider.DirectoryConfigProvider
config.providers.strimzidir.param.allowed.paths=/opt/kafka

##########
# User provided configuration
##########
config.providers.strimzienv.class=org.apache.kafka.common.config.provider.EnvVarConfigProvider
config.providers.strimzienv.param.allowlist.pattern=test.*
```

### Expected behavior

Config providers is a critical configuration for the operator, so any conflicting user configuration should throw an `InvalidConfiguration` exception.

### Strimzi version

main

### Kubernetes version

1.32

### Installation method

_No response_

### Infrastructure

_No response_

### Configuration files and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MichaelMorrisEst**
### Type of change

- Bugfix

### Description

Closes #11349. Handles the scenario where the user specifies config providers than conflict with the Strimzi defined config providers. When the situation arises, a warning is generated and the conflicting user config providers are ignored (as agreed at community call 29th May) 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [X] Write tests
- [X] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java [hunk 1]
```diff
@@ -805,6 +807,35 @@ private void configProviders(KafkaConfiguration userConfig)    {
...
+                && !userConfig.getConfiguration().isEmpty()
+                && userConfig.getConfigOption("config.providers") != null) {
+            Collection<String> userAliases = Arrays.asList(userConfig.getConfigOption("config.providers").split(","));
+            Collection<String> strimziAliases = Arrays.asList(strimziConfigProviders.split(","));
+            
+            Set<String> validUserAliases = new HashSet<>();
+            userAliases.stream().forEach(alias -> {
+                if (strimziAliases.contains(alias)) {
+                    LOGGER.warnCr(reconciliation, "config.provider " + alias + " ignored as it is not permitted. Not permitted aliases: " + strimziAliases);
+                    userConfig.removeConfigOption("config.providers." + alias + ".class");
```
Comment (fvaleri) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: A simple warning log can be easily missed. Also, the operator should never change the user-provided configuration, even if it's wrong or conflicting. 

As suggested in the bug report, we can raise an `InvalidConfigurationException`, and let the reconciliation fail. With that, the error would be logged and surfaced in the Kafka resource status. Wdyt?

**Review by fvaleri — COMMENTED** [review]
Hi @MichaelMorrisEst, sorry for the late review, and thanks for working on this. I left one comment for you to consider.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java (hunk 1 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: Not sure if it is that simple, as we need to keep backwards compatibility in mind as well. 

So what do we do today? IIRC, we just overwrite it? In which case warning while overwritting it is likely much better than failing the whole reconciliation.

Comment (fvaleri) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: We don't overwrite. We keep both configurations and the user-provided one wins because it is applied last. Obviously, this make the operator fails if it is not compatible with what it expects (see the issue report). For this reason, I don't think there is a backwards compatibility issue raising an config exception. Of course, we can leave a release note about this change.

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: Ok, I thought we just overwrote it. But if it is as you say, throwing the exception is good. Thanks for the clarification! 👍

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java [hunk 2]
```diff
@@ -809,32 +807,29 @@ private void configProviders(KafkaConfiguration userConfig)    {
     }
     
     /**
-     * Get the user provided Kafka configuration provider aliases, dropping any that would overwrite the Strimzi defined configuration providers
+     * Get the user provided Kafka configuration provider aliases, throwing an InvalidConfigurationException if any are found that would that overwrite the Strimzi defined configuration providers
```
Comment (fvaleri) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: I think you have an extra "that" on this comment.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java [hunk 3]
```diff
@@ -780,16 +782,14 @@ private void configProviders(KafkaConfiguration userConfig)    {
...
-        if (userConfig != null
-                && !userConfig.getConfiguration().isEmpty()
-                && userConfig.getConfigOption("config.providers") != null) {
-            writer.println("# Configuration providers configured by the user and by Strimzi");
-            writer.println("config.providers=" + userConfig.getConfigOption("config.providers") + "," + strimziConfigProviders);
-            userConfig.removeConfigOption("config.providers");
-        } else {
+        
+        final String userConfigProviders = getUserConfigProviderAliases(strimziConfigProviders, userConfig);
+        if ("".equals(userConfigProviders)) {
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: why not using `isEmpty()` here? I can understand if `userConfigProviders` could be null but as far as I understand from the method, it would return `""` (empty string) in the worse scenario and never null, or?

Comment (MichaelMorrisEst) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: Yes the method will not return null, just thought it was marginally safer in case the method was ever changed, but I can change it to isEmpty()

**Review by im-konge — APPROVED** [review]

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java [hunk 4]
```diff
@@ -805,6 +805,32 @@ private void configProviders(KafkaConfiguration userConfig)    {
...
+     * @return                          The user defined Kafka configuration provider aliases or empty string
+     */
+    private String getUserConfigProviderAliases(String strimziConfigProviders, KafkaConfiguration userConfig) {
+        String userConfigProviderAliases = "";
+        if (userConfig != null
+                && !userConfig.getConfiguration().isEmpty()
+                && userConfig.getConfigOption("config.providers") != null) {
+            userConfigProviderAliases = userConfig.getConfigOption("config.providers");
+            Collection<String> userAliases = Arrays.asList(userConfigProviderAliases.split(","));
+            Collection<String> strimziAliases = Arrays.asList(strimziConfigProviders.split(","));
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: I wonder if the code should be reworked a bit more. We can create the Strimzi Config Providers as Set/List in the first place instead of using String and then splitting it.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java [hunk 5]
```diff
@@ -805,6 +805,32 @@ private void configProviders(KafkaConfiguration userConfig)    {
...
+            
+            userAliases.stream().forEach(alias -> {
+                if (strimziAliases.contains(alias)) {
+                    throw new InvalidConfigurationException("config.provider " + alias + " not permitted as it reserved for Strimzi. Not permitted aliases: " + strimziAliases); 
+                }
+            });
+            userConfig.removeConfigOption("config.providers");
+        }
+        return userConfigProviderAliases;
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: I guess this can have a bit improved readability with something like this?

```suggestion
        if (userConfig != null
                && !userConfig.getConfiguration().isEmpty()
                && userConfig.getConfigOption("config.providers") != null) {
            String userConfigProviderAliases = userConfig.getConfigOption("config.providers");
            Collection<String> userAliases = Arrays.asList(userConfigProviderAliases.split(","));
            Collection<String> strimziAliases = Arrays.asList(strimziConfigProviders.split(","));
            
            userAliases.stream().forEach(alias -> {
                if (strimziAliases.contains(alias)) {
                    throw new InvalidConfigurationException("config.provider " + alias + " not permitted as it reserved for Strimzi. Not permitted aliases: " + strimziAliases); 
                }
            });
            
            userConfig.removeConfigOption("config.providers");
            return userConfigProviderAliases;
        } else {
            return "";
        }
```

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java [hunk 6]
```diff
@@ -780,16 +782,14 @@ private void configProviders(KafkaConfiguration userConfig)    {
...
-            userConfig.removeConfigOption("config.providers");
-        } else {
+        
+        final String userConfigProviders = getUserConfigProviderAliases(strimziConfigProviders, userConfig);
+        if (userConfigProviders.isEmpty()) {
             writer.println("# Configuration providers configured by Strimzi");
             writer.println("config.providers=" + strimziConfigProviders);
+        } else {
+            writer.println("# Configuration providers configured by the user and by Strimzi");
+            writer.println("config.providers=" + userConfigProviders + "," + strimziConfigProviders);
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: Doesn't this create wierd configurations such as `config.providers=,strimzienv`? Also, would it make sense to do the merging already in the separate method?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java (hunk 4 above)
Comment (MichaelMorrisEst) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: Done

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java (hunk 5 above)
Comment (MichaelMorrisEst) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: Done

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java (hunk 6 above)
Comment (MichaelMorrisEst) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java]: Done

**Comment by ppatierno** [comment]
@MichaelMorrisEst can you please take a look at the failed build, there is a Spotbug issue:

```shell
[ERROR] Medium: io.strimzi.operator.cluster.model.KafkaBrokerConfigurationBuilder.getConfigProviderAliases(KafkaConfiguration) concatenates strings using + in a loop [io.strimzi.operator.cluster.model.KafkaBrokerConfigurationBuilder] At KafkaBrokerConfigurationBuilder.java:[line 820] SBSC_USE_STRINGBUFFER_CONCATENATION
```

**Comment by ppatierno** [comment]
@scholzj do you have any more comments on this?

**Comment by scholzj** [comment]
Thanks for the PR.
