### PR TITLE
Use `ConfigMapUtils.createConfigMap()` in places we are re-using existing ConfigMaps

### LINKED ISSUE #12447: Strange `KafkaRebalance` reconciliation error on completed rebalance
While testing Strimzi 0.51.0-rc1, I did a rebalance to add a new broker to the cluster. The rebalance seemed to have completed successfully. But even through it is completed, I see the following errors in the CO log for every reconciliation:

```
2026-02-24 21:11:53 INFO  AbstractOperator:265 - Reconciliation #1010(timer) KafkaRebalance(myproject/my-rebalance): KafkaRebalance my-rebalance will be checked for creation or modification
2026-02-24 21:11:53 INFO  KafkaRebalanceAssemblyOperator:397 - Reconciliation #1010(timer) KafkaRebalance(myproject/my-rebalance): Rebalancing is completed. You can use the `refresh` annotation to ask for a new rebalance request
2026-02-24 21:11:53 ERROR KafkaRebalanceAssemblyOperator:461 - Reconciliation #1010(timer) KafkaRebalance(myproject/my-rebalance): Status updated to [NotReady] due to error: Failure executing: PATCH at: https://10.96.0.1:443/api/v1/namespaces/myproject/configmaps/my-rebalance?fieldManager=strimzi-kafka-operator&force=false. Message: metadata.managedFields must be nil. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=metadata.managedFields must be nil, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
2026-02-24 21:11:53 ERROR ContextImpl:69 - Unhandled exception
java.lang.IllegalStateException: Result is already complete
        at io.vertx.core.Promise.complete(Promise.java:77)
        at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.lambda$handleRebalance$11(KafkaRebalanceAssemblyOperator.java:462)
        at io.vertx.core.impl.future.FutureImpl.lambda$onComplete$0(FutureImpl.java:88)
        at io.vertx.core.impl.future.FutureBase.emitResult(FutureBase.java:68)
        at io.vertx.core.impl.future.FutureImpl.completeInternal(FutureImpl.java:163)
        at io.vertx.core.impl.future.FutureImpl$ListenerArray.complete(FutureImpl.java:214)
        at io.vertx.core.impl.future.FutureBase.emitResult(FutureBase.java:68)
        at io.vertx.core.impl.future.FutureImpl.completeInternal(FutureImpl.java:163)
        at io.vertx.core.impl.future.FutureBase.emitResult(FutureBase.java:68)
        at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:99)
        at io.vertx.core.impl.future.Composition.complete(Composition.java:48)
        at io.vertx.core.impl.future.FutureBase.lambda$emitResult$0(FutureBase.java:59)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:148)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:141)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:535)
        at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:201)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1195)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
2026-02-24 21:11:53 INFO  AbstractOperator:547 - Reconciliation #1010(timer) KafkaRebalance(myproject/my-rebalance): reconciled
```

It seems that this showed up already earlier while the reconciliation was in progress. There seem to be several issues:
* Completing completed promise
* Failing to patch the Config Map ... but not sure with what, especially at the end, when the rebalance is complete

Attached are the Cruise Control log (likely unrelated) as well as the KafkaRebalance YAML and its ConfigMap. 

[rebalance-progress.yaml](https://github.com/user-attachments/files/25530926/rebalance-progress.yaml)
[rebalance.yaml](https://github.com/user-attachments/files/25530925/rebalance.yaml)
[cc.log](https://github.com/user-attachments/files/25530927/cc.log)

This seems to be related to the server-side-apply. We need to decide if this is a blocker or not for the 0.51.0 release.

Note: This does not seem to break anything. Its just an ugly exception in the log :-/.

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Bugfix

### Description

This PR adds `ConfigMapUtils.createConfigMap()` to places where we are re-using existing ConfigMap in Namespace.
It will ensure that we are making of copy of the ConfigMap, without fields like `managedFields` in `.metadata` that is forbidden when using Server-Side Apply.
The issue was discovered in `KafkaRebalance` as described in #12447 , however the same thing applies also for the `AbstractConnectOperator.generateListOffsetsConfigMap`.

Fixes #12447 and #12462

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by im-konge** [comment]
> I don't think this is the right approach. I think you should use `createConfigMap` and the newly built proper information should be passed into it. The only thing to copy from the old CM should be the data section where appropriate.

Okay, fine. From the discussion we had I thought that having something like this is the right approach. Anyway, I'm gonna remove everything and use the `createConfigMap` instead :)

**Comment by im-konge** [comment]
@scholzj you meant it like this?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java [hunk 1]
```diff
@@ -869,20 +869,27 @@ private Future<ConfigMap> generateListOffsetsConfigMap(String configMapName, Str
...
-                    objectMeta.setLabels(labels);
-                    existingConfigMap.setMetadata(objectMeta);
 
-                    if (existingConfigMap.getMetadata().getOwnerReferences().isEmpty()) {
-                        existingConfigMap.addOwnerReference(ModelUtils.createOwnerReference(resource, false));
+                    OwnerReference ownerReference = ModelUtils.createOwnerReference(resource, false);
+
+                    if (!existingConfigMap.getMetadata().getOwnerReferences().isEmpty()) {
+                        ownerReference = existingConfigMap.getMetadata().getOwnerReferences().get(0);
                     }
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: Don't. This resource owns it, so just set the owner reference and ignore the old one.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java [hunk 2]
```diff
@@ -869,20 +869,27 @@ private Future<ConfigMap> generateListOffsetsConfigMap(String configMapName, Str
                         ));
                     }
 
+                    Map<String, String> data = existingConfigMap.getData();
+                    data.putAll(offsetsData);
+
                     Map<String, String> labels = existingConfigMap.getMetadata().getLabels();
                     labels.putAll(resource.getMetadata().getLabels());
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: Same as below. I think you should probably ignore the old labels completely and use something like this:
```
Labels.generateDefaultLabels(resource, componentName, componentType, STRIMZI_CLUSTER_OPERATOR_NAME)
```
that is used in the model classes.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 3]
```diff
@@ -350,11 +351,16 @@ private static Future<MapAndStatus<ConfigMap, KafkaRebalanceStatus>> updateProgr
...
                     if (existingConfigMap != null) {
                         if (desiredConfigMap == null) {
-                            // we need to remove the managedFields from the metadata, as we cannot apply/update the resource
-                            // with this field configured
-                            existingConfigMap.getMetadata().setManagedFields(null);
-                            desiredStatusAndMap.setLoadAndProgressConfigMap(existingConfigMap);
-                            desiredConfigMap = existingConfigMap;
+                            ConfigMap loadAndProgressConfigMap = ConfigMapUtils.createConfigMap(
+                                existingConfigMap.getMetadata().getName(),
+                                existingConfigMap.getMetadata().getNamespace(),
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java]: I would stick with the old logic and get it from the rebalance resource.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 4]
```diff
@@ -350,11 +351,16 @@ private static Future<MapAndStatus<ConfigMap, KafkaRebalanceStatus>> updateProgr
...
+                                Labels.fromMap(existingConfigMap.getMetadata().getLabels()),
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java]: Same as for the Connect part. We should get the labels from the ModeUtils. Should be easier here as there is no MM2 versus Connect issue.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 5]
```diff
@@ -946,7 +961,16 @@ private void handleUserTaskStatusResponse(Reconciliation reconciliation, CruiseC
...
                 configMapOperator.getAsync(kafkaRebalance.getMetadata().getNamespace(), kafkaRebalance.getMetadata().getName())
-                        .onSuccess(loadmap -> p.complete(new MapAndStatus<>(loadmap, buildRebalanceStatusFromPreviousStatus(kafkaRebalance.getStatus(), conditions))));
+                        .onSuccess(loadmap -> p.complete(new MapAndStatus<>(
+                            ConfigMapUtils.createConfigMap(
+                                loadmap.getMetadata().getName(),
+                                loadmap.getMetadata().getNamespace(),
+                                Labels.fromMap(loadmap.getMetadata().getLabels()),
+                                ModelUtils.createOwnerReference(kafkaRebalance, false),
+                                loadmap.getData()
+                            ),
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java]: I guess this whole thing used in multiple places can be moved to a new private mehtod you would just call and pass the data in?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java (hunk 1 above)
Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: I was just re-using the code which was there to not break things. Even in the tests we are checking that the owner reference will not be changed in case that there is already OwnerReference present. In case that it's wrong, I can change it. FYI @katheris

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 5 above)
Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java]: So I should have private method that will have parameters same as I'm putting here -> wouldn't it be unnecessary encapsulation? I mean, even if I would not pass there `loadmap.getMetadata().getName()` and I would pass there the existing CM, I would anyway need other things like the KafkaRebalance for creating the labels (or pass there the labels) etc.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java (hunk 2 above)
Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: In this case for the Connect, few lines above the Labels are obtained from the `resource` - that's wrong as well?
```
                    if (existingConfigMap == null) {
                        return Future.succeededFuture(ConfigMapUtils.createConfigMap(
                                configMapName,
                                configMapNamespace,
                                Labels.fromMap(resource.getMetadata().getLabels()),
                                ModelUtils.createOwnerReference(resource, false),
                                offsetsData
                        ));
                    }
```

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: Yes, that is wrong. These are the user labels. Not the Strimzi labels.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java (hunk 1 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: That seems wrong to me. Updating the reference is pretty important for example in relation to the APi version change as it will update at that point.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 5 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java]: Well, you seem to have basically the exactly same piece of code in several different places. Don't you? So why not have just in one place and pass there the necessary parameters. I think you should not even need the whole old CM. Just the data and the rebalance resource.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java (hunk 1 above)
Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: In that case, I will change it. Let's see if @katheris will have some point why it was like this (if it was on purpose because of something).

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java (hunk 2 above)
Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: I'm gonna change that one as well then :)

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 5 above)
Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java]: Yeah I didn't see that 2 hours back :) I thought that on some places we don't have the `KafkaRebalance`, but actually we have. Sorry for stupid comment :)

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 6]
```diff
@@ -880,7 +871,10 @@ private void handleUserTaskStatusResponse(Reconciliation reconciliation, CruiseC
             LOGGER.warnCr(reconciliation, "The maximum number of active user tasks that Cruise Control can run concurrently has been reached, therefore will retry getting user tasks in the next reconciliation. " +
                     "If this occurs often, consider increasing the value for max.active.user.tasks in the Cruise Control configuration.");
             configMapOperator.getAsync(kafkaRebalance.getMetadata().getNamespace(), kafkaRebalance.getMetadata().getName())
-                    .onSuccess(loadmap -> p.complete(new MapAndStatus<>(loadmap, buildRebalanceStatusFromPreviousStatus(kafkaRebalance.getStatus(), conditions))));
+                    .onSuccess(loadmap -> p.complete(new MapAndStatus<>(
+                        loadmap != null ? createConfigMapForRebalance(kafkaRebalance, loadmap.getData()) : null,
```
Comment (im-konge) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:875]: I know this might not be the best possible solution, but TBH I'm not totally sure in which cases the `loadmap` should be and shouldn't be present. I think in cases where it shouldn't be present we can have different checks or return null without need of this. But yeah, it seems that we have the `null` "hidden" until the moment when I added the creation of the ConfigMap from existing data. 

WDYT @ppatierno ?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java [hunk 7]
```diff
@@ -859,30 +859,19 @@ private Future<ConfigMap> generateListOffsetsConfigMap(String configMapName, Str
...
-                    }
-
-                    Map<String, String> labels = existingConfigMap.getMetadata().getLabels();
-                    labels.putAll(resource.getMetadata().getLabels());
-                    ObjectMeta objectMeta = existingConfigMap.getMetadata();
-                    objectMeta.setLabels(labels);
-                    existingConfigMap.setMetadata(objectMeta);
+                    Map<String, String> data = Optional.ofNullable(existingConfigMap)
+                        .map(ConfigMap::getData)
+                        .orElseGet(HashMap::new);
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: Wouldn't a simple if-else be easier and more readable?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 8]
```diff
@@ -715,15 +714,7 @@ protected static MapAndStatus<ConfigMap, Map<String, Object>> processOptimizatio
...
-        ConfigMap rebalanceMap = new ConfigMapBuilder()
-                .withNewMetadata()
-                    .withNamespace(kafkaRebalance.getMetadata().getNamespace())
-                    .withName(kafkaRebalance.getMetadata().getName())
-                    .withLabels(Collections.singletonMap("app", "strimzi"))
-                    .withOwnerReferences(ModelUtils.createOwnerReference(kafkaRebalance, false))
-                .endMetadata()
-                .withData(Collections.singletonMap(BROKER_LOAD_KEY, beforeAndAfterBrokerLoad.toPrettyString()))
-                .build();
+        ConfigMap rebalanceMap = createConfigMapForRebalance(kafkaRebalance, Collections.singletonMap(BROKER_LOAD_KEY, beforeAndAfterBrokerLoad.toPrettyString()));
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java]: `Map.of` would be better I guess?

```suggestion
        ConfigMap rebalanceMap = createConfigMapForRebalance(kafkaRebalance, Map.of(BROKER_LOAD_KEY, beforeAndAfterBrokerLoad.toPrettyString()));
```

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java (hunk 7 above)
Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: TBH before having this I had exactly the if-else, but I thought this will be maybe clearer. So it's I guess matter of preference. I can return it back to if-else so it will be more readable :)

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 6 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:875]: I think it should be ok looking at the code we have right now.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java (hunk 1 above)
Comment (katheris) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: This was intentional because the ConfigMap might be one that was created and is managed by the user rather than Strimzi. So this allows the user to have a ConfigMap that for example is not deleted when a specific KafkaConnector resource is deleted. It's described in the proposal for this feature https://github.com/strimzi/proposals/blob/main/083-mm2-connector-offsets-support.md#listing-offsets

**Review by katheris — CHANGES_REQUESTED** [review]
I'm happy with the code in general, but it changes the behaviour for users providing a custom owner reference for the list offsets ConfigMap. So we should either actively decide to change the behaviour and adjust the docs accordingly, or leave the owner reference part as before.

**Comment by scholzj** [comment]
> I'm happy with the code in general, but it changes the behaviour for users providing a custom owner reference for the list offsets ConfigMap. So we should either actively decide to change the behaviour and adjust the docs accordingly, or leave the owner reference part as before.

TBH, I think that is a problematic pattern. Either it is user's ConfigMap and we should only edit the data and nothing else. And also never create it. Or it is our ConfigMap and we own it, including all labels and owner references. I do not think it can be both.

**Comment by ppatierno** [comment]
> but it changes the behaviour for users providing a custom owner reference for the list offsets ConfigMap

Of course it's something coming from the proposal we approved but @katheris can you remember me why a user should provide a custom owner reference?

**Comment by im-konge** [comment]
Okay so how we proceed with this? @katheris @scholzj @ppatierno 
I found this in the documentation:
```
The owner reference pointing to the KafkaConnector resource for the source connector. To provide a custom owner reference, create the config map in advance and set the owner reference.
```
but I guess there will be more mentions.

It's bugfix, I suppose it should be backported to 0.51.0 branch, I agree it's a change in behavior -> with this I would again sneakily change behavior of something that may be useful for the users in some way? I don't remember the use-case, from my side it makes sense to have ConfigMap owned by Strimzi, as it is for other things.

I can revert it back as it was (meaning I will add back the check if the OwnerReference exists or not) and then open a separate PR with changes to this behavior. WDYT?

**Comment by scholzj** [comment]
So, I think if it is a documented behavior, it is not nice ti break it in some RC2 and then change it again. But it is not only about the owner reference. The problem is that we need to have some clarity:
* If it is User's ConfigMap, we should not touch the labels or owner references.
* If it is our ConfigMap, we have to maintain those ... the owner references, labels, etc.
* If it can be both, I think we are screwed.

I do not know what to do with it TBH. It's bad design, not just a bug. What is the actual issue with the Connect stuff? The STs are not failing. So how does the problem show up here? For the Rebalance, the actual problem is kind of negated by the bad futures handling. But I have no idea what it really does here. 

Should we just add the `getMetadata.setManagedFields(null)` right now, and think a bit more on how to deal with this later?

**Comment by im-konge** [comment]
For the Connect and MM2, it's not failing in the tests as we have there just list offsets once.
In case that you do the list offsets once and then annotate the resource once again, you will get something like this in the status:

```
    - lastTransitionTime: "2026-02-26T21:28:18.644061340Z"
      message: 'Encountered error listing connector offsets. Failure executing: PATCH
        at: https://10.96.0.1:443/api/v1/namespaces/namespace-0/configmaps/cluster-f5392a51-offsets-list?fieldManager=strimzi-kafka-operator&force=false.
        Message: metadata.managedFields must be nil. Received status: Status(apiVersion=v1,
        code=400, details=null, kind=Status, message=metadata.managedFields must be
        nil, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null,
        selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure,
        additionalProperties={}).'
      reason: ListOffsets
      status: "True"
      type: Warning
```
and then in the logs:

```
2026-02-26 21:28:18 DEBUG AbstractNamespacedResourceOperator:297 - Reconciliation #188(watch) KafkaMirrorMaker2(namespace-0/cluster-f5392a51): Caught exception while patching ConfigMap cluster-f5392a51-offsets-list in namespace namespace-0
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://10.96.0.1:443/api/v1/namespaces/namespace-0/configmaps/cluster-f5392a51-offsets-list?fieldManager=strimzi-kafka-operator&force=false. Message: metadata.managedFields must be nil. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=metadata.manage
dFields must be nil, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:205)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:507)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:419)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:397)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handlePatch(BaseOperation.java:764)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:231)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:236)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:261)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:44)
        at io.strimzi.operator.cluster.operator.resource.kubernetes.AbstractNamespacedResourceOperator.internalServerSideApply(AbstractNamespacedResourceOperator.java:281)
        at io.strimzi.operator.cluster.operator.resource.kubernetes.AbstractNamespacedResourceOperator.lambda$reconcile$0(AbstractNamespacedResourceOperator.java:126)
        at io.vertx.core.impl.future.Composition.complete(Composition.java:40)
        at io.vertx.core.impl.future.FutureBase.lambda$emitResult$0(FutureBase.java:59)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:148)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:141)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:535)
        at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:201)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1195)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://10.96.0.1:443/api/v1/namespaces/namespace-0/configmaps/cluster-f5392a51-offsets-list?fieldManager=strimzi-kafka-operator&force=false. Message: metadata.managedFields must be nil. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=metadata.managedFields must be nil, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:642)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:622)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:582)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:549)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
        at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:141)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
        at io.fabric8.kubernetes.client.utils.AsyncUtils.lambda$retryWithExponentialBackoff$3(AsyncUtils.java:91)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        ... 1 more
2026-02-26 21:28:18 WARN  AbstractConnectOperator:837 - Reconciliation #188(watch) KafkaMirrorMaker2(namespace-0/cluster-f5392a51): Encountered error listing connector offsets. Failure executing: PATCH at: https://10.96.0.1:443/api/v1/namespaces/namespace-0/configmaps/cluster-f5392a51-offsets-list?fieldManager=strimzi-kafka-operator&force=false. Message: metadata.managedFields must be nil. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=metadata.managedFields must be nil, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
```

And then it fails on every reconciliation actually.

**Comment by im-konge** [comment]
In the Connect/MM2 the issue is worse because it will not update the CM at all. In KafkaRebalance it seems it goes through.

From my side, I would just go with the solution we have in this PR in the Connect part, just bring back the labels and OwnerReference stuff. We can deal with it in the separate PR (I can open an issue for that and even a PR). I wouldn't go with reverting the changes completely in the `AbstractConnectOperator` and then just setting the `managedFields` to null.

**Comment by scholzj** [comment]
> From my side, I would just go with the solution we have in this PR in the Connect part, just bring back the labels and OwnerReference stuff. We can deal with it in the separate PR (I can open an issue for that and even a PR). I wouldn't go with reverting the changes completely in the `AbstractConnectOperator` and then just setting the `managedFields` to null.

I don't know. I don't think it is that easy to mix the labels and owner references.

**Comment by im-konge** [comment]
> > From my side, I would just go with the solution we have in this PR in the Connect part, just bring back the labels and OwnerReference stuff. We can deal with it in the separate PR (I can open an issue for that and even a PR). I wouldn't go with reverting the changes completely in the `AbstractConnectOperator` and then just setting the `managedFields` to null.
> 
> I don't know. I don't think it is that easy to mix the labels and owner references.

I'm not saying it's easy or something. I think that if it was like that before, we can keep it for now and at least fix the issues with the CMs.

**Comment by katheris** [comment]
Hey, sorry for only just getting back to this as I was away.

In terms of what we want to do going forwards, I think the intention (as far as I remember) is that we wanted to allow the user flexibility to have Strimzi manage the ConfigMap or manage it themselves. So to me it makes sense that we change the design so that if the ConfigMap already exists and does not have the Strimzi owner reference we just update the data, and if it does have the Strimzi owner reference then we do update the labels.

I don't think that would constitute a breaking change to existing users and gives them flexibility to manage the ConfigMap themselves if they want

**Comment by im-konge** [comment]
> Hey, sorry for only just getting back to this as I was away.
> 
> In terms of what we want to do going forwards, I think the intention (as far as I remember) is that we wanted to allow the user flexibility to have Strimzi manage the ConfigMap or manage it themselves. So to me it makes sense that we change the design so that if the ConfigMap already exists and does not have the Strimzi owner reference we just update the data, and if it does have the Strimzi owner reference then we do update the labels.
> 
> I don't think that would constitute a breaking change to existing users and gives them flexibility to manage the ConfigMap themselves if they want

With SSA they will anyway be able to do updates to the ConfigMap without operator overwriting these changes. I think that having yet another handling of the creation/update of the CM would be confusing. But that's just my take.

**Comment by scholzj** [comment]
I do not think the presence of an owner reference is enough to determin if it is our map or not. I think we need to have a more reliable way to determine if it is our map in which case we should set the owner reference, labels, etc. Or user's map, in whihc case we should set the data only.

**Comment by katheris** [comment]
> I do not think the presence of an owner reference is enough to determin if it is our map or not. I think we need to have a more reliable way to determine if it is our map in which case we should set the owner reference, labels, etc. Or user's map, in whihc case we should set the data only.

Can you expand on why you think the owner reference isn't reliable? And do you have a suggestion of alternative way to do it?

**Comment by scholzj** [comment]
> > I do not think the presence of an owner reference is enough to determin if it is our map or not. I think we need to have a more reliable way to determine if it is our map in which case we should set the owner reference, labels, etc. Or user's map, in whihc case we should set the data only.
> 
> Can you expand on why you think the owner reference isn't reliable? And do you have a suggestion of alternative way to do it?

Because the owner reference is not a stable thing. Our own will change in 1.0.0 because of the APi change. Also because users might actually add Strimzi owner reference themself even if the want a self-managed CM to trigger the deletion.

**Comment by katheris** [comment]
Ok, I went back through the old proposals PR comments to see why we made the behaviour the way it was, so it seems the discussion was very brief https://github.com/strimzi/proposals/pull/121#discussion_r1648853494. Basically it seems the thought was just that people might want to prevent the ConfigMap being deleted when the KafkaConnector CR is deleted, so actually I think we should be viewing it more as the ConfigMap is owned by Strimzi, but you can set your own ownerReference in order to influence the cleanup of the ConfigMap, which matches with what it says in the docs:
```
To use a custom owner reference, create the ConfigMap in advance and set the owner reference explicitly.
```

So if Strimzi owns the ConfigMap and the only behaviour we need to maintain is the ability for a user to have a custom owner reference for cleanup reasons, then I would argue the existing behaviour of always updating the labels makes sense. We could add some field to the API to customise the owner reference or specify if the owner reference should be managed by Strimzi, but I don't think that is necessary as I don't know that many people will actually use this feature.

**Comment by scholzj** [comment]
I think the SSA might maintain the custom owner reference out of the box (would need to be checked I guess; Also, SSA can be still disabled by users).

**Comment by katheris** [comment]
Doing a quick test with minikube and using kubectl commands it allowed me to overwrite the owner reference. Are you happy with my suggestion above @scholzj that we treat the ConfigMap as owned by Strimzi but just respect a custom owner reference if it is set?

**Comment by scholzj** [comment]
> Doing a quick test with minikube and using kubectl commands it allowed me to overwrite the owner reference. Are you happy with my suggestion above @scholzj that we treat the ConfigMap as owned by Strimzi but just respect a custom owner reference if it is set?

I did not test the code. But I'm fine with the idea that it is our Secret with our labels and owner references and we let the user add their own owner reference to it.

**Comment by im-konge** [comment]
> > Doing a quick test with minikube and using kubectl commands it allowed me to overwrite the owner reference. Are you happy with my suggestion above @scholzj that we treat the ConfigMap as owned by Strimzi but just respect a custom owner reference if it is set?
> 
> I did not test the code. But I'm fine with the idea that it is our Secret with our labels and owner references and we let the user add their own owner reference to it.

Okay, so if I will change the code to just get the OwnerReference(s) from the existing ConfigMap and use them during the update, you will be both okay with it? @katheris @scholzj 
I think that once SSA will be in GA, we can possibly remove that as anyone can then add OwnerReference to the CMs.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ConfigMapUtils.java [hunk 9]
```diff
@@ -29,24 +30,51 @@ private ConfigMapUtils() { }
...
+        Map<String, String> data
+    ) {
+        return createConfigMap(
+            name,
+            namespace,
+            labels,
+            List.of(ownerReference),
+            data
+        );
+    }
```
Comment (im-konge) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ConfigMapUtils.java:52]: Because we are everywhere just using our single OwnerReference, I had to add overloading method to handle the list of OwnerReferences that we will pass there. That's only because of the list offsets CM. It shouldn't break anything, as it's a similar way how it worked before. I think that once SSA is GA, we can remove this overloading method and stuff in the `AbstractConnectOperator.java‎`.

@scholzj @katheris JFYI

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java [hunk 10]
```diff
@@ -821,33 +822,34 @@ private Future<ConfigMap> generateListOffsetsConfigMap(String configMapName, Str
...
-                                offsetsData
-                        ));
+                    List<OwnerReference> ownerReferences = existingConfigMap != null
+                        ? new ArrayList<>(existingConfigMap.getMetadata().getOwnerReferences())
+                        : new ArrayList<>();
+
+                    OwnerReference ownerReference = ModelUtils.createOwnerReference(resource, false);
+                    // Check if our OwnerReference already exists in the list, if not, add it there
+                    if (ownerReferences.stream().noneMatch(or ->
+                        or.getName().equals(ownerReference.getName()) && or.getKind().equals(ownerReference.getKind()))) {
```
Comment (im-konge) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: I wanted to add a check for not adding our OwnerReference in case that it's already there. I guess if we would just do `ownerReferences.add(ownerReference);` it would add our OwnerReference regardless if it is duplicate.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ConfigMapUtils.java [hunk 11]
```diff
@@ -29,24 +30,51 @@ private ConfigMapUtils() { }
      * @param name              Name of the Config Map
      * @param namespace         Namespace of the Config Map
      * @param labels            Labels of the Config Map
-     * @param ownerReference    OwnerReference of the Config Map
+     * @param ownerReference    OwnerReferences of the Config Map
```
Comment (katheris) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ConfigMapUtils.java]: I don't think this should be plural

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java (hunk 10 above)
Comment (katheris) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: Why are we adding the owner reference if the ConfigMap already exists and doesn't contain our owner reference. I thought the point was that Strimzi would only add the Strimzi owner reference if ConfigMap hadn't been created yet, otherwise we can just reuse the existing owner references can't we?

Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: I implemented it based on this [comment](https://github.com/strimzi/strimzi-kafka-operator/pull/12451#issuecomment-4026861871). And that's how I also understood your previous comment with:
```
Are you happy with my suggestion above @scholzj that we treat the ConfigMap as owned by Strimzi but just respect a custom owner reference if it is set?
```
The way I understand it is - add Strimzi OwnerReference and in case that user had their own OwnerReference, respect it and add them to the list.

Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java]: We had offline discussion with @katheris about the OwnerReferences and what it means for the users having their own OwnerReference.
In case that user will have their own OwnerReference(s) there and we will add Strimzi OwnerReference, in case that KafkaConnector or MM2 will be deleted, the ConfigMap will not be garbage collected. That's because we will set the `controller: false` in this Strimzi's OwnerReference, so it will not depend on it. Once all other OwnerReferences are deleted, the ConfigMap will be removed as well. I tested this scenario. So this way we are keeping it as it was, just with adding our Strimzi OwnerReference to the CM.
