### PR TITLE
Configurable `scope` for Maven type artifacts in Kafka Connect Buil

### LINKED ISSUE #11799: [Bug]: KafkaConnect build ignores maven scopes which can cause problems with plugins that depend on Kafka artifacts
### Bug Description

Some Kafka Connect plugins include Connect artifacts as dependencies.

For example, I include this in my `KafkaConnect` custom resource:

```yaml
spec:
  build:
    plugins:
      - name: myconnector
        artifacts:
          - artifact: debezium-scripting
            group: io.debezium
            type: maven
            version: 3.2.1.Final
```

And my resulting plugins folder contains:
```
7751d6fd:
total 103228
-rw-r--r--. 1 kafka root     4149 May 30 14:30 annotations-1.4.0.jar
-rw-r--r--. 1 kafka root   126113 Mar 29 15:13 asm-9.8.jar
-rw-r--r--. 1 kafka root    35151 Mar 29 15:13 asm-analysis-9.8.jar
-rw-r--r--. 1 kafka root    73498 Mar 29 15:13 asm-commons-9.8.jar
-rw-r--r--. 1 kafka root    51934 Mar 29 15:13 asm-tree-9.8.jar
-rw-r--r--. 1 kafka root    94559 Mar 29 15:13 asm-util-9.8.jar
-rw-r--r--. 1 kafka root  1396119 Jan 18  2025 assertj-core-3.27.3.jar
-rw-r--r--. 1 kafka root  8469021 Dec 15  2024 byte-buddy-1.15.11.jar
-rw-r--r--. 1 kafka root    88470 May 30 14:30 compiler-1.4.0.jar
-rw-r--r--. 1 kafka root   109977 May 12 05:10 connect-api-3.9.1.jar
-rw-r--r--. 1 kafka root   118601 May 12 05:12 connect-transforms-3.9.1.jar
-rw-r--r--. 1 kafka root    30976 Aug 13 09:24 debezium-api-3.2.1.Final.jar
-rw-r--r--. 1 kafka root    14816 Aug 13 09:24 debezium-common-3.2.1.Final.jar
-rw-r--r--. 1 kafka root   430640 Aug 13 09:24 debezium-core-3.2.1.Final-tests.jar
-rw-r--r--. 1 kafka root  1305726 Aug 13 09:24 debezium-core-3.2.1.Final.jar
-rw-r--r--. 1 kafka root    14683 Aug 13 09:24 debezium-openlineage-api-3.2.1.Final.jar
-rw-r--r--. 1 kafka root    32888 Sep  1 15:15 debezium-scripting-3.2.1.Final.jar
-rw-r--r--. 1 kafka root     1629 Aug 13 09:24 debezium-scripting-languages-3.2.1.Final.pom
-rw-r--r--. 1 kafka root   813240 Oct 16  2023 graal-sdk-23.0.2.jar
-rw-r--r--. 1 kafka root  7597629 Dec 19  2023 groovy-4.0.17.jar
-rw-r--r--. 1 kafka root   129920 Dec 19  2023 groovy-json-4.0.17.jar
-rw-r--r--. 1 kafka root    16924 Dec 19  2023 groovy-jsr223-4.0.17.jar
-rw-r--r--. 1 kafka root    45024 Jul  9  2012 hamcrest-core-1.3.jar
-rw-r--r--. 1 kafka root 14386028 Oct 19  2022 icu4j-72.1.jar
-rw-r--r--. 1 kafka root    78481 Mar  9  2024 jackson-annotations-2.16.2.jar
-rw-r--r--. 1 kafka root   582784 Mar  9  2024 jackson-core-2.16.2.jar
-rw-r--r--. 1 kafka root  1638583 Mar  9  2024 jackson-databind-2.16.2.jar
-rw-r--r--. 1 kafka root   127530 Mar  9  2024 jackson-datatype-jsr310-2.16.2.jar
-rw-r--r--. 1 kafka root   126898 Aug 24  2018 javax.ws.rs-api-2.1.1.jar
-rw-r--r--. 1 kafka root 27387378 Oct 16  2023 js-23.0.2.jar
-rw-r--r--. 1 kafka root    75769 Oct 16  2023 js-scriptengine-23.0.2.jar
-rw-r--r--. 1 kafka root   382708 Oct 11  2020 junit-4.13.1.jar
-rw-r--r--. 1 kafka root  9215194 May 12 05:08 kafka-clients-3.9.1.jar
-rw-r--r--. 1 kafka root   232073 Dec  1  2023 logback-classic-1.2.13.jar
-rw-r--r--. 1 kafka root   449638 Dec  1  2023 logback-core-1.2.13.jar
-rw-r--r--. 1 kafka root   682804 Jun 19  2021 lz4-java-1.8.0.jar
-rw-r--r--. 1 kafka root  3097882 Oct 16  2023 regex-23.0.2.jar
-rw-r--r--. 1 kafka root   104459 May 30 14:30 runtime-1.4.0.jar
-rw-r--r--. 1 kafka root    41125 Feb  8  2022 slf4j-api-1.7.36.jar
-rw-r--r--. 1 kafka root  2299797 Sep 27  2023 snappy-java-1.1.10.5.jar
-rw-r--r--. 1 kafka root 16210116 Oct 16  2023 truffle-api-23.0.2.jar
-rw-r--r--. 1 kafka root   172837 May 30 14:30 wasm-1.4.0.jar
-rw-r--r--. 1 kafka root  7325504 Sep 22  2024 zstd-jni-1.5.6-6.jar
```

The connect jars are the problem:
```
-rw-r--r--. 1 kafka root   109977 May 12 05:10 connect-api-3.9.1.jar
-rw-r--r--. 1 kafka root   118601 May 12 05:12 connect-transforms-3.9.1.jar
```

This is because I'm running Kafka 4.x and the mismatch results in a runtime error

```
java.lang.NoSuchMethodError: org/apache/kafka/common/utils/ConfigUtils.translateDeprecatedConfigs(Ljava/util/Map;[[Ljava/lang/String;)Ljava/util/Map;
        (loaded from file:/opt/kafka/libs/kafka-clients-4.0.0.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@ef1275b)
        called from class org.apache.kafka.connect.transforms.ReplaceField (loaded
        from file:/opt/kafka/plugins/myconnector/7751d6fd/connect-transforms-3.9.1.jar by
        PluginClassLoader{pluginLocation=file:/opt/kafka/plugins/myconnector/}).\n\tat org.apache.kafka.connect.transforms.ReplaceField.configure(ReplaceField.java:101)\n\tat
        org.apache.kafka.connect.runtime.ConnectorConfig.transformationStages(ConnectorConfig.java:316)\n\tat
        org.apache.kafka.connect.runtime.Worker$TaskBuilder.build(Worker.java:1793)\n\tat
        org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:702)\n\tat org.apache.kafka.connect.runtime.Worker.startSourceTask(Worker.java:591)\n\tat
        org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:2042)\n\tat
        org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$39(DistributedHerder.java:2059)\n\tat
        java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat
        java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat
        java.base/java.lang.Thread.run(Thread.java:853)
```

The maven artifact does have the Connect dependencies in a "provided" scope ([ref](https://mvnrepository.com/artifact/io.debezium/debezium-scripting/3.2.1.Final)) so it feels reasonable that we could've known to exclude them from the build.

Looking at the BuildConfig that the Strimzi Operator generated, the dockerfile contains:

```sh
      RUN 'curl' '-f' '-L' '--create-dirs' '--output' '/tmp/myconnector/7751d6fd/pom.xml' 'https://repo1.maven.org/maven2/io/debezium/debezium-scripting/3.2.1.Final/debezium-scripting-3.2.1.Final.pom' \
            && 'echo' '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"><profiles><profile><id>download</id><repositories><repository><id>custom-repo</id><url>https://repo1.maven.org/maven2/</url></repository></repositories></profile></profiles><activeProfiles><activeProfile>download</activeProfile></activeProfiles></settings>' > '/tmp/7751d6fd.xml' \
            && 'mvn' 'dependency:copy-dependencies' '-s' '/tmp/7751d6fd.xml' '-DoutputDirectory=/tmp/artifacts/myconnector/7751d6fd' '-f' '/tmp/myconnector/7751d6fd/pom.xml' \
            && 'curl' '-f' '-L' '--create-dirs' '--output' '/tmp/artifacts/myconnector/7751d6fd/debezium-scripting-3.2.1.Final.jar' 'https://repo1.maven.org/maven2/io/debezium/debezium-scripting/3.2.1.Final/debezium-scripting-3.2.1.Final.jar'
```

We're copying all dependencies, irregardless of scope. 

I think if we added `-DincludeScope=runtime` to the mvn dependency:copy-dependencies command, it'd be more appropriate. This would have excluded the provided dependencies, so there wouldn't be duplicate / conflicting Kafka jars in the plugins path. (It'd also exclude test dependencies which isn't a bad thing as it'll reduce the size of the resulting image).

I've seen this today with Debezium plugins, but I've seen the same problem previously with Apicurio plugins

e.g. you can recreate java.lang.NoSuchMethodError errors by creating a KafkaConnect with:

```yaml
- artifact: apicurio-registry-serdes-avro-serde
  group: io.apicurio
  type: maven
  version: <VERSION>
- artifact: apicurio-registry-utils-converter
  group: io.apicurio
  type: maven
  version: <VERSION>
```

Does it sound like I'm on the right track here? 

### Steps to reproduce

1. Create a KafkaConnect custom resource using Kafka 4.x
2. Add artifacts to the build spec that have provided scope dependencies of Kafka 3.x (e.g. Apicurio, Debezium, etc.)
3. Start a connector that uses one of those dependencies 

### Expected behavior

The connector should start without a java.lang.NoSuchMethodError

### Strimzi version

main

### Kubernetes version

OpenShift 4.19

### Installation method

_No response_

### Infrastructure

_No response_

### Configuration files and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by neeraj-laad**
### Type of change

- Enhancement / new feature

### Description

Implements changes needed for the proposal https://github.com/strimzi/proposals/blob/main/119-add-includeScope-parameter-to-maven-artifact-for-kafka-connect-build.md

- Adds a new optional parameter to KafkaConnect build using Maven artifacts
- Uses the value provided by user (only if the option is used)

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [x] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by neeraj-laad** [comment]
Is there a process to be followed for updating the documentation for this change?

**Comment by ppatierno** [comment]
> Is there a process to be followed for updating the documentation for this change?

Most of the times we just update the documentation within the same PR, so you could do it here.

**Comment by scholzj** [comment]
> Is there a process to be followed for updating the documentation for this change?

If you build the project and try it, it will generate most of the documentation for you 😉

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java [hunk 1]
```diff
@@ -88,4 +89,16 @@ public Boolean getInsecure() {
     public void setInsecure(Boolean insecure) {
         this.insecure = insecure;
     }
+
+    @Description("Include scope threshold to configure which dependencies are included for the Maven artifact. " +
```
Comment (neeraj-laad) [inline api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java]:
```suggestion
    @Description("Scope threshold for copying dependencies included for the Maven artifact. " +
```

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java [hunk 2]
```diff
@@ -88,4 +89,16 @@ public Boolean getInsecure() {
     public void setInsecure(Boolean insecure) {
         this.insecure = insecure;
     }
+
+    @Description("Scope threshold for copying dependencies included for the Maven artifact. " +
```
Comment (neeraj-laad) [inline api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java]:
```suggestion
    @Description("Scope threshold for including dependencies for the Maven artifact. " +
```

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java [hunk 3]
```diff
@@ -88,4 +89,16 @@ public Boolean getInsecure() {
     public void setInsecure(Boolean insecure) {
         this.insecure = insecure;
     }
+
+    @Description("Scope threshold for including dependencies for the Maven artifact. " +
```
Comment (neeraj-laad) [inline api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java]:
```suggestion
    @Description("Scope threshold for including dependencies for the artifact. " +
```

**Comment by ppatierno** [comment]
> If you build the project and try it, it will generate most of the documentation for you 😉

Yeah, the documentation coming from the model for the API reference will be auto-generated, unless you want to add a more descriptive doc and example in this section for example https://strimzi.io/docs/operators/latest/deploying#creating-new-image-using-kafka-connect-build-str then you will need to update the documentation by hands.

**Comment by neeraj-laad** [comment]
IMO this is a small change and completely backwards compatible so does not need special documentation handling. We should just make sure the API description is good enough. Please let me know if you feel I need to do more, and I will happily add that to this PR.

**Comment by scholzj** [comment]
@neeraj-laad This is not a question of what we want. This is a question of what you have to do before you open the PR in the first place. You have to build the code before you submit a PR (you should also test it)! That would also show you that you are missing all the generated stuff - including the docs - but also the CRDs, for example.

**Comment by neeraj-laad** [comment]
@scholzj I did run a build locally including running the tests for the area, but I did not check in the generated documentation and packaging files as a result of the build. I shall do that today. Thanks!

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java [hunk 4]
```diff
@@ -88,4 +89,16 @@ public Boolean getInsecure() {
     public void setInsecure(Boolean insecure) {
         this.insecure = insecure;
     }
+
+    @Description("Scope threshold for including dependencies for the artifact. " +
+            "Valid values are `compile`, `provided`, `runtime`, `test`, and `system`. " +
+            "Applicable to the `maven` artifact type only.")
```
Comment (ppatierno) [inline api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java:96]: I guess we should mention what's the default value if it's not set.

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifactIncludeScope.java [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+package io.strimzi.api.kafka.model.connect.build;
+
+import com.fasterxml.jackson.annotation.JsonCreator;
+import com.fasterxml.jackson.annotation.JsonValue;
+
+import java.util.Locale;
+
+/**
+ * Enum defining the supported Maven dependency include scopes for dependency
+ * inclusion
```
Comment (ppatierno) [inline api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifactIncludeScope.java]: can we have it just on the previous line?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfileTest.java [hunk 6]
```diff
@@ -700,4 +700,48 @@ public void testMavenDockerfileWithEscapedRepoUrl()   {
...
                 "\n"));
     }
+
+    @Test
+    public void testMavenArtifactWithIncludeScope()   {
+        MavenArtifact mvn = new MavenArtifactBuilder()
+                .withGroup("g1")
+                .withArtifact("a1")
+                .withVersion("v1")
+                .withIncludeScope(io.strimzi.api.kafka.model.connect.build.MavenArtifactIncludeScope.RUNTIME)
```
Comment (ppatierno) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfileTest.java]: do we need the full FQDN here?

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java (hunk 4 above)
Comment (neeraj-laad) [reply api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java:96]: If `includeScope` is not set by the user, we do not use it at all. This results in all dependencies to be copied (which is the current behaviour). 

As per maven plugin doc:
```
runtime - include scope gives runtime and compile dependencies,
compile - include scope gives compile, provided, and system dependencies,
test - include scope gives all dependencies (equivalent to default),
provided - include scope just gives provided dependencies,
system - include scope just gives system dependencies.
```
so we could say the default (current behaviour) is `test`, but I prefer saying that this is optional field and is used only if configured by the user.

Comment (ppatierno) [reply api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java:96]: Can't we say "all dependencies are copied"? Just for clarity?

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifactIncludeScope.java (hunk 5 above)
Comment (neeraj-laad) [reply api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifactIncludeScope.java]: Fixed in next commit.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfileTest.java (hunk 6 above)
Comment (neeraj-laad) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfileTest.java]: Nope. Fixed in next commit.

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java (hunk 4 above)
Comment (neeraj-laad) [reply api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java:96]: Maven dependency scope used to filter which dependencies are included with the artifact. Valid values are `compile`, `provided`, `runtime`, `test`, and `system`. When not configured, all dependencies are included. Applicable to the `maven` artifact type only.

Would something like above be clearer?

Comment (ppatierno) [reply api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java:96]: +1 yes

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java [hunk 7]
```diff
@@ -88,4 +89,17 @@ public Boolean getInsecure() {
     public void setInsecure(Boolean insecure) {
         this.insecure = insecure;
     }
+
+    @Description("Scope threshold for including dependencies for the artifact. " +
+            "Valid values are `compile`, `provided`, `runtime`, `test`, and `system`. " +
+            "When not specified, all transitive dependencies are included. " +
```
Comment (scholzj) [inline api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java]: This is useful. But you should still name the default value here.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfileTest.java [hunk 8]
```diff
@@ -700,4 +701,95 @@ public void testMavenDockerfileWithEscapedRepoUrl()   {
...
+                "# Connector plugin my-connector-plugin\n" +
+                "##########\n" +
+                "COPY --from=downloadArtifacts '/tmp/artifacts/my-connector-plugin/64cebd9c' '/opt/kafka/plugins/my-connector-plugin/64cebd9c'\n" +
+                "\n" +
+                "USER 1001\n" +
+                "\n"));
+    }
+
+    @Test
+    public void testInsecureMavenArtifactWithIncludeScope()   {
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfileTest.java]: Why is this test useful?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfile.java [hunk 9]
```diff
@@ -154,23 +154,36 @@ private void connectorPluginsPreStage(PrintWriter writer, List<Plugin> plugins)
                     String settingsXml = "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"><profiles><profile><id>download</id><repositories><repository><id>custom-repo</id><url>" + escapeXml(repo) + "</url></repository></repositories></profile></profiles><activeProfiles><activeProfile>download</activeProfile></activeProfiles></settings>";
 
                     Cmd cmd;
+                    String includeScopeParam = mvn.getIncludeScope() != null ? "-DincludeScope=" + mvn.getIncludeScope().toValue() : null;
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfile.java]: Why don't you set the default scope here and use it everywhere instead of using null and ifing it everywhere? It would make the code muhc better, more readable and simpler.

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. I left some comments how to improve it. This should also have an CHANGELOG record I think.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfile.java (hunk 9 above)
Comment (neeraj-laad) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfile.java]: I was trying to avoid adding this parameter when user does not specify it to make sure there is no unintentional side-effects to existing flows/users.

While Maven plugin describes test - include scope gives all dependencies (equivalent to default), and I do not think this is something that changes frequently, it could change in a future plugin release and then things will need to be changed in Strimzi code as well perhaps.

Happy to do that and simplify the code if we feel it is very unlikely and the risk is acceptable.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfileTest.java (hunk 8 above)
Comment (neeraj-laad) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfileTest.java]: Indeed, I did not write this initially, but the build pipeline flagged here https://github.com/strimzi/strimzi-kafka-operator/pull/12652#issuecomment-4281140281 that those lines were not tested and the PR will result in reduced code coverage than before. So I added this specifically to test those lines.

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java (hunk 7 above)
Comment (neeraj-laad) [reply api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java]: Would this work: `Maven dependency scope used to filter which dependencies are included with the artifact. Valid values are compile, provided, runtime, test, and system. When not configured, all dependencies are included (equivalent to test scope). Applicable to the maven artifact type only.`

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfile.java (hunk 9 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfile.java]: I'm not sure I follow what the unintentional consequences are. Are you saying that the default scope is not defined?

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java (hunk 7 above)
Comment (scholzj) [reply api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java]: I don't think we use the test scope today as default, do we?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfile.java (hunk 9 above)
Comment (neeraj-laad) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectDockerfile.java]: Looking at this again - https://maven.apache.org/plugins/maven-dependency-plugin/copy-dependencies-mojo.html

I had missed this statement - `An empty string indicates include all dependencies (default).` and was unsure about using test `test include scope gives all dependencies (equivalent to default),` 

However reading this again, I could change the code to set an empty string as the default value if not specified by the user, and then we can remove the if/else blocks.

File: api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java (hunk 7 above)
Comment (neeraj-laad) [reply api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java]: Apologies, this is my mistake of not reading the plugin docs properly. The docs do say this: `An empty string indicates include all dependencies (default)`. I was instead focusing on `test include scope gives all dependencies (equivalent to default). 

So we should use empty string as the default value. What is the pattern usually followed in Strimzi for handling this, do we need a named value `default` or `all` or do we just use '' as the default internally?

Comment (scholzj) [reply api/src/main/java/io/strimzi/api/kafka/model/connect/build/MavenArtifact.java]: Sounds good if that works in the code. The docs can then say something like `When not configured, no scope is set, and all dependencies are included.`

**Comment by neeraj-laad** [comment]
Thanks for all the comments so far I believe all the comments have been addressed except for the CHANGELOG. Do I simply add a new 1.1.0 entry in CHANGELOG.md and add a record for this change?

**Comment by scholzj** [comment]
> Thanks for all the comments so far I believe all the comments have been addressed except for the CHANGELOG. Do I simply add a new 1.1.0 entry in CHANGELOG.md and add a record for this change?

Yes please. Just into the first part of the `1.1.0` section where we currenty hace something like `Nothing here yet, but we will surely develop something new pretty soon` add some osimple description in one or two sentences. For example:

```
* Support or scope configuration of Maven artifacts in Kafka Connect Build
```

II had a look and the Pr looks good to me otherwise. Thanks.

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks!

**Comment by scholzj** [comment]
@neeraj-laad Sorry, it looks like I created a conflct here. Could you please rebase it? It looks good otherwise I think. Thanks.

**Review by scholzj — APPROVED** [review]
