### PR TITLE
Fix comparing of doubles when diffing the broker configuration

### LINKED ISSUE #12293: [Bug]: Kafka reconciliation stuck in dynamic config update loop likely due to precision value issues
### Bug Description

We observed a repeat of log entry of "Updating cluster configuration : log.cleaner.io.max.bytes.per.second -> 102400000" as well as a full printout of configs. This happened once every minute on each broker pod. It ended up generating more than 90% extra logs.

Our Kafka config looked like:
`log.cleaner.io.max.bytes.per.second: 102400000`

The temporary workaround that stopped this reconciliation loop was to set as a scientific notation string.
`log.cleaner.io.max.bytes.per.second: "1.024E8"`

I suspected that there was some double precision issue when the dynamic config diff happened, as Kafka could print out the double values in scientific notations. The part we would want to fix might be around https://github.com/strimzi/strimzi-kafka-operator/blob/062fc715f7968e529f7f762c69ca394cdc1cc850/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaConfigurationDiff.java#L302

I haven't dug further to find out how to fix it, but I would like to report it here first.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Strimzi version

0.49.1,0.46.0

### Kubernetes version

1.29.1

### Installation method

_No response_

### Infrastructure

_No response_

### Configuration files and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

As described in #12293, when comparing configuration values based on double - especially `log.cleaner.io.max.bytes.per.second`, which is the only double-based configuration option with an expected large number as a configuration value (other are mostly values such as `0.5` etc.), we might get false positive changes because Kafka changes the format of the double to scientific notation when serializing it.

This PR adds a special branch to compare the double-typed options that parses the double and only then compare it, rather than comparing it only as Strings. When the values are the same, the option is not reconcifgured. While this might still update the values in some niche situations when the double comparison fails (because the double type is not exact), it should help with the majority of cases.

This resolves #12293

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaConfigurationDiff.java [hunk 1]
```diff
@@ -323,10 +324,17 @@ private Collection<AlterConfigOp> diff(NodeRef nodeRef, String desired,
...
         if (!isIgnorableProperty(propertyName)) {
             if (KafkaConfiguration.isCustomConfigurationOption(propertyName, configModel)) {
                 LOGGER.traceCr(reconciliation, "custom property {} has been updated/added {}", propertyName, desiredMap.get(propertyName));
+            } else if (KafkaConfiguration.isDouble(propertyName, configModel)) {
+                // Double properties get special handling because Kafka might reformat them during serialization
+                if (areDoublesEqual(propertyName, desiredMap, currentMap)) {
+                    LOGGER.debugCr(reconciliation, "{} is ignorable because the doubles are equal {}=={}", propertyName, currentMap.get(propertyName), desiredMap.get(propertyName));
+                } else {
+                    updatedCE.add(new AlterConfigOp(new ConfigEntry(propertyName, desiredMap.get(propertyName)), AlterConfigOp.OpType.SET));
+                }
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaConfigurationDiff.java]: what about using the following:

```java
} else if (KafkaConfiguration.isDouble(propertyName, configModel) && areDoublesEqual(propertyName, desiredMap, currentMap)) {
    LOGGER.debugCr(reconciliation, "{} is ignorable because the doubles are equal {}=={}", propertyName, currentMap.get(propertyName), desiredMap.get(propertyName));
}
```

if they are double but different or not double, the code will just follow what we have from line 339

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaConfigurationDiff.java [hunk 2]
```diff
@@ -396,4 +404,27 @@ protected Collection<AlterConfigOp> getConfigDiff(Scope scope) {
...
     }
+
+    /**
+     * Checks if two Double properties are equal in the current and desired configuration. This method just converts
+     * the values to doubles and compares them without any tolerable difference. This is not optimal because double is
+     * not an exact representation. But it is the best we can do.
+     *
+     * @param optionName    Name of the property to check
+     * @param current       The map with the current configuration
+     * @param desired       The map with the desired configuration
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaConfigurationDiff.java:411]: just a nit, if we could take the declaration order from the signature

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaConfigurationDiff.java (hunk 1 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaConfigurationDiff.java]: I know it is technically the same. But I find it more understandable this way for what we do and why.

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaConfigurationDiff.java]: What exactly is less understandable in a condition where you are saying ...  "if it's a double and equals to the other double then skip and log, otherwise do what was already there before". With your solution there is code duplication and I can't see it as more understandable tbh.

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaConfigurationDiff.java]: I think it makes it more clear that there is a special handling for double values and what the handling is. But if you insist, I will change it 🤷

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaConfigurationDiff.java (hunk 2 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaConfigurationDiff.java:411]: Good point. I actually changed the order of the parameters as current first made more sense and seems to be the order we use in most other places.

**Comment by mimaison** [comment]
FYI: I pushed an update to Kafka to document the serialization logic in ConfigDef.convertToString()'s javadoc: https://github.com/apache/kafka/commit/9d5bbf58277133ea2793cdbfbb75e68beac16117

**Comment by shk3** [comment]
Thanks a lot for the fix!
