### PR TITLE
Fixed recovery of new CA certificate trusting phase on CO stopped

### LINKED ISSUE #8402: Certificate key replacement fails when Cluster Operator crashes before the trust is established
When a Cluster CA private key is replaced, the operator needs to follow through a series of three different rolling updates:

1. First rolling update establishes the trust to the new CA while still using the old server certificates and trusting the old CA as well
2. Second rolling update issues and rolls out the new server certificates signed by the new CA (while still trusting the old CA as well)
3. Third rolling update removes the trust in the old CA

When the operator crashes before the first step is completed, it can happen that the operands will not trust the new CA. however, the operator will not detect it and recover from it and instead proceed with phase 2 and roll out the new certificates. This will not work, because trust will not be established and the operands will not sync during the rolling updates. If the trust is not rolled only to EO, KE or CC, it might still recover later. But if it fails before trust is rolled out to Zoo or Kafka, the clusters might not get back online anymore.

Note: This bug is present in the code already for some time :-/

Note 2: The description above describes the ideal state. But right now, due to #8401, phase 2 will actually pass successfully as it does not renew the certificates and everything will fall apart only in phase 3 when the trust is removed.

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Bugfix

### Description

This PR fixes #8402.
As discussed in the issue, it works by adding a new `strimzi.io/cluster-ca-key-trusted-generation` annotation on the pods which has to match the `strimzi.io/strimzi.io/cluster-ca-key-generation` in order to consider the "trusting" phase to be completed.
This is done as the first step in the `CaReconciler` to check such annotation on all the pods. If it's not consistent with the new CA key generation, pods should continue to roll for the "trusting" phase. During it, even the CO Secret doesn't have to be updated otherwise if something goes wrong it will already get the new signed certs and won't be able to connect to Kafka and ZooKeeper pods anymore.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [x] Make sure all tests pass
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java [hunk 1]
```diff
@@ -373,6 +382,47 @@ Future<Void> rollingUpdateForNewCaKey() {
...
+     * Verify that all the pods are already trusting the new CA certificate signed by a new CA key.
+     * It checks each pod's CA key generation, compared with the new CA key generation.
+     * When the trusting phase is not completed (i.e. because CO stopped), it needs to be recovered from where it was left.
+     */
+    Future<Void> isClusterCaFullyTrusted() {
+        // Building the selector for Kafka related components
+        Labels labels =  Labels.forStrimziCluster(reconciliation.name()).withStrimziKind(Kafka.RESOURCE_KIND);
+
+        isClusterCaFullyTrusted = true;
+        return podOperator.listAsync(reconciliation.namespace(), labels)
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:395]: Just a thought ... the list is a relatively expensive operation ... and we will now do it twice for every reconciliation just in the `CaReconciler`. Would it make sense to list the pods once at the beginning to establish both:
* Whether the new CA is fully trusted
* Whether the the old CA can be removed

And then in two separate steps handle the flags?

File: operator-common/src/main/java/io/strimzi/operator/cluster/model/Ca.java [hunk 2]
```diff
@@ -174,6 +174,11 @@ public String getSuffix() {
      */
     public static final String ANNO_STRIMZI_IO_CLIENTS_CA_CERT_GENERATION = Annotations.STRIMZI_DOMAIN + "clients-ca-cert-generation";
 
+    /**
+     * Annotation for tracking the Cluster CA key generation trusted by Kubernetes resources
+     */
+    public static final String ANNO_STRIMZI_IO_CLUSTER_CA_KEY_TRUSTED_GENERATION = Annotations.STRIMZI_DOMAIN + "cluster-ca-key-trusted-generation";
```
Comment (scholzj) [inline operator-common/src/main/java/io/strimzi/operator/cluster/model/Ca.java:180]: As we discussed on the call => since we add the annotation only when the CA KEY generation is actually used an not just trusted, should we instead get back to just use the `CLUSTER_CA_KEY_GENERATION` annotation?

**Review by scholzj — COMMENTED** [review]
Some nits. But I think it looks mostly good. I wonder if there is some way to have some more tests for this?

File: operator-common/src/main/java/io/strimzi/operator/cluster/model/Ca.java (hunk 2 above)
Comment (ppatierno) [reply operator-common/src/main/java/io/strimzi/operator/cluster/model/Ca.java:180]: Yeah I meant to do the change and forgot :-(

Comment (scholzj) [reply operator-common/src/main/java/io/strimzi/operator/cluster/model/Ca.java:180]: 😆

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java (hunk 1 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:395]: That's a good point. My only thought is the following ...
Between the trusting check and the CA cert removal there is the rolling for new CA key. While we don't expect changes in the `Pod` definition, they will be "technically" different pods, even with different names (actually ZK and K pods will have same names but EO, CC, KE will not). We should also discard the pods in "terminating" state when listing because they won't be there anymore during the CA cert removal.

**Comment by ppatierno** [comment]
>  I wonder if there is some way to have some more tests for this?

I thought more about this but didn't find a good way for an integration test at least. I think this is something that could be tested more with system tests, where you can kill the CO pod and check everything will continue "smoothly".

**Comment by ppatierno** [comment]
> I don't think you can test this in STs because you cannto know the right moment to kill the operator.

Well you can force the key replacement, waiting for the first ZK pod to be rolled and then kill the CO, that should be enough.

> But in unit tests, you can mock exactly the right state into which the CaReconciler starts.

Not sure I have got this :-(

**Comment by scholzj** [comment]
> > But in unit tests, you can mock exactly the right state into which the CaReconciler starts.
> 
> Not sure I have got this :-(

You can mock the state of the cluster exactly as you need it in a unit test. you can prepare the Pods with different annotations, you can prepare terminating pods, etc. And then you can run the CaReconciler on it to see that it reacts as you expect.

**Comment by ppatierno** [comment]
@scholzj I have added a couple of tests. One to check the new method which verifies that the CA key is trusted or not. The other one checks that the right rolling reason is specified (to roll nodes) when the CA key is not trusted.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/TestUtils.java [hunk 3]
```diff
@@ -66,21 +69,34 @@ public static Map<String, String> containerEnvVars(Container container) {
...
+    }
+
+    public static Pod podWithNameAndAnnotations(String name, Map<String, String> annotations) {
+        return new PodBuilder()
+                .withNewMetadata()
+                    .withName(name)
+                    .withAnnotations(annotations)
+                .endMetadata()
+                .build();
+    }
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/TestUtils.java:101]: There are many different places where similar logic is used. So it makes sense to have it shared. But you should go through all the tests doing this and update them to use this method as well.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CaReconcilerTest.java [hunk 4]
```diff
@@ -1451,4 +1458,195 @@ public void testClientsCASecretsWithoutOwnerReference(Vertx vertx, VertxTestCont
...
+                    .endKafka()
+                    .withNewZookeeper()
+                        .withReplicas(3)
+                        .withNewEphemeralStorage()
+                        .endEphemeralStorage()
+                    .endZookeeper()
+                .endSpec()
+                .build();
+
+
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CaReconcilerTest.java:1484]: Double empty line probably not needed.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CaReconcilerTest.java [hunk 5]
```diff
@@ -1451,4 +1458,195 @@ public void testClientsCASecretsWithoutOwnerReference(Vertx vertx, VertxTestCont
...
+                supplier, vertx, certManager, passwordGenerator);
+        mockCaReconciler
+                .reconcile(Clock.systemUTC())
+                .onComplete(context.succeeding(c -> context.verify(() -> {
+                    assertThat(mockCaReconciler.isClusterCaFullyTrusted, is(false));
+                    assertThat(mockCaReconciler.zkPodRestartReasons.contains(RestartReason.CLUSTER_CA_CERT_KEY_REPLACED), is(true));
+                    assertThat(mockCaReconciler.kPodRollReasons.contains(RestartReason.CLUSTER_CA_CERT_KEY_REPLACED), is(true));
+                    assertThat(mockCaReconciler.deploymentRollReason.size() == 3, is(true));
+                    for (String reason: mockCaReconciler.deploymentRollReason) {
+                        assertThat(reason.equals(RestartReason.CLUSTER_CA_CERT_KEY_REPLACED.getDefaultNote()), is(true));
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CaReconcilerTest.java:1596]: Why where the deployments rolled if accroding to the `Kafka` resource none should exist?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java (hunk 1 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:395]: So, what about this comment?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/TestUtils.java (hunk 3 above)
Comment (ppatierno) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/TestUtils.java:101]: I already moved this out from the manual rolling update test class. These methods were declared just there. I moved in this common TestUtils to be reused by my tests. If we want to use the same somewhere else, I don't think it's part of this PR.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java (hunk 1 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:395]: Actually I was waiting for your feedback on my concern. The list of pods at the beginning could be different from the one across the steps (at least the first 2 which are done in the same reconciliation).

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:395]: But is it really possible that that changes the result?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/TestUtils.java (hunk 3 above)
Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/TestUtils.java:101]: Anyway, I guess I can live with this if needed.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CaReconcilerTest.java (hunk 5 above)
Comment (ppatierno) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CaReconcilerTest.java:1609]: I added the deployment(s) get and changed the mocked CaReconcile logic as well.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java (hunk 1 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:395]: maybe not. the two steps you mentioned above are checking a couple annotation that won't change across the reconcile. What bothers me is just that they will really be different pods between step 1 and 2 :-)
but if you like I can make it listing one time and storing in the CaReconciler as a member field.

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:398]: I have pushed changes with listing the pods just one time at the beginning of the CA reconciliation.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java [hunk 6]
```diff
@@ -327,6 +333,10 @@ private void checkCustomCaSecret(CertificateAuthority ca, Secret certSecret, Sec
 
     Future<Void> clusterOperatorSecret(Clock clock) {
         oldCoSecret = clusterCa.clusterOperatorSecret();
+        if (!this.isClusterCaFullyTrusted) {
+            LOGGER.warnCr(reconciliation, "Cluster CA not fully trusted, keeping current CO secret and certs");
+            return Future.succeededFuture();
+        }
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:339]: Should there be some check for the secret's existence? I.e. what happens if the secret is deleted during a renewal (if the CA is already expired, that is a common approach to delete all secrets and have the operator recreate them).

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java [hunk 7]
```diff
@@ -373,6 +385,64 @@ Future<Void> rollingUpdateForNewCaKey() {
...
+                    this.pods.clear();
+                    if (pods.isEmpty()) {
+                        return Future.succeededFuture();
+                    }
+                    for (Pod pod : pods) {
+                        // with "RollingUpdate" strategy on Deployment(s) (i.e. the Cruise Control one),
+                        // while the Deployment is reported to be ready, the old pod is still alive but terminating
+                        // this condition is for skipping "Terminating" pods for checks on the CA key and old certificates
+                        if (pod.getMetadata().getDeletionTimestamp() == null) {
+                            this.pods.add(pod);
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:409]: Wouldn't it make sense to instead of storing all the pods in the object to run the two checks on them and store the booleans instead? It seems like that would safe a lot of memory.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java [hunk 8]
```diff
@@ -381,7 +451,7 @@ Future<Void> rollingUpdateForNewCaKey() {
      *
      * @return  Current number of ZooKeeper replicas
      */
-    private Future<Integer> getZooKeeperReplicas() {
+    Future<Integer> getZooKeeperReplicas() {
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:454]: Is it used in tests? Should it be in that case
```suggestion
    /* test */ Future<Integer> getZooKeeperReplicas() {
```
as we normally do for other methods?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java [hunk 9]
```diff
@@ -404,7 +474,7 @@ private Future<Integer> getZooKeeperReplicas() {
      * @return  Future which completes when this step is done either by rolling the ZooKeeper cluster or by deciding
      *          that no rolling is needed.
      */
-    private Future<Void> maybeRollZookeeper(int replicas, RestartReasons podRestartReasons) {
+    Future<Void> maybeRollZookeeper(int replicas, RestartReasons podRestartReasons) {
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:477]: Same as above and in few more methods below.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java (hunk 6 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java]: Yeah, I added it.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java (hunk 8 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java]: Yep done.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java [hunk 10]
```diff
@@ -373,6 +385,71 @@ Future<Void> rollingUpdateForNewCaKey() {
...
+                    LOGGER.debugCr(reconciliation, "Current cluster CA key generation {}", clusterCaKeyGeneration);
+
+
+                    for (Pod pod : pods) {
+                        // with "RollingUpdate" strategy on Deployment(s) (i.e. the Cruise Control one),
+                        // while the Deployment is reported to be ready, the old pod is still alive but terminating
+                        // this condition is for skipping "Terminating" pods for checks on the CA key and old certificates
+                        if (pod.getMetadata().getDeletionTimestamp() == null) {
+                            int podClusterCaCertGeneration = Annotations.intAnnotation(pod, Ca.ANNO_STRIMZI_IO_CLUSTER_CA_CERT_GENERATION, clusterCaCertGeneration);
+                            LOGGER.debugCr(reconciliation, "Pod {} cluster CA cert generation {}", pod.getMetadata().getName(), podClusterCaCertGeneration);
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:428]: A nit ... but should this have some message or at least some verb?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java [hunk 11]
```diff
@@ -373,6 +385,71 @@ Future<Void> rollingUpdateForNewCaKey() {
...
+                                    pod.getMetadata().getName(), podClusterCaKeyGeneration, clusterCaKeyGeneration);
+
+                            // only if all Kafka related components pods are updated to the new cluster CA cert generation,
+                            // there is the possibility that we should remove the older cluster CA from the Secret and stores
+                            if (clusterCaCertGeneration != podClusterCaCertGeneration) {
+                                this.isClusterCaFullyUsed = false;
+                            }
+
+                            if (clusterCaKeyGeneration != podClusterCaKeyGeneration) {
+                                LOGGER.debugCr(reconciliation, "Need to continue trusting new CA key ....");
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:441]: This will be in some situations logged for every pod. Is it really needed? If we want to log something, would it make more sense to log it:
* Once at the end?
* For both flags?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java [hunk 12]
```diff
@@ -373,6 +385,71 @@ Future<Void> rollingUpdateForNewCaKey() {
...
+                                this.isClusterCaNeedFullTrust = true;
+                            }
+
+                        } else {
+                            LOGGER.infoCr(reconciliation, "Skipping CA key generation check on pod {}, it's terminating", pod.getMetadata().getName());
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:446]: Does this make sense at INFO level? Seems more like DEBUG to me.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CaReconcilerTest.java [hunk 13]
```diff
@@ -1451,4 +1459,233 @@ public void testClientsCASecretsWithoutOwnerReference(Vertx vertx, VertxTestCont
...
+
+        @Override
+        Future<Void> rollDeploymentIfExists(String deploymentName, String reason) {
+            return deploymentOperator.getAsync(reconciliation.namespace(), deploymentName)
+                    .compose(dep -> {
+                        if (dep != null) {
+                            this.deploymentRollReason.add(reason);
+                        }
+                        return Future.succeededFuture();
+                    });
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CaReconcilerTest.java:1683]: Wouldn't doing this through Mockito as the other operations be more elegant than doing it here in the override?

Comment (ppatierno) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/CaReconcilerTest.java:1683]: The `deploymentOperator.getAsync` is already mocked in the test to return the Deployment(s).
What I am adding here is the rolling reason which is a field in the MockCaReconciler (and via the override I am avoiding the base class behaviour which would rolling the deployment instead).

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java (hunk 12 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java]: Agree.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java [hunk 14]
```diff
@@ -373,6 +383,77 @@ Future<Void> rollingUpdateForNewCaKey() {
...
+
+                        } else {
+                            LOGGER.debugCr(reconciliation, "Skipping CA key generation check on pod {}, it's terminating", pod.getMetadata().getName());
+                        }
+
+                        if (isClusterCaNeedFullTrust) {
+                            LOGGER.debugCr(reconciliation, "Need to continue trusting new cluster CA key ....");
+                        }
+                        if (!isClusterCaFullyUsed) {
+                            LOGGER.debugCr(reconciliation, "The cluster CA certificate is not used across all nodes to sign the certificates");
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:450]:
```suggestion
                            LOGGER.debugCr(reconciliation, "The old Cluster CA is still used by some server certificates and cannot be removed");
```

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java [hunk 15]
```diff
@@ -373,6 +383,77 @@ Future<Void> rollingUpdateForNewCaKey() {
...
+                            if (clusterCaKeyGeneration != podClusterCaKeyGeneration) {
+                                this.isClusterCaNeedFullTrust = true;
+                            }
+
+                        } else {
+                            LOGGER.debugCr(reconciliation, "Skipping CA key generation check on pod {}, it's terminating", pod.getMetadata().getName());
+                        }
+
+                        if (isClusterCaNeedFullTrust) {
+                            LOGGER.debugCr(reconciliation, "Need to continue trusting new cluster CA key ....");
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:447]:
```suggestion
                            LOGGER.debugCr(reconciliation, "The new Cluster CA is not yet trusted by all pods");
```

**Review by scholzj — APPROVED** [review]
Some nits to the logs to maybe make them more understandable. But LGTM otherwise - no need to re-review.
