### PR TITLE
Fix kafka pod address used to check if replication port is listening

### LINKED ISSUE #7798: KafkaRoller tcp probe uses incorrect host
In the KafkaRoller if we fail to connect an admin client connection to a broker pod (when determining if it is a controller) we try to make a TCP connection to the replication port. If that fails then we force restart the pod. I don't think the hostname we are connecting to is correct, we are connecting on `${podName}:${replicationPort}` [here](https://github.com/strimzi/strimzi-kafka-operator/blob/ef1bf282d97ecfa2ff3aa3a8ee759a11c52e9a49/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java#L803).

Debugging locally I can see that the admin client bootstraps using:
`my-cluster-kafka-0.my-cluster-kafka-brokers.myproject.svc.cluster.local:9091`

But the tcp probe tries to connect using:
`my-cluster-kafka-0:9091` which doesn't resolve to anything (edit: on minikube, does this host work in other environments?)

### PR DESCRIPTION
**Pull request by robobario**
Fixes #7798

### Type of change

- Bugfix

### Description

The KafkaRoller was trying to connect to `${podName}:${replicaPort}` which doesn't resolve to anything from the operator.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [ ] Make sure all tests pass
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by robobario** [comment]
I'm wondering if we're better off without the unit test changes as they are quite ugly. The problem is that the tests currently use this subclass, TestKafkaRoller which overrides the `controller` method.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java [hunk 1]
```diff
@@ -817,7 +817,7 @@ private void maybeTcpProbe(PodRef podRef, Exception executionException, RestartC
      * @param port The port
      * @throws IOException if anything went wrong.
      */
-    void tcpProbe(String hostname, int port) throws IOException {
+    protected void tcpProbe(String hostname, int port) throws IOException {
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:820]: Does it really need to be `protected`? Wouldn't default (with `/* test */` marker) be enough?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java [hunk 2]
```diff
@@ -826,6 +826,10 @@ void tcpProbe(String hostname, int port) throws IOException {
         }
     }
 
+    private String podDnsName(String podName) {
+        return DnsNameGenerator.podDnsName(namespace, KafkaResources.brokersServiceName(cluster), podName);
+    }
+
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:832]: Do we really need a method which just calls another method and is used from 2 places? TBH, I would say no.

(And if we would decide that this should stay ... maybe it can at least include the port as well then?)

**Review by scholzj — COMMENTED** [review]
Not sure abotu the test ... I think I will leave it to @tombentley to comment.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java (hunk 2 above)
Comment (SamBarker) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:832]: Given the root issue is inconsistent (and incorrect) addressing of pods a single method that gets it right seem appropriate to me. 

Including the port won't work for the TCP probe as the socket requires both address and port as separate arguments (either directly or via `InetSocketAddress`).

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java (hunk 1 above)
Comment (robobario) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java]: Yep, not sure why I changed it. Changed to default with the marker.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java (hunk 2 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:832]: There is a single consistent method ... its called `DnsNameGenerator.podDnsName`. It will not help with consistency if every class hides it into a separate layer of obfuscation.

Comment (robobario) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java]: I've changed it to introduce an `Endpoint` record to pass back the host/port and make the new method do a little more work.

**Comment by scholzj** [comment]
So, what is the plan for this? I still think this should be simplified and not add unnecessary methods and classes which just make it less readable. And nobody else from @strimzi/maintainers seemed to have jumped in and approved it either.

**Comment by robobario** [comment]
Happy to rollback and re-introduce the duplication. I agree it's a bit much now.

**Comment by scholzj** [comment]
I would certainly just use the DnsGenerator directly.

**Review by scholzj — APPROVED** [review]
Thanks @robobario

**Comment by scholzj** [comment]
@tombentley Do you think you can have a look at this one? Thanks.

**Review by tombentley — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the fix @robobario
