### PR TITLE
[systemtest] Fix tests which were not working with KRaft mode

### LINKED ISSUE #6863: System test investigation for KRaft mode
There are several system tests that are failing with KRaft mode enabled and need further investigation:

- `ColdBackupScriptIsolatedST#backupAndRestore`
- `LoggingChangeST#testJSONFormatLogging`
- `JmxIsolatedST#testKafkaZookeeperAndKafkaConnectWithJMX`

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Type of change

- Test fixes

### Description

This PR fixes one ST, which was failing with `+UseKRaft` FG and also removes the `@Disabled` tag from `testKafkaZookeeperAndKafkaConnectWithJMX`, which is working now.

Fixes #6863 

### Checklist

- [ ] Make sure all tests pass

### CODE REVIEW

File: systemtest/src/test/java/io/strimzi/systemtest/log/LoggingChangeST.java [hunk 1]
```diff
@@ -90,7 +90,7 @@ class LoggingChangeST extends AbstractST {
     private final String namespace = testSuiteNamespaceManager.getMapOfAdditionalNamespaces().get(LoggingChangeST.class.getSimpleName()).stream().findFirst().get();
 
     @ParallelNamespaceTest
-    @KRaftNotSupported("Debug needed - https://github.com/strimzi/strimzi-kafka-operator/issues/6863")
+//    @KRaftNotSupported("Debug needed - https://github.com/strimzi/strimzi-kafka-operator/issues/6863")
```
Comment (Frawless) [inline systemtest/src/test/java/io/strimzi/systemtest/log/LoggingChangeST.java:93]: leftover?

**Review by Frawless — APPROVED** [review]

**Review by scholzj — APPROVED** [review]
