### PR TITLE
Fixed check on missing cluster-ca-cert-generation annotation on pods

### LINKED ISSUE #6763: `NumberFormatException` raised when a pod doesn't have the `strimzi.io/cluster-ca-cert-generation` annotation
Up to the Strimzi 0.28.0, the Cruise Control pod doesn't have the `strimzi.io/cluster-ca-cert-generation` annotation.
When upgrading to the latest (not released yet) version, the following exception is raised on the first reconcile:

```shell
2022-05-03 16:53:35 ERROR AbstractOperator:247 - Reconciliation #81(timer) Kafka(strimzi-kafka/anubis): createOrUpdate failed
java.lang.NumberFormatException: null
    at java.lang.Integer.parseInt(Integer.java:614) ~[?:?]
    at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
    at io.strimzi.operator.cluster.operator.assembly.CaReconciler.lambda$maybeRemoveOldClusterCaCertificates$19(CaReconciler.java:480) ~[io.strimzi.cluster-operator-0.29.0-SNAPSHOT.jar:0.29.0-SNAPSHOT]
    at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[io.netty.netty-common-4.1.74.Final.jar:4.1.74.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[io.netty.netty-common-4.1.74.Final.jar:4.1.74.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.74.Final.jar:4.1.74.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[io.netty.netty-common-4.1.74.Final.jar:4.1.74.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.74.Final.jar:4.1.74.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.74.Final.jar:4.1.74.Final]
    at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

This is because there is no null check in the `CaReconcile.maybeRemoveOldClusterCaCertificates` method where such annotation is evaluated for deleting old CA certficates.

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Bugfix

### Description

This PR fixes #6763.
It sets the `strimzi.io/cluster-ca-cert-generation` on the pod where it's missing by using the current generation.

### Checklist

- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java [hunk 1]
```diff
@@ -477,7 +477,10 @@ Future<Void> maybeRemoveOldClusterCaCertificates() {
                     // only if all Kafka related components pods are updated to the new cluster CA cert generation,
                     // there is the possibility that we should remove the older cluster CA from the Secret and stores
                     for (Pod pod : pods) {
-                        int podClusterCaCertGeneration = Integer.parseInt(pod.getMetadata().getAnnotations().get(Ca.ANNO_STRIMZI_IO_CLUSTER_CA_CERT_GENERATION));
+                        int podClusterCaCertGeneration =
+                                pod.getMetadata().getAnnotations() != null && pod.getMetadata().getAnnotations().containsKey(Ca.ANNO_STRIMZI_IO_CLUSTER_CA_CERT_GENERATION) ?
+                                        Integer.parseInt(pod.getMetadata().getAnnotations().get(Ca.ANNO_STRIMZI_IO_CLUSTER_CA_CERT_GENERATION)) :
+                                        clusterCaCertGeneration;
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:483]: What about using something like this:
```suggestion
                        int podClusterCaCertGeneration = Annotations.intAnnotation(pod, Ca.ANNO_STRIMZI_IO_CLUSTER_CA_CERT_GENERATION, clusterCaCertGeneration);
```

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/CaReconciler.java:483]: Absolutely! I forgot we have that `Annotations` utility class.

**Review by scholzj — APPROVED** [review]

**Review by Frawless — APPROVED** [review]
