### PR TITLE
Fixed missing deletion of the migration znode on KRaft migration rollback

### LINKED ISSUE #11262: [Bug]: Restarting a rolled back KRaft migration may lead to a broken cluster
### Bug Description

At the start of a KRaft migration the controller checks for the Zookeeper node `/migration`. If it does not exist, the metadata is synced from ZK to KRaft. However, if it does, this sync step is skipped.
Rolling back a migration does not delete the ZK node `/migration`, such that a following migration skips the sync from ZK to KRaft but directly syncs from KRaft to ZK, as it is assumed the initial sync was already done.
If the PVs of the controllers were deleted after rollback, the metadata in KRaft is empty and everything is removed from Zookeeper. Afterwards the cluster is completly broken and needs to be restored from a backup or be set up from scratch. In case the PVs were not deleted but there were changes to the metadata in ZK, those changes will get lost.

The necessity of removing `/migration` has been added to the Kafka documentation only for [version 3.9](https://kafka.apache.org/39/documentation.html#kraft_zk_migration), not [before](https://kafka.apache.org/38/documentation.html#kraft_zk_migration):

> Additionally, run get /migration followed by rmr /migration to clear the migration state from ZooKeeper. This will allow you to re-attempt the migration in the future. The data read from "/migration" can be useful for debugging.

Therefore, strimzi-kafka-operator needs to delete `/migration` in a similar way as `/controller` in [ZooKeeperReconciler.java](https://github.com/strimzi/strimzi-kafka-operator/blob/0.45.0/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java#L220).

I have added a patch proposal to the section "Configuration files and logs" where I have just copied and adjusted the code removing the `/controller` node.

To manually remove the `/migration` node, exec into one of the zookeeper pods, execute `bin/zookeeper-shell.sh localhost:12181` and run `delete /migration`.

### Steps to reproduce

1. Setup a Zookeeper backed Kafka cluster
2. Start migration to KRaft
3. Rollback
4. Delete controller PVs
5. Start migration again

### Expected behavior

Migration after rollback and deletion of controller PVs succeeds.

### Strimzi version

0.45.0

### Kubernetes version

OpenShft 4.15

### Installation method

_No response_

### Infrastructure

_No response_

### Configuration files and logs

```
From d555a416d03c62a894c02a3e8203bc266cc62394 Mon Sep 17 00:00:00 2001
From: Volker Klasen <volker.klasen@hornbach.com>
Date: Mon, 10 Mar 2025 09:46:43 +0100
Subject: [PATCH] Remove /migration znode during KRaft migration rollback

Signed-off-by: Volker Klasen <volker.klasen@hornbach.com>
---
 .../assembly/KRaftMigrationUtils.java         | 36 +++++++++++++++++++
 .../assembly/ZooKeeperReconciler.java         | 31 +++++++++++++++-
 2 files changed, 66 insertions(+), 1 deletion(-)

diff --git a/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KRaftMigrationUtils.java b/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KRaftMigrationUtils.java
index 473610abb..bb53edd2a 100644
--- a/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KRaftMigrationUtils.java
+++ b/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KRaftMigrationUtils.java
@@ -67,6 +67,42 @@ public class KRaftMigrationUtils {
                 });
     }
 
+    /**
+     * This method deletes the /migration znode from ZooKeeper to allow for a new migration.
+     *
+     * @param reconciliation            Reconciliation information
+     * @param vertx                     Vert.x instance
+     * @param zooKeeperAdminProvider    ZooKeeper Admin client provider
+     * @param coTlsPemIdentity          Trust set and identity for TLS client authentication for connecting to ZooKeeper
+     * @param operationTimeoutMs        Timeout to be set on the ZooKeeper request configuration
+     * @param zkConnectionString        Connection string to the ZooKeeper ensemble to connect to
+     *
+     * @return Completes when the /migration znode deletion is done or any error
+     */
+    public static Future<Void> deleteZooKeeperMigrationZnode(Reconciliation reconciliation, Vertx vertx, ZooKeeperAdminProvider zooKeeperAdminProvider, TlsPemIdentity coTlsPemIdentity, long operationTimeoutMs, String zkConnectionString) {
+        // Setup truststore from PEM file in cluster CA secret
+        File trustStoreFile = Util.createFileStore(KRaftMigrationUtils.class.getName(), PemTrustSet.CERT_SUFFIX, coTlsPemIdentity.pemTrustSet().trustedCertificatesPemBytes());
+
+        // Setup keystore from PEM in cluster-operator secret
+        File keyStoreFile = Util.createFileStore(KRaftMigrationUtils.class.getName(), PemAuthIdentity.PEM_SUFFIX, coTlsPemIdentity.pemAuthIdentity().pemKeyStore());
+
+        return connectToZooKeeper(reconciliation, vertx, zooKeeperAdminProvider, trustStoreFile, keyStoreFile, operationTimeoutMs, zkConnectionString)
+                .compose(zkAdmin -> {
+                    Promise<Void> znodeDeleted = Promise.promise();
+                    try {
+                        zkAdmin.delete("/migration", -1);
+                        LOGGER.infoCr(reconciliation, "Deleted the '/migration' znode as part of the KRaft migration rollback");
+                        znodeDeleted.complete();
+                    } catch (Exception e)    {
+                        LOGGER.warnCr(reconciliation, "Failed to delete '/migration' znode", e);
+                        znodeDeleted.fail(e);
+                    } finally {
+                        closeZooKeeperConnection(reconciliation, vertx, zkAdmin, trustStoreFile, keyStoreFile, operationTimeoutMs);
+                    }
+                    return znodeDeleted.future();
+                });
+    }
+
     private static Future<ZooKeeperAdmin> connectToZooKeeper(Reconciliation reconciliation, Vertx vertx, ZooKeeperAdminProvider zooKeeperAdminProvider, File trustStoreFile, File keyStoreFile, long operationTimeoutMs, String zkConnectionString) {
         Promise<ZooKeeperAdmin> connected = Promise.promise();
 
diff --git a/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java b/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java
index ef0ca8a82..6181e9eb5 100644
--- a/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java
+++ b/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/ZooKeeperReconciler.java
@@ -217,7 +217,8 @@ public class ZooKeeperReconciler {
                 .compose(i -> serviceEndpointsReady())
                 .compose(i -> headlessServiceEndpointsReady())
                 .compose(i -> deletePersistentClaims())
-                .compose(i -> maybeDeleteControllerZnode());
+                .compose(i -> maybeDeleteControllerZnode())
+                .compose(i -> maybeDeleteMigrationZnode());
     }
 
     /**
@@ -914,4 +915,32 @@ public class ZooKeeperReconciler {
                 zkConnectionString
         );
     }
+
+    /**
+     * Defers to the Kafka metadata state manager to determine if there is a KRaft migration rollback ongoing and in such case,
+     * it will delete the /migration znode to allow for a new migration.
+     *
+     * @return  Completes when the possible /migration znode deletion is done or no deletion is required
+     */
+    protected Future<Void> maybeDeleteMigrationZnode() {
+        return this.isKRaftMigrationRollback ? deleteMigrationZnode() : Future.succeededFuture();
+    }
+
+    /**
+     * Deletes the /migration znode to allow for a new migration.
+     *
+     * @return  Completes when the /migration znode deletion is done
+     */
+    protected Future<Void> deleteMigrationZnode() {
+        // migration rollback process ongoing
+        String zkConnectionString = DnsNameGenerator.serviceDnsNameWithoutClusterDomain(reconciliation.namespace(), KafkaResources.zookeeperServiceName(reconciliation.name()))  + ":" + ZookeeperCluster.CLIENT_TLS_PORT;
+        return KRaftMigrationUtils.deleteZooKeeperMigrationZnode(
+                reconciliation,
+                vertx,
+                this.zooKeeperAdminProvider,
+                this.tlsPemIdentity,
+                operationTimeoutMs,
+                zkConnectionString
+        );
+    }
 }
-- 
2.47.2

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Bugfix

### Description

This PR fixes #11262 by adding the deletion of the `/migration` znode when rolling back from a KRaft migration.

### Checklist

- [x] Make sure all tests pass
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by im-konge — APPROVED** [review]

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KRaftMigrationUtils.java [hunk 1]
```diff
@@ -33,6 +34,8 @@ public class KRaftMigrationUtils {
     /**
      * This method deletes the /controller znode from ZooKeeper to allow the brokers, which are now in ZooKeeper mode again,
      * to elect a new controller among them taking the KRaft controllers out of the picture.
+     * It also deletes the /migration znode from ZooKeeper to reset the migration status in case of rollback and the user
+     * wants to start a KRaft migration again.
```
Comment (fvaleri) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KRaftMigrationUtils.java:38]: Should we also add why this is needed? I mean to avoid skipping the initial ZK to KRaft sync.

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KRaftMigrationUtils.java]: Done.

**Review by fvaleri — APPROVED** [review]
LGTM.Thanks.

**Comment by ppatierno** [comment]
@PaulRMellor are you ok with latest changes we agreed offline?

**Review by katheris — APPROVED** [review]

**Review by PaulRMellor — APPROVED** [review]
Great. Thanks, Paolo

File: CHANGELOG.md [hunk 2]
```diff
@@ -2,7 +2,8 @@
 
 ## 0.45.1
 
-* Dependency updates (Vert.x 4.5.13, Netty 4.1.118.Final)
+* Dependency updates (Vert.x 4.5.13, Netty 4.1.118.Final).
+* Fixed bug which may lead to a broken cluster when restarting a KRaft migration after a previous rollback due to missing `/migration` znode deletion.
```
[the remark this answers is not in the document]
Comment (ppatierno) [reply CHANGELOG.md:6]: It's a metadata loss in reality. I will change this way if you are ok.
