### PR TITLE
Fix NPE when EO doesn't contain both UO and TO - Closes #1396

### LINKED ISSUE #1396: NPE while deploying Kafka cluster without TO and UO
NPE in CO logs while deploying Kafka cluster without TO and UO.

Step to reproduce:
1. Deploying the Cluster Operator
2. Remove `topicOperator: {}` and `userOperator: {}` form `kafka-ephemeral.yaml`
Yaml should looks like ```   entityOperator: {} ```
3. Deploy Kafka cluster via commend `oc apply -f examples/kafka/kafka-ephemeral.yaml`

CO has NPE:
```
2019-03-01 13:54:19 ERROR AbstractAssemblyOperator:179 - Reconciliation #0(watch) Kafka(myproject/my-cluster): createOrUpdate failed
java.lang.NullPointerException: null
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$getEntityOperatorDescription$82(KafkaAssemblyOperator.java:1622) ~[cluster-operator-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273) ~[cluster-operator-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[cluster-operator-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [cluster-operator-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

This is a fix for #1396 - There seems to be NPE not only when neither TO and UO are defined, but also when only one of them is defined. 

### Checklist

- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 1]
```diff
@@ -1704,7 +1714,7 @@ ReconciliationState createReconciliationState(Reconciliation reconciliation, Kaf
         }
 
         Future<ReconciliationState> entityOperatorDeployment(Supplier<Date> dateSupplier) {
-            if (this.entityOperator != null) {
+            if (this.entityOperator != null && eoDeployment != null) {
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: tbh I didn't run the code, but it really possible that if `entityOperator` is not null, the `eoDeployment` could be null and we have to check here? I see that the `eoDeployment` generation code : 

```java
this.eoDeployment = entityOperator.generateDeployment(isOpenShift, annotations, imagePullPolicy);
```

is already inside the block where `entityOperator` is not null.

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java]: Yes, I added this because of the exception which was thrown in this code. The `eoDeployment` will be null when neither TO nor UO are specified - i.e. when you do this:

```yaml
entityoperator: {}
```

In this case the `entityOperator` seems to be not null but the `eoDeployment` is. That is why I added the check.
