### PR TITLE
Fix lock management issue with early lock release - Closes #2260

### LINKED ISSUE #2260: Lock management for reconciliations doesn't seem to work properly - locks are immediately released
It looks like the lock mechanism to protect reconciling the same CR in parallel doesn§t work after the Kafka Operator change was merged:

You can see it for example from these logs:

```
2019-12-01 22:02:15 INFO  OperatorWatcher:39 - Reconciliation #0(watch) Kafka(myproject/my-cluster): Kafka my-cluster in namespace myproject was ADDED
2019-12-01 22:02:15 DEBUG AbstractOperator:172 - Reconciliation #0(watch) Kafka(myproject/my-cluster): Lock lock::myproject::Kafka::my-cluster acquired
2019-12-01 22:02:15 INFO  AbstractOperator:121 - Reconciliation #0(watch) Kafka(myproject/my-cluster): Kafka my-cluster should be created or updated
2019-12-01 22:02:15 DEBUG AbstractOperator:177 - Reconciliation #0(watch) Kafka(myproject/my-cluster): Lock lock::myproject::Kafka::my-cluster released
```

or

```
2019-12-01 22:03:05 DEBUG AbstractOperator:172 - Reconciliation #1(timer) Kafka(myproject/my-cluster): Lock lock::myproject::Kafka::my-cluster acquired
2019-12-01 22:03:05 INFO  AbstractOperator:121 - Reconciliation #1(timer) Kafka(myproject/my-cluster): Kafka my-cluster should be created or updated
2019-12-01 22:03:05 DEBUG AbstractOperator:177 - Reconciliation #1(timer) Kafka(myproject/my-cluster): Lock lock::myproject::Kafka::my-cluster released
```

There seems to be a bug in the code in `AbstractOperator.java`, where the lock is released after the callable is called but not after it is finished:

```java
Future<T> result = callable.call();
lock.release();
log.debug("{}: Lock {} released", reconciliation, lockName);
```

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

As described in #2260, the Connector Operator PR broke the locking mechanism for ensuring multiple reconciliation of the same CR would never run in parallel.

This PR releases the lock only in exception or after the callable finishs and returns some result.

This PR should fix the issue #2260.

### Checklist

- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests

File: operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java [hunk 1]
```diff
@@ -172,10 +172,16 @@ private String getLockName(String namespace, String name) {
...
-                    result.setHandler(handler);
+                    callable.call().setHandler(callableRes -> {
+                        if (callableRes.succeeded()) {
+                            handler.complete(callableRes.result());
+                        } else {
+                            handler.fail(callableRes.cause());
+                        }
+
+                        log.debug("{}: Lock {} released", reconciliation, lockName);
+                        lock.release();
```
Comment (ppatierno) [inline operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java]: we should use the same order of release and log as before (as it happens in the catch as well) to log that it's actually released.

Comment (scholzj) [reply operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java]: That makes sense. Fixed.

**Comment by scholzj** [comment]
@tombentley no worries ... these things happen.
