### PR TITLE
Reflect the current roles when rolling Kafka nodes in KafkaRoller

### LINKED ISSUE #9434: [KRaft] `KafkaRoller` is strugling to  transition controller-only nodes to mixed nodes
When having a controller-only node pool and trying to add a broker role to it, the operator / `KafkaRoller` seem to strugle to roll the nodes to change the configuration. It seems they try to treat the nodes as mixed nodes already, but fail to connect to them on the port 9091 as they are still controllers only.

It looks like the eventually roll them after the timeout expires. But it is not clear if they properly ensure the quorum availability during this. If nothing else, we have to check that this does not break the quorum -> but if possible, we should try to improve the process.

```
2023-12-05 15:05:47 INFO  KafkaAssemblyOperator:844 - Reconciliation #735(watch) Kafka(myproject/my-cluster): KafkaNodePool controllers in namespace myproject was MODIFIED
2023-12-05 15:05:47 INFO  AbstractOperator:265 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Kafka my-cluster will be checked for creation or modification
2023-12-05 15:05:47 INFO  CrdOperator:122 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Status of KafkaNodePool controllers in namespace myproject has been updated
2023-12-05 15:05:47 WARN  NetworkClient:814 - [AdminClient clientId=adminclient-226] Connection to node -7 (my-cluster-controllers-0.my-cluster-kafka-brokers.myproject.svc.cluster.local/172.16.14.234:9091) could not be established. Broker may not be available.
2023-12-05 15:06:17 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-0/0 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 250ms
2023-12-05 15:06:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:06:47 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-1/1 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 250ms
2023-12-05 15:07:17 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-2/2 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 250ms
2023-12-05 15:07:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:07:47 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-0/0 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 500ms
2023-12-05 15:08:06 INFO  ClusterOperator:142 - Triggering periodic reconciliation for namespace myproject
2023-12-05 15:08:17 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-1/1 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 500ms
2023-12-05 15:08:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:08:48 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-2/2 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 500ms
2023-12-05 15:09:18 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-0/0 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 1000ms
2023-12-05 15:09:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:09:48 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-1/1 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 1000ms
2023-12-05 15:10:18 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-2/2 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 1000ms
2023-12-05 15:10:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:10:48 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-0/0 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 2000ms
2023-12-05 15:11:18 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-1/1 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 2000ms
2023-12-05 15:11:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:11:48 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-2/2 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 2000ms
2023-12-05 15:12:06 INFO  ClusterOperator:142 - Triggering periodic reconciliation for namespace myproject
2023-12-05 15:12:18 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-0/0 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 4000ms
2023-12-05 15:12:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:12:48 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-1/1 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 4000ms
2023-12-05 15:13:18 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-2/2 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 4000ms
2023-12-05 15:13:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:13:48 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-0/0 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 8000ms
2023-12-05 15:14:18 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-1/1 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 8000ms
2023-12-05 15:14:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:14:48 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-2/2 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 8000ms
2023-12-05 15:15:18 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-0/0 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 16000ms
2023-12-05 15:15:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:15:48 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-1/1 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 16000ms
2023-12-05 15:16:18 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-2/2 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 16000ms
2023-12-05 15:16:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:16:48 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-0/0 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 32000ms
2023-12-05 15:17:18 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-1/1 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 32000ms
2023-12-05 15:17:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:17:48 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-2/2 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 32000ms
2023-12-05 15:18:18 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-0/0 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 64000ms
2023-12-05 15:18:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:18:48 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-1/1 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 64000ms
2023-12-05 15:19:18 INFO  KafkaRoller:396 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Will temporarily skip verifying pod my-cluster-controllers-2/2 is up-to-date due to ForceableProblem: Error getting broker config, retrying after at least 64000ms
2023-12-05 15:19:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:19:52 WARN  KafkaRoller:501 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Pod my-cluster-controllers-0/0 will be force-rolled, due to error: Pod my-cluster-controllers-0 is the active controller and there are other pods to verify first
2023-12-05 15:19:52 INFO  PodOperator:54 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Rolling pod my-cluster-controllers-0
2023-12-05 15:20:44 WARN  KafkaRoller:501 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Pod my-cluster-controllers-1/1 will be force-rolled, due to error: Pod my-cluster-controllers-1 is the active controller and there are other pods to verify first
2023-12-05 15:20:44 INFO  PodOperator:54 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Rolling pod my-cluster-controllers-1
2023-12-05 15:20:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:21:37 INFO  KafkaRoller:476 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Rolling Pod my-cluster-controllers-2/2 due to [Pod has old revision]
2023-12-05 15:21:37 INFO  PodOperator:54 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Rolling pod my-cluster-controllers-2
2023-12-05 15:21:47 INFO  AbstractOperator:400 - Reconciliation #735(watch) Kafka(myproject/my-cluster): Reconciliation is in progress
2023-12-05 15:22:06 INFO  ClusterOperator:142 - Triggering periodic reconciliation for namespace myproject
2023-12-05 15:22:21 INFO  AbstractOperator:537 - Reconciliation #735(watch) Kafka(myproject/my-cluster): reconciled
```

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

This PR updates the KafkaRoller to roll the Kafka nodes based on their current roles and not based on the desired roles. The current roles are taken from the Pod labels. If the pod or the annotation is missing, we assume that the role did not change and use the desired roles (this is what is done today all the time). This fix improves the transitions between architectures and enables moving from dedicated controller nodes to mixed nodes by adding the broker role to the controller nodes. Additional testing will be done in system tests in a separate PR.

This should resolve #9434.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java [hunk 1]
```diff
@@ -458,16 +460,21 @@ private void restartIfNecessary(NodeRef nodeRef, RestartContext restartContext)
 
         restartContext.restartReasons = podNeedsRestart.apply(pod);
 
+        // We try to detect the current roles. If we fail to do so, we optimistically assume the roles did not
+        // change and the desired roles still apply.
+        boolean isBroker = isAlreadyBroker(pod).orElse(nodeRef.broker());
```
Comment (tinaselenge) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:465]: Would `isCurrentlyBroker`/`isCurrentlyController` sound better?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java [hunk 2]
```diff
@@ -704,6 +706,33 @@ podOps, noException(), null, noException(), noException(), noException(),
...
+        Pod pod = new PodBuilder().withNewMetadata().withName("my-pod").endMetadata().build();
+        assertThat(KafkaRoller.isAlreadyBroker(pod), is(Optional.empty()));
+        assertThat(KafkaRoller.isAlreadyController(pod), is(Optional.empty()));
+
+        // Annotation set to false
+        pod = new PodBuilder().withNewMetadata().withName("my-pod").withLabels(Map.of(Labels.STRIMZI_BROKER_ROLE_LABEL, "grr", Labels.STRIMZI_CONTROLLER_ROLE_LABEL, "meh")).endMetadata().build();
+        assertThat(KafkaRoller.isAlreadyBroker(pod).orElseThrow(), is(false));
+        assertThat(KafkaRoller.isAlreadyController(pod).orElseThrow(), is(false));
+
+        // Annotation set to wrong value
```
Comment (tinaselenge) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/KafkaRollerTest.java:725]: I think the comment is other way around with line 720?

File: documentation/modules/configuring/proc-joining-node-pool-roles.adoc [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+= Transitioning to dual-role nodes
+
+[role="_abstract"]
+This procedure describes how to transition from separate node pools with broker-only and controller-only roles to using a node pool with dual-roles.
+If your Kafka cluster is using node pools with dedicated controller and broker nodes, you can transition to using a single node pool with both roles.
+To do this, add the `broker` role to the controller-only node pool, rebalance the cluster to move partition replicas to the dual-role node pool, and then delete the old broker-only node pool.
+
+In this procedure, we start with two node pools `pool-a`, which has only the `controller` role and `pool-b` which has only the `broker` role:
+
+.Dual-role node pool
```
Comment (tinaselenge) [inline documentation/modules/configuring/proc-joining-node-pool-roles.adoc:15]: Should this be something like `Dedicated role node pool` or `Single role node pool` if it's describing specs below?

File: documentation/modules/configuring/proc-joining-node-pool-roles.adoc [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+    type: jbod
+    volumes:
+      - id: 0
+        type: persistent-claim
+        size: 100Gi
+        deleteClaim: false
+  # ...
+----
+
+. Apply the new `KafkaNodePool` resource to add the `broker` role to the `pool-a` nodes.
```
Comment (tinaselenge) [inline documentation/modules/configuring/proc-joining-node-pool-roles.adoc:109]: We could add an example of the command for this step as well if you want.

**Review by tinaselenge — COMMENTED** [review]
I left a few minor comments, otherwise LGTM

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java [hunk 5]
```diff
@@ -1047,5 +1053,49 @@ protected Future<Void> isReady(String namespace, String podName) {
...
+    /**
+     * Generic method to extract a boolean value from Kubernetes resource labels
+     *
+     * @param pod           Kube resource with metadata
+     * @param annotation    Name of the label for which we want to extract the boolean value
+     *
+     * @return  Optional with true if the label is present and is set to `true`, false if it is present and not set to
+     * `true` or empty optional if the label is not present.
+     */
+    private static Optional<Boolean> checkBooleanLabel(HasMetadata pod, String annotation)    {
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:1090]: we are looking for label, maybe the `annotation` parameter name could be misleading.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java (hunk 1 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:465]: `If we fail to do so` ... I was wondering if this is really possible. From the rest of the code, empty Optional is returned if the label is not present, is that really possible? Someone removing it manually? But wouldn't the operator resets it?

File: documentation/modules/configuring/proc-joining-node-pool-roles.adoc (hunk 4 above)
Comment (scholzj) [reply documentation/modules/configuring/proc-joining-node-pool-roles.adoc:109]: The general expectation is that every user does it differently. Someone does `kubectl edit`, someone does `kubectl apply` on a YAML file. Someone would need to commit the change to Git to have it propagated. I removed the Apply part completely as it might be confusing.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java (hunk 1 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java]: @ppatierno I guess the only situation where this would happen is when user somehow manipulates the Pods? But I guess it is better to be safe than sorry and we already have the alternative value here?

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java]: I agree but in that case it's the `optimistically` part which scared me. If it's a controller instead, our assumption could drive to wrong behaviours. Anyway there is nothing we can do more.

**Review by ppatierno — APPROVED** [review]

File: documentation/modules/configuring/con-config-node-pool-roles.adoc [hunk 6]
```diff
@@ -15,7 +15,8 @@ For example, you may have a node pool that contains nodes that perform dual brok
 In this case, you create a new node pool with nodes that act only as brokers, and then reassign partitions from the dual-role nodes to the new brokers.
 You can then switch the old node pool to a controller-only role.
 
-WARNING: Although it is possible to split node pool roles in this way, it is not currently possible to transition a dedicated node pool containing only controller or broker nodes to a combined node pool where nodes operate as brokers and controllers.
+Or the other way around, when you want to move from node pools with controller-only and broker-only roles to a node pool that contains nodes that perform dual broker and controller roles.
+In this case, you can add the `broker` role to the existing controller-only node pool, reassign partitions from the broker-only nodes to the dual-role nodes, and then delete the broker-only node pool.
```
Comment (PaulRMellor) [inline documentation/modules/configuring/con-config-node-pool-roles.adoc:19]:
```suggestion
You can also perform the reverse operation by moving from node pools with controller-only and broker-only roles to a node pool that contains nodes that perform dual broker and controller roles.
In this case, you add the `broker` role to the existing controller-only node pool, reassign partitions from the broker-only nodes to the dual-role nodes, and then delete the broker-only node pool.
```

File: documentation/modules/configuring/proc-joining-node-pool-roles.adoc [hunk 7]
```diff
@@ -0,0 +1,151 @@
+// Module included in the following assemblies:
+//
+// assembly-config.adoc
+
+[id='proc-joining-node-pools-roles-{context}']
+= Transitioning to dual-role nodes
+
+[role="_abstract"]
+This procedure describes how to transition from separate node pools with broker-only and controller-only roles to using a node pool with dual-roles.
```
Comment (PaulRMellor) [inline documentation/modules/configuring/proc-joining-node-pool-roles.adoc:9]:
```suggestion
This procedure describes how to transition from separate node pools with broker-only and controller-only roles to using a dual-role node pool.
```

**Review by PaulRMellor — APPROVED** [review]
Looks good to me. :+1: 
Couple of suggestions

File: documentation/modules/configuring/proc-joining-node-pool-roles.adoc [hunk 8]
```diff
@@ -0,0 +1,151 @@
...
+
+. Edit the node pool `pool-a` and add the `broker` role to it.
++
+.Example node pool configuration
+[source,yaml,subs="+attributes"]
+----
+apiVersion: {KafkaNodePoolApiVersion}
+kind: KafkaNodePool
+metadata:
+  name: pool-b
```
Comment (fvaleri) [inline documentation/modules/configuring/proc-joining-node-pool-roles.adoc:91]: Shouldn't be pool-a?

File: documentation/modules/configuring/proc-joining-node-pool-roles.adoc [hunk 9]
```diff
@@ -0,0 +1,151 @@
...
+  replicas: 3
+  roles:
+    - controller
+    - broker
+  storage:
+    type: jbod
+    volumes:
+      - id: 0
+        type: persistent-claim
+        size: 100Gi
```
Comment (fvaleri) [inline documentation/modules/configuring/proc-joining-node-pool-roles.adoc:104]: Shouldn't be 20Gi?

**Review by tinaselenge — APPROVED** [review]

**Review by katheris — APPROVED** [review]

**Review by fvaleri — APPROVED** [review]
