### PR TITLE
Fix custom, oauth and authz-keycloak related P12 truststore are not built correctly

### LINKED ISSUE #3823: [Bug] Custom, oauth and authz-keycloak related P12 truststore are not built correctly
While testing the latest RC1 I noticed that, if you specify a custom certificate for an external listener like the following example:

```yaml
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: openshift
        port: 9094
        type: route
        tls: true
        configuration:
          brokerCertChainAndKey:
            secretName: strimzi-letsencrypt-cert
            certificate: tls.crt
            key: tls.key  
```

The Kafka pod is crash-looping with following error:

```shell
2020-10-15 13:21:24,641 ERROR Modification time of key store could not be obtained: /tmp/kafka/custom-openshift-9094.keystore.p12 (org.apache.kafka.common.security.ssl.DefaultSslEngineFactory) [main]
java.nio.file.NoSuchFileException: /tmp/kafka/custom-openshift-9094.keystore.p12
```

The volume `/opt/kafka/certificates/custom-openshift-9094-certs` is mounted correctly and the certificate and the key should be there but the problem seems to be in the script in the Kafka image (kafka_tls_prepare_certificates.sh) generating the P12 truststores where hardcoded paths are used as for the previous format of listeners that were fixed (plain, tls, external) while now they can have different name and port.
Probably the same bug affects oauth and authz-keycloak related certificates generation.

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Bugfix

### Description

This PR fixes #3823. 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

File: docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh [hunk 1]
```diff
@@ -72,19 +72,31 @@ create_keystore /tmp/kafka/cluster.keystore.p12 "$CERTS_STORE_PASSWORD" \
     "$HOSTNAME"
 echo "Preparing keystore for replication and clienttls listener is complete"
 
-CUSTOM_CERT_DIR="/opt/kafka/certificates/custom-tls-9093-certs"
-if [ -d "$CUSTOM_CERT_DIR" ]; then
-    echo "Preparing custom keystore for tls listener"
-    create_keystore_without_ca_file /tmp/kafka/custom-tls-9093.keystore.p12 "$CERTS_STORE_PASSWORD" "${CUSTOM_CERT_DIR}/tls.crt" "${CUSTOM_CERT_DIR}/tls.key" custom-key
-    echo "Preparing custom keystore for tls listener is complete"
-fi
+regex="^\/opt\/kafka\/certificates\/custom-([a-z0-9]{1,11})-([0-9]+)-certs$"
```
Comment (scholzj) [inline docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh:75]: Do we really need the regex? Is the prefix not enough? This is something what just ties it too much to changes in other places.

File: docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh [hunk 2]
```diff
@@ -72,19 +72,31 @@ create_keystore /tmp/kafka/cluster.keystore.p12 "$CERTS_STORE_PASSWORD" \
...
+#    create_keystore_without_ca_file /tmp/kafka/custom-tls-9093.keystore.p12 "$CERTS_STORE_PASSWORD" "${CUSTOM_CERT_DIR}/tls.crt" "${CUSTOM_CERT_DIR}/tls.key" custom-key
+#    echo "Preparing custom keystore for tls listener is complete"
+#fi
+
+#CUSTOM_CERT_DIR="/opt/kafka/certificates/custom-external-9094-certs"
+#if [ -d "$CUSTOM_CERT_DIR" ]; then
+#    echo "Preparing custom keystore for external listener"
+#    create_keystore_without_ca_file /tmp/kafka/custom-external-9094.keystore.p12 "$CERTS_STORE_PASSWORD" "${CUSTOM_CERT_DIR}/tls.crt" "${CUSTOM_CERT_DIR}/tls.key" custom-key
+#    echo "Preparing custom keystore for external listener is complete"
+#fi
```
Comment (scholzj) [inline docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh:99]: I guess this can be deleted (maybe you planned to do it later)

File: docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh (hunk 1 above)
Comment (ppatierno) [reply docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh]: Done.

Comment (scholzj) [reply docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh]: I do not think you addresses my main point. I think having the regex too exact is a risk because if we change for whatever reason the rules for port names we would need to do it on multiple places. So I wonder if using something more general for example such as `^\/opt\/kafka\/certificates\/(custom|oauth)-(.*+)-(.*+)-certs$` wouldn't work equally well with less dependency on the Java code.

File: docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh [hunk 3]
```diff
@@ -72,19 +72,28 @@ create_keystore /tmp/kafka/cluster.keystore.p12 "$CERTS_STORE_PASSWORD" \
...
-fi
+regex="^\/opt\/kafka\/certificates\/(custom|oauth)-([a-z0-9]{1,11})-([0-9]+)-certs$"
+for CERT_DIR in /opt/kafka/certificates/*; do
+  if [[ $CERT_DIR =~ $regex ]]; then
+    echo "Preparing store for ${BASH_REMATCH[1]} ${BASH_REMATCH[2]} listener"
+    if [[ ${BASH_REMATCH[1]} == "custom"  ]]; then
+      echo /tmp/kafka/"${BASH_REMATCH[1]}"-"${BASH_REMATCH[2]}"-"${BASH_REMATCH[3]}".keystore.p12
+      create_keystore_without_ca_file /tmp/kafka/"${BASH_REMATCH[1]}"-"${BASH_REMATCH[2]}"-"${BASH_REMATCH[3]}".keystore.p12 "$CERTS_STORE_PASSWORD" "${CERT_DIR}/tls.crt" "${CERT_DIR}/tls.key" custom-key
+    fi
+    if [[ ${BASH_REMATCH[1]} == "oauth"  ]]; then
```
Comment (scholzj) [inline docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh:83]: Should this be `elif`? I think it would make the code more readable as one would need to stop and think whether both can be true or not.

File: docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh [hunk 4]
```diff
@@ -72,19 +72,28 @@ create_keystore /tmp/kafka/cluster.keystore.p12 "$CERTS_STORE_PASSWORD" \
...
-CUSTOM_CERT_DIR="/opt/kafka/certificates/custom-external-9094-certs"
-if [ -d "$CUSTOM_CERT_DIR" ]; then
-    echo "Preparing custom keystore for external listener"
-    create_keystore_without_ca_file /tmp/kafka/custom-external-9094.keystore.p12 "$CERTS_STORE_PASSWORD" "${CUSTOM_CERT_DIR}/tls.crt" "${CUSTOM_CERT_DIR}/tls.key" custom-key
-    echo "Preparing custom keystore for external listener is complete"
-fi
+regex="^\/opt\/kafka\/certificates\/(custom|oauth)-([a-z0-9]{1,11})-([0-9]+)-certs$"
+for CERT_DIR in /opt/kafka/certificates/*; do
+  if [[ $CERT_DIR =~ $regex ]]; then
+    echo "Preparing store for ${BASH_REMATCH[1]} ${BASH_REMATCH[2]} listener"
```
Comment (scholzj) [inline docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh:78]: I know the listener name is unique, but should we list also `${BASH_REMATCH[3]}` for clarity?

File: docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh [hunk 5]
```diff
@@ -72,19 +72,28 @@ create_keystore /tmp/kafka/cluster.keystore.p12 "$CERTS_STORE_PASSWORD" \
...
+        echo "Adding $CRT to truststore $OAUTH_STORE with alias $ALIAS"
+        create_truststore "$OAUTH_STORE" "$CERTS_STORE_PASSWORD" "$CRT" "$ALIAS"
+        INDEX+=1
+      done
+    fi
+    echo "Preparing store for ${BASH_REMATCH[1]} ${BASH_REMATCH[2]} listener is complete"  
+  fi
+done
 
 echo "Preparing truststore for clienttls listener"
```
Comment (scholzj) [inline docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh:98]: I know this was here before. But could you fix the message? I think it is supposed to say _Preparing truststore for client authentication_ or something like that.

File: docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh [hunk 6]
```diff
@@ -96,54 +105,6 @@ for CRT in /opt/kafka/client-ca-certs/*.crt; do
 done
 echo "Preparing truststore for clienttls listener is complete"
```
Comment (scholzj) [inline docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh:106]: Same as above.

File: docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh [hunk 7]
```diff
@@ -72,19 +72,28 @@ create_keystore /tmp/kafka/cluster.keystore.p12 "$CERTS_STORE_PASSWORD" \
...
-    echo "Preparing custom keystore for external listener"
-    create_keystore_without_ca_file /tmp/kafka/custom-external-9094.keystore.p12 "$CERTS_STORE_PASSWORD" "${CUSTOM_CERT_DIR}/tls.crt" "${CUSTOM_CERT_DIR}/tls.key" custom-key
-    echo "Preparing custom keystore for external listener is complete"
-fi
+regex="^\/opt\/kafka\/certificates\/(custom|oauth)-([a-z0-9]{1,11})-([0-9]+)-certs$"
+for CERT_DIR in /opt/kafka/certificates/*; do
+  if [[ $CERT_DIR =~ $regex ]]; then
+    echo "Preparing store for ${BASH_REMATCH[1]} ${BASH_REMATCH[2]} listener"
+    if [[ ${BASH_REMATCH[1]} == "custom"  ]]; then
+      echo /tmp/kafka/"${BASH_REMATCH[1]}"-"${BASH_REMATCH[2]}"-"${BASH_REMATCH[3]}".keystore.p12
```
Comment (scholzj) [inline docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh:80]: Should we improve this message instead of just printing the path? Or is that a debug left overs.

**Review by scholzj — COMMENTED** [review]
Bunch of nits. But I think the core code is good. I also left a comment for one of the older comments.

File: docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh (hunk 7 above)
Comment (ppatierno) [reply docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh:80]: Well I think it's good to have it here, as for oauth in the "Adding ... " message it mention the oauth store path, here we are printing the keystore path. We could improve but the line before says "Preparing store ... " and then the echo prints the keystore name.

Comment (scholzj) [reply docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh:80]: Yeah, I do not object to the log message ... but we should then improve it to not just print the path but add some explanation text.

File: docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh (hunk 1 above)
Comment (ppatierno) [reply docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh]: > wouldn't work equally well with less dependency on the Java code

So I am confused, is the above statement missing a question mark? Are you suggesting to use the more general grouping or not?

Comment (scholzj) [reply docker-images/kafka/scripts/kafka_tls_prepare_certificates.sh]: Yeah, there is missing question mark, sorry ... I think more general would be better.

**Comment by ppatierno** [comment]
@scholzj I think I have addressed all your comments now

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
@strimzi-ci run tests testcase=ListenersST profile=regression

**Review by Frawless — APPROVED** [review]
@im-konge `io.strimzi.systemtest.kafka.listeners.ListenersST.testCustomCertRouteAndTlsRollingUpdate` is something you are fixing in different PR right?

**Comment by im-konge** [comment]
@Frawless yep it will be fixed in #3787

**Comment by scholzj** [comment]
@Frawless @im-konge So what are we missing from merging that PR? Because CustomCerts are exactly what this PR is fixing.

**Comment by im-konge** [comment]
@scholzj you can merge my PR with fixes and then run the suite again..

**Comment by Frawless** [comment]
I think we can merge this and then enhance STs. The changes didn't break anything according to CI.

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=oauth

**Comment by scholzj** [comment]
Merged as suggested by @Frawless
