### PR TITLE
Handling `min.insync.replicas` deletion operation when possible based on ELR version

### LINKED ISSUE #11854: Unspecified `min.insync.replicas` in `Kafka.spac.kafka.config` leads to a never-ending rolling update
When a Kafka cluster is created without configuring the `min.insync.replicas` in `.spec.kafka.config`, it seems to end in a never-ending rolling update, where the brokers are rolled again and again. This seems to be related to the ELR changes.

```
2025-09-10 16:14:36 INFO  KafkaBrokerConfigurationDiff:220 - Reconciliation #112(watch) Kafka(myproject/my-cluster): min.insync.replicas not set in desired, unsetting back to default deleted entry
2025-09-10 16:14:36 ERROR KafkaRoller:706 - Reconciliation #112(watch) Kafka(myproject/my-cluster): Error updating cluster-wide configuration
org.apache.kafka.common.errors.InvalidConfigurationException: Cluster-level min.insync.replicas cannot be removed while ELR is enabled.
2025-09-10 16:14:36 INFO  KafkaRoller:449 - Reconciliation #112(watch) Kafka(myproject/my-cluster): Rolling Pod my-cluster-bodymoor-3000/3000 due to []
2025-09-10 16:14:37 INFO  PodOperator:54 - Reconciliation #112(watch) Kafka(myproject/my-cluster): Rolling pod my-cluster-bodymoor-3000
```

This is likely a blocker for 0.48.0 release.

### PR DESCRIPTION
**Pull request by ppatierno**
This PR fixes #11854.
More details about the rationale behind this fix are described in the issue.

### CODE REVIEW

**Comment by ppatierno** [comment]
Going to ignore Codecov about missing unit test. It's not that simple because of the issue I opened here https://github.com/strimzi/strimzi-kafka-operator/issues/11859

**Comment by ppatierno** [comment]
After comments from @showuon on the issue https://github.com/strimzi/strimzi-kafka-operator/issues/11854#issuecomment-3284475997 I went into a different direction. It seems we should focus on `min.insync.replicas` here taking into account even when ELR is enabled or not.
The PR is in draft because I have a couple of TODO per discussion to be removed when we reach (or not) an agreement on the solution.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaBrokerConfigurationDiff.java [hunk 1]
```diff
@@ -215,7 +223,11 @@ private void removeProperty(Map<String, ConfigModel> configModel, Collection<Alt
         } else {
             // entry is in current, is not in desired, is not default -> it was using non-default value and was removed
             // if the entry was custom, it should be deleted
-            if (!isIgnorableProperty(pathValueWithoutSlash, nodeIsController)) {
+            // TODO: to evaluate if we want a list of such properties or leaving the single one involved
+            //       also if the elrVersion could be even higher than 1 in the future so condition should be > 1
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaBrokerConfigurationDiff.java]: @showuon what's your take on future versions being > 1?

Comment (showuon) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaBrokerConfigurationDiff.java]: Yes, it's possible it'll be > 1, so it's safe to test with `elrVersion >= 1`.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java [hunk 2]
```diff
@@ -657,6 +662,17 @@ private void checkIfRestartOrReconfigureRequired(NodeRef nodeRef, boolean isCont
         restartContext.brokerConfigDiff = brokerConfigDiff;
     }
 
+    /**
+     * Returns the information about the features within the Kafka Cluster
+     * @return information about the features
+     */
+    /* test */ FeatureMetadata featureMetadata() throws ForceableProblem, InterruptedException {
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:669]: This seems pretty risky given how we don't know what state the cluster is in. Or?

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:669]: Wdym? Can you elaborate a bit?

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:669]: Anything to do with rolling is sensitive to whether you can or cannot connect to the cluster. So adding yet another connection there seems pretty risky to me.

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:669]: I can see your point. We are already getting the broker configuration though. With the "features" thing added in Kafka we are entering times where I think we need such information because users can enable/disable them. In this specific case, the `min.insync.replicas` change is pretty related to the ELR feature being enabled or not, so I can't see a different way to get such information if not connecting to the cluster.
I think that with https://github.com/strimzi/strimzi-kafka-operator/issues/11453 and the corresponding proposal we'll go in a direction where a well structured support for preview features will be in Strimzi at some point.
For the contingent issue, ... we need to know if `min.insync.replicas` can be deleted or not and it depends on ELR feature to be get from the cluster.

Comment (tinaselenge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:669]: We only continue to this point, if we can connect to the cluster. If we cannot connect, we start the broker and fail the reconciliation.

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:669]: Ok, it might work in that case I guess.

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java:669]: Yeah any error happening when trying to get broker configuration or features throws a `ForceableProblem` which force a broker restart (which hopefully will recover the connection allowing to get what we need later on).

**Comment by tinaselenge** [comment]
The new solution looks good to me but I would like to clarify my understanding of the reason for going with this solution. 

Previously we removed configuration that is not in the CR, meaning that we reset it to cluster static default value. So for example, the user had changed the default value of `min.insync.replicas` to 2 (via alter config request with empty broker set) but also have `min.insync.replicas` set to 2 in the Kafka CR. When user removes it from their Kafka CR, then this would be reset to 1 by the removal.

With the previous solution or if we just skipped removal of `min.insync.replicas` (without checking ELR), this existing behaviour would have changed. When the config is removed from the CR, it would stay with value of 2(current value = dynamic default) instead of 1(static default) because we don't do the removal. So to avoid changing existing behaviour for all the configuration including `min.insync.replicas`, we are checking ELR version first before skipping removal of `min.insync.replicas`. Is this correct?

I feel like we should be respecting dynamic default for configurations when removed from the CR, therefore not do the removal if the config value is equal to dynamic default (the previous solution).  Because when ELR is enabled, we cannot remove the `min.insync.replicas` anyway, so when the config is removed from the CR, the dynamic default will be used if there is one (not the static default). However I do understand that we want to avoid changing the existing behaviour when ELR is not enabled and am happy with this solution. 

When ELR is permanently enabled (user cannot disable it), I guess we can remove the ELR check?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaBrokerConfigurationDiff.java [hunk 3]
```diff
@@ -215,7 +218,9 @@ private void removeProperty(Map<String, ConfigModel> configModel, Collection<Alt
         } else {
             // entry is in current, is not in desired, is not default -> it was using non-default value and was removed
             // if the entry was custom, it should be deleted
-            if (!isIgnorableProperty(pathValueWithoutSlash, nodeIsController)) {
+            if ("min.insync.replicas".equals(entry.name()) && elrVersion >= 1) {
+                LOGGER.infoCr(reconciliation, "min.insync.replicas cannot be deleted when ELR is enabled");
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaBrokerConfigurationDiff.java]: Assuming this is now ready for review ... this likely should not be here on this level.

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaBrokerConfigurationDiff.java]: Right. I will update it at TRACE level when/if all regressions are green (to be sure I don't need additional changes).

**Comment by ppatierno** [comment]
> So to avoid changing existing behaviour for all the configuration including min.insync.replicas, we are checking ELR version first before skipping removal of min.insync.replicas. Is this correct?

As @showuon said in the issue, there are still properties that can be safely deleted (even is they have `DYNAMIC_DEFAULT_BROKER_CONFIG` as source), so skipping them all (including our dear `min.insync.replicas` was not ok).

> However I do understand that we want to avoid changing the existing behaviour when ELR is not enabled and am happy with this solution. When ELR is permanently enabled (user cannot disable it), I guess we can remove the ELR check?

Yes. Currently you can still disable ELR (even with Kafka 4.1.0) and `min.insync.replicas` deletion is allowed so we should keep this possibility. If Kafka will enable ELR permanently then we can change the current implementation not taking ELR into account anymore.

**Comment by showuon** [comment]
> Previously we removed configuration that is not in the CR, meaning that we reset it to cluster static default value. So for example, the user had changed the default value of min.insync.replicas to 2 (via alter config request with empty broker set) but also have min.insync.replicas set to 2 in the Kafka CR. When user removes it from their Kafka CR, then this would be reset to 1 by the removal.

I'd like to add something here:
1. The goal of ELR to set `min.insync.replicas` in cluster-level is that it wants to have the same value across all the brokers. 
2. Because of that, the source of truth for the config in strimzi is not the config map anymore. The `min.insync.replicas` in cluster-level could be set to 1 by ELR feature itself, but our config map has no entry for `min.insync.replicas`.

To fix the diverge problem, we can 
1. Skip the removal like we have in the PR, but it will have the issue that Tina said, when the `min.insync.replicas=2`in config map, then after user deletes it, nothing will be changed, which has different behavior as other configs.
2. Force the `min.insync.replicas` to be set in the config map, no matter users explicitly add it or not. So the config map can still be the source of truth of the configs. Then when users explicitly delete it, we'll automatically change `min.insync.replicas=1` (default value) in config map, then go with the normal alter config operation.

WDYT?

**Comment by ppatierno** [comment]
> Force the min.insync.replicas to be set in the config map, no matter users explicitly add it or not. So the config map can still be the source of truth of the configs. Then when users explicitly delete it, we'll automatically change min.insync.replicas=1 (default value) in config map, then go with the normal alter config operation.

That could be a way but I think that doing this trick is actually "covering" the expected behaviour from Kafka.
I mean, for people who knows Kafka and the ELR implication, they expect that you cannot delete the `min.insync.replicas` (when ELR is enabled) so the value on the broker will remain the same as the current (and not necessarily defaulting to 1).
It seems to me that applying this trick we are kind of trying to keep an old behaviour on a thing which is changed within Kafka instead of adapting to Apache Kafka itself.
I think we should just document better this "breaking change" with the ELR in our doc.

**Review by showuon — APPROVED** [review]
+1 to document what we did here for `min.insync.replicas` config.

**Comment by ppatierno** [comment]
Together with @PaulRMellor we found a good place where putting a warning about the behaviour of removing `min.insync.replicas` depending on ELR.

**Review by PaulRMellor — APPROVED** [review]
Note is clear. Thanks, Paolo

**Comment by ppatierno** [comment]
The Azure regression before my last doc change was green as well, so we are good to merge this. Thanks all!
