### PR TITLE
Fix issue with running KafkaConnect build with a sidecar

### LINKED ISSUE #4604: Kafka Connect build not recognized as complete due to pod sidecar container
**Describe the bug**
Despite the Kafka Connect build container successfully completing, the operator's status check did not recognize the completion because a permanently running sidecar container was still in the running state. Even if that sidecar was changed to terminate when it's the only container left running in a pod, the code in [src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperator.java](https://github.com/strimzi/strimzi-kafka-operator/blob/d3efe95307cd9218c71b88dd0a0cb0af2ba0f403/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperator.java#L381-L382) incorrectly assumes there will only be one container in the pod, so it's possible it will instead check the final status of the sidecar container depending on the order of the list returned from `getContainers()`.

**To Reproduce**
There's probably an easier way to reproduce this, but for us:
1. Setup [Istio with automatic sidecar injection](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#automatic-sidecar-injection)
2. Create KafkaConnect custom resource w/ build specified
```
  build:
    output:
      type: docker
      image: <image>
    plugins:
      - name: camel-salesforce
        artifacts:
          - type: jar
            url: https://repo.maven.apache.org/maven2/org/apache/camel/kafkaconnector/camel-salesforce-kafka-connector/0.8.0/camel-salesforce-kafka-connector-0.8.0.jar
 ```
3. Wait for Status of build container to be `Complete`, `kubectl get pod -o yaml <build_pod>`
4. Build gets "stuck", eventually times out and operator restarts the build

**Expected behavior**
The operator continues the Kafka Connect deployment upon successful completion of the build container

**Environment (please complete the following information):**
- Strimzi version: 0.21.1
- Installation method: Helm chart
- Kubernetes cluster: Kubernetes 1.18
- Infrastructure: Amazon EKS, Istio

**YAML files and logs**

Operator logs showing eventual timeout:
```
2021-03-18 20:16:08 DEBUG PodOperator:107 - Pods events-cluster/connect-cluster-connect-build does not exist, creating it
2021-03-18 20:16:09 DEBUG PodOperator:218 - Pods connect-cluster-connect-build in namespace events-cluster has been created
2021-03-18 20:16:09 DEBUG Util:94 - Waiting for Pods resource connect-cluster-connect-build in namespace events-cluster to get complete
2021-03-18 20:17:55 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace events-cluster...
2021-03-18 20:17:55 DEBUG AbstractOperator:356 - Reconciliation #504(timer) KafkaConnect(events-cluster/connect-cluster): Try to acquire lock lock::events-cluster::KafkaConnect::connect-cluster
2021-03-18 20:18:05 WARN  AbstractOperator:379 - Reconciliation #504(timer) KafkaConnect(events-cluster/connect-cluster): Failed to acquire lock lock::events-cluster::KafkaConnect::connect-cluster within 10000ms.
2021-03-18 20:19:55 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace events-cluster...
2021-03-18 20:19:55 DEBUG AbstractOperator:356 - Reconciliation #505(timer) KafkaConnect(events-cluster/connect-cluster): Try to acquire lock lock::events-cluster::KafkaConnect::connect-cluster
2021-03-18 20:20:05 WARN  AbstractOperator:379 - Reconciliation #505(timer) KafkaConnect(events-cluster/connect-cluster): Failed to acquire lock lock::events-cluster::KafkaConnect::connect-cluster within 10000ms.
2021-03-18 20:21:09 ERROR Util:125 - Exceeded timeout of 300000ms while waiting for Pods resource connect-cluster-connect-build in namespace events-cluster to be complete
2021-03-18 20:21:09 ERROR AbstractOperator:240 - Reconciliation #503(timer) KafkaConnect(events-cluster/connect-cluster): createOrUpdate failed
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Pods resource connect-cluster-connect-build in namespace events-cluster to be complete
```

Status of build pod showing completion of build container:
```
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-03-18T22:09:55Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-03-18T22:10:40Z'
      reason: ContainersNotReady
      message: >-
        containers with unready status:
        [connect-cluster-connect-build]
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-03-18T22:10:40Z'
      reason: ContainersNotReady
      message: >-
        containers with unready status:
        [connect-cluster-connect-build]
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-03-18T22:09:53Z'
  containerStatuses:
    - name: istio-proxy
      state:
        running:
          startedAt: '2021-03-18T22:09:55Z'
      lastState: {}
      ready: true
      restartCount: 0
      containerID: >-
        docker://991316bf212b7a71dbe95e5fd735069bb23af57f7abba90d754b4589cb7370ee
      started: true
    - name: connect-cluster-connect-build
      state:
        terminated:
          exitCode: 0
          reason: Completed
          message: >
            *********.dkr.ecr.***.amazonaws.com/****/******@sha256:4813e6e629c879d235ce4ee30b8cd62ed99f14a12ecab17ad6d96d8695963a2f
          startedAt: '2021-03-18T22:09:58Z'
          finishedAt: '2021-03-18T22:10:40Z'
          containerID: >-
            docker://998ac6252b6195d519b941a77056aa4a6150bbde357a345bcc578422ac1006e7
      lastState: {}
      ready: false
      restartCount: 0
      image: 'gcr.io/kaniko-project/executor:v1.3.0'
      imageID: >-
        docker-pullable://gcr.io/kaniko-project/executor@sha256:99eec410fa32cd77cdb7685c70f86a96debb8b087e77e63d7fe37eaadb178709
      containerID: >-
        docker://998ac6252b6195d519b941a77056aa4a6150bbde357a345bcc578422ac1006e7
      started: false
```
**Additional context**
As a workaround I was able to use the template for the build pod to add an annotation to disable Istio sidecar injection for the pod, but it seems like Strimzi could be more resilient here by checking explicitly for what it cares about (the build container status by container name/id being complete).
```
  template:
    buildPod:
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
```

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Type of change

- Bugfix

### Description

How mentioned in #4604 , when running KafkaConnect build with sidecar, the build is basically never completed, as we are checking always the first container status (which could be status of the sidecar).

This PR fixes this behavior - adding possibility to run KafkaConnect build with the sidecar.

Fixes #4604 

### Checklist

- [ ] Make sure all tests pass
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java [hunk 1]
```diff
@@ -21,9 +22,9 @@ public static boolean buildPodComplete(Pod pod)   {
                 && pod.getStatus() != null
                 && pod.getStatus().getContainerStatuses() != null
                 && pod.getStatus().getContainerStatuses().size() > 0
-                && pod.getStatus().getContainerStatuses().get(0) != null
-                && pod.getStatus().getContainerStatuses().get(0).getState() != null
-                && pod.getStatus().getContainerStatuses().get(0).getState().getTerminated() != null;
+                && getConnectBuildContainerStatus(pod) != null
+                && getConnectBuildContainerStatus(pod).getState() != null
+                && getConnectBuildContainerStatus(pod).getState().getTerminated() != null;
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java:27]: I think you should try to avoid streaming through the conditions 3 times. Maybe make the `getConnectBuildContainerStatus` method smarter to to check the null and return the state or you can split the if and get the container status once and then use it multiple times?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java [hunk 2]
```diff
@@ -83,4 +84,15 @@ public static boolean buildSucceeded(Build build)   {
     public static boolean buildComplete(Build build)   {
         return buildSucceeded(build) || buildFailed(build);
     }
+
+    /**
+     * Get ContainerStatus of the Connect build container
+     *
+     * @param pod - Pod which contains ContainerStatus of the Connect build
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java:91]:
```suggestion
     * @param pod Pod which contains ContainerStatus of the Connect build
```

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java (hunk 1 above)
Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java]: Yeah, makes totally sense. This should be fixed now. Thanks :)

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java [hunk 3]
```diff
@@ -83,4 +83,17 @@ public static boolean buildSucceeded(Build build)   {
...
+     * Get ContainerStatus of the Connect build container
+     *
+     * @param pod Pod which contains ContainerStatus of the Connect build
+     *
+     * @return ContainerStatus of the build container
+     */
+    public static ContainerState getConnectBuildContainerStatus(Pod pod)   {
+        ContainerStatus containerStatus = pod.getStatus().getContainerStatuses().stream()
+            .filter(conStatus -> conStatus.getName().equals(pod.getMetadata().getName())).findFirst().orElseGet(ContainerStatus::new);
+        return containerStatus.getState() != null ? containerStatus.getState() : new ContainerState();
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java:97]: I think this should probably return null when it is not there, or?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java [hunk 4]
```diff
@@ -83,4 +83,17 @@ public static boolean buildSucceeded(Build build)   {
...
+    /**
+     * Get ContainerStatus of the Connect build container
+     *
+     * @param pod Pod which contains ContainerStatus of the Connect build
+     *
+     * @return ContainerStatus of the build container
+     */
+    public static ContainerState getConnectBuildContainerStatus(Pod pod)   {
+        ContainerStatus containerStatus = pod.getStatus().getContainerStatuses().stream()
+            .filter(conStatus -> conStatus.getName().equals(pod.getMetadata().getName())).findFirst().orElseGet(ContainerStatus::new);
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java:96]: Do we have something better to use here than `pod.getMetadata().getName()` for container name? Seems a bit wierd to me.

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java:96]: That would be better, yes. I wonder why the Pod name is the container name. But if we did it like that, it might not make sense to change it right now.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java (hunk 3 above)
Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java:97]: In this moment we can return just `containerStatus.getState()`, as it already can contain `null`

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java:97]: Yeah, sure.

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuildUtils.java]: That is not exactly what I meant. There is a difference between the ContainerState being null and you creating a new ContainerState. I think you should not create it and just return the null.

**Review by scholzj — COMMENTED** [review]
LGTM. Maybe you should add some tests with multiple containers as well? For example for the Util methods.

**Comment by im-konge** [comment]
Thanks, I forgot about it! Will add them soon.

**Comment by im-konge** [comment]
@scholzj I added class for the `KafkaConnectBuildUtils` with simple test with multi-container pod. Can you take a look at it please?

**Review by ppatierno — APPROVED** [review]

**Review by scholzj — APPROVED** [review]
