### PR TITLE
Manage SCRAM-SHA-512 credentials without starting new JVMs

### LINKED ISSUE #965: User Operator doesn't scale
The User Operator doesn't scale when used with amount of users. It tries to start multiple processes and starts running out of memory. It should be probably changed to avoid starting new JVM processes to manage the SCRAM users.

```
Oct 10, 2018 7:15:58 PM io.vertx.core.impl.BlockedThreadChecker
--
  | WARNING: Thread Thread[vert.x-eventloop-thread-4,5,main] has been blocked for 2486 ms, time limit is 2000
  | Oct 10, 2018 7:15:58 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 2588 ms, time limit is 2000
  | Oct 10, 2018 7:15:58 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-5,5,main] has been blocked for 2287 ms, time limit is 2000
  | Oct 10, 2018 7:15:58 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 2591 ms, time limit is 2000
  | 2018-10-10 19:15:59 INFO  ProcessHelper:32 - Started process java.lang.UNIXProcess@38faae02 with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java, -cp, /user-operator-0.8.0-SNAPSHOT.jar, kafka.admin.ConfigCommand, kafka-configs.sh, --zookeeper, localhost:2181, --describe, --entity-name, my-user2, --entity-type, users]
  | 2018-10-10 19:15:59 INFO  ProcessHelper:32 - Started process java.lang.UNIXProcess@12383e8a with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java, -cp, /user-operator-0.8.0-SNAPSHOT.jar, kafka.admin.ConfigCommand, kafka-configs.sh, --zookeeper, localhost:2181, --describe, --entity-name, my-user, --entity-type, users]
  | Oct 10, 2018 7:15:59 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 3589 ms, time limit is 2000
  | Oct 10, 2018 7:15:59 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 3592 ms, time limit is 2000
  | 2018-10-10 19:16:00 INFO  ProcessHelper:32 - Started process java.lang.UNIXProcess@49fa91da with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java, -cp, /user-operator-0.8.0-SNAPSHOT.jar, kafka.admin.ConfigCommand, kafka-configs.sh, --zookeeper, localhost:2181, --describe, --entity-name, kafka-test-apps-consumer, --entity-type, users]
  | 2018-10-10 19:16:00 INFO  ProcessHelper:32 - Started process java.lang.UNIXProcess@68b7dc51 with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java, -cp, /user-operator-0.8.0-SNAPSHOT.jar, kafka.admin.ConfigCommand, kafka-configs.sh, --zookeeper, localhost:2181, --describe, --entity-name, kafka-test-apps-producer, --entity-type, users]
  | 2018-10-10 19:16:36 INFO  ProcessHelper:36 - Process java.lang.UNIXProcess@68b7dc51: exited with status 137
  | 2018-10-10 19:16:36 INFO  ProcessHelper:36 - Process java.lang.UNIXProcess@38faae02: exited with status 137
  | 2018-10-10 19:16:36 ERROR KafkaUserOperator:181 - Reconciliation #1(watch) KafkaUser(myproject/kafka-test-apps-producer): createOrUpdate failed
  | java.lang.RuntimeException: io.strimzi.operator.common.process.ProcessHelper$ProcessResult@18699a2a exited with code 137 and is missing expected output
  | at io.strimzi.operator.user.operator.ScramShaCredentials.unexpectedOutput(ScramShaCredentials.java:139) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.strimzi.operator.user.operator.ScramShaCredentials.exists(ScramShaCredentials.java:103) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.strimzi.operator.user.operator.ScramShaCredentialsOperator.lambda$reconcile$0(ScramShaCredentialsOperator.java:28) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [user-operator-0.8.0-SNAPSHOT.jar:?]
  | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
  | 2018-10-10 19:16:36 ERROR KafkaUserOperator:181 - Reconciliation #3(watch) KafkaUser(myproject/my-user2): createOrUpdate failed
  | java.lang.RuntimeException: io.strimzi.operator.common.process.ProcessHelper$ProcessResult@3b3d2df6 exited with code 137 and is missing expected output
  | at io.strimzi.operator.user.operator.ScramShaCredentials.unexpectedOutput(ScramShaCredentials.java:139) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.strimzi.operator.user.operator.ScramShaCredentials.exists(ScramShaCredentials.java:103) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.strimzi.operator.user.operator.ScramShaCredentialsOperator.lambda$reconcile$0(ScramShaCredentialsOperator.java:28) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [user-operator-0.8.0-SNAPSHOT.jar:?]
  | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
  | 2018-10-10 19:16:40 INFO  ProcessHelper:36 - Process java.lang.UNIXProcess@12383e8a: exited with status 0
  | 2018-10-10 19:16:40 INFO  ProcessHelper:32 - Started process java.lang.UNIXProcess@6a78e67f with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java, -cp, /user-operator-0.8.0-SNAPSHOT.jar, kafka.admin.ConfigCommand, --zookeeper, localhost:2181, --alter, --entity-name, my-user, --entity-type, users, --add-config, SCRAM-SHA-512=[password=mcCi9HrKicrG]]
  | 2018-10-10 19:16:40 INFO  ProcessHelper:36 - Process java.lang.UNIXProcess@49fa91da: exited with status 0
  | 2018-10-10 19:16:40 INFO  KafkaUserOperator:340 - Reconciliation #0(watch) KafkaUser(myproject/kafka-test-apps-consumer): User reconciled
  | 2018-10-10 19:16:48 INFO  ProcessHelper:36 - Process java.lang.UNIXProcess@6a78e67f: exited with status 0
  | 2018-10-10 19:16:48 INFO  KafkaUserOperator:340 - Reconciliation #2(watch) KafkaUser(myproject/my-user): User reconciled
  | 2018-10-10 19:17:53 INFO  UserOperator:85 - Triggering periodic reconciliation for namespace myproject...
  | 2018-10-10 19:17:53 INFO  ProcessHelper:32 - Started process java.lang.UNIXProcess@13823b1e with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java, -cp, /user-operator-0.8.0-SNAPSHOT.jar, kafka.admin.ConfigCommand, kafka-configs.sh, --zookeeper, localhost:2181, --describe, --entity-type, users]
  | Oct 10, 2018 7:17:55 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2093 ms, time limit is 2000
  | Oct 10, 2018 7:17:56 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3093 ms, time limit is 2000
  | Oct 10, 2018 7:17:57 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4093 ms, time limit is 2000
  | Oct 10, 2018 7:17:58 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5093 ms, time limit is 2000
  | io.vertx.core.VertxException: Thread blocked
  | at java.lang.Object.wait(Native Method)
  | at java.lang.Object.wait(Object.java:502)
  | at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
  | at io.strimzi.operator.common.process.ProcessHelper.executeSubprocess(ProcessHelper.java:34)
  | at io.strimzi.operator.user.operator.ScramShaCredentials.exec(ScramShaCredentials.java:171)
  | at io.strimzi.operator.user.operator.ScramShaCredentials.list(ScramShaCredentials.java:113)
  | at io.strimzi.operator.user.operator.ScramShaCredentialsOperator.list(ScramShaCredentialsOperator.java:47)
  | at io.strimzi.operator.user.operator.KafkaUserOperator.lambda$reconcileAll$8(KafkaUserOperator.java:250)
  | at io.strimzi.operator.user.operator.KafkaUserOperator$$Lambda$249/1443115643.handle(Unknown Source)
  | at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:76)
  | at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289)
  | at io.vertx.core.impl.ContextImpl$$Lambda$179/1250484127.handle(Unknown Source)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
  | at io.vertx.core.impl.ContextImpl$$Lambda$168/865858182.run(Unknown Source)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  |  
  | Oct 10, 2018 7:17:59 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 6092 ms, time limit is 2000
  | io.vertx.core.VertxException: Thread blocked
  | at java.lang.Object.wait(Native Method)
  | at java.lang.Object.wait(Object.java:502)
  | at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
  | at io.strimzi.operator.common.process.ProcessHelper.executeSubprocess(ProcessHelper.java:34)
  | at io.strimzi.operator.user.operator.ScramShaCredentials.exec(ScramShaCredentials.java:171)
  | at io.strimzi.operator.user.operator.ScramShaCredentials.list(ScramShaCredentials.java:113)
  | at io.strimzi.operator.user.operator.ScramShaCredentialsOperator.list(ScramShaCredentialsOperator.java:47)
  | at io.strimzi.operator.user.operator.KafkaUserOperator.lambda$reconcileAll$8(KafkaUserOperator.java:250)
  | at io.strimzi.operator.user.operator.KafkaUserOperator$$Lambda$249/1443115643.handle(Unknown Source)
  | at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:76)
  | at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289)
  | at io.vertx.core.impl.ContextImpl$$Lambda$179/1250484127.handle(Unknown Source)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
  | at io.vertx.core.impl.ContextImpl$$Lambda$168/865858182.run(Unknown Source)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  |  
  | Oct 10, 2018 7:18:00 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 7093 ms, time limit is 2000
  | io.vertx.core.VertxException: Thread blocked
  | at java.lang.Object.wait(Native Method)
  | at java.lang.Object.wait(Object.java:502)
  | at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
  | at io.strimzi.operator.common.process.ProcessHelper.executeSubprocess(ProcessHelper.java:34)
  | at io.strimzi.operator.user.operator.ScramShaCredentials.exec(ScramShaCredentials.java:171)
  | at io.strimzi.operator.user.operator.ScramShaCredentials.list(ScramShaCredentials.java:113)
  | at io.strimzi.operator.user.operator.ScramShaCredentialsOperator.list(ScramShaCredentialsOperator.java:47)
  | at io.strimzi.operator.user.operator.KafkaUserOperator.lambda$reconcileAll$8(KafkaUserOperator.java:250)
  | at io.strimzi.operator.user.operator.KafkaUserOperator$$Lambda$249/1443115643.handle(Unknown Source)
  | at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:76)
  | at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289)
  | at io.vertx.core.impl.ContextImpl$$Lambda$179/1250484127.handle(Unknown Source)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
  | at io.vertx.core.impl.ContextImpl$$Lambda$168/865858182.run(Unknown Source)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  |  
  | Oct 10, 2018 7:18:01 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 8093 ms, time limit is 2000
  | io.vertx.core.VertxException: Thread blocked
  | at java.lang.Object.wait(Native Method)
  | at java.lang.Object.wait(Object.java:502)
  | at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
  | at io.strimzi.operator.common.process.ProcessHelper.executeSubprocess(ProcessHelper.java:34)
  | at io.strimzi.operator.user.operator.ScramShaCredentials.exec(ScramShaCredentials.java:171)
  | at io.strimzi.operator.user.operator.ScramShaCredentials.list(ScramShaCredentials.java:113)
  | at io.strimzi.operator.user.operator.ScramShaCredentialsOperator.list(ScramShaCredentialsOperator.java:47)
  | at io.strimzi.operator.user.operator.KafkaUserOperator.lambda$reconcileAll$8(KafkaUserOperator.java:250)
  | at io.strimzi.operator.user.operator.KafkaUserOperator$$Lambda$249/1443115643.handle(Unknown Source)
  | at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:76)
  | at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289)
  | at io.vertx.core.impl.ContextImpl$$Lambda$179/1250484127.handle(Unknown Source)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
  | at io.vertx.core.impl.ContextImpl$$Lambda$168/865858182.run(Unknown Source)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  |  
  | 2018-10-10 19:18:02 INFO  ProcessHelper:36 - Process java.lang.UNIXProcess@13823b1e: exited with status 0
  | 2018-10-10 19:18:02 INFO  KafkaUserOperator:172 - Reconciliation #4(timer) KafkaUser(myproject/kafka-test-apps-producer): User kafka-test-apps-producer should be created or updated
  | 2018-10-10 19:18:02 INFO  ProcessHelper:32 - Started process java.lang.UNIXProcess@4eb9264e with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java, -cp, /user-operator-0.8.0-SNAPSHOT.jar, kafka.admin.ConfigCommand, kafka-configs.sh, --zookeeper, localhost:2181, --describe, --entity-name, kafka-test-apps-producer, --entity-type, users]
  | 2018-10-10 19:18:02 INFO  KafkaUserOperator:172 - Reconciliation #5(timer) KafkaUser(myproject/my-user2): User my-user2 should be created or updated
  | 2018-10-10 19:18:03 INFO  KafkaUserOperator:172 - Reconciliation #6(timer) KafkaUser(myproject/kafka-test-apps-consumer): User kafka-test-apps-consumer should be created or updated
  | 2018-10-10 19:18:03 INFO  ProcessHelper:32 - Started process java.lang.UNIXProcess@27e90918 with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java, -cp, /user-operator-0.8.0-SNAPSHOT.jar, kafka.admin.ConfigCommand, kafka-configs.sh, --zookeeper, localhost:2181, --describe, --entity-name, my-user2, --entity-type, users]
  | 2018-10-10 19:18:03 INFO  ProcessHelper:32 - Started process java.lang.UNIXProcess@135ec268 with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java, -cp, /user-operator-0.8.0-SNAPSHOT.jar, kafka.admin.ConfigCommand, kafka-configs.sh, --zookeeper, localhost:2181, --describe, --entity-name, kafka-test-apps-consumer, --entity-type, users]
  | 2018-10-10 19:18:03 INFO  KafkaUserOperator:172 - Reconciliation #7(timer) KafkaUser(myproject/my-user): User my-user should be created or updated
  | 2018-10-10 19:18:03 INFO  ProcessHelper:32 - Started process java.lang.UNIXProcess@5c952b3d with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/bin/java, -cp, /user-operator-0.8.0-SNAPSHOT.jar, kafka.admin.ConfigCommand, kafka-configs.sh, --zookeeper, localhost:2181, --describe, --entity-name, my-user, --entity-type, users]
  | 2018-10-10 19:18:34 INFO  ProcessHelper:36 - Process java.lang.UNIXProcess@27e90918: exited with status 137
  | 2018-10-10 19:18:34 INFO  ProcessHelper:36 - Process java.lang.UNIXProcess@4eb9264e: exited with status 137
  | 2018-10-10 19:18:34 ERROR KafkaUserOperator:181 - Reconciliation #4(timer) KafkaUser(myproject/kafka-test-apps-producer): createOrUpdate failed
  | java.lang.RuntimeException: io.strimzi.operator.common.process.ProcessHelper$ProcessResult@1ad465e3 exited with code 137 and is missing expected output
  | at io.strimzi.operator.user.operator.ScramShaCredentials.unexpectedOutput(ScramShaCredentials.java:139) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.strimzi.operator.user.operator.ScramShaCredentials.exists(ScramShaCredentials.java:103) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.strimzi.operator.user.operator.ScramShaCredentialsOperator.lambda$reconcile$0(ScramShaCredentialsOperator.java:28) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [user-operator-0.8.0-SNAPSHOT.jar:?]
  | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
  | 2018-10-10 19:18:34 ERROR KafkaUserOperator:181 - Reconciliation #5(timer) KafkaUser(myproject/my-user2): createOrUpdate failed
  | java.lang.RuntimeException: io.strimzi.operator.common.process.ProcessHelper$ProcessResult@66ee0136 exited with code 137 and is missing expected output
  | at io.strimzi.operator.user.operator.ScramShaCredentials.unexpectedOutput(ScramShaCredentials.java:139) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.strimzi.operator.user.operator.ScramShaCredentials.exists(ScramShaCredentials.java:103) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.strimzi.operator.user.operator.ScramShaCredentialsOperator.lambda$reconcile$0(ScramShaCredentialsOperator.java:28) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273) ~[user-operator-0.8.0-SNAPSHOT.jar:?]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [user-operator-0.8.0-SNAPSHOT.jar:?]
  | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix
- Enhancement / new feature

### Description

The User Operator is currently using the `kafka-configs.sh` binary to manage SCRAM-SHA-512 users. This binary starts new VM inside the container and that doesn't scale well with multiple users, when the UO starts running out of memory after it tries to start multiple JVMs in parallel.

This PR changes the way the SCRAM users are managed to manage them directly in the Zookeeper database without starting new JVMs and using the `kafka-configs.sh` utility. That should allow it to scale better, as it should handle the resources in a better way.

This PR should close #965 

### Checklist

- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

File: user-operator/src/main/java/io/strimzi/operator/user/operator/ScramShaCredentials.java [hunk 1]
```diff
@@ -4,199 +4,176 @@
...
-                throw unexpectedOutput(pr);
-            }
+        byte[] data = zkClient.readData("/config/users/" + username, true);
+
+        if (data != null)   {
+            log.debug("Deleting {} credentials for user {}", mechanism.mechanismName(), username);
+
+            JsonObject json = new JsonObject()
+                    .put("version", 1)
+                    .put("config", new JsonObject());
```
Comment (tombentley) [inline user-operator/src/main/java/io/strimzi/operator/user/operator/ScramShaCredentials.java]: Users can have other configs apart from `SCRAM-SHA-512`: `producer_byte_rate`, `consumer_byte_rate`, `request_percentage`. To preserve those we should really fetch their existing configs, remove `SCRAM-SHA-512` and update.

File: user-operator/src/main/java/io/strimzi/operator/user/operator/ScramShaCredentials.java [hunk 2]
```diff
@@ -4,199 +4,176 @@
...
+            ScramCredential credentials = formatter.generateCredential(password, ITERATIONS);
 
-    public static void main(String[] args) {
-        ScramShaCredentials scramSha = new ScramShaCredentials("localhost:2181");
-        scramSha.createOrUpdate("tom", "password", -1);
-        scramSha.createOrUpdate("tom", "password", 4096);
-        scramSha.delete("tom");
+            JsonObject json = new JsonObject()
+                    .put("version", 1)
+                    .put("config", new JsonObject().put(mechanism.mechanismName(), ScramCredentialUtils.credentialToString(credentials)));
```
Comment (tombentley) [inline user-operator/src/main/java/io/strimzi/operator/user/operator/ScramShaCredentials.java]: Similarly, because this is used on the update path this will obliterate and existing user configs.

File: user-operator/src/main/java/io/strimzi/operator/user/operator/ScramShaCredentials.java (hunk 1 above)
Comment (scholzj) [reply user-operator/src/main/java/io/strimzi/operator/user/operator/ScramShaCredentials.java]: Fair enough ... I didn't know that quotas are stored here as well. I thought it's only the SCRAM credentials.

**Comment by scholzj** [comment]
@tombentley Ok, it should be fixed now. Wanna do another review?

File: systemtest/src/test/java/io/strimzi/systemtest/KafkaST.java [hunk 3]
```diff
@@ -415,6 +415,11 @@ void testSendMessagesPlainScramSha() {
                             .withPlain(listenerTls)
                         .endListeners()
                     .endKafka()
+                    .editEntityOperator()
+                        .editUserOperator()
+                            .withImage("scholzj/user-operator:latest")
```
Comment (ppatierno) [inline systemtest/src/test/java/io/strimzi/systemtest/KafkaST.java]: why the master should use a personal image? I guess it's a typo right?

Comment (scholzj) [reply systemtest/src/test/java/io/strimzi/systemtest/KafkaST.java]: Dammit ... that should have been never committed ;-)
