### PR TITLE
Avoid infinite reconciliation loop of Ingress resources on Rancher

### LINKED ISSUE #11414: [Bug]: Infinite loop reconcile due to Rancher annotations
### Bug Description

We are running Strimzi (v0.45.0) Kafka (v3.9.0) alongside Rancher (v2.7.9).
There is an issue with Ingress resource, where our Nginx ingress controller keeps syncing with new Ingress that has been reconciled by Strimzi Operator. Rancher agent and Strimzi Operator keep competing over annotation, and every 2 seconds Ingress gets updated and new resourceVersion assigned.

Here is the operator log:
2025-05-06 14:49:06 DEBUG ResourceDiff:65 - Reconciliation #1652(watch) Kafka(kafka/xxx-cluster): Ingress xxx-cluster-kafka-externaltls-bootstrap differs: {"op":"remove","path":"/metadata/annotations/field.cattle.io~1publicEndpoints"} 
2025-05-06T16:49:06.065012677+02:00 2025-05-06 14:49:06 DEBUG ResourceDiff:66 - Reconciliation #1652(watch) Kafka(kafka/xxx-cluster): Current Ingress xxx-cluster-kafka-externaltls-bootstrap path /metadata/annotations/field.cattle.io~1publicEndpoints has value 2025-05-06T16:49:06.065029748+02:00 2025-05-06 14:49:06 DEBUG ResourceDiff:67 - Reconciliation #1652(watch) Kafka(kafka/xxx-cluster): Desired Ingress xxx-cluster-kafka-externaltls-bootstrap path /metadata/annotations/field.cattle.io~1publicEndpoints has value 
2025-05-06 14:49:06 DEBUG AbstractNamespacedResourceOperator:236 - Reconciliation #1652(watch) Kafka(kafka/xxx-cluster): Ingress xxx-cluster-kafka-externaltls-bootstrap in namespace kafka has been patched

I have noticed there was a bug report already on this long time ago, and that it was fixed with LOADBALANCER_ANNOTATION_IGNORELIST (https://github.com/strimzi/strimzi-kafka-operator/issues/4035), but we are still experiencing the problem.

### Steps to reproduce

_No response_

### Expected behavior

Resources updated by Rancher annotations should not trigger reconciliation.

### Strimzi version

0.45.0

### Kubernetes version

1.28.15

### Installation method

Helm chart

### Infrastructure

Bare-metal

### Configuration files and logs

2025-05-06 14:49:06 DEBUG ResourceDiff:65 - Reconciliation #1652(watch) Kafka(kafka/xxx-cluster): Ingress xxx-cluster-kafka-externaltls-bootstrap differs: {"op":"remove","path":"/metadata/annotations/field.cattle.io~1publicEndpoints"} 
2025-05-06T16:49:06.065012677+02:00 2025-05-06 14:49:06 DEBUG ResourceDiff:66 - Reconciliation #1652(watch) Kafka(kafka/xxx-cluster): Current Ingress xxx-cluster-kafka-externaltls-bootstrap path /metadata/annotations/field.cattle.io~1publicEndpoints has value 2025-05-06T16:49:06.065029748+02:00 2025-05-06 14:49:06 DEBUG ResourceDiff:67 - Reconciliation #1652(watch) Kafka(kafka/xxx-cluster): Desired Ingress xxx-cluster-kafka-externaltls-bootstrap path /metadata/annotations/field.cattle.io~1publicEndpoints has value 
2025-05-06 14:49:06 DEBUG AbstractNamespacedResourceOperator:236 - Reconciliation #1652(watch) Kafka(kafka/xxx-cluster): Ingress xxx-cluster-kafka-externaltls-bootstrap in namespace kafka has been patched

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

When using Ingress listener on Rancher clusters, Rancher might set additional annotations to the Ingress resources. And Strimzi will be removing them and thus they wil be running a there and back again and again. This PR adds an ignore list to the Ingress reconciliation, similarly to what we already have for Services (also on Rancher) to avoid the sam eproblem.

As part of this, it also:
* Moves the ignore list definition from the `Annotations` class to the operator classes (there is no reason to have these constants as public in the common module when each of them is used only in one place in the cluster operator module and thus can be private). The ignore list is anyway different from the annotations used by Strimzi directly, so not sure why we had it in that class.
* Uses a single static method in a new `KubernetesResourceOperatorUtils` -> this seemed better than having it in one of the abstract classes as the use of this method is only in two classes out of almost 30.

This PR should resolve #11414 

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Review by im-konge — APPROVED** [review]
LGTM, thanks.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/kubernetes/IngressOperator.java [hunk 1]
```diff
@@ -14,10 +14,19 @@
...
+
 /**
  * Operations for {@code Ingress}es.
  */
 public class IngressOperator extends AbstractNamespacedResourceOperator<KubernetesClient, Ingress, IngressList, Resource<Ingress>> {
+    /**
+     * List of predicates that allows existing ingress annotations to be retained while reconciling the resources.
+     */
+    private static final List<Predicate<String>> INGRESS_ANNOTATION_IGNORELIST = List.of(
+            annotation -> annotation.startsWith("field.cattle.io")
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/kubernetes/IngressOperator.java:29]: should we have a comment to make it clear that this annotation is coming from Rancher. I don't know Rancher so looking at the code I would not understand why this specific text is part of the ignore list.
A comment would be sufficient or we could have a well named constant to define it (i.e. something with `RANCHER_xxxxx`)

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/kubernetes/ServiceOperator.java [hunk 2]
```diff
@@ -44,6 +40,14 @@ public class ServiceOperator extends AbstractNamespacedResourceOperator<Kubernet
                     "|/spec/internalTrafficPolicy" + // Set by Kubernetes to Cluster as default (not configurable through Strimzi as it does nto seem to make much sense for us, so we ignore it)
                     "|/status)$");
 
+    /**
+     * List of predicates that allows existing load balancer service annotations to be retained while reconciling the resources.
+     */
+    private static final List<Predicate<String>> LOADBALANCER_ANNOTATION_IGNORELIST = List.of(
+            annotation -> annotation.startsWith("cattle.io/"),
+            annotation -> annotation.startsWith("field.cattle.io")
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/kubernetes/ServiceOperator.java:49]: Ditto as above, just a comment to make it clear from where they are coming.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/kubernetes/IngressOperator.java (hunk 1 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/kubernetes/IngressOperator.java:29]: It might be only question of time until we add annotations for something else than Rancher. So I do not think renaming the variables makes sense. But I added the comments -> that is for sure useful.
