### PR TITLE
Fixed the KafkaRebalance resource reconciliation getting stuck if CC pod is restarted during rebalance

### LINKED ISSUE #10091: [Bug]: KafkaRebalance resource reconciliation gets stuck if CC pod is restarted during rebalance
### Bug Description

Encountered a weird behaviour in 0.40. If the CC pod is restarted in the middle of a rebalance, the KafkaRebalance resource reconciliation gets stuck with the following cluster operator logs:
```
2024-05-09 09:27:54 INFO KafkaRebalanceAssemblyOperator:1018 - Reconciliation #184(kafkarebalance-watch) KafkaRebalance(strimzi/my-rebalance): Getting Cruise Control rebalance user task status
2024-05-09 09:27:54 ERROR ContextImpl: - Unhandled exception
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
    at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
    at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
    at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
    at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
    at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
    at io.vertx.core.json.JsonArray.getJsonObject(JsonArray.java:243) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.strimzi.operator.cluster.operator.resource.cruisecontrol.CruiseControlApiImpl.lambda$getUserTaskStatus$14(CruiseControlApiImpl.java:328) ~[io.strimzi.cluster-operator-0.40.0.1.0.0-b274.jar:0.40.0.1.0.0-b274]
    at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:305) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:295) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:57) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:246) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:79) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:250) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$new$0(Http1xClientConnection.java:418) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:134) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:705) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:320) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:300) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:941) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:811) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:775) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:159) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153) ~[io.vertx.vertx-core-4.5.4.jar:4.5.4]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[io.netty.netty-codec-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[io.netty.netty-codec-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475) ~[io.netty.netty-handler-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338) ~[io.netty.netty-handler-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387) ~[io.netty.netty-handler-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[io.netty.netty-codec-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[io.netty.netty-codec-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[io.netty.netty-codec-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[io.netty.netty-transport-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.107.Final.jar:4.1.107.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.107.Final.jar:4.1.107.Final]
    at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Steps to reproduce

1. Create a kafka cluster with 1 nodepool, 3 brokers and CC
2. Create an imbalanced state (e.g. 1 topic, 120 partitions, RF=2 and all replicas on broker 0 and 1) (Just make sure that rebalancing from this state would take at least a few minutes)
3. Trigger a rebalance
4. After the rebalance started, scale up the nodepool to 4
5. Observe as the CC pod gets restarted due to the new broker in the middle of the rebalance
6. Observe how the reconciliation of the KafkaRebalance resource gets stuck (CC does not persist tasks)

### Expected behavior

_No response_

### Strimzi version

0.40.0

### Kubernetes version

v1.28.7+k3s1

### Installation method

helm

### Infrastructure

Bare-metal

### Configuration files and logs

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: pool-a
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: ephemeral
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.7.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.7"
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
  cruiseControl: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: my-rebalance
  labels:
    strimzi.io/cluster: my-cluster
# no goals specified, using the default goals from the Cruise Control configuration
spec: {}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ShubhamRwt**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

This PR fixes #10091 . This PR makes sure that in case the CC pod is restarted in middle of a rebalance, then we generate a new optimization proposal and then this newly generated proposal can be reviewed by the user.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [x] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 1]
```diff
@@ -957,53 +957,57 @@ private Future<MapAndStatus<ConfigMap, KafkaRebalanceStatus>> onRebalancing(Reco
...
-                            // proposal was still being prepared (in progress). In that case the rebalance will start when
-                            // the proposal is complete but the optimisation proposal summary will be missing.
-                            if (kafkaRebalance.getStatus().getOptimizationResult() == null ||
-                                    kafkaRebalance.getStatus().getOptimizationResult().isEmpty()) {
-                                LOGGER.infoCr(reconciliation, "Rebalance ({}) optimization proposal is now ready and has been added to the status", sessionId);
-                                p.complete(buildRebalanceStatus(
-                                        kafkaRebalance, sessionId, KafkaRebalanceState.Rebalancing, taskStatusJson, conditions));
-                            } else {
+                    if (cruiseControlResponse.getJson().isEmpty()) {
+                        LOGGER.infoCr(reconciliation, "Cruise Control restarted, going to generate a new proposal");
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:961]: Maybe you should make it a bit more generic? Or are you really sure the restart is the only thing that can cause it? Also, should this be a warning?

File: systemtest/src/test/java/io/strimzi/systemtest/cruisecontrol/CruiseControlST.java [hunk 2]
```diff
@@ -238,6 +238,49 @@ void testCruiseControlChangesFromRebalancingtoProposalReadyWhenSpecUpdated() {
         KafkaRebalanceUtils.waitForKafkaRebalanceCustomResourceState(clusterOperator.getDeploymentNamespace(), testStorage.getClusterName(), KafkaRebalanceState.ProposalReady);
     }
 
+    @IsolatedTest
+    void testCruiseControlChangesToProposalReadyWhenRestartedWhileRebalancing() {
```
Comment (scholzj) [inline systemtest/src/test/java/io/strimzi/systemtest/cruisecontrol/CruiseControlST.java:242]: I don't think this will work well because you rely on lucky timing too much. You should IMHO need to test it with some unit tests using mocks.

Comment (fvaleri) [reply systemtest/src/test/java/io/strimzi/systemtest/cruisecontrol/CruiseControlST.java:242]: It works fine for me. We can also add a unit test using the `MockCruiseControl` class.

**Review by fvaleri — COMMENTED** [review]
Thanks @ShubhamRwt. Left few comments, but overall it LGTM.

File: systemtest/src/test/java/io/strimzi/systemtest/cruisecontrol/CruiseControlST.java (hunk 2 above)
Comment (ShubhamRwt) [reply systemtest/src/test/java/io/strimzi/systemtest/cruisecontrol/CruiseControlST.java:242]: Added the unit test

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java [hunk 3]
```diff
@@ -1451,6 +1451,60 @@ public void testCruiseControlDisabledToEnabledBehaviour(VertxTestContext context
...
+                .withObservedGeneration(1L)
+                .withConditions(new ConditionBuilder()
+                        .withType("ProposalReady")
+                        .withStatus("True")
+                        .build())
+                .endStatus()
+                .build();
+
+        Crds.kafkaRebalanceOperation(client).inNamespace(namespace).resource(kr).create();
+        Crds.kafkaRebalanceOperation(client).inNamespace(namespace).resource(kr).updateStatus();
```
Comment (fvaleri) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: Why do we need this?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java [hunk 4]
```diff
@@ -1451,6 +1451,60 @@ public void testCruiseControlDisabledToEnabledBehaviour(VertxTestContext context
                 }));
     }
 
+    @Test
+    public void testKrWhenCCUserTaskIsEmpty(VertxTestContext context) throws IOException, URISyntaxException {
```
Comment (fvaleri) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1455]: The test name is not great IMO. Should we rename to `shouldGenerateNewProposalWhenUserTasksResponseHasNoTasks`, or something similar?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControl.java [hunk 5]
```diff
@@ -514,6 +514,27 @@ public void setupCCUserTasksCompletedWithError() throws IOException, URISyntaxEx
                                 .withDelay(TimeUnit.SECONDS, 0));
     }
 
+    public void setupUserTasktoEmpty() throws IOException, URISyntaxException {
```
Comment (fvaleri) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControl.java:517]: Who is throwing these exceptions? I guess we don't need them.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 6]
```diff
@@ -958,7 +958,7 @@ private Future<MapAndStatus<ConfigMap, KafkaRebalanceStatus>> onRebalancing(Reco
             apiClient.getUserTaskStatus(host, cruiseControlPort, sessionId)
                 .onSuccess(cruiseControlResponse -> {
                     if (cruiseControlResponse.getJson().isEmpty()) {
-                        LOGGER.infoCr(reconciliation, "Cruise Control restarted, going to generate a new proposal");
+                        LOGGER.warnCr(reconciliation, "Json data for response is empty since user task was not found, going to generate a new proposal");
```
Comment (fvaleri) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:961]: I would simply log:

```sh
LOGGER.warnCr(reconciliation, "User task {} not found, going to generate a new proposal", sessionId);
```

Also, so we want to add a comment on why this could happen?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java (hunk 3 above)
Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: It is there so we can directly move the Rebalance resource to `ProposalReady` state.

Comment (fvaleri) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: But you are already creating the resource with `ProposalReady` state.

Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: Yes but to reflect that state we require the above two things if I recall correctly

Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: Not when using a proper Kubernetes API Server. I think Shubham has this right.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java (hunk 4 above)
Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1455]: Yeah, I think that would be a better name

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java (hunk 3 above)
Comment (fvaleri) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: I asked because I wasn't sure and it seems to work without it.

Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: So understanding it in a bit more depth I see that the logs change in both the cases. If you remove 
`  Crds.kafkaRebalanceOperation(client).inNamespace(namespace).resource(kr).updateStatus();`Looking into it more, I guess the proposal never moved to `PendingProposal` state and directly moved to Proposal ready?

Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: I guess there is a difference, If you remove         `Crds.kafkaRebalanceOperation(client).inNamespace(namespace).resource(kr).updateStatus();` , the logs says 
```
2024-06-24 21:45:15 INFO  AbstractOperator:264 - Reconciliation #1(test-trigger) KafkaRebalance(testkrwhenccusertaskisempty/my-rebalance): KafkaRebalance my-rebalance will be checked for creation or modification
2024-06-24 21:45:15 INFO  KafkaRebalanceAssemblyOperator:370 - Reconciliation #1(test-trigger) KafkaRebalance(testkrwhenccusertaskisempty/my-rebalance): Rebalance action is performed and KafkaRebalance resource is currently in [New] state
2024-06-24 21:45:15 INFO  KafkaRebalanceAssemblyOperator:1170 - Reconciliation #1(test-trigger) KafkaRebalance(testkrwhenccusertaskisempty/my-rebalance): Requesting Cruise Control rebalance [dryrun=true]
2024-06-24 21:45:16 INFO  CrdOperator:123 - Reconciliation #1(test-trigger) KafkaRebalance(testkrwhenccusertaskisempty/my-rebalance): Status of KafkaRebalance my-rebalance in namespace testkrwhenccusertaskisempty has been updated
2024-06-24 21:45:16 INFO  AbstractOperator:536 - Reconciliation #1(test-trigger) KafkaRebalance(testkrwhenccusertaskisempty/my-rebalance): reconciled
2024-06-24 21:45:16 INFO  AbstractOperator:264 - Reconciliation #2(test-trigger) KafkaRebalance(testkrwhenccusertaskisempty/my-rebalance): KafkaRebalance my-rebalance will be checked for creation or modification
2024-06-24 21:45:16 INFO  KafkaRebalanceAssemblyOperator:370 - Reconciliation #2(test-trigger) KafkaRebalance(testkrwhenccusertaskisempty/my-rebalance): Rebalance action is performed and KafkaRebalance resource is currently in [ProposalReady] state
```
But if you don't remove that part the logs are different
```
2024-06-24 21:46:32 INFO  AbstractOperator:264 - Reconciliation #1(test-trigger) KafkaRebalance(testkrwhenccusertaskisempty/my-rebalance): KafkaRebalance my-rebalance will be checked for creation or modification
2024-06-24 21:46:32 INFO  KafkaRebalanceAssemblyOperator:370 - Reconciliation #1(test-trigger) KafkaRebalance(testkrwhenccusertaskisempty/my-rebalance): Rebalance action is performed and KafkaRebalance resource is currently in [ProposalReady] state
2024-06-24 21:46:32 INFO  AbstractOperator:536 - Reconciliation #1(test-trigger) KafkaRebalance(testkrwhenccusertaskisempty/my-rebalance): reconciled
2024-06-24 21:46:32 INFO  AbstractOperator:264 - Reconciliation #2(test-trigger) KafkaRebalance(testkrwhenccusertaskisempty/my-rebalance): KafkaRebalance my-rebalance will be checked for creation or modification
```

Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: So basically in the first case the rebalance resource never moved to `PendingProposal` and directly to `ProposalReady` from `New` state?

Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: @fvaleri Just to clarify ... In Kubernetes, a regular POST/PUT/PATH request does not change the `.status` section. You have a special request for it. So if you do only `create()`, you will have only the `.metadata` and `.spec` set. You need to do also the `updateStatus()` to set the `.status` part. So from Kube perspective, if you want to prepare the custom resource with some specific status, you have to do both calls. Whether you really need the status and what role it plays is up to the test of course.  So in general, these two calls might make sense, but I personally didn't study the test to see how it uses it.

(Also, one needs to be careful about race conditions here. It is easy to do this in preparation. But if the test is already running, it creates two separate events.)

Comment (fvaleri) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: @scholzj that's also my understanding. The point I was trying to raise is that I don't think we need to set the status when creating the KR as we then call reconcile. Translating this into code, I think we should simply do:

```sh
KafkaRebalance kr = createKafkaRebalance(namespace, CLUSTER_NAME, RESOURCE_NAME, EMPTY_KAFKA_REBALANCE_SPEC, false);
Crds.kafkaRebalanceOperation(client).inNamespace(namespace).resource(kr).create();
```

Wdyt?

Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: In general, you might have two reasons to do something like this:
* Improve the speed of the tests by mocking the initial state where the test starts (for example here it starts with a ready proposal, so I guess it avoids at least two reconciliations to get there?).
* Reduce the amount of required mocking. By starting already in some particular state, you do not need to mock how to get the proposal.

So I think it is valid in general. But if the test passes with it commented out, it seems a bit strange to me and suggests some flawed logic.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java [hunk 7]
```diff
@@ -1451,6 +1451,60 @@ public void testCruiseControlDisabledToEnabledBehaviour(VertxTestContext context
...
+        Crds.kafkaRebalanceOperation(client).inNamespace(namespace).resource(kr).updateStatus();
+
+        crdCreateKafka();
+        crdCreateCruiseControlSecrets();
+
+        Checkpoint checkpoint = context.checkpoint();
+        krao.reconcile(new Reconciliation("test-trigger", KafkaRebalance.RESOURCE_KIND, namespace, RESOURCE_NAME))
+                .onComplete(context.succeeding(v -> context.verify(() -> {
+                    // the resource moved to ProposalReady
+                    assertState(context, client, namespace, RESOURCE_NAME, KafkaRebalanceState.ProposalReady);
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1479]: As discussed in the other thread - you are already creating it as ProposalReady. So it should not move to ProposalReady here. so the comment is wrong ... and it is not clear what the first reconciliation really does.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java [hunk 8]
```diff
@@ -1451,6 +1451,60 @@ public void testCruiseControlDisabledToEnabledBehaviour(VertxTestContext context
...
+                })))
+                .compose(v -> {
+                    if (!Annotations.booleanAnnotation(kr, Annotations.ANNO_STRIMZI_IO_REBALANCE_AUTOAPPROVAL, false)) {
+                        annotate(client, namespace, kr.getMetadata().getName(), KafkaRebalanceAnnotation.approve);
+                    }
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1484]: When would this be true / false? I do not see any parametrization (but maybe I missed it?).

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java [hunk 9]
```diff
@@ -1451,6 +1451,60 @@ public void testCruiseControlDisabledToEnabledBehaviour(VertxTestContext context
...
+                        cruiseControlServer.setupUserTasktoEmpty();
+                    } catch (IOException | URISyntaxException e) {
+                        throw new RuntimeException(e);
+                    }
+
+                    return krao.reconcile(new Reconciliation("test-trigger", KafkaRebalance.RESOURCE_KIND, namespace, kr.getMetadata().getName()));
+                })
+                .onComplete(context.succeeding(v -> {
+                    // the resource transitioned from 'Rebalancing' to 'ProposalReady'
+                    assertState(context, client, namespace, RESOURCE_NAME, KafkaRebalanceState.ProposalReady);
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1503]: Shouldn't this first move to the stage of waiting for the proposal?

File: systemtest/src/test/java/io/strimzi/systemtest/cruisecontrol/CruiseControlST.java (hunk 2 above)
Comment (scholzj) [reply systemtest/src/test/java/io/strimzi/systemtest/cruisecontrol/CruiseControlST.java:242]: It is great that you added the unit test. But my point was that you should remove it because this will not be reliable test.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java [hunk 10]
```diff
@@ -326,46 +327,52 @@ public Future<CruiseControlResponse> getUserTaskStatus(String host, int port, St
                                 String userTaskID = response.result().getHeader(USER_TASK_ID_HEADER);
                                 response.result().bodyHandler(buffer -> {
                                     JsonObject json = buffer.toJsonObject();
-                                    JsonObject jsonUserTask = json.getJsonArray("userTasks").getJsonObject(0);
-                                    // This should not be an error with a 200 status but we play it safe
-                                    if (jsonUserTask.containsKey(CC_REST_API_ERROR_KEY)) {
-                                        result.fail(new CruiseControlRestException(
-                                                "Error for request: " + host + ":" + port + path + ". Server returned: " +
-                                                        json.getString(CC_REST_API_ERROR_KEY)));
-                                    }
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:335]: What if this is some different error? Do we really want to loop on every single error?

Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:335]: What if this is some different error? Do we really want to loop on every single error?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 11]
```diff
@@ -957,53 +957,57 @@ private Future<MapAndStatus<ConfigMap, KafkaRebalanceStatus>> onRebalancing(Reco
...
-                            // The proposal field can be empty if a rebalance(dryrun=false) was called and the optimisation
-                            // proposal was still being prepared (in progress). In that case the rebalance will start when
-                            // the proposal is complete but the optimisation proposal summary will be missing.
-                            if (kafkaRebalance.getStatus().getOptimizationResult() == null ||
-                                    kafkaRebalance.getStatus().getOptimizationResult().isEmpty()) {
-                                LOGGER.infoCr(reconciliation, "Rebalance ({}) optimization proposal is now ready and has been added to the status", sessionId);
-                                p.complete(buildRebalanceStatus(
-                                        kafkaRebalance, sessionId, KafkaRebalanceState.Rebalancing, taskStatusJson, conditions));
-                            } else {
+                    if (cruiseControlResponse.getJson().isEmpty()) {
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:960]: Would it be cleaner to have this as another state in the switch case below ... e.g. `MISSING`?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java (hunk 10 above)
Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:335]: It was something present there since the start, This condition is just to be sure nothing went wrong even after we got a 200 status response. I am not sure what that edge case could be but I guess its good to have something to tackle it

Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:335]: Also as you said `what if there is some different error`,  I think thats a good point but if there is CC related error and status code is 200 then it should be present in the `json` with the `CC_REST_API_ERROR_KEY`.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java (hunk 7 above)
Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1479]: The first reconciliation doesn't do much, it is just a normal reconcile after which Iam checking if the `proposal` was in the correct state i.e. `ProposalReady` but yah I can remove this extra step.

Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1479]: Normally, in a unit test, you would try to avoid doing things that _doesn't do much_. It either does something that matters to the test and that is why it is there ... or it can be removed. 😉

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 11 above)
Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:960]: I tried to look into this......So the other states are based possibles option for `Status` in the JSON returned by the CC. We return back the  task status after looking up in the `status` of the `json` if we are getting those states. `Missing` is not a possible option w.r.t to possible option for `Status` so that would mean it will be an extra State we are adding and it wouldn't align with Cruise Control Api

Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:960]: I think I can still make it work but I don't if it would be good to add a state which can never  be a possibility

Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:960]: @ppatierno @fvaleri wdyt?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java (hunk 3 above)
Comment (fvaleri) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: I see the proposal moving directly from "New" - "ProposalReady" at the first reconciliation called by the test. I guess this is the effect of how the mock response has been setup, so it should be fine. That's how you improve the speed of the test in this case.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java (hunk 8 above)
Comment (fvaleri) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1484]: Yeah, you don't need the if, just annotate. Alternatively, you can edit the KR at creation time and add the auto-approval annotation there, which I think it's better.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 11 above)
Comment (fvaleri) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:960]: > Would it be cleaner to have this as another state in the switch case below ... e.g. MISSING?

I don't think so, as the switch states directly maps to the `user_tasks` response from CC, and there is no `MISSING` state there. Adding that would be really confusing.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java (hunk 3 above)
Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1470]: I have configured the Mock response to return the `PendingProposal` first instead of directly moving to `ProposalReady`

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java (hunk 9 above)
Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java]: Done

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java (hunk 7 above)
Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java]: Removed the unnecessary steps

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 6 above)
Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java]: Done. I have added the commment which you are using for Topic operator

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControl.java (hunk 5 above)
Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/MockCruiseControl.java]: Removed

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java [hunk 12]
```diff
@@ -1451,6 +1451,46 @@ public void testCruiseControlDisabledToEnabledBehaviour(VertxTestContext context
...
+        Checkpoint checkpoint = context.checkpoint();
+        krao.reconcile(new Reconciliation("test-trigger", KafkaRebalance.RESOURCE_KIND, namespace, RESOURCE_NAME))
+                .onComplete(context.succeeding(v -> {
+                    // the resource moved to `Rebalancing` since auto-approval annotation is set on the resource
+                    assertState(context, client, namespace, RESOURCE_NAME, KafkaRebalanceState.Rebalancing);
+                }))
+                .compose(v -> {
+                    // Sets the user task to empty
+                    cruiseControlServer.setupUserTasktoEmpty();
+
```
Comment (fvaleri) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1484]: Please remove empty line.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java [hunk 13]
```diff
@@ -1451,6 +1451,46 @@ public void testCruiseControlDisabledToEnabledBehaviour(VertxTestContext context
...
+        crdCreateCruiseControlSecrets();
+
+        Checkpoint checkpoint = context.checkpoint();
+        krao.reconcile(new Reconciliation("test-trigger", KafkaRebalance.RESOURCE_KIND, namespace, RESOURCE_NAME))
+                .onComplete(context.succeeding(v -> {
+                    // the resource moved to `Rebalancing` since auto-approval annotation is set on the resource
+                    assertState(context, client, namespace, RESOURCE_NAME, KafkaRebalanceState.Rebalancing);
+                }))
+                .compose(v -> {
+                    // Sets the user task to empty
```
Comment (fvaleri) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1482]:
```suggestion
                    // Sets a user_tasks response with an empty task list simulating CC restart
```

**Review by fvaleri — APPROVED** [review]
LGTM. Left some nits.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java (hunk 12 above)
Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1484]: I intentionally added them to have some differentiation but I will remove it.

**Review by scholzj — APPROVED** [review]
LGTM. Should be reviewed by @ppatierno as an SME.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 14]
```diff
@@ -916,53 +916,59 @@ private Future<MapAndStatus<ConfigMap, KafkaRebalanceStatus>> onRebalancing(Reco
...
+                        // Cruise Control restarted: reset the state because the tasks queue is not persisted
+                        // this may also happen when the tasks' retention time expires, or the cache becomes full
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:921]: I would not strictly say the CC was restarted. Let's be generic about receiving an empty task queue from CC, or anyway the task we are asking for doesn't exist anymore. Of course CC restarted could be a reason but maybe not the only one.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java [hunk 15]
```diff
@@ -338,47 +339,53 @@ public Future<CruiseControlResponse> getUserTaskStatus(Reconciliation reconcilia
...
-                                                    originalResponse.getJsonObject(CruiseControlRebalanceKeys.LOAD_AFTER_OPTIMIZATION.getKey()));
-                                            break;
-                                        case COMPLETED_WITH_ERROR:
-                                            // Completed with error tasks will have "CompletedWithError" as their original response, which is not Json.
-                                            statusJson.put(CruiseControlRebalanceKeys.SUMMARY.getKey(), jsonUserTask.getString(CruiseControlRebalanceKeys.ORIGINAL_RESPONSE.getKey()));
-                                            break;
-                                        default:
-                                            throw new IllegalStateException("Unexpected user task status: " + taskStatus);
+                                    if (userTasks.isEmpty()) {
+                                        // Cruise Control restarted
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:345]: Ditto as before, it could be not just about CC restarted.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java [hunk 16]
```diff
@@ -338,47 +339,53 @@ public Future<CruiseControlResponse> getUserTaskStatus(Reconciliation reconcilia
...
-                                                    CruiseControlRebalanceKeys.LOAD_AFTER_OPTIMIZATION.getKey(),
-                                                    originalResponse.getJsonObject(CruiseControlRebalanceKeys.LOAD_AFTER_OPTIMIZATION.getKey()));
-                                            break;
-                                        case COMPLETED_WITH_ERROR:
-                                            // Completed with error tasks will have "CompletedWithError" as their original response, which is not Json.
-                                            statusJson.put(CruiseControlRebalanceKeys.SUMMARY.getKey(), jsonUserTask.getString(CruiseControlRebalanceKeys.ORIGINAL_RESPONSE.getKey()));
-                                            break;
-                                        default:
-                                            throw new IllegalStateException("Unexpected user task status: " + taskStatus);
+                                    if (userTasks.isEmpty()) {
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:344]: Not sure we are tackling this right. I mean, the CC tasks could have multiple tasks but the one we are looking for, for any reasons I can't imagine right now, could have been removed by CC from the tasks list while others are still there.
If this happens, we are assuming the list not empty and then getting just the first task in the list which could even not be the one we are looking for.
Thinking more, it could have been wrong even before.
What I am saying is that we should look for the requested `userTaskId` in this list and if not found returning the empty status.
@kyguy @fvaleri wdyt?

**Comment by ppatierno** [comment]
@ShubhamRwt I had a pass and left comments, but also `testKafkaCCAndRebalanceWithMultipleCOs` seems to fail. Could you also "resolve conversation" for the feedback you addressed please? (to shrink the long page here, thanks!).

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 14 above)
Comment (fvaleri) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:921]: CC restart will be the most common cause, but I think the second line clarifies that it's not the only possible cause for this.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java (hunk 15 above)
Comment (fvaleri) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:345]: Here we should say "Cruise Control restarted, or the task response expired, or it was deleted because the internal cache was full".

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java (hunk 16 above)
Comment (fvaleri) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:344]: I think this is correct, because the  response is for a single `userTaskId`. If it is empty, then Cruise Control restarted, or the task response expired, or it was deleted because the internal cache was full.

This is indeed a minor issue with the Topic Operator, that has the ability to do batch requests to the `user_tasks` endpoint. I say minor, because it will simply results in a very little overhead caused by duplicates requests that would be no-ops (RF was already changed). Anyway, I'm taking note and will fix it soon.

**Comment by scholzj** [comment]
`testKafkaCCAndRebalanceWithMultipleCOs` is IIRC flaky, so it _might_ be unrelated.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java (hunk 16 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:344]: > I think this is correct, because the response is for a single userTaskId.

Genuine question. Are you sure about that? Should we look at CC code as well? I am wondering why if it's the response to a single task, it contains a list of `userTasks` instead of just the `Status` for that task or an empty JSON. I am worried that CC could always return the entire list.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 14 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:921]: so "Cruise Control restarted" should be used as a use case, not as a strong statement

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java (hunk 15 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:345]: And it should be used even for the other comment I think.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 14 above)
Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:921]: So something  like:
```
This may happen if:
1. Cruise Control restarted so resetting the state because the tasks queue is not persisted
2. Task's retention time expired, or the cache has become full
```

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java (hunk 15 above)
Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:345]: Same as above ? 
```
This may happen if:
1. Cruise Control restarted so resetting the state because the tasks queue is not persisted
2. Task's retention time expired, or the cache has become full
```

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java (hunk 16 above)
Comment (fvaleri) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:344]: I'm quite sure. I tested that for the RF change feature. The response contains a task list because the endpoint supports batch requests, that we don't leverage in the Rebalance operator.

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:344]: See here https://github.com/linkedin/cruise-control/blob/main/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/handler/sync/UserTasksRequest.java#L47 and https://github.com/linkedin/cruise-control/blob/main/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/UserTaskManager.java#L510 

isn't it getting ALL user tasks?

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:344]: Ok wait wait, the endpoint by default returns all user tasks but luckily in our code we are using this ...

```java
if (userTaskId != null) {
            pathBuilder.withParameter(CruiseControlParameters.USER_TASK_IDS, userTaskId);
        }
```

we are setting the `user_task_ids` parameter on the query string. But without it, it would return all tasks as I said.

See also https://github.com/linkedin/cruise-control/wiki/REST-APIs#query-the-user-request-result

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 14 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:921]: fine with me

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java (hunk 15 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:345]: Yep

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 14 above)
Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:921]: Great, Thanks Paolo

**Comment by ppatierno** [comment]
@ShubhamRwt have you tried if the issue happens when we are in `PendingProposal` and not `Rebalancing`? Because I see your code fixes the scenario in `onRebalancing` only.

**Comment by ShubhamRwt** [comment]
> @ShubhamRwt have you tried if the issue happens when we are in `PendingProposal` and not `Rebalancing`? Because I see your code fixes the scenario in `onRebalancing` only.

Reading through the code we have @ppatierno I reached to the conclusion that this issue can happen in case of `Rebalancing` state only.  The error logs states that the error happens when the `usertasks` array is empty and going through the our code we are using the `getUserTaskStatus` method or you can say the `userTask` related stuff only in the `Rebalancing` state. I can try the use case you suggested and see if we get some completely different issue with it

**Comment by ppatierno** [comment]
No need to investigate, I was curious if you did such a test, because I noticed a different behaviour we apply between asking for a proposal/checking the status and rebalancing/checking the status.
When we ask for a proposal, we hit the rebalance endpoint with a POST but we do the same even for checking the status.
When we ask for the rebalancing, we hit the rebalance endpoint with a POST first and then the user tasks endpoint with a GET for checking the status.
This reflects what you say but at the same time rings an alarm to me ... why do we have this different behaviour? Why we don't use the same POST and GET (for the status) for a proposal? Maybe we should investigate more on this, unless there is an obvious reason (I don't remember). @kyguy any thoughts?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java (hunk 16 above)
Comment (fvaleri) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:344]: Yep, that's correct.

**Comment by ShubhamRwt** [comment]
Waiting for the regression test to complete, I will push the new comments related changes w.r.t it.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java (hunk 16 above)
Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:344]: Do we need some change w.r.t to this?  Following the discussion it sounds we agree that its correct this way

Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java:344]: Yes that's correct

**Review by ppatierno — APPROVED** [review]

**Review by kyguy — APPROVED** [review]
Nice work @ShubhamRwt

**Comment by scholzj** [comment]
Thanks @ShubhamRwt

**Comment by kyguy** [comment]
> This reflects what you say but at the same time rings an alarm to me ... why do we have this different behaviour? Why we don't use the same POST and GET (for the status) for a proposal? In the end they are different for the dryrun flag. Maybe we should investigate more on this, unless there is an obvious reason (I don't remember). @kyguy any thoughts?

@ppatierno  I don't remember any specific reason why we would do this on purpose, I believe this was an oversight.
