### PR TITLE
[ST] Use Test-Frame's LogCollector in STs

### LINKED ISSUE #9927: [ST] System tests should collect init-container logs for failed tests
Some of the System Tests using things such as node ports or rack awareness rely on the use of init-containers. But when the system test fails, the logs from the init containers are not collected. This would be a useful enhancement to collect them if the init container was used.

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Enhancement

### Description

This PR implements LogCollector from Test-Frame (https://github.com/skodjob/test-frame/tree/main/test-frame-log-collector). Until now, we had our own implementation, which worked for most of the time, but it missed a few things (for example functionality to collect logs from init-containers) and every new addition to the code broke something already working. Also, it wasn't tested in any way, only during regular test runs when some of the tests failed.

The Test-Frame's LogCollector is implemented newly, with all of the missing features and tests, which gives more trust into the tool.

Closes #9927 

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by im-konge** [comment]
Because I left two wrong asserts in the tests 🤦 you can check how the collection of the logs look like https://dev.azure.com/cncf/strimzi/_build/results?buildId=181032&view=artifacts&type=publishedArtifacts

File: systemtest/src/main/java/io/strimzi/systemtest/logs/TestLogCollector.java [hunk 1]
```diff
@@ -0,0 +1,267 @@
...
+     * From there, if there are no sub-dirs created - for each of the test-case run/re-run - the method returns the
+     * full path containing the specified path and index (1).
+     * Otherwise, it lists all the directories, filtering all the folders that are indexes, takes the last one, and returns
+     * the full path containing specified path and index increased by one.
+     *
+     * @param rootPathToLogsForTestCase     complete path for test-class/test-class and test-case logs
+     *
+     * @return  full path to logs directory built from specified root path and index
+     */
+    private String checkPathAndReturnFullRootPathWithIndexFolder(String rootPathToLogsForTestCase) {
```
Comment (kornys) [inline systemtest/src/main/java/io/strimzi/systemtest/logs/TestLogCollector.java:181]: instead of string and string join with "/" path delimiter, use `Paths` and methods resolve etc please

File: systemtest/src/main/java/io/strimzi/systemtest/logs/TestLogCollector.java [hunk 2]
```diff
@@ -0,0 +1,267 @@
...
+     * @param testClass     name of the test-class
+     * @param testCase      name of the test-case
+     *
+     * @return full path to the logs for test-class and test-case, together with index
+     */
+    private String buildFullPathToLogs(String testClass, String testCase) {
+        String rootPathToLogsForTestCase = String.join("/", Environment.TEST_LOG_DIR, CURRENT_DATE, testClass);
+
+        if (testCase != null) {
+            rootPathToLogsForTestCase = String.join("/", rootPathToLogsForTestCase, testCase);
```
Comment (kornys) [inline systemtest/src/main/java/io/strimzi/systemtest/logs/TestLogCollector.java:222]: Use Paths resolve

**Review by Frawless — APPROVED** [review]

File: systemtest/src/main/java/io/strimzi/systemtest/logs/TestLogCollector.java (hunk 1 above)
Comment (im-konge) [reply systemtest/src/main/java/io/strimzi/systemtest/logs/TestLogCollector.java:181]: Good point, thanks.

**Review by see-quick — APPROVED** [review]
LGTM, thanks for working on this! Nice job 👍

**Review by kornys — APPROVED** [review]
