### PR TITLE
#4035: Patch Rancher Cattle annotations when reconciling services

### LINKED ISSUE #4035: [Bug] Operator continuously update resources in AKS
**Describe the bug**
In our case we noticed that when we trying to create internal LB in AKS managed by Rancher (this is important) using annotation:
```
externalBootstrapService:
  metadata:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
perPodService:
  metadata:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```
we see that time needed for creating LB is ~15 min.
The root cause is that Strimzi operator and Rancher (which adds custom annotations like `/metadata/annotations/field.cattle.io~1publicEndpoints`) simultaneously try to change the same services of LoadBalancer type. Rancher adds some labels and annotations to services and Strimzi operator removes that data. That process caused continuously updating Azure load balancer configuration. As a result, Azure load balancer stays in an "updating" state with a long processing queue.

**To Reproduce**
1. Create internal LB for external listener
2. Create AKS cluster managed by Rancher (https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/aks/)
3. Create Internal LB by adding annotations: creating takes more than 15 min

**Expected behavior**
LB creation takes less than 2 min.

**Environment (please complete the following information):**
 - Strimzi version: 0.18
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.18
 - Infrastructure: Azure AKS/Rancher

**YAML files and logs**

image

**Additional context**
Suggestion: add ability ignore changes for annotations/labels for resources watched by operator:
```
example:
ignore_changes = [
      metadata[0].annotations["cattle.io/*"],
      metadata[0].annotations["field.cattle.io~1publicEndpoints"]
    ]
```

### PR DESCRIPTION
**Pull request by mluiten**
### Type of change

- Bugfix

### Description

Should fix #4035, by whitelisting all "cattle.io" annotations, and patching them into the desired spec for Services of the type LoadBalancer or NodePort.

- Is it better to make the "cattle.io" seed configurable?

### Checklist

- [X] Write tests
- [X] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR, this looks good to me. Can you please fix the DCO sign-off? The instructions should under the _Details_ link next tot he DCO status in the PR status section. We cannot merge the PR without it.

File: operator-common/src/main/java/io/strimzi/operator/common/operator/resource/ServiceOperator.java [hunk 1]
```diff
@@ -11,13 +11,19 @@
...
 
+import java.util.Map;
+import java.util.function.Function;
+import java.util.stream.Collectors;
+
 /**
  * Operations for {@code Service}s.
  */
 public class ServiceOperator extends AbstractResourceOperator<KubernetesClient, Service, ServiceList, DoneableService, ServiceResource<Service, DoneableService>> {
+    private static final String CATTLE_ANNOTATION_SEED = "cattle.io";
```
Comment (ppatierno) [inline operator-common/src/main/java/io/strimzi/operator/common/operator/resource/ServiceOperator.java:26]: I think we should be more precise to have RANCHER in the const name because it's the only one having this annotation AFAIU, right?

File: operator-common/src/main/java/io/strimzi/operator/common/operator/resource/ServiceOperator.java [hunk 2]
```diff
@@ -70,6 +77,31 @@ public ServiceOperator(Vertx vertx, KubernetesClient client) {
...
+    /**
+     * Finds annotations managed by the Rancher cattle agents (if any), and merge them into the desired spec.
+     *
+     * This makes sure there is no infinite loop where Rancher tries to add annotations, while Rancher keeps
+     * removing them during reconciliation.
+     *
+     * @param current   Current Service
+     * @param desired   Desired Service
+     */
+    private void patchCattleAnnotations(Service current, Service desired) {
```
Comment (ppatierno) [inline operator-common/src/main/java/io/strimzi/operator/common/operator/resource/ServiceOperator.java:89]: instead of having a specific method for just this "cattle" annotation, why not having a more general one passing a list of annotations to patch which in this case will continue just one annotation for now?

Comment (mluiten) [reply operator-common/src/main/java/io/strimzi/operator/common/operator/resource/ServiceOperator.java:89]: Is there a preferred place (like configuration file / dependency) to store this "list of annotations", or would the `private static final` OK for this?

Comment (ppatierno) [reply operator-common/src/main/java/io/strimzi/operator/common/operator/resource/ServiceOperator.java:89]: We have this `Annotations` class https://github.com/strimzi/strimzi-kafka-operator/blob/master/operator-common/src/main/java/io/strimzi/operator/common/Annotations.java

Comment (mluiten) [reply operator-common/src/main/java/io/strimzi/operator/common/operator/resource/ServiceOperator.java]: I have refactored the code; can you check if this is better? :)

**Review by ppatierno — APPROVED** [review]

File: operator-common/src/main/java/io/strimzi/operator/common/operator/resource/ServiceOperator.java [hunk 3]
```diff
@@ -70,6 +78,31 @@ public ServiceOperator(Vertx vertx, KubernetesClient client) {
...
+     * removing them during reconciliation.
+     *
+     * @param current   Current Service
+     * @param desired   Desired Service
+     */
+    private void patchAnnotations(Service current, Service desired) {
+        Map<String, String> currentAnnotations = current.getMetadata().getAnnotations();
+        if (currentAnnotations != null) {
+            Map<String, String> matchedAnnotations = currentAnnotations.keySet().stream()
+                    .filter(annotation -> LOADBALANCER_ANNOTATION_WHITELIST.stream().anyMatch(whitelist -> whitelist.test(annotation)))
```
Comment (scholzj) [inline operator-common/src/main/java/io/strimzi/operator/common/operator/resource/ServiceOperator.java:94]: I wonder if we really need the matching here. If the `contains` or `startsWith` which was used originally wasn't better in terms of performance etc. @tombentley WDYT?

Comment (mluiten) [reply operator-common/src/main/java/io/strimzi/operator/common/operator/resource/ServiceOperator.java:94]: I replaced the regex'es with `startsWith` :-)

**Comment by scholzj** [comment]
@mluiten I pushed in a small fix for unused import and some indentation. Hopefully the build passes. It looks good otherwise, so once it does we can merge it.

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR.

**Comment by mluiten** [comment]
@scholzj yw. Do you do backporting of these fixes to older releases for kafka-strimzi? We're still running Kafka 2.4.x, so it would help us we can backport this to 0.19 as well :-)

**Comment by scholzj** [comment]
I do not think we have any plans to release a path version of 0.19 ... but I can help you built it your self if you want.

**Comment by mluiten** [comment]
Ok thanks! I'll check if we can do an upgrade to 0.20 soon, otherwise I'll let you know :) what's your expected ETA for 0.21?

**Comment by scholzj** [comment]
I plan to do 0.21.0 ASAP after Kafka 2.7.0 release.

**Comment by scholzj** [comment]
I tried to pick this fix for the 0.20.1. But it did not work because 0.20.x and earlier was based on Java 8 (whereas 0.21 is now on Java 11). So backporting it is slightly untrivial :-/. Waiting for the 0.21 sounds like the best way ... hopefully Kafka 2.7.0 is out soon and we can release it.
