### PR TITLE
Fix bugs for automatic refresh of KafkaRebalance

### LINKED ISSUE #10423: Fix update of status in `KafkaRebalanceAssemblyOperator` when refresh annotation is added
In the `KafkaRebalanceAccessOperator`, there is a code for adding the refresh annotation when the spec changed:

```java
        if (kafkaRebalance.getStatus() != null
                && kafkaRebalance.getStatus().getObservedGeneration() != kafkaRebalance.getMetadata().getGeneration()) {

            KafkaRebalanceBuilder patchedKafkaRebalance = new KafkaRebalanceBuilder(kafkaRebalance);

            patchedKafkaRebalance
                    .editMetadata()
                         .addToAnnotations(Map.of(ANNO_STRIMZI_IO_REBALANCE, KafkaRebalanceAnnotation.refresh.toString()))
                    .endMetadata()
                    .editStatus()
                         .withObservedGeneration(kafkaRebalance.getMetadata().getGeneration())
                    .endStatus();

            kafkaRebalanceOperator.patchAsync(reconciliation, patchedKafkaRebalance.build()).onComplete(
                    r -> LOGGER.debugCr(reconciliation, "The KafkaRebalance resource is updated with refresh annotation"));
        }
```

It updates the `.status` section of the resource. But it call only `patch` afterwards and does not patch the status. That makes the status change completely ignored and useless. That is either a bug if the status update is really needed (but it does not seem so as nobody complained that it is not updated) and we should also call `patchStatus` to update the status as well. Or we should remove the status change in the first place to not mislead anyone that it is being updated.

Also the indentation of the in the builder is wrong as it uses 5 characters instead of 4.

### PR DESCRIPTION
**Pull request by tinaselenge**
### Type of change

- Bugfix

### Description

- Automatic refreshing of the KafkaRebalance is plugged into the asynchronous flow of the Vert.x futures
- Move the logic so that it's done after checking Kafka cluster exists and is ready, and the resource belongs to the operator annotating it. 
- Remove unnecessary status update that gets ignored

Closes #10423 and #10416 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 1]
```diff
@@ -1043,21 +1026,46 @@ private Future<MapAndStatus<ConfigMap, KafkaRebalanceStatus>> onReady(Reconcilia
...
+                                            future.complete();
+                                        } else {
+                                        LOGGER.errorCr(reconciliation, "Failed to update the KafkaRebalance resource with refresh annotation");
+                                        future.fail(r.cause());
+                                        }
+                                    });
+                        } else {
+                            future.complete();
+                        }
+                    });
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1053]: I think that normally, we would do it something like this:

```suggestion
                    Future<Void> resourcePatchFuture;
                    if (kafkaRebalance.getStatus() != null
                            && kafkaRebalance.getStatus().getObservedGeneration() != kafkaRebalance.getMetadata().getGeneration()) {
                        KafkaRebalanceBuilder patchedKafkaRebalance = new KafkaRebalanceBuilder(kafkaRebalance)
                                    .editMetadata()
                                        .addToAnnotations(Map.of(ANNO_STRIMZI_IO_REBALANCE, KafkaRebalanceAnnotation.refresh.toString()))
                                    .endMetadata()
                                    .build()

                        resourcePatchFuture = kafkaRebalanceOperator.patchAsync(reconciliation, patchedKafkaRebalance);
                    } else {
                        resourcePatchFuture = Future.succeededFuture();
                    }
```

(I did not test it or wrote it in an IDE, so it might be misaligned or buggy ... but it should give you an idea :-D)

**Review by ShubhamRwt — APPROVED** [review]

**Review by kyguy — APPROVED** [review]
Looks good, thanks for the fix @tinaselenge!

**Review by scholzj — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks!
