### PR TITLE
Include CA chain in broker certificates

### LINKED ISSUE #12364: [Bug]: TLS handshake failures on internal listeners after upgrade to 0.49.x with externally managed CA – brokers present only leaf certificate, omitting full chain
### Bug Description

After upgrading the Strimzi operator from 0.47.0 to 0.49.1 with an externally managed cluster CA (`clusterCa.generateCertificateAuthority: false`), internal TLS listeners (e.g., plaintext over TLS on port 9093) stop working for clients.

- Brokers now present only the leaf (broker) certificate during TLS handshake.

- In 0.47.0, the broker keystore included the full certificate chain (leaf + intermediate(s) + root, concatenated from the provided cluster-ca Secret).

- Clients trusting only the root/intermediate CA (standard for custom/multi-level PKI) fail validation → SSLHandshakeException / PKIX path building failed / certificate_unknown.

- No changes to Secrets, CRs, certificates, SANs, or keys (PKCS#8 confirmed).

- Rollback to 0.47.0 restores full chain presentation and fixes connectivity immediately.

- Operator reconciles normally with no TLS-related errors in logs.

- External listeners (e.g., routes/NodePort) may be similarly affected if using the same custom CA setup.

- Strimzi does not validate/enforce SANs when using external CA, so mismatch is not the cause.

This appears to be a regression in how `ssl.keystore.certificate.chain` is populated from Secrets when `generateCertificateAuthority: false`.

### Steps to reproduce

1. Deploy a Kafka cluster on Strimzi 0.47.0 using an externally managed cluster CA: 

- Set spec.clusterCa.generateCertificateAuthority: false

- Provide custom CA certificate(s) and private key via Secrets (e.g., my-cluster-cluster-ca-cert containing ca.crt (full chain or root+intermediate) and ca.p12 / key in PKCS#8).

- Example minimal listener config in Kafka CR
````yaml
listeners:
  - name: plain
    port: 9092
    type: internal
    tls: false
  - name: tls
    port: 9093
    type: internal
    tls: true
    authentication:
      type: tls   # or scram-sha-512, etc.
````

- Deploy with typical 3-broker setup (replicas: 3, storage, etc.).

- Confirm internal clients connect successfully to my-cluster-kafka-bootstrap.my-ns.svc.cluster.local:9093 (using truststore with root/intermediate CA).

2. Upgrade the Strimzi operator deployment to 0.49.1 (or 0.49.0):

- Update the operator image / Helm chart / YAML to version 0.49.1.

- Do not change the Kafka CR, Secrets, certificates, or any TLS-related fields.

- Wait for operator reconciliation (brokers roll out new pods if needed).

3. Test connectivity from an internal client (e.g., pod with kcat, Java producer, or Kafka console producer):

- Use bootstrap: my-cluster-kafka-bootstrap.my-ns.svc.cluster.local:9093

- Security protocol: SSL (or SASL_SSL if auth enabled)

- Truststore: contains only root/intermediate CA (no leaf cert)

- Observe SSL handshake failure:
```
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: ... PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

4. (Optional verification) Exec into a broker pod and check presented chain

5. Roll back operator to 0.47.0 → connectivity restores immediately (full chain presented again).

### Expected behavior

Brokers present the full certificate chain (as in 0.47.0) when using externally provided certificates, so clients can build a trust path to their trusted root CA.

### Strimzi version

0.49.1

### Kubernetes version

1.27+

### Installation method

Helm charts

### Infrastructure

Bare-Metal, Azure

### Configuration files and logs

[strimzi-kafka.zip](https://github.com/user-attachments/files/24940451/strimzi-kafka.zip)

### Additional context

https://github.com/orgs/strimzi/discussions/12340

- Operator logs: normal reconciliation, no certificate errors.

- Broker logs: may show client connection attempts failing at TLS layer.

- Certificate setup: multi-level CA (e.g., Root → Intermediate → kafka-cluster-ca), common in enterprise PKI.

- Workarounds (from discussion):Rollback to 0.47.0

   - Use custom per-listener certificates with full chain embedded (spec.listeners[].brokerCertChainAndKey)

### PR DESCRIPTION
**Pull request by tinaselenge**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

In 0.49.0, we removed the shell script that generated PKCS12 certificates for brokers based on the volume mounted PEM certificates from Kubernetes secrets. Instead of this, KubernetesSecretConfigProvider is used to access the secrets directly to configure brokers. The shell script generated broker certificates with full CA chain, however, broker certificates stored in the Kubernetes secrets only contain leaf certificate. This has caused an issue for several users who relied on brokers providing full certificate chain. 

This PR includes CA certificate when broker certificates are generated and put into in secrets. 

Closes #12364. 
### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

File: operator-common/src/test/java/io/strimzi/operator/common/operator/MockCertManager.java [hunk 1]
```diff
@@ -174,7 +174,8 @@ public class MockCertManager implements CertManager {
             yPlKo9idFuhf2IhFwd1ucX3S+ZWRXxzQGeLjdpqf0vBUA9uqP5bjMZHwums1s/MB
             MyngL6wecFymyjqK3kduVNKvIo/juPq0NV8u70gdHltsaJArw4sfMw/4LnR++hRD
             EgqE8p9hEapdshRN9+YQchN44URq4xwcE/fDebru+IxPbkDOCMsj5x1WcUCg7w==
-            -----END CERTIFICATE-----""";
+            -----END CERTIFICATE-----
+            """;
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/common/operator/MockCertManager.java:178]: Is this the right thing to do? Esepcially with the user-suplied certificates, we do not have gurantees that there will be a new line at the end. So if this mocks one of the internal certificates, it is likely fine. If it mocks one of the user-suplied certs such as the CA, it is likely something the code needs to handle without the new line.

Comment (tinaselenge) [reply operator-common/src/test/java/io/strimzi/operator/common/operator/MockCertManager.java:178]: I changed this line as all the other mock certificates had a line in the end and these didn't. The failing tests were reconciling broker certificates generated by the operator. 
This mock also seemed to be used for user-supplied end-entity certs but in that case, I think this is not an issue, because it wouldn't go through the internal certificate generation (in Ca.java) where we concatenate the broker leaf and CA certificate? I don't think it's an issue for CA certificates as they get appended to end of the leaf certificates.

Comment (tinaselenge) [reply operator-common/src/test/java/io/strimzi/operator/common/operator/MockCertManager.java:178]: if we want to be sure, we could always add a new line inbetween leaf certificate and CA certificate.

Comment (scholzj) [reply operator-common/src/test/java/io/strimzi/operator/common/operator/MockCertManager.java:178]: As long as it works without the new-line at the end of the user-created certs, it is ok.

File: systemtest/src/main/java/io/strimzi/systemtest/utils/kubeUtils/objects/SecretUtils.java [hunk 2]
```diff
@@ -208,6 +210,18 @@ public static X509Certificate getCertificateFromSecret(Secret secret, String dat
...
     }
 
+    public static List<X509Certificate> getCertificatesFromSecret(Secret secret, String dataKey) {
+        String certs = secret.getData().get(dataKey);
+        byte[] decoded = Util.decodeBytesFromBase64(certs);
+        List<X509Certificate> certificates = new ArrayList<>();
+        try {
+            CertificateFactory.getInstance("X.509").generateCertificates(new ByteArrayInputStream(decoded)).forEach(c -> certificates.add((X509Certificate) c));
+        } catch (CertificateException e) {
+            e.printStackTrace();
```
Comment (scholzj) [inline systemtest/src/main/java/io/strimzi/systemtest/utils/kubeUtils/objects/SecretUtils.java:220]: I guess this is not what we want here? Assuming we want to continue, we should at least log a proper error?

File: operator-common/src/main/java/io/strimzi/operator/common/model/Ca.java [hunk 3]
```diff
@@ -450,20 +450,31 @@ public CertAndKey addKeyAndCertToKeyStore(String alias, byte[] key, byte[] cert)
...
 
             String keyStorePassword = passwordGenerator.generate();
             certManager.addKeyAndCertToKeyStore(keyFile, certFile, subject.commonName(), keyStoreFile, keyStorePassword);
 
+            byte[] certChain;
+            if (includeCaChain) {
+                byte[] leafCert = Files.readAllBytes(certFile.toPath());
+                certChain = new byte[leafCert.length + caCertBytes.length];
+                System.arraycopy(leafCert, 0, certChain, 0, leafCert.length);
+                System.arraycopy(caCertBytes, 0, certChain, leafCert.length, caCertBytes.length);
```
Comment (ppatierno) [inline operator-common/src/main/java/io/strimzi/operator/common/model/Ca.java:470]: shouldn't we use a new line to separate each certificate in the chain? I mean is that right having a PEM file with a long unique string which is a chain of certificates?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/model/ClusterCaRenewalTest.java [hunk 4]
```diff
@@ -214,9 +219,11 @@ public void noRenewal() throws IOException {
                 NODES,
                 SUBJECT_FN,
                 initialCerts,
-                true
+                true,
+                false
         );
 
+
```
Comment (ppatierno) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/model/ClusterCaRenewalTest.java]: is this new line necessary? I see others across this file.

File: systemtest/src/main/java/io/strimzi/systemtest/utils/kubeUtils/objects/SecretUtils.java (hunk 2 above)
Comment (katheris) [reply systemtest/src/main/java/io/strimzi/systemtest/utils/kubeUtils/objects/SecretUtils.java:220]: This matches what we have elsewhere in this class, I guess because this is a utils file for the system tests

File: operator-common/src/main/java/io/strimzi/operator/common/model/Ca.java (hunk 3 above)
Comment (katheris) [reply operator-common/src/main/java/io/strimzi/operator/common/model/Ca.java:470]: My understanding is that we create the leaf certificate with a new line at the end so we shouldn't need to add an extra new line

File: systemtest/src/main/java/io/strimzi/systemtest/utils/kubeUtils/objects/SecretUtils.java (hunk 2 above)
Comment (scholzj) [reply systemtest/src/main/java/io/strimzi/systemtest/utils/kubeUtils/objects/SecretUtils.java:220]: Damn, I missed that it is _just a test utils class_ ... I can live with it there.

_(That said, the class has a logger and does log in many places, so I'm not sure there is a reason to not use it and just print the stacktrace. But I would be happy to leave it for some other time if it is done in different places here as well.)_

File: operator-common/src/main/java/io/strimzi/operator/common/model/Ca.java (hunk 3 above)
Comment (tinaselenge) [reply operator-common/src/main/java/io/strimzi/operator/common/model/Ca.java:470]: Yes, as Kate said, the cert gets created with a new line at the end so I contemplated whether I should append a new line here or not, just in case (as mentioned in my comment here https://github.com/strimzi/strimzi-kafka-operator/pull/12390#discussion_r2769392054). I guess it couldn't hurt to append a line here.

Comment (ppatierno) [reply operator-common/src/main/java/io/strimzi/operator/common/model/Ca.java:470]: If there is already a new line in the cert at the end, there is no need to append another one here.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/model/ClusterCaRenewalTest.java (hunk 4 above)
Comment (tinaselenge) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/model/ClusterCaRenewalTest.java]: I removed the lines that got added accidentally.
