### PR TITLE
Release lock and cancel timer regardless of callable's outcome

### LINKED ISSUE #5927: Unhandled exception during AbstractOperator.handleResult
**Describe the bug**
When an exception is encountered/thrown by `AbstractOperator.handleResult` (e.g. during a call to `updateResourceState`), the `result` is never completed and the reconciliation task becomes a zombie.
https://github.com/strimzi/strimzi-kafka-operator/blob/f93334d520b32206e92077863a596e824eb54579/operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java#L269-L275

**To Reproduce**
1. Working on reproducer - we are seeing a similar stack trace to the one in #4703 

**Expected behavior**
Reconciliation should complete/fail/retry

**Environment (please complete the following information):**
 - Strimzi version: 0.23.0, code remains the same in `main`

**Additional context**
In our case, the root cause error related to a transient permissions issue that caused the operator to lose permission to GET `kafkas` CRs in the cluster. Secondary to the original error during reconciliation, the same exception occurred in `updateResourceState` and the `result` was not completed.

### PR DESCRIPTION
**Pull request by MikeEdgar**
Fixes #5927

Signed-off-by: Michael Edgar <medgar@redhat.com>

### Type of change
- Bugfix

### Description
- Safely execute `callable.call`, `handler.success` and `handler.fail` within `withLock`. Ensure release of `lock` and `timer` are completed regardless of any exceptions thrown.
- Ensure `result.handled` is called at end of reconcile. There seems to be a potential need for changes in `handleResult` to ensure metrics are captured in situations where an exception is thrown, but I have not made those changes here.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [x] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

File: operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java [hunk 1]
```diff
@@ -268,8 +268,11 @@ private String getLockName(String namespace, String name) {
 
         Promise<Void> result = Promise.promise();
         handler.onComplete(reconcileResult -> {
-            handleResult(reconciliation, reconcileResult, reconciliationTimerSample);
-            result.handle(reconcileResult);
+            try {
+                handleResult(reconciliation, reconcileResult, reconciliationTimerSample);
+            } finally {
+                result.handle(reconcileResult);
```
Comment (k-wall) [inline operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java:274]: did you think about whether it would it be more correct to fail the promise in the case of a throwable?

Comment (MikeEdgar) [reply operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java:274]: I considered that, but thought the `handleResult` processing is more bookkeeping than reconciliation. It also seems that the result of the promise is generally ignored outside of test code.

**Comment by scholzj** [comment]
Can you share the log from when the #5934 issue occurs?

**Comment by MikeEdgar** [comment]
Stack trace
```
2021-11-22 13:11:53 ERROR ContextImpl: - Unhandled exception
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/apis/kafka.strimzi.io/v1beta2/namespaces/kafka-namespace123/kafkas/***. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. kafkas.kafka.strimzi.io "***" is forbidden: User "system:serviceaccount:***:strimzi-cluster-operator" cannot get resource "kafkas" in API group "kafka.strimzi.io" in the namespace "kafka-namespace123".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:570)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:474)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:402)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:384)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:925)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:220)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:186)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:85)
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.get(AbstractResourceOperator.java:275)
	at io.strimzi.operator.common.AbstractOperator.updateResourceState(AbstractOperator.java:549)
	at io.strimzi.operator.common.AbstractOperator.handleResult(AbstractOperator.java:513)
	at io.strimzi.operator.common.AbstractOperator.lambda$reconcile$8(AbstractOperator.java:307)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:128)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:79)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:198)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.core.Promise.fail(Promise.java:89)
	at io.strimzi.operator.common.AbstractOperator.lambda$withLock$14(AbstractOperator.java:407)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:128)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:79)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:198)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.core.Promise.fail(Promise.java:89)
	at io.strimzi.operator.common.AbstractOperator.lambda$reconcile$3(AbstractOperator.java:279)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:128)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:79)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:198)
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:79)
	at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:92)
	at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:79)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:198)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:71)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

File: operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java [hunk 2]
```diff
@@ -300,6 +303,61 @@ protected Status createStatus() {
                 })));
     }
 
+
+    @Test
+    @SuppressWarnings({ "unchecked", "rawtypes" })
+    public void testFailingReconcileWithClientExceptionNotBlocked(VertxTestContext context)  {
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java:309]: I don't think this really tests metrics. Can we find some better class for this? Or does it depend on some shared code in this class?

File: operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java [hunk 3]
```diff
@@ -663,4 +721,24 @@ public void setStatus(Object status) {
             }
         };
     }
+
+    @SuppressWarnings({ "rawtypes", "unchecked" })
+    private AbstractWatchableStatusedResourceOperator resourceOperatorWithKubernetesClientException() {
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java:726]: Same as above ...

**Comment by MikeEdgar** [comment]
Moving this to draft status. I'll be updating the changes to also ensure the lock and timer are always released/cleared in `AbstractOperator.withLock`.

File: operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java [hunk 4]
```diff
@@ -390,6 +379,32 @@ protected void addWarningsToStatus(Status status, Set<Condition> unknownAndDepre
...
+
+    private <H> Handler<H> handleSafely(Reconciliation reconciliation, Handler<H> handler) {
+        return result -> {
+            try {
+                handler.handle(result);
+            } catch (Throwable ex) {
+                LOGGER.errorCr(reconciliation, "Reconciliation completion handler failed", ex);
+            }
+        };
+    }
```
Comment (scholzj) [inline operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java:399]: Maybe these deserve some javadoc to explain what exactly _safely_ means here.

File: operator-common/src/test/java/io/strimzi/operator/common/AbstractOperatorTest.java [hunk 5]
```diff
@@ -0,0 +1,278 @@
...
+import java.util.concurrent.Callable;
+import java.util.concurrent.TimeUnit;
+
+import static org.hamcrest.CoreMatchers.instanceOf;
+import static org.hamcrest.CoreMatchers.is;
+import static org.hamcrest.MatcherAssert.assertThat;
+
+@ExtendWith(VertxExtension.class)
+@Group("strimzi")
+@Version("v1")
```
Comment (scholzj) [inline operator-common/src/test/java/io/strimzi/operator/common/AbstractOperatorTest.java:43]: What is this expected to do? I don't think these have any meaning.

**Review by scholzj — COMMENTED** [review]
I left some nits. But LGTM overall. Thanks.

File: operator-common/src/test/java/io/strimzi/operator/common/AbstractOperatorTest.java (hunk 5 above)
Comment (MikeEdgar) [reply operator-common/src/test/java/io/strimzi/operator/common/AbstractOperatorTest.java]: Removed the annotations - these were copied from another test without any consideration.

File: operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java (hunk 4 above)
Comment (MikeEdgar) [reply operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java]: Added some docs to these methods. Let me know if it's OK. I also wouldn't mind to change the terminology if something else makes more sense, etc.

**Review by scholzj — APPROVED** [review]
Thanks for the PR!

File: operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java (hunk 4 above)
Comment (scholzj) [reply operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java]: I feel like the name is not perfect ... but TBH I do not have any better :-D. So as far as I'm concerned, the comment nicely explains what makes it safe so that we don't forget it, so it is good 👍

File: operator-common/src/test/java/io/strimzi/operator/common/AbstractOperatorTest.java [hunk 6]
```diff
@@ -0,0 +1,274 @@
...
+                assertThat(lock, instanceOf(Lock.class));
+                lock.release();
+                lockObtained.flag();
+            })));
+    }
+
+    @Test
+    /**
+     * Verifies that lock is released by call to `releaseLockAndTimer` via chain of futures ending
+     * with `eventually` after a failed execution via an unhandled exception in the `Callable`
```
Comment (PaulRMellor) [inline operator-common/src/test/java/io/strimzi/operator/common/AbstractOperatorTest.java:131]:
```suggestion
     * Verifies that the lock is released by a call to `releaseLockAndTimer`.
     * The call is made through a chain of futures ending with `eventually` after a failed execution via an unhandled exception in the `Callable`.
```

File: operator-common/src/test/java/io/strimzi/operator/common/AbstractOperatorTest.java [hunk 7]
```diff
@@ -0,0 +1,274 @@
...
+                lock.release();
+                lockObtained.flag();
+            })));
+    }
+
+    @Test
+    /**
+     * Verifies that lock is released by call to `releaseLockAndTimer` via chain of futures ending
+     * with `eventually` after a failed execution via an unhandled exception in the `Callable` followed
+     * by an unhandled exception occurring in the onFailure handler.
```
Comment (PaulRMellor) [inline operator-common/src/test/java/io/strimzi/operator/common/AbstractOperatorTest.java:169]:
```suggestion
     * Verifies that lock is released by call to `releaseLockAndTimer`. 
     * The call is made through a chain of futures ending with `eventually` after a failed execution via an unhandled exception in the `Callable`, 
     * followed by an unhandled exception occurring in the `onFailure` handler.
```

**Review by PaulRMellor — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Review by sknot-rh — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR.
