### PR TITLE
Replace the Apache Zookeeper project's client with ZkClient

### LINKED ISSUE #339: Session expired on Zookeeper node restart : not able to create topics
Let's consider the following scenario ...

A cluster with 1 Zookeeper node and 3 Kafka brokers (but they can be more or just one) is deployed using "persistent" storage. 
Update the cluster ConfigMap in order to have a rolling update started for the ZK node (i.e. healthcheck initial delay parameter). The running ZK pod is killed and a new one is created. As opposed to what happen with "ephemeral" storage (see #238), the Kafka brokers are able to reconnect to the new ZK pod and all works fine.
The problem is with the topic controller : trying to create a new topic ConfigMap in order to create a topic drives to the following exception ...

```
[2018-03-27 12:50:34,654] INFO  <ClientCnxn  :876> [46.166:2181)] Socket connection established to 172.30.46.166/172.30.46.166:2181, initiating session
[2018-03-27 12:50:34,661] WARN  <ClientCnxn  :1285> [46.166:2181)] Unable to reconnect to ZooKeeper service, session 0x162671046950004 has expired
[2018-03-27 12:50:34,661] INFO  <ClientCnxn  :1154> [46.166:2181)] Unable to reconnect to ZooKeeper service, session 0x162671046950004 has expired, closing socket connection
[2018-03-27 12:50:34,661] INFO  <ClientCnxn  :519> [-EventThread] EventThread shut down for session: 0x162671046950004
[2018-03-27 12:50:34,661] ERROR <opicsWatcher:67> [oop-thread-7] Error on zone /brokers/topics children
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for for path: /brokers/topics
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at io.strimzi.controller.topic.zk.ZkImpl.mapResult(ZkImpl.java:135)
	at io.strimzi.controller.topic.zk.ZkImpl.lambda$children$10(ZkImpl.java:343)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:601)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
[2018-03-27 12:51:35,154] INFO  <Session     :166> [oop-thread-0] Starting periodic reconciliation
[2018-03-27 12:52:03,481] INFO  <igMapWatcher:35> [0.1:8443/...] ConfigMap watch received event ADDED on map orders with labels {strimzi.io/cluster=my-cluster, strimzi.io/kind=topic}
[2018-03-27 12:52:04,051] ERROR <igMapWatcher:47> [oop-thread-8] Failure processing ConfigMap watch event ADDED on map orders with labels {strimzi.io/cluster=my-cluster, strimzi.io/kind=topic}: KeeperErrorCode = Session expired for for path: /strimzi/topics/orders
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for for path: /strimzi/topics/orders
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at io.strimzi.controller.topic.zk.ZkImpl.mapResult(ZkImpl.java:135)
	at io.strimzi.controller.topic.zk.ZkImpl.lambda$getData$5(ZkImpl.java:192)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:572)
	at org.apache.zookeeper.ClientCnxn$EventThread.queuePacket(ClientCnxn.java:485)
	at org.apache.zookeeper.ClientCnxn.finishPacket(ClientCnxn.java:655)
	at org.apache.zookeeper.ClientCnxn.conLossPacket(ClientCnxn.java:673)
	at org.apache.zookeeper.ClientCnxn.queuePacket(ClientCnxn.java:1449)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1269)
	at io.strimzi.controller.topic.zk.ZkImpl.getData(ZkImpl.java:220)
	at io.strimzi.controller.topic.ZkTopicStore.read(ZkTopicStore.java:60)
	at io.strimzi.controller.topic.Controller.reconcileOnCmChange(Controller.java:826)
	at io.strimzi.controller.topic.Controller.access$1100(Controller.java:24)
	at io.strimzi.controller.topic.Controller$6.handle(Controller.java:777)
	at io.strimzi.controller.topic.Controller$6.handle(Controller.java:774)
	at io.strimzi.controller.topic.InFlight.lambda$null$0(InFlight.java:110)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
[2018-03-27 12:52:04,072] WARN  <Controller  :90> [oop-thread-8] Failure processing ConfigMap watch event ADDED on map orders with labels {strimzi.io/cluster=my-cluster, strimzi.io/kind=topic}: KeeperErrorCode = Session expired for for path: /strimzi/topics/orders
```
The TC is able to reconnect to the new ZK pod but "something" related to the previous session (now expired) is still there. 
This issue needs further investigation and having TC to cope better with ZK restarts.

### LINKED ISSUE #1030: TO has a blocked thread [vert.x-eventloop-thread-0,5,main] after deploy
TO has WARNING about a blocked thread in log for 30 seconds after deploying.

```
[2018-10-25 12:51:25,338] INFO  <ZooKeeper   :442> [oop-thread-0] Initiating client connection, connectString=localhost:2181 sessionTimeout=20000 watcher=io.strimzi.operator.topic.zk.ZkImpl$$Lambda$12/266121811@453b4655
--
  | [2018-10-25 12:51:25,374] INFO  <ClientCnxn  :1029> [alhost:2181)] Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
  | [2018-10-25 12:51:25,375] INFO  <ClientCnxn  :1166> [alhost:2181)] Socket error occurred: localhost/127.0.0.1:2181: Connection refused
  | 2018-10-25T12:51:25.491+0000: [Full GC (Metadata GC Threshold) 2018-10-25T12:51:25.491+0000: [Tenured: 0K->12533K(339968K), 0.0430188 secs] 73608K->12533K(492992K), [Metaspace: 20741K->20741K(1069056K)], 0.0430849 secs] [Times: user=0.04 sys=0.00, real=0.05 secs]
  | [2018-10-25 12:51:26,477] INFO  <ClientCnxn  :1029> [alhost:2181)] Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
  | [2018-10-25 12:51:26,478] INFO  <ClientCnxn  :1166> [alhost:2181)] Socket error occurred: localhost/127.0.0.1:2181: Connection refused
  | [2018-10-25 12:51:27,578] INFO  <ClientCnxn  :1029> [alhost:2181)] Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
  | [2018-10-25 12:51:27,579] INFO  <ClientCnxn  :1166> [alhost:2181)] Socket error occurred: localhost/127.0.0.1:2181: Connection refused
  | Oct 25, 2018 12:51:27 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2882 ms, time limit is 2000
  | [2018-10-25 12:51:28,679] INFO  <ClientCnxn  :1029> [alhost:2181)] Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
  | [2018-10-25 12:51:28,680] INFO  <ClientCnxn  :1166> [alhost:2181)] Socket error occurred: localhost/127.0.0.1:2181: Connection refused
  | Oct 25, 2018 12:51:28 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3882 ms, time limit is 2000
  | [2018-10-25 12:51:29,782] INFO  <ClientCnxn  :1029> [alhost:2181)] Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
  | [2018-10-25 12:51:29,782] INFO  <ClientCnxn  :1166> [alhost:2181)] Socket error occurred: localhost/127.0.0.1:2181: Connection refused
  | Oct 25, 2018 12:51:29 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4883 ms, time limit is 2000
  | [2018-10-25 12:51:30,883] INFO  <ClientCnxn  :1029> [alhost:2181)] Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
  | [2018-10-25 12:51:30,883] INFO  <ClientCnxn  :1166> [alhost:2181)] Socket error occurred: localhost/127.0.0.1:2181: Connection refused
  | Oct 25, 2018 12:51:30 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5889 ms, time limit is 2000
  | io.vertx.core.VertxException: Thread blocked
  | at sun.misc.Unsafe.park(Native Method)
  | at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  | at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
  | at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
  | at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
  | at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
  | at io.strimzi.operator.topic.zk.ZkImpl.<init>(ZkImpl.java:101)
  | at io.strimzi.operator.topic.zk.Zk.create(Zk.java:22)
  | at io.strimzi.operator.topic.Session.start(Session.java:139)
  | at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
  | at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
  | at io.vertx.core.impl.DeploymentManager$$Lambda$9/391630194.handle(Unknown Source)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
  | at io.vertx.core.impl.ContextImpl$$Lambda$10/989447607.run(Unknown Source)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  |  
  | Oct 25, 2018 12:51:31 PM io.vertx.core.impl.BlockedThreadChecker
```

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Bugfix

### Description

Fixes #1030 and probably fixes #339 and #383

* Revise API for Zk to fit with ZkClient:
    * Asynchronous disconnect()
    * Remove methods which were only being called from test methods
* Rewrite ZkImpl accordingly for the new ZkClient
* Configurable connect timeout
* Fix tests

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

File: topic-operator/src/main/java/io/strimzi/operator/topic/zk/ZkImpl.java [hunk 1]
```diff
@@ -8,382 +8,229 @@
...
+            handler);
         return this;
     }
 
-    @Override
-    public Zk unwatchExists(String path) {
-        watches.remove(PREFIX_EXISTS + path);
-        return this;
+    private WorkerExecutor workerPool() {
+        return vertx.createSharedWorkerExecutor(getClass().getName(), 4);
```
Comment (ppatierno) [inline topic-operator/src/main/java/io/strimzi/operator/topic/zk/ZkImpl.java]: what is the rationale for 4?

File: topic-operator/src/main/java/io/strimzi/operator/topic/ZkTopicStore.java [hunk 2]
```diff
@@ -32,18 +33,25 @@
...
-                if (!(result.cause() instanceof KeeperException.NodeExistsException)) {
-                    LOGGER.error("Error creating {}", path, result.cause());
+                if (!(result.cause() instanceof ZkNodeExistsException)) {
+                    LOGGER.error("Error creating {}", "/strimzi", result.cause());
                     throw new RuntimeException(result.cause());
                 }
             }
+            zk.create(TOPICS_PATH, null, acl, CreateMode.PERSISTENT, result2 -> {
+                if (result.failed()) {
+                    if (!(result.cause() instanceof ZkNodeExistsException)) {
```
[the remark this answers is not in the document]
Comment (tombentley) [reply topic-operator/src/main/java/io/strimzi/operator/topic/ZkTopicStore.java]: Good spot, thanks!

File: topic-operator/src/main/java/io/strimzi/operator/topic/zk/ZkImpl.java (hunk 1 above)
Comment (tombentley) [reply topic-operator/src/main/java/io/strimzi/operator/topic/zk/ZkImpl.java]: What do you think is the right number of threads in the pool? I think 4 is probably _way_ more than needed. 1 would probably suffice, or maybe 2. Wdyt?

Comment (ppatierno) [reply topic-operator/src/main/java/io/strimzi/operator/topic/zk/ZkImpl.java]: It could depend on how many calls you need to start in parallel having free threads from the pool. For this reason, I was asking if there were a rationale behind it. If not, then 4 is a reasonable choice.

**Comment by tombentley** [comment]
@ppatierno thansk for the review. All fixed. Any further comments?
