### PR TITLE
KafkaRebalanceOperator now checks for cluster readiness before creating KafkaRebalance resources

### LINKED ISSUE #7643: KafkaRebalanceOperator does not check for cluster readiness before creating KafkaRebalance resources
**Describe the bug**

The KafkaRebalanceAssemblyOperator does not check for Kafka cluster readiness before attempting to create `KafkaRebalance` resources. It currently checks if the `Kafka` resource exists and has Cruise Control enabled but not for Kafka cluster readiness itself. This causes the operator  to throw misleading errors like this:

```
2022-11-16 17:47:10 ERROR AbstractOperator:264 - Reconciliation #75(timer) KafkaRebalance(myproject/my-rebalance): createOrUpdate failed
java.lang.RuntimeException: Secret myproject/my-cluster-cruise-control-certs does not exist
	at io.strimzi.operator.common.Util.missingSecretException(Util.java:217) ~[io.strimzi.operator-common-0.31.1.jar:0.31.1]
	at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.lambda$reconcileRebalance$31(KafkaRebalanceAssemblyOperator.java:1184) ~[io.strimzi.cluster-operator-0.31.1.jar:0.31.1]
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.CompositeFutureImpl.complete(CompositeFutureImpl.java:172) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.CompositeFutureImpl.lambda$join$3(CompositeFutureImpl.java:109) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

To make matters worse, the `KafkaRebalance` status section remains blank without any error message describing what is wrong.

**To Reproduce**
1. Create a `Kafka` custom resource with Cruise Control enabled and resource requests that are higher than what is currently available to the nodes i.e.:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  cruiseControl: {}
  kafka:
    resources:
      requests:
        cpu: 1000
    version: 3.2.3
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
2. Create a `KafkaRebalance` custom resource
3. Check the Strimzi cluster operator logs for error

**Expected behavior**
The KafkaRebalanceAssemblyOperator should check for Kafka cluster readiness before attempting to create a `KafkaRebalance` resource and log an error that it cannot create the `KafkaRebalance` resource when the Kafka cluster it is assigned to is not ready.

**Environment (please complete the following information):**
 - Strimzi version:  0.32.0
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.20,
 - Infrastructure: Minikube

### PR DESCRIPTION
**Pull request by ShubhamRwt**
Signed-off-by: ShubhamRwt <srawat@redhat.com>

### Type of change

- Bugfix

### Description

This PR fixes #7643. This PR adds a check for Cluster readiness. If the user applies a KafkaRebalance resource before the creation of Kafka Cluster, We get the desired warning and errors in the KafkaRebalance Status.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 1]
```diff
@@ -1160,6 +1160,13 @@ private Future<MapAndStatus<ConfigMap, KafkaRebalanceStatus>> onReady(Reconcilia
                                 new NoSuchResourceException("Kafka resource '" + clusterName
                                         + "' identified by label '" + Labels.STRIMZI_CLUSTER_LABEL
                                         + "' does not exist in namespace " + clusterNamespace + ".")).mapEmpty();
+                    } else if (kafka.getStatus().getConditions().stream().noneMatch(condition -> condition.getType().equals("Ready") && condition.getStatus().equals("True"))) {
+                        String errorString = "Kafka cluster is being deployed";
+                        LOGGER.warnCr(reconciliation, errorString);
+                        KafkaRebalanceStatus status = new KafkaRebalanceStatus();
+                        status.addCondition(StatusUtils.buildWarningCondition(CruiseControlIssues.kafkaClusterNotReady.getReason(), errorString));
+                        return updateStatus(reconciliation, kafkaRebalance, status,
+                                new RuntimeException("Secret " + clusterNamespace + "/my-cluster-cruise-control-certs does not exist")).mapEmpty();
```
Comment (kyguy) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1169]: Shouldn't the RuntimeException message here be related to the Kafka cluster not being ready instead of a secret missing?

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 2]
```diff
@@ -1392,7 +1399,13 @@ private enum CruiseControlIssues {
...
          * Cruise Control was not declared in the Kafka Resource
          */
-        cruiseControlDisabled("Cruise Control disabled");
+        cruiseControlDisabled("Cruise Control disabled"),
+
+        /**
+         * Kafka Cluster is not ready
+         *
+         */
+        kafkaClusterNotReady("Creating Kafka Cluster");
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1408]: If it is named` kafkaClusterNotReady` maybe it should say `Kafka cluster is not ready` and not `Creating Kafka Cluster`?

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java [hunk 3]
```diff
@@ -1386,10 +1392,17 @@ public void testCruiseControlDisabled(VertxTestContext context) {
         Kafka kafka =
                 new KafkaBuilder(ResourceUtils.createKafka(CLUSTER_NAMESPACE, CLUSTER_NAME, replicas, image, healthDelay, healthTimeout))
                         .editSpec()
-                        .editKafka()
-                        .withVersion(version)
-                        .endKafka()
+                            .editKafka()
+                            .withVersion(version)
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:1396]: Great that you are aligning this block for better readability. But you should indent this version once more.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 1 above)
Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1169]: Actually we are getting two conditions in the status. This Runtime Exception is an exception condition which moves the rebalance resource to `NotReady` and states the erro due to which the resource went to `NotReady` state. The other condition is `kafkaClusterNotReady` which is basically a warning condition stating that the Kafka resource is not ready yet

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java [hunk 4]
```diff
@@ -19,10 +19,9 @@
 import io.strimzi.api.kafka.model.KafkaRebalanceSpec;
 import io.strimzi.api.kafka.model.KafkaRebalanceSpecBuilder;
 import io.strimzi.api.kafka.model.balancing.KafkaRebalanceMode;
-import io.strimzi.api.kafka.model.status.Condition;
+import io.strimzi.api.kafka.model.status.*;
```
[the remark this answers is not in the document]
Comment (ShubhamRwt) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperatorTest.java:22]: Resolved

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 5]
```diff
@@ -1160,6 +1160,13 @@ private Future<MapAndStatus<ConfigMap, KafkaRebalanceStatus>> onReady(Reconcilia
                                 new NoSuchResourceException("Kafka resource '" + clusterName
                                         + "' identified by label '" + Labels.STRIMZI_CLUSTER_LABEL
                                         + "' does not exist in namespace " + clusterNamespace + ".")).mapEmpty();
+                    } else if (kafka.getStatus().getConditions().stream().noneMatch(condition -> condition.getType().equals("Ready") && condition.getStatus().equals("True"))) {
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1163]: Looks like this comment got lost somewhere while I was doing the review ... I think this smells after NPE. What if the status or the conditions are null? That can easily happen in situations like this. (and it would indicate that it is not ready as well)

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 1 above)
Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1169]: Sorry, I don't get the explanation. I'm with Kyle here. You check that the cluster is not ready. Nothing about the secret. So that should be the error here.

Comment (kyguy) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1169]: Do we need both conditions? The secret  "does not exist" runtime error happens if the KafkaRebalanceOperator attempts to connect to a Kafka cluster that is not ready right? If the new logic added prevents that and knows when the Kafka cluster is not ready, shouldn't we just have that in the status, the the Kafka cluster is not ready?

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1169]: The problem here is that the new check is much wider then just checking the secret. So it does not know anything about the secrets existence. It might be not ready because some worker node went down and one ZooKeeper pod is pending for example.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 5 above)
Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1163]: Okay, I will include 2 more condition in the `else if`. Something like this --> ```        else if (kafka.getStatus() == null 
                || kafka.getStatus().getConditions() 
                || kafka.getStatus().getConditions().stream().noneMatch(condition -> condition.getType().equals("Ready") && condition.getStatus().equals("True"))){```

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 6]
```diff
@@ -1160,6 +1160,14 @@ private Future<MapAndStatus<ConfigMap, KafkaRebalanceStatus>> onReady(Reconcilia
                                 new NoSuchResourceException("Kafka resource '" + clusterName
                                         + "' identified by label '" + Labels.STRIMZI_CLUSTER_LABEL
                                         + "' does not exist in namespace " + clusterNamespace + ".")).mapEmpty();
+                    } else if (kafka.getStatus() == null
+                            || kafka.getStatus().getConditions() == null
+                            || kafka.getStatus().getConditions().stream().noneMatch(condition -> condition.getType().equals("Ready") && condition.getStatus().equals("True"))) {
+                        String errorString = "Kafka cluster is being deployed";
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1166]: Maybe you can fix this error message as well to be more clear and say `Kafka cluster is not Ready`.

**Review by scholzj — APPROVED** [review]
One more nit. But LGTM otherwise.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java [hunk 7]
```diff
@@ -1392,7 +1400,13 @@ private enum CruiseControlIssues {
         /**
          * Cruise Control was not declared in the Kafka Resource
          */
-        cruiseControlDisabled("Cruise Control disabled");
+        cruiseControlDisabled("Cruise Control disabled"),
+
+        /**
+         * Kafka Cluster is not ready
+         *
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1407]: remove blank line

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 6 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java:1166]: Agree +1

**Review by ppatierno — APPROVED** [review]
Just a very stupid nit but LGTM.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 6 above)
Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java]: Fixed

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java (hunk 7 above)
Comment (ShubhamRwt) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java]: Fixed

**Review by kyguy — APPROVED** [review]
Looks greats, thanks @ShubhamRwt!

**Comment by scholzj** [comment]
Thanks for the PR @ShubhamRwt
