### PR TITLE
[ST] Fix `LoggingChangeST#testDynamicallySetConnectLoggingLevels` for Kafka versions below 3.7.x

### LINKED ISSUE #9897: `LoggingChangeST.testDynamicallySetConnectLoggingLevels` should run only on Kafka 3.7.0+?
The system test changes done in #9834 are based on a Apache Kafka change that is available from Kafka 3.7.0 up. And the test does not seem to work properly on Kafka 3.6.x. We should probably fix it to either make the test pass on older versions as well or disable it on Kafka 3.6.x.

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Bugfix

### Description

This PR fixes the issue when running `LoggingChangeST#testDynamicallySetConnectLoggingLevels` with Kafka version (set in `ST_KAFKA_VERSION`) below 3.7.0, where logging change set across multiple connect instances was added.

It adds check for the Kafka version and based on that it assigns either 1 or 3 replicas, with which should be KafkaConnect deployed.

Fixes #9897 

### Checklist

- [ ] Make sure all tests pass

### CODE REVIEW

File: systemtest/src/test/java/io/strimzi/systemtest/log/LoggingChangeST.java [hunk 1]
```diff
@@ -712,7 +713,10 @@ void testDynamicallySetConnectLoggingLevels() {
         final Pattern log4jPatternDebugLevel = Pattern.compile("^(?<date>[\\d-]+) (?<time>[\\d:,]+) DEBUG (?<message>.+)");
         final Pattern log4jPatternInfoLevel = Pattern.compile("^(?<date>[\\d-]+) (?<time>[\\d:,]+) INFO (?<message>.+)");
 
-        final KafkaConnect connect = KafkaConnectTemplates.kafkaConnect(testStorage.getClusterName(), testStorage.getNamespaceName(), 3)
+        // logging changes on multiple Connect instances are possible from Kafka 3.7.0
```
Comment (see-quick) [inline systemtest/src/test/java/io/strimzi/systemtest/log/LoggingChangeST.java:716]: Should we add a comment to remember that after we support Kafka 3.7.0 and greater then remove this conditional?

**Review by see-quick — APPROVED** [review]
LGTM, just one note worth of consideration.. 👍 good job

File: systemtest/src/test/java/io/strimzi/systemtest/log/LoggingChangeST.java (hunk 1 above)
Comment (im-konge) [reply systemtest/src/test/java/io/strimzi/systemtest/log/LoggingChangeST.java:716]: Yeah good point, we have the similar check in `MigrationST`, so I will add comment to those places
