### PR TITLE
Fix ACL Username handling for SCRAM users - Closes #825

### LINKED ISSUE #825: KafkaPrincipal names vs KafkaUser names and ACLs
Following on from [this conversation](https://github.com/strimzi/strimzi-kafka-operator/pull/795#issuecomment-415151013) we need to decide what to do about ACLs if a `KafkaUser` gets changed from SCRAM-SHA to TLS or vice versa.

Currently a `KafkaUser` setup for TLS authn gets a `KafkaPrincipal` named like `CN=jakub`, whereas one setup for SCRAM-SHA authn get named like `jakub`. This means that there are potentially two sets of ACLs with those two names.

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

Currently, the ACL names generated for SCRAM users have the names of the TLS users and therefore ACLs don't work with SCRAM. This PR should fix that as well as the issue #825 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

File: user-operator/src/main/java/io/strimzi/operator/user/model/KafkaUserModel.java [hunk 1]
```diff
@@ -308,4 +323,30 @@ public void setSimpleAclRules(List<AclRule> rules) {
...
         this.simpleAclRules = simpleAclRules;
     }
+
+    /**
+     * Returns true if the user is using TLS authentication
+     *
+     * @return
+     */
+    public boolean isTlsUser()  {
+        if (authentication instanceof KafkaUserTlsClientAuthentication) {
```
Comment (ppatierno) [inline user-operator/src/main/java/io/strimzi/operator/user/model/KafkaUserModel.java]: just ...

`return (authentication instanceof KafkaUserTlsClientAuthentication)` ?

File: user-operator/src/main/java/io/strimzi/operator/user/model/KafkaUserModel.java [hunk 2]
```diff
@@ -308,4 +323,30 @@ public void setSimpleAclRules(List<AclRule> rules) {
...
+        return false;
+    }
+
+    /**
+     * Returns true if the user is using SCRAM-SHA-512 authentication
+     *
+     * @return
+     */
+    public boolean isScramUser()  {
+        if (authentication instanceof KafkaUserScramSha512ClientAuthentication) {
```
Comment (ppatierno) [inline user-operator/src/main/java/io/strimzi/operator/user/model/KafkaUserModel.java]: Ditto as for `isTlsUser` ?
