### PR TITLE
Fix issues with labels, selectors and their changes - Closes #699

### LINKED ISSUE #122: Handle Label modifications
Cluster Controller should be able to handle situations when labels are changed on the source config map. Either change the labels on the managed resources as well or intentionally ignore it.

### LINKED ISSUE #699: Editing Kafka CR adding labels doesn't reflect all labels to all resources
Deploying a Kafka cluster adding a user label in the Kafka CR works. So having the following snippet : 
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
  labels:
     mylabel: myvalue
```
all the deployed resources will have that label.

```
[ppatiern@new-host-3 ~]$ oc get all -l mylabel=myvalue
NAME                               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/my-cluster-topic-operator   1         1         1            1           23m

NAME                                      DESIRED   CURRENT   READY     AGE
rs/my-cluster-topic-operator-6df5bdb777   1         1         1         23m

NAME                                DESIRED   CURRENT   AGE
statefulsets/my-cluster-kafka       3         3         24m
statefulsets/my-cluster-zookeeper   3         3         24m

NAME                                            READY     STATUS    RESTARTS   AGE
po/my-cluster-kafka-0                           2/2       Running   0          24m
po/my-cluster-kafka-1                           2/2       Running   0          24m
po/my-cluster-kafka-2                           2/2       Running   0          24m
po/my-cluster-topic-operator-6df5bdb777-fpdvq   2/2       Running   0          23m
po/my-cluster-zookeeper-0                       2/2       Running   0          24m
po/my-cluster-zookeeper-1                       2/2       Running   0          24m
po/my-cluster-zookeeper-2                       2/2       Running   0          24m

NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                               AGE
svc/my-cluster-kafka-bootstrap    ClusterIP   172.30.100.8    <none>        9092/TCP,9093/TCP,9091/TCP,9404/TCP   24m
svc/my-cluster-kafka-brokers      ClusterIP   None            <none>        9092/TCP,9091/TCP,9093/TCP            24m
svc/my-cluster-zookeeper-client   ClusterIP   172.30.68.203   <none>        9404/TCP,2181/TCP                     24m
svc/my-cluster-zookeeper-nodes    ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP            24m
```

when editing the CR adding a new "mynewlabel: mynewvalue", it's applied only to Zookeeper related services : 

```
[ppatiern@new-host-3 ~]$ oc get all -l mynewlabel=mynewvalue
NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
svc/my-cluster-zookeeper-client   ClusterIP   172.30.68.203   <none>        9404/TCP,2181/TCP            24m
svc/my-cluster-zookeeper-nodes    ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP   24m
```

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix
- ~~Enhancement / new feature~~
- ~~Refactoring~~
- ~~Documentation~~

### Description

Label changes do not work. Also, to allow label changes, we need to use only our own labels for selectors to make sure that label changes do not decouple the pods from the services or statefulsets.

This PR:
- Add new method `strimziLabels` to the Labels class which filters only Srtrmzi labels from the map with all labels
- It uses these labels for all selectors. In services, deployments, deployment configs and stateful sets.

This should close the issue #699. I expect that the problem there was that CO errored on the selectors and didn't managed to get through to change the labels on other objects. Thsi should also close #122 

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

File: operator-common/src/main/java/io/strimzi/operator/common/model/Labels.java [hunk 1]
```diff
@@ -242,6 +242,18 @@ public ResourceType type() {
         return type != null ? ResourceType.fromName(type) : null;
     }
 
+    public Labels strimziLabels() {
+        Map<String, String> newLabels = new HashMap<>(labels.size() + 1);
```
Comment (ppatierno) [inline operator-common/src/main/java/io/strimzi/operator/common/model/Labels.java]: out of curiosity, why the +1?

Comment (scholzj) [reply operator-common/src/main/java/io/strimzi/operator/common/model/Labels.java]: Yeah ... good eyes. That is just bad copy paste programming. I changed it to 3 which is the usual number of `strimzi.io` labels we have currently
