### PR TITLE
Store push secret correctly for Connect Build with Buildah

### LINKED ISSUE #12157: Kafka Connect Build with Buildah fails to push to container registries with authentication
When the `UseConnectBuildWithBuildah` feature gate is enabled and Buildah is used as the builder in the Kafka Connect Build, it fails to push the newly built container image to container registries using authentication because of incorrect mount path for the push credentials, which is based on the Kaniko build:

```yaml
        - name: docker-credentials
          mountPath: /kaniko/.docker
```

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Bugfix

### Description

This PR fixes issue with not functional push secret in case that Buildah is used in Connect Build (and the particular feature gate).
The push secret wasn't configured correctly at all, this way we will mount it to one place and reference it by `REGISTRY_AUTH_FILE` env variable (so we will not have to pass it through option in every Buildah command).

Fixes #12157 

### Checklist

- [ ] Make sure all tests pass
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java [hunk 1]
```diff
@@ -346,10 +351,16 @@ private List<VolumeMount> getVolumeMounts() {
...
-    private List<EnvVar> getBuildContainerEnvVars() {
+    private List<EnvVar> getBuildContainerEnvVars(boolean isBuildahBuild) {
         // Add shared environment variables used for all containers
         List<EnvVar> varList = new ArrayList<>(sharedEnvironmentProvider.variables());
 
+        if (build.getOutput() instanceof DockerOutput output) {
+            if (output.getPushSecret() != null && isBuildahBuild) {
+                varList.add(new EnvVarBuilder().withName("REGISTRY_AUTH_FILE").withValue("/build/.docker/config.json").build());
+            }
+        }
```
Comment (scholzj) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java]: * Should this be merged into a single if?
* What happens when the user for some reason wants to use `--authfile` in `additionalPushOptions`? Is the expectation that in such a case `output.getPushSecret()` will be always `null`?

Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java]: - Yeah I think I can merge it to one
- I think the option specified in the command itself takes precedense. We are not checking that if the `additionalPushOptions` contains `--authfile` or some other option security option, the `output.getPushSecret()` has to be null and vice versa. Do you think it would be worth to check it?

Comment (scholzj) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java]: > Do you think it would be worth to check it?

I don't know, I wondered about the priorities and expectations. That is why I raised it. But no strong opinions. I guess if someone specifies custom push secret parameter, they maybe should not specify the push secret through the API at the same time?  So maybe that part is fine. 🤷

**Comment by scholzj** [comment]
> BTW: A unit test might be nice for this as well?

I guess ideally both for the volume mount and the env var. As it seems a bit lacking the coverage.

**Comment by im-konge** [comment]
Yeah I will add more tests for those methods. I saw that they are not covered.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java (hunk 1 above)
Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java]: I merged the ifs where it makes sense. And I think the other part can be kept as it is I suppose.

**Comment by im-konge** [comment]
@scholzj I added UTs for both Kaniko and Buildah Volumes, VolumeMounts, and EnvVars. Please have a look if it's better now or you want to test it differently. Thanks.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectBuildTest.java [hunk 2]
```diff
@@ -840,4 +846,291 @@ public void testInvalidKanikoOptionsInAdditionalBuildOptions() {
...
+        assertThat(volumeMounts.contains(new VolumeMountBuilder().withName("dockerfile").withMountPath("/dockerfile").build()), is(true));
+
+
+        List<EnvVar> envVars = kafkaConnectBuild.getBuildContainerEnvVars(false);
+
+        assertThat(envVars.size(), is(1));
+        assertThat(envVars.get(0).equals(new EnvVarBuilder().withName("MY_ENV").withValue("value").build()), is(true));
+
+        // now check the Volumes, VolumeMounts, and EnvVars without additional volume, env var, and also push secret
+        kc = new KafkaConnectBuilder()
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectBuildTest.java]: I would split this into two separate tests.

File: cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectBuildTest.java [hunk 3]
```diff
@@ -840,4 +846,291 @@ public void testInvalidKanikoOptionsInAdditionalBuildOptions() {
...
+        assertThat(volumeMounts.contains(new VolumeMountBuilder().withName("dockerfile").withMountPath("/dockerfile").build()), is(true));
+
+
+        List<EnvVar> envVars = kafkaConnectBuild.getBuildContainerEnvVars(true);
+
+        assertThat(envVars.size(), is(2));
+        assertThat(envVars.contains(new EnvVarBuilder().withName("MY_ENV").withValue("value").build()), is(true));
+        assertThat(envVars.contains(new EnvVarBuilder().withName("REGISTRY_AUTH_FILE").withValue("/build/.docker/config.json").build()), is(true));
+
+        // now check the Volumes, VolumeMounts, and EnvVars without additional volume, env var, and also push secret
```
Comment (scholzj) [inline cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectBuildTest.java]: Same as above, I would split this into a separate test. Overall, not sure we need a dedicated test for how the extra volume / env is handled with Kaniko and Buildah as there do not seem to be major differences in the code.

Comment (im-konge) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectBuildTest.java]: I think it will not hurt to have those test cases there, the same could be said for the case without any additional stuff. Those tests are just checking that with every branch everything works as expected. So I would keep them.
But I will split the tests.

Comment (scholzj) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectBuildTest.java]: Ok, fine. But you should still split it into separate tests, I think.

Comment (im-konge) [reply cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaConnectBuildTest.java]: The tests are split now, plus I fixed the issue which was there because of the condition I merged. Now it should work fine I hope.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java [hunk 4]
```diff
@@ -322,15 +323,18 @@ private List<Volume> getVolumes(boolean isOpenShift) {
...
 
         if (build.getOutput() instanceof DockerOutput output) {
-
             if (output.getPushSecret() != null) {
-                volumeMounts.add(new VolumeMountBuilder().withName("docker-credentials").withMountPath("/kaniko/.docker").build());
+                if (isBuildahBuild) {
+                    volumeMounts.add(new VolumeMountBuilder().withName("docker-credentials").withMountPath("/build/.docker").build());
+                } else {
+                    volumeMounts.add(new VolumeMountBuilder().withName("docker-credentials").withMountPath("/kaniko/.docker").build());
+                }
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java]: just my personal preference to make the code cleaner but no need to change it (even because performance wise there is no advantage) but I would have:

```java
String path = isBuildahBuild ? "/build/.docker" : "/kaniko/.docker";
volumeMounts.add(new VolumeMountBuilder().withName("docker-credentials").withMountPath(path).build());
```

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java [hunk 5]
```diff
@@ -346,10 +350,14 @@ private List<VolumeMount> getVolumeMounts() {
      *
      * @return  List of environment variables
      */
-    private List<EnvVar> getBuildContainerEnvVars() {
+    /* test */ List<EnvVar> getBuildContainerEnvVars(boolean isBuildahBuild) {
         // Add shared environment variables used for all containers
         List<EnvVar> varList = new ArrayList<>(sharedEnvironmentProvider.variables());
 
+        if (build.getOutput() instanceof DockerOutput output && output.getPushSecret() != null && isBuildahBuild) {
```
Comment (ppatierno) [inline cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java]: This line is just in case Buildah is used so what about putting the `isBuildahBuild` condition as the first one in the chain. When false, it will allow to skip immediately the evaluation of the rest.

Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java]: Before I had it like `if (build.getOutput() instanceof DockerOutput output && isBuildahBuild)` and then check for the push secret and I got comment from Jakub that we can merge those conditions. I think it doesn't make much difference, as if it's Buildah build, it should be DockerOutput anyway (there is no other option for the build), so having them both together make sense to me more rather than having `isBuildahBuild` as a first if and then checking the DockerOutput and pushSecret.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java (hunk 4 above)
Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java]: Sure I can do something like that :) no problem.

File: cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java (hunk 5 above)
Comment (ppatierno) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java]: Maybe I was misleading I meant this ...

```java
if (isBuildahBuild && build.getOutput() instanceof DockerOutput output && output.getPushSecret() != null)
```

If `isBuildahBuild` is false, the other conditions are not checked at all.

Comment (im-konge) [reply cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java]: Ah yeah right, good point. Thanks
